import type { Codelist } from "@node-zugferd/core";
import { registerCodelist } from "@node-zugferd/data-types";

const item = [
	{
		value: "AA",
		name: "Product version number",
		key: "PRODUCT_VERSION_NUMBER",
	},
	{ value: "AB", name: "Assembly", key: "ASSEMBLY" },
	{
		value: "AC",
		name: "HIBC (Health Industry Bar Code)",
		key: "HIBC_HEALTH_INDUSTRY_BAR_CODE",
	},
	{ value: "AD", name: "Cold roll number", key: "COLD_ROLL_NUMBER" },
	{ value: "AE", name: "Hot roll number", key: "HOT_ROLL_NUMBER" },
	{ value: "AF", name: "Slab number", key: "SLAB_NUMBER" },
	{
		value: "AG",
		name: "Software revision number",
		key: "SOFTWARE_REVISION_NUMBER",
	},
	{
		value: "AH",
		name: "UPC (Universal Product Code) Consumer package code (1-5-5)",
		key: "UPC_UNIVERSAL_PRODUCT_CODE_CONSUMER_PACKAGE_CODE_1_5_5",
	},
	{
		value: "AI",
		name: "UPC (Universal Product Code) Consumer package code (1-5-5-",
		key: "UPC_UNIVERSAL_PRODUCT_CODE_CONSUMER_PACKAGE_CODE_1_5_5",
	},
	{ value: "AJ", name: "Sample number", key: "SAMPLE_NUMBER" },
	{ value: "AK", name: "Pack number", key: "PACK_NUMBER" },
	{
		value: "AL",
		name: "UPC (Universal Product Code) Shipping container code (1-2-",
		key: "UPC_UNIVERSAL_PRODUCT_CODE_SHIPPING_CONTAINER_CODE_1_2",
	},
	{
		value: "AM",
		name: "UPC (Universal Product Code)/EAN (European article number)",
		key: "UPC_UNIVERSAL_PRODUCT_CODE_EAN_EUROPEAN_ARTICLE_NUMBER",
	},
	{
		value: "AN",
		name: "UPC (Universal Product Code) suffix",
		key: "UPC_UNIVERSAL_PRODUCT_CODE_SUFFIX",
	},
	{ value: "AO", name: "State label code", key: "STATE_LABEL_CODE" },
	{ value: "AP", name: "Heat number", key: "HEAT_NUMBER" },
	{ value: "AQ", name: "Coupon number", key: "COUPON_NUMBER" },
	{ value: "AR", name: "Resource number", key: "RESOURCE_NUMBER" },
	{ value: "AS", name: "Work task number", key: "WORK_TASK_NUMBER" },
	{ value: "AT", name: "Price look up number", key: "PRICE_LOOK_UP_NUMBER" },
	{
		value: "AU",
		name: "NSN (North Atlantic Treaty Organization Stock Number)",
		key: "NSN_NORTH_ATLANTIC_TREATY_ORGANIZATION_STOCK_NUMBER",
	},
	{ value: "AV", name: "Refined product code", key: "REFINED_PRODUCT_CODE" },
	{ value: "AW", name: "Exhibit", key: "EXHIBIT" },
	{ value: "AX", name: "End item", key: "END_ITEM" },
	{
		value: "AY",
		name: "Federal supply classification",
		key: "FEDERAL_SUPPLY_CLASSIFICATION",
	},
	{ value: "AZ", name: "Engineering data list", key: "ENGINEERING_DATA_LIST" },
	{
		value: "BA",
		name: "Milestone event number",
		key: "MILESTONE_EVENT_NUMBER",
	},
	{ value: "BB", name: "Lot number", key: "LOT_NUMBER" },
	{
		value: "BC",
		name: "National drug code 4-4-2 format",
		key: "NATIONAL_DRUG_CODE_4_4_2_FORMAT",
	},
	{
		value: "BD",
		name: "National drug code 5-3-2 format",
		key: "NATIONAL_DRUG_CODE_5_3_2_FORMAT",
	},
	{
		value: "BE",
		name: "National drug code 5-4-1 format",
		key: "NATIONAL_DRUG_CODE_5_4_1_FORMAT",
	},
	{
		value: "BF",
		name: "National drug code 5-4-2 format",
		key: "NATIONAL_DRUG_CODE_5_4_2_FORMAT",
	},
	{ value: "BG", name: "National drug code", key: "NATIONAL_DRUG_CODE" },
	{ value: "BH", name: "Part number", key: "PART_NUMBER" },
	{
		value: "BI",
		name: "Local Stock Number (LSN)",
		key: "LOCAL_STOCK_NUMBER_LSN",
	},
	{
		value: "BJ",
		name: "Next higher assembly number",
		key: "NEXT_HIGHER_ASSEMBLY_NUMBER",
	},
	{ value: "BK", name: "Data category", key: "DATA_CATEGORY" },
	{ value: "BL", name: "Control number", key: "CONTROL_NUMBER" },
	{
		value: "BM",
		name: "Special material identification code",
		key: "SPECIAL_MATERIAL_IDENTIFICATION_CODE",
	},
	{
		value: "BN",
		name: "Locally assigned control number",
		key: "LOCALLY_ASSIGNED_CONTROL_NUMBER",
	},
	{ value: "BO", name: "Buyer's colour", key: "BUYER_S_COLOUR" },
	{ value: "BP", name: "Buyer's part number", key: "BUYER_S_PART_NUMBER" },
	{
		value: "BQ",
		name: "Variable measure product code",
		key: "VARIABLE_MEASURE_PRODUCT_CODE",
	},
	{ value: "BR", name: "Financial phase", key: "FINANCIAL_PHASE" },
	{ value: "BS", name: "Contract breakdown", key: "CONTRACT_BREAKDOWN" },
	{ value: "BT", name: "Technical phase", key: "TECHNICAL_PHASE" },
	{ value: "BU", name: "Dye lot number", key: "DYE_LOT_NUMBER" },
	{
		value: "BV",
		name: "Daily statement of activities",
		key: "DAILY_STATEMENT_OF_ACTIVITIES",
	},
	{
		value: "BW",
		name: "Periodical statement of activities within a bilaterally",
		key: "PERIODICAL_STATEMENT_OF_ACTIVITIES_WITHIN_A_BILATERALLY",
	},
	{
		value: "BX",
		name: "Calendar week statement of activities",
		key: "CALENDAR_WEEK_STATEMENT_OF_ACTIVITIES",
	},
	{
		value: "BY",
		name: "Calendar month statement of activities",
		key: "CALENDAR_MONTH_STATEMENT_OF_ACTIVITIES",
	},
	{
		value: "BZ",
		name: "Original equipment number",
		key: "ORIGINAL_EQUIPMENT_NUMBER",
	},
	{
		value: "CC",
		name: "Industry commodity code",
		key: "INDUSTRY_COMMODITY_CODE",
	},
	{ value: "CG", name: "Commodity grouping", key: "COMMODITY_GROUPING" },
	{ value: "CL", name: "Colour number", key: "COLOUR_NUMBER" },
	{ value: "CR", name: "Contract number", key: "CONTRACT_NUMBER" },
	{
		value: "CV",
		name: "Customs article number",
		key: "CUSTOMS_ARTICLE_NUMBER",
	},
	{
		value: "DR",
		name: "Drawing revision number",
		key: "DRAWING_REVISION_NUMBER",
	},
	{ value: "DW", name: "Drawing", key: "DRAWING" },
	{
		value: "EC",
		name: "Engineering change level",
		key: "ENGINEERING_CHANGE_LEVEL",
	},
	{ value: "EF", name: "Material code", key: "MATERIAL_CODE" },
	{
		value: "EMD",
		name: "EMDN (European Medical Device Nomenclature)",
		key: "EMDN_EUROPEAN_MEDICAL_DEVICE_NOMENCLATURE",
	},
	{
		value: "EN",
		name: "International Article Numbering Association (EAN)",
		key: "INTERNATIONAL_ARTICLE_NUMBERING_ASSOCIATION_EAN",
	},
	{ value: "FS", name: "Fish species", key: "FISH_SPECIES" },
	{
		value: "GB",
		name: "Buyer's internal product group code",
		key: "BUYER_S_INTERNAL_PRODUCT_GROUP_CODE",
	},
	{ value: "GMN", name: "Global model number", key: "GLOBAL_MODEL_NUMBER" },
	{
		value: "GN",
		name: "National product group code",
		key: "NATIONAL_PRODUCT_GROUP_CODE",
	},
	{
		value: "GS",
		name: "General specification number",
		key: "GENERAL_SPECIFICATION_NUMBER",
	},
	{ value: "HS", name: "Harmonised system", key: "HARMONISED_SYSTEM" },
	{
		value: "IB",
		name: "ISBN (International Standard Book Number)",
		key: "ISBN_INTERNATIONAL_STANDARD_BOOK_NUMBER",
	},
	{ value: "IN", name: "Buyer's item number", key: "BUYER_S_ITEM_NUMBER" },
	{
		value: "IS",
		name: "ISSN (International Standard Serial Number)",
		key: "ISSN_INTERNATIONAL_STANDARD_SERIAL_NUMBER",
	},
	{ value: "IT", name: "Buyer's style number", key: "BUYER_S_STYLE_NUMBER" },
	{ value: "IZ", name: "Buyer's size code", key: "BUYER_S_SIZE_CODE" },
	{ value: "MA", name: "Machine number", key: "MACHINE_NUMBER" },
	{
		value: "MF",
		name: "Manufacturer's (producer's) article number",
		key: "MANUFACTURER_S_PRODUCER_S_ARTICLE_NUMBER",
	},
	{ value: "MN", name: "Model number", key: "MODEL_NUMBER" },
	{
		value: "MP",
		name: "Product/service identification number",
		key: "PRODUCT_SERVICE_IDENTIFICATION_NUMBER",
	},
	{ value: "NB", name: "Batch number", key: "BATCH_NUMBER" },
	{ value: "ON", name: "Customer order number", key: "CUSTOMER_ORDER_NUMBER" },
	{
		value: "PD",
		name: "Part number description",
		key: "PART_NUMBER_DESCRIPTION",
	},
	{
		value: "PL",
		name: "Purchaser's order line number",
		key: "PURCHASER_S_ORDER_LINE_NUMBER",
	},
	{ value: "PO", name: "Purchase order number", key: "PURCHASE_ORDER_NUMBER" },
	{
		value: "PPI",
		name: "Phytosanitary Passport identifier",
		key: "PHYTOSANITARY_PASSPORT_IDENTIFIER",
	},
	{
		value: "PV",
		name: "Promotional variant number",
		key: "PROMOTIONAL_VARIANT_NUMBER",
	},
	{
		value: "QS",
		name: "Buyer's qualifier for size",
		key: "BUYER_S_QUALIFIER_FOR_SIZE",
	},
	{
		value: "RC",
		name: "Returnable container number",
		key: "RETURNABLE_CONTAINER_NUMBER",
	},
	{ value: "RN", name: "Release number", key: "RELEASE_NUMBER" },
	{ value: "RU", name: "Run number", key: "RUN_NUMBER" },
	{
		value: "RY",
		name: "Record keeping of model year",
		key: "RECORD_KEEPING_OF_MODEL_YEAR",
	},
	{
		value: "SA",
		name: "Supplier's article number",
		key: "SUPPLIER_S_ARTICLE_NUMBER",
	},
	{
		value: "SG",
		name: "Standard group of products (mixed assortment)",
		key: "STANDARD_GROUP_OF_PRODUCTS_MIXED_ASSORTMENT",
	},
	{
		value: "SK",
		name: "SKU (Stock keeping unit)",
		key: "SKU_STOCK_KEEPING_UNIT",
	},
	{ value: "SN", name: "Serial number", key: "SERIAL_NUMBER" },
	{ value: "SRS", name: "RSK number", key: "RSK_NUMBER" },
	{
		value: "SRT",
		name: "IFLS (Institut Francais du Libre Service) 5 digit product",
		key: "IFLS_INSTITUT_FRANCAIS_DU_LIBRE_SERVICE_5_DIGIT_PRODUCT",
	},
	{
		value: "SRU",
		name: "IFLS (Institut Francais du Libre Service) 9 digit product",
		key: "IFLS_INSTITUT_FRANCAIS_DU_LIBRE_SERVICE_9_DIGIT_PRODUCT",
	},
	{
		value: "SRV",
		name: "GS1 Global Trade Item Number",
		key: "GS1_GLOBAL_TRADE_ITEM_NUMBER",
	},
	{
		value: "SRW",
		name: "EDIS (Energy Data Identification System)",
		key: "EDIS_ENERGY_DATA_IDENTIFICATION_SYSTEM",
	},
	{ value: "SRX", name: "Slaughter number", key: "SLAUGHTER_NUMBER" },
	{
		value: "SRY",
		name: "Official animal number",
		key: "OFFICIAL_ANIMAL_NUMBER",
	},
	{
		value: "SRZ",
		name: "Harmonized tariff schedule",
		key: "HARMONIZED_TARIFF_SCHEDULE",
	},
	{
		value: "SS",
		name: "Supplier's supplier article number",
		key: "SUPPLIER_S_SUPPLIER_ARTICLE_NUMBER",
	},
	{ value: "SSA", name: "46 Level DOT Code", key: "46_LEVEL_DOT_CODE" },
	{ value: "SSB", name: "Airline Tariff 6D", key: "AIRLINE_TARIFF_6_D" },
	{
		value: "SSC",
		name: "Title 49 Code of Federal Regulations",
		key: "TITLE_49_CODE_OF_FEDERAL_REGULATIONS",
	},
	{
		value: "SSD",
		name: "International Civil Aviation Administration code",
		key: "INTERNATIONAL_CIVIL_AVIATION_ADMINISTRATION_CODE",
	},
	{
		value: "SSE",
		name: "Hazardous Materials ID DOT",
		key: "HAZARDOUS_MATERIALS_ID_DOT",
	},
	{ value: "SSF", name: "Endorsement", key: "ENDORSEMENT" },
	{
		value: "SSG",
		name: "Air Force Regulation 71-4",
		key: "AIR_FORCE_REGULATION_71_4",
	},
	{ value: "SSH", name: "Breed", key: "BREED" },
	{
		value: "SSI",
		name: "Chemical Abstract Service (CAS) registry number",
		key: "CHEMICAL_ABSTRACT_SERVICE_CAS_REGISTRY_NUMBER",
	},
	{
		value: "SSJ",
		name: "Engine model designation",
		key: "ENGINE_MODEL_DESIGNATION",
	},
	{
		value: "SSK",
		name: "Institutional Meat Purchase Specifications (IMPS) Number",
		key: "INSTITUTIONAL_MEAT_PURCHASE_SPECIFICATIONS_IMPS_NUMBER",
	},
	{
		value: "SSL",
		name: "Price Look-Up code (PLU)",
		key: "PRICE_LOOK_UP_CODE_PLU",
	},
	{
		value: "SSM",
		name: "International Maritime Organization (IMO) Code",
		key: "INTERNATIONAL_MARITIME_ORGANIZATION_IMO_CODE",
	},
	{
		value: "SSN",
		name: "Bureau of Explosives 600-A (rail)",
		key: "BUREAU_OF_EXPLOSIVES_600_A_RAIL",
	},
	{
		value: "SSO",
		name: "United Nations Dangerous Goods List",
		key: "UNITED_NATIONS_DANGEROUS_GOODS_LIST",
	},
	{
		value: "SSP",
		name: "International Code of Botanical Nomenclature (ICBN)",
		key: "INTERNATIONAL_CODE_OF_BOTANICAL_NOMENCLATURE_ICBN",
	},
	{
		value: "SSQ",
		name: "International Code of Zoological Nomenclature (ICZN)",
		key: "INTERNATIONAL_CODE_OF_ZOOLOGICAL_NOMENCLATURE_ICZN",
	},
	{
		value: "SSR",
		name: "International Code of Nomenclature for Cultivated Plants",
		key: "INTERNATIONAL_CODE_OF_NOMENCLATURE_FOR_CULTIVATED_PLANTS",
	},
	{
		value: "SSS",
		name: "Distributor’s article identifier",
		key: "DISTRIBUTOR_S_ARTICLE_IDENTIFIER",
	},
	{
		value: "SST",
		name: "Norwegian Classification system ENVA",
		key: "NORWEGIAN_CLASSIFICATION_SYSTEM_ENVA",
	},
	{
		value: "SSU",
		name: "Supplier assigned classification",
		key: "SUPPLIER_ASSIGNED_CLASSIFICATION",
	},
	{
		value: "SSV",
		name: "Mexican classification system AMECE",
		key: "MEXICAN_CLASSIFICATION_SYSTEM_AMECE",
	},
	{
		value: "SSW",
		name: "German classification system CCG",
		key: "GERMAN_CLASSIFICATION_SYSTEM_CCG",
	},
	{
		value: "SSX",
		name: "Finnish classification system EANFIN",
		key: "FINNISH_CLASSIFICATION_SYSTEM_EANFIN",
	},
	{
		value: "SSY",
		name: "Canadian classification system ICC",
		key: "CANADIAN_CLASSIFICATION_SYSTEM_ICC",
	},
	{
		value: "SSZ",
		name: "French classification system IFLS5",
		key: "FRENCH_CLASSIFICATION_SYSTEM_IFLS5",
	},
	{ value: "ST", name: "Style number", key: "STYLE_NUMBER" },
	{
		value: "STA",
		name: "Dutch classification system CBL",
		key: "DUTCH_CLASSIFICATION_SYSTEM_CBL",
	},
	{
		value: "STB",
		name: "Japanese classification system JICFS",
		key: "JAPANESE_CLASSIFICATION_SYSTEM_JICFS",
	},
	{
		value: "STC",
		name: "European Union dairy subsidy eligibility classification",
		key: "EUROPEAN_UNION_DAIRY_SUBSIDY_ELIGIBILITY_CLASSIFICATION",
	},
	{
		value: "STD",
		name: "GS1 Spain classification system",
		key: "GS1_SPAIN_CLASSIFICATION_SYSTEM",
	},
	{
		value: "STE",
		name: "GS1 Poland classification system",
		key: "GS1_POLAND_CLASSIFICATION_SYSTEM",
	},
	{
		value: "STF",
		name: "Federal Agency on Technical Regulating and Metrology of the",
		key: "FEDERAL_AGENCY_ON_TECHNICAL_REGULATING_AND_METROLOGY_OF_THE",
	},
	{
		value: "STG",
		name: "Efficient Consumer Response (ECR) Austria classification",
		key: "EFFICIENT_CONSUMER_RESPONSE_ECR_AUSTRIA_CLASSIFICATION",
	},
	{
		value: "STH",
		name: "GS1 Italy classification system",
		key: "GS1_ITALY_CLASSIFICATION_SYSTEM",
	},
	{
		value: "STI",
		name: "CPV (Common Procurement Vocabulary)",
		key: "CPV_COMMON_PROCUREMENT_VOCABULARY",
	},
	{
		value: "STJ",
		name: "IFDA (International Foodservice Distributors Association)",
		key: "IFDA_INTERNATIONAL_FOODSERVICE_DISTRIBUTORS_ASSOCIATION",
	},
	{
		value: "STK",
		name: "AHFS (American Hospital Formulary Service) pharmacologic -",
		key: "AHFS_AMERICAN_HOSPITAL_FORMULARY_SERVICE_PHARMACOLOGIC",
	},
	{
		value: "STL",
		name: "ATC (Anatomical Therapeutic Chemical) classification system",
		key: "ATC_ANATOMICAL_THERAPEUTIC_CHEMICAL_CLASSIFICATION_SYSTEM",
	},
	{
		value: "STM",
		name: "CLADIMED (Classification des Dispositifs Médicaux)",
		key: "CLADIMED_CLASSIFICATION_DES_DISPOSITIFS_ME_DICAUX",
	},
	{
		value: "STN",
		name: "CMDR (Canadian Medical Device Regulations) classification",
		key: "CMDR_CANADIAN_MEDICAL_DEVICE_REGULATIONS_CLASSIFICATION",
	},
	{
		value: "STO",
		name: "CNDM (Classificazione Nazionale dei Dispositivi Medici)",
		key: "CNDM_CLASSIFICAZIONE_NAZIONALE_DEI_DISPOSITIVI_MEDICI",
	},
	{
		value: "STP",
		name: "UK DM&amp;D (Dictionary of Medicines &amp; Devices) standard coding",
		key: "UK_DM_AMP_D_DICTIONARY_OF_MEDICINES_AMP_DEVICES_STANDARD_CODING",
	},
	{ value: "STQ", name: "eCl@ss", key: "E_CL_SS" },
	{
		value: "STR",
		name: "EDMA (European Diagnostic Manufacturers Association)",
		key: "EDMA_EUROPEAN_DIAGNOSTIC_MANUFACTURERS_ASSOCIATION",
	},
	{
		value: "STS",
		name: "EGAR (European Generic Article Register)",
		key: "EGAR_EUROPEAN_GENERIC_ARTICLE_REGISTER",
	},
	{
		value: "STT",
		name: "GMDN (Global Medical Devices Nomenclature)",
		key: "GMDN_GLOBAL_MEDICAL_DEVICES_NOMENCLATURE",
	},
	{
		value: "STU",
		name: "GPI (Generic Product Identifier)",
		key: "GPI_GENERIC_PRODUCT_IDENTIFIER",
	},
	{
		value: "STV",
		name: "HCPCS (Healthcare Common Procedure Coding System)",
		key: "HCPCS_HEALTHCARE_COMMON_PROCEDURE_CODING_SYSTEM",
	},
	{
		value: "STW",
		name: "ICPS (International Classification for Patient Safety)",
		key: "ICPS_INTERNATIONAL_CLASSIFICATION_FOR_PATIENT_SAFETY",
	},
	{
		value: "STX",
		name: "MedDRA (Medical Dictionary for Regulatory Activities)",
		key: "MED_DRA_MEDICAL_DICTIONARY_FOR_REGULATORY_ACTIVITIES",
	},
	{ value: "STY", name: "Medical Columbus", key: "MEDICAL_COLUMBUS" },
	{
		value: "STZ",
		name: "NAPCS (North American Product Classification System)",
		key: "NAPCS_NORTH_AMERICAN_PRODUCT_CLASSIFICATION_SYSTEM",
	},
	{
		value: "SUA",
		name: "NHS (National Health Services) eClass",
		key: "NHS_NATIONAL_HEALTH_SERVICES_E_CLASS",
	},
	{
		value: "SUB",
		name: "US FDA (Food and Drug Administration) Product Code",
		key: "US_FDA_FOOD_AND_DRUG_ADMINISTRATION_PRODUCT_CODE",
	},
	{
		value: "SUC",
		name: "SNOMED CT (Systematized Nomenclature of Medicine-Clinical",
		key: "SNOMED_CT_SYSTEMATIZED_NOMENCLATURE_OF_MEDICINE_CLINICAL",
	},
	{
		value: "SUD",
		name: "UMDNS (Universal Medical Device Nomenclature System)",
		key: "UMDNS_UNIVERSAL_MEDICAL_DEVICE_NOMENCLATURE_SYSTEM",
	},
	{
		value: "SUE",
		name: "GS1 Global Returnable Asset Identifier, non-serialised",
		key: "GS1_GLOBAL_RETURNABLE_ASSET_IDENTIFIER_NON_SERIALISED",
	},
	{ value: "SUF", name: "IMEI", key: "IMEI" },
	{ value: "SUG", name: "Waste Type (EMSA)", key: "WASTE_TYPE_EMSA" },
	{
		value: "SUH",
		name: "Ship's store classification type",
		key: "SHIP_S_STORE_CLASSIFICATION_TYPE",
	},
	{ value: "SUI", name: "Emergency fire code", key: "EMERGENCY_FIRE_CODE" },
	{
		value: "SUJ",
		name: "Emergency spillage code",
		key: "EMERGENCY_SPILLAGE_CODE",
	},
	{ value: "SUK", name: "IMDG packing group", key: "IMDG_PACKING_GROUP" },
	{ value: "SUL", name: "MARPOL Code IBC", key: "MARPOL_CODE_IBC" },
	{
		value: "SUM",
		name: "IMDG subsidiary risk class",
		key: "IMDG_SUBSIDIARY_RISK_CLASS",
	},
	{
		value: "TG",
		name: "Transport group number",
		key: "TRANSPORT_GROUP_NUMBER",
	},
	{
		value: "TSN",
		name: "Taxonomic Serial Number",
		key: "TAXONOMIC_SERIAL_NUMBER",
	},
	{
		value: "TSO",
		name: "IMDG main hazard class",
		key: "IMDG_MAIN_HAZARD_CLASS",
	},
	{
		value: "TSP",
		name: "EU Combined Nomenclature",
		key: "EU_COMBINED_NOMENCLATURE",
	},
	{
		value: "TSQ",
		name: "Therapeutic classification number",
		key: "THERAPEUTIC_CLASSIFICATION_NUMBER",
	},
	{
		value: "TSR",
		name: "European Waste Catalogue",
		key: "EUROPEAN_WASTE_CATALOGUE",
	},
	{ value: "TSS", name: "Price grouping code", key: "PRICE_GROUPING_CODE" },
	{ value: "TST", name: "UNSPSC", key: "UNSPSC" },
	{ value: "TSU", name: "EU RoHS Directive", key: "EU_RO_HS_DIRECTIVE" },
	{
		value: "UA",
		name: "Ultimate customer's article number",
		key: "ULTIMATE_CUSTOMER_S_ARTICLE_NUMBER",
	},
	{
		value: "UP",
		name: "UPC (Universal product code)",
		key: "UPC_UNIVERSAL_PRODUCT_CODE",
	},
	{ value: "VN", name: "Vendor item number", key: "VENDOR_ITEM_NUMBER" },
	{
		value: "VP",
		name: "Vendor's (seller's) part number",
		key: "VENDOR_S_SELLER_S_PART_NUMBER",
	},
	{
		value: "VS",
		name: "Vendor's supplemental item number",
		key: "VENDOR_S_SUPPLEMENTAL_ITEM_NUMBER",
	},
	{
		value: "VX",
		name: "Vendor specification number",
		key: "VENDOR_SPECIFICATION_NUMBER",
	},
	{ value: "ZZZ", name: "Mutually defined", key: "MUTUALLY_DEFINED" },
] as const satisfies Codelist;

declare module "@node-zugferd/core" {
	interface ZugferdCodelistRegistry {
		item: typeof item;
	}
}
registerCodelist("item", item);

export default item;
