import { defineConfig } from "tsup";

export default defineConfig((env) => {
	return {
		entry: {
			index: "./src/index.ts",
			profile: "./src/profiles/index.ts",
			"profile/minimum": "./src/profiles/minimum/index.ts",
			"profile/basic": "./src/profiles/basic/index.ts",
			"profile/basic-wl": "./src/profiles/basic-wl/index.ts",
			"profile/en16931": "./src/profiles/en16931/index.ts",
			"profile/extended": "./src/profiles/extended/index.ts",
			types: "./src/types/index.ts",
			"codelist/allowance": "./src/codelists/allowance.gen.ts",
			"codelist/characteristic": "./src/codelists/characteristic.gen.ts",
			"codelist/charge": "./src/codelists/charge.gen.ts",
			"codelist/country": "./src/codelists/country.gen.ts",
			"codelist/currency": "./src/codelists/currency.gen.ts",
			"codelist/date": "./src/codelists/date.gen.ts",
			"codelist/eas": "./src/codelists/eas.gen.ts",
			"codelist/filename": "./src/codelists/filename.gen.ts",
			"codelist/fiscal-id": "./src/codelists/fiscal-id.gen.ts",
			"codelist/hybrid-conformance":
				"./src/codelists/hybrid-conformance.gen.ts",
			"codelist/hybrid-document": "./src/codelists/hybrid-document.gen.ts",
			"codelist/hybrid-version": "./src/codelists/hybrid-version.gen.ts",
			"codelist/icd": "./src/codelists/icd.gen.ts",
			"codelist/incoterms": "./src/codelists/incoterms.gen.ts",
			"codelist/item": "./src/codelists/item.gen.ts",
			"codelist/language": "./src/codelists/language.gen.ts",
			"codelist/line-reason": "./src/codelists/line-reason.gen.ts",
			"codelist/line-status": "./src/codelists/line-status.gen.ts",
			"codelist/mime": "./src/codelists/mime.gen.ts",
			"codelist/payment": "./src/codelists/payment.gen.ts",
			"codelist/text": "./src/codelists/text.gen.ts",
			"codelist/time": "./src/codelists/time.gen.ts",
			"codelist/transport": "./src/codelists/transport.gen.ts",
			"codelist/unit": "./src/codelists/unit.gen.ts",
			"codelist/untdid-1001": "./src/codelists/untdid-1001.gen.ts",
			"codelist/untdid-1153": "./src/codelists/untdid-1153.gen.ts",
			"codelist/untdid-3035": "./src/codelists/untdid-3035.gen.ts",
			"codelist/untdid-3139": "./src/codelists/untdid-3139.gen.ts",
			"codelist/untdid-5305": "./src/codelists/untdid-5305.gen.ts",
			"codelist/untdid-4451": "./src/codelists/untdid-4451.gen.ts",
			"codelist/vat-cat": "./src/codelists/vat-cat.gen.ts",
			"codelist/vat-id": "./src/codelists/vat-id.gen.ts",
			"codelist/vatex": "./src/codelists/vatex.gen.ts",
		},
		format: ["cjs", "esm"],
		bundle: true,
		publicDir: "./src/assets",
		splitting: false,
		cjsInterop: true,
		skipNodeModulesBundle: true,
	};
});
