import type { Codelist } from "@node-zugferd/core";
import { registerCodelist } from "@node-zugferd/data-types";

const characteristic = [
	{
		"@source": "6313",
		value: "A",
		name: "Consolidated weight",
		description: "The measured consolidated weight.",
		key: "CONSOLIDATED_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AAA",
		name: "Net weight",
		description:
			"Weight of goods including any packaging that normally going with the goods.",
		key: "NET_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AAB",
		name: "Goods item gross weight",
		description:
			"Weight (mass) of goods including packing but excluding the carrier's equipment.",
		key: "GOODS_ITEM_GROSS_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AAC",
		name: "Total net weight",
		description: "Total weight of goods excluding packaging.",
		key: "TOTAL_NET_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AAD",
		name: "Consignment gross weight",
		description:
			"Total gross weight (mass) of all goods items referred to as one consignment including packaging but excluding any transport equipment.",
		key: "CONSIGNMENT_GROSS_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AAF",
		name: "Net net weight",
		description: "Weight (mass) if goods without any packaging.",
		key: "NET_NET_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AAG",
		name: "Stern thrust",
		description:
			"Force exerted by a thruster installed at the stern of a vessel.",
		key: "STERN_THRUST",
	},
	{
		"@source": "6313",
		value: "AAH",
		name: "Bow thrust",
		description:
			"Force exerted by a thruster installed at the bow of a vessel.",
		key: "BOW_THRUST",
	},
	{
		"@source": "6313",
		value: "AAI",
		name: "Hydrate content of an alcoholic product at bottling",
		description:
			"The hydrate content of an alcoholic product at the moment of bottling.",
		key: "HYDRATE_CONTENT_OF_AN_ALCOHOLIC_PRODUCT_AT_BOTTLING",
	},
	{
		"@source": "6313",
		value: "AAJ",
		name: "Number of units per pallet",
		description: "The number of units contained on a pallet.",
		key: "NUMBER_OF_UNITS_PER_PALLET",
	},
	{
		"@source": "6313",
		value: "AAK",
		name: "Fat content",
		description: "An indication of the fat content of a product.",
		key: "FAT_CONTENT",
	},
	{
		"@source": "6313",
		value: "AAM",
		name: "Transport means gross weight",
		description:
			"The measure of the overall size of a ship determined in accordance with the provisions of the International Convention on Tonnage Measurement of Ships.",
		key: "TRANSPORT_MEANS_GROSS_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AAN",
		name: "Net tonnage of the vessel",
		description:
			"The measure of the useful capacity of a ship determined in accordance with the provisions of the International Convention on Tonnage Measurement of Ships.",
		key: "NET_TONNAGE_OF_THE_VESSEL",
	},
	{
		"@source": "6313",
		value: "AAO",
		name: "Humidity",
		description: "Degree of moisture.",
		key: "HUMIDITY",
	},
	{
		"@source": "6313",
		value: "AAP",
		name: "Voltage",
		description:
			"Electromotive force, or difference of electronic potential between two points.",
		key: "VOLTAGE",
	},
	{
		"@source": "6313",
		value: "AAQ",
		name: "Power consumption",
		description: "Value of energy consumption.",
		key: "POWER_CONSUMPTION",
	},
	{
		"@source": "6313",
		value: "AAR",
		name: "Heat dissipation",
		description: "Measurement of the rate of dispersal of heat.",
		key: "HEAT_DISSIPATION",
	},
	{
		"@source": "6313",
		value: "AAS",
		name: "Air flow",
		description: "Measurement of the flow of air.",
		key: "AIR_FLOW",
	},
	{
		"@source": "6313",
		value: "AAT",
		name: "Shock impact",
		description: "Measurement of the impact of a shock.",
		key: "SHOCK_IMPACT",
	},
	{
		"@source": "6313",
		value: "AAU",
		name: "Operative temperature",
		description:
			"Temperature identified system or process works according to specifications.",
		key: "OPERATIVE_TEMPERATURE",
	},
	{
		"@source": "6313",
		value: "AAV",
		name: "Non operative temperature",
		description:
			"Temperature identified system or process does not work according to specifications.",
		key: "NON_OPERATIVE_TEMPERATURE",
	},
	{
		"@source": "6313",
		value: "AAW",
		name: "Gross volume",
		description:
			"The volume unadjusted for factors such as temperature or gravity.",
		key: "GROSS_VOLUME",
	},
	{
		"@source": "6313",
		value: "AAX",
		name: "Net volume",
		description:
			"The volume after adjustment for factors such as temperature or gravity.",
		key: "NET_VOLUME",
	},
	{
		"@source": "6313",
		value: "AAY",
		name: "Water content",
		description: "Water content in product.",
		key: "WATER_CONTENT",
	},
	{
		"@source": "6313",
		value: "AAZ",
		name: "Tensile stress",
		description: "The measured tensile stress.",
		key: "TENSILE_STRESS",
	},
	{
		"@source": "6313",
		value: "ABA",
		name: "Fibrosity",
		description: "The measured fibrosity.",
		key: "FIBROSITY",
	},
	{
		"@source": "6313",
		value: "ABB",
		name: "Gauge length",
		description: "The measured gauge length.",
		key: "GAUGE_LENGTH",
	},
	{
		"@source": "6313",
		value: "ABC",
		name: "Radius",
		description: "The measured radius.",
		key: "RADIUS",
	},
	{
		"@source": "6313",
		value: "ABD",
		name: "Straightness",
		description: "Straightness of the item.",
		key: "STRAIGHTNESS",
	},
	{
		"@source": "6313",
		value: "ABE",
		name: "Strain",
		description: "The measured strain.",
		key: "STRAIN",
	},
	{
		"@source": "6313",
		value: "ABF",
		name: "Item width when unrolled",
		description: "The width of an item when unrolled.",
		key: "ITEM_WIDTH_WHEN_UNROLLED",
	},
	{
		"@source": "6313",
		value: "ABG",
		name: "Item length when unrolled",
		description: "The length of an item when unrolled.",
		key: "ITEM_LENGTH_WHEN_UNROLLED",
	},
	{
		"@source": "6313",
		value: "ABH",
		name: "Item area when unrolled",
		description: "The area occupied by an item when unrolled.",
		key: "ITEM_AREA_WHEN_UNROLLED",
	},
	{
		"@source": "6313",
		value: "ABI",
		name: "Original wort",
		description:
			"Measure of the malt and hops content of beer, before fermentation has taken place.",
		key: "ORIGINAL_WORT",
	},
	{
		"@source": "6313",
		value: "ABJ",
		name: "Volume",
		description:
			"The amount of air space taken up by the entity identified in the 6311 qualifier.",
		key: "VOLUME",
	},
	{
		"@source": "6313",
		value: "ABK",
		name: "Angle",
		description: "The angle of an object.",
		key: "ANGLE",
	},
	{
		"@source": "6313",
		value: "ABL",
		name: "Peg hole horizontal distance from package leftmost edge",
		description:
			"Horizontal distance from the left most edge of the package to the center of the hole into which the peg is inserted.",
		key: "PEG_HOLE_HORIZONTAL_DISTANCE_FROM_PACKAGE_LEFTMOST_EDGE",
	},
	{
		"@source": "6313",
		value: "ABM",
		name: "Peg hole vertical distance from package top",
		description:
			"Vertical distance from the top of the package to the top of the hole into which the peg is inserted.",
		key: "PEG_HOLE_VERTICAL_DISTANCE_FROM_PACKAGE_TOP",
	},
	{
		"@source": "6313",
		value: "ABN",
		name: "Number of layers per pallet",
		description: "The number of layers per pallet.",
		key: "NUMBER_OF_LAYERS_PER_PALLET",
	},
	{
		"@source": "6313",
		value: "ABO",
		name: "Product strengh, chemical",
		description:
			"The amount of the single active chemical ingredient within a product.",
		key: "PRODUCT_STRENGH_CHEMICAL",
	},
	{
		"@source": "6313",
		value: "ABP",
		name: "Product strength basis, chemical",
		description:
			"Amount of product used as the basis for the specification of the chemical product strenght.",
		key: "PRODUCT_STRENGTH_BASIS_CHEMICAL",
	},
	{
		"@source": "6313",
		value: "ABS",
		name: "Item weight",
		description: "Weight at line item level.",
		key: "ITEM_WEIGHT",
	},
	{
		"@source": "6313",
		value: "ABT",
		name: "Payload weight, maximum",
		description: "The maximum weight of a payload.",
		key: "PAYLOAD_WEIGHT_MAXIMUM",
	},
	{
		"@source": "6313",
		value: "ABX",
		name: "Weight of conveyance",
		description: "Tonnage of conveyance.",
		key: "WEIGHT_OF_CONVEYANCE",
	},
	{
		"@source": "6313",
		value: "ABY",
		name: "Conveyance summer dead weight",
		description: "Registered summer dead weight total tonnage of the vessel.",
		key: "CONVEYANCE_SUMMER_DEAD_WEIGHT",
	},
	{
		"@source": "6313",
		value: "ABZ",
		name: "Containerized cargo on vessel's weight",
		description: "Total weight of containerized cargo on vessel.",
		key: "CONTAINERIZED_CARGO_ON_VESSEL_S_WEIGHT",
	},
	{
		"@source": "6313",
		value: "ACA",
		name: "Non-containerized cargo on vessel's weight",
		description: "Total weight of non-containerized cargo on vessel.",
		key: "NON_CONTAINERIZED_CARGO_ON_VESSEL_S_WEIGHT",
	},
	{
		"@source": "6313",
		value: "ACE",
		name: "Ascertained weight",
		description:
			"Endorsement of the true weight (mass) as ascertained or verified.",
		key: "ASCERTAINED_WEIGHT",
	},
	{
		"@source": "6313",
		value: "ACG",
		name: "Chargeable weight",
		description: "The weight on which charges are based.",
		key: "CHARGEABLE_WEIGHT",
	},
	{
		"@source": "6313",
		value: "ACN",
		name: "Estimated gross weight",
		description:
			"Estimated weight (mass) of goods, including packing and excluding carrier's.",
		key: "ESTIMATED_GROSS_WEIGHT",
	},
	{
		"@source": "6313",
		value: "ACP",
		name: "Estimated volume",
		description: "Estimated size or measure of anything in three dimensions.",
		key: "ESTIMATED_VOLUME",
	},
	{
		"@source": "6313",
		value: "ACS",
		name: "Vessel overall length",
		description: "Total overall length of the vessel.",
		key: "VESSEL_OVERALL_LENGTH",
	},
	{
		"@source": "6313",
		value: "ACV",
		name: "Loading meters",
		description:
			"The length in a vehicle, whereby the complete width and height over that length is needed for the goods.",
		key: "LOADING_METERS",
	},
	{
		"@source": "6313",
		value: "ACW",
		name: "Number of axles",
		description:
			"Number of axles of movable equipment or means of transport on wheels.",
		key: "NUMBER_OF_AXLES",
	},
	{
		"@source": "6313",
		value: "ACX",
		name: "Payload",
		description: "The revenue-producing load carried by a means of transport.",
		key: "PAYLOAD",
	},
	{
		"@source": "6313",
		value: "ADR",
		name: "Start position in the length",
		description:
			"The starting position from the beginning of an item located in the length direction.",
		key: "START_POSITION_IN_THE_LENGTH",
	},
	{
		"@source": "6313",
		value: "ADS",
		name: "End position in the length",
		description:
			"The end position from the beginning of an item located in the length direction.",
		key: "END_POSITION_IN_THE_LENGTH",
	},
	{
		"@source": "6313",
		value: "ADT",
		name: "Start position in the width",
		description:
			"The start position from the beginning of an item located in the width direction.",
		key: "START_POSITION_IN_THE_WIDTH",
	},
	{
		"@source": "6313",
		value: "ADU",
		name: "End position in the width",
		description:
			"The end position from the beginning of an item located in the width direction.",
		key: "END_POSITION_IN_THE_WIDTH",
	},
	{
		"@source": "6313",
		value: "ADV",
		name: "Start position in the thickness",
		description:
			"The start position from the beginning of an item located in the thickness direction.",
		key: "START_POSITION_IN_THE_THICKNESS",
	},
	{
		"@source": "6313",
		value: "ADW",
		name: "End position in the thickness",
		description:
			"The end position from the beginning of an item located in the thickness direction.",
		key: "END_POSITION_IN_THE_THICKNESS",
	},
	{
		"@source": "6313",
		value: "ADX",
		name: "Transport container actual filling weight",
		description: "Actual filling weight of a transport container.",
		key: "TRANSPORT_CONTAINER_ACTUAL_FILLING_WEIGHT",
	},
	{
		"@source": "6313",
		value: "ADY",
		name: "Transport container maximum capacity",
		description: "Maximum capacity of a transport container.",
		key: "TRANSPORT_CONTAINER_MAXIMUM_CAPACITY",
	},
	{
		"@source": "6313",
		value: "ADZ",
		name: "Declared net weight",
		description:
			"The declared net weight of a product or products used for invoicing, customs or transport purposes.",
		key: "DECLARED_NET_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AEA",
		name: "Loading height",
		description:
			"Maximum height of products or packages loaded onto a given transportation device or equipment such as a pallet.",
		key: "LOADING_HEIGHT",
	},
	{
		"@source": "6313",
		value: "AEB",
		name: "Stacking height",
		description:
			"Maximum height up to which the same product or package may be placed one upon the other for storage purposes.",
		key: "STACKING_HEIGHT",
	},
	{
		"@source": "6313",
		value: "AEC",
		name: "Calculated weight",
		description:
			"The calculated weight of the item based on the ordered dimensions.",
		key: "CALCULATED_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AED",
		name: "Ferrite",
		description: "The chemical composition ferrite.",
		key: "FERRITE",
	},
	{
		"@source": "6313",
		value: "AEE",
		name: "Impurity",
		description:
			"The impurity of the product i.e. the measurement of other chemical elements not normally appearing in a product.",
		key: "IMPURITY",
	},
	{
		"@source": "6313",
		value: "AEF",
		name: "Grain size",
		description: "The grain size.",
		key: "GRAIN_SIZE",
	},
	{
		"@source": "6313",
		value: "AEG",
		name: "Lanthanides",
		description: "The chemical element Lanthanides.",
		key: "LANTHANIDES",
	},
	{
		"@source": "6313",
		value: "AEH",
		name: "Elasticity",
		description: "The value of the elasticity.",
		key: "ELASTICITY",
	},
	{
		"@source": "6313",
		value: "AEI",
		name: "Drained weight",
		description:
			"The weight of a product when all liquids used in the packaging of the product have been removed.",
		key: "DRAINED_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AEJ",
		name: "Gallium",
		description: "Measurement of the gallium component.",
		key: "GALLIUM",
	},
	{
		"@source": "6313",
		value: "AEK",
		name: "Strontium",
		description: "Measurement of the strontium component.",
		key: "STRONTIUM",
	},
	{
		"@source": "6313",
		value: "AEL",
		name: "Area",
		description: "Extent or measure of a surface.",
		key: "AREA",
	},
	{
		"@source": "6313",
		value: "AEM",
		name: "Equipment storage limitation",
		description: "Maximum storage limit of the equipment.",
		key: "EQUIPMENT_STORAGE_LIMITATION",
	},
	{
		"@source": "6313",
		value: "AEN",
		name: "Radioactive index of transport",
		description:
			"The index of transport determines the maximum radiation level at a distance of 1m from the external surface.",
		key: "RADIOACTIVE_INDEX_OF_TRANSPORT",
	},
	{
		"@source": "6313",
		value: "AEO",
		name: "Radioactivity",
		description: "Activity of radioactive material.",
		key: "RADIOACTIVITY",
	},
	{
		"@source": "6313",
		value: "AEP",
		name: "Average gross weight",
		description:
			"Weight which is the outcome of the division of the total gross weight by the number of units.",
		key: "AVERAGE_GROSS_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AEQ",
		name: "Forward draft",
		description:
			"Depth of water from the surface of water to the bottom of the vessel measured at the draft mark of the bow.",
		key: "FORWARD_DRAFT",
	},
	{
		"@source": "6313",
		value: "AER",
		name: "After draft",
		description:
			"Depth of water from the surface of water to the bottom of the vessel measured at the draft mark of the stern.",
		key: "AFTER_DRAFT",
	},
	{
		"@source": "6313",
		value: "AES",
		name: "Acidity",
		description: "The quality, state, or degree of being acid.",
		key: "ACIDITY",
	},
	{
		"@source": "6313",
		value: "AET",
		name: "Transport equipment gross weight",
		description:
			"Weight of a transport equipment including the cargo and carrier's equipment.",
		key: "TRANSPORT_EQUIPMENT_GROSS_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AEU",
		name: "Total transport equipment gross weight",
		description:
			"Total weight of all transport equipment including the cargo and carrier's equipment.",
		key: "TOTAL_TRANSPORT_EQUIPMENT_GROSS_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AEV",
		name: "Acidity of juice",
		description: "Acid measurement of juice.",
		key: "ACIDITY_OF_JUICE",
	},
	{
		"@source": "6313",
		value: "AEW",
		name: "Penetrometry",
		description:
			"Measurement of force required to drive a standard penetrating stamp.",
		key: "PENETROMETRY",
	},
	{
		"@source": "6313",
		value: "AEX",
		name: "Durofel",
		description:
			"Measurement of the elastic force using a standard penetrating stamp.",
		key: "DUROFEL",
	},
	{
		"@source": "6313",
		value: "AEY",
		name: "Juice weight per 100 grams",
		description:
			"Measurement of weight of juice, based on 100 grams of the entire weight.",
		key: "JUICE_WEIGHT_PER_100_GRAMS",
	},
	{
		"@source": "6313",
		value: "AEZ",
		name: "Fruit skin colour",
		description: "Measurement of the colouring of the epidermis of a fruit.",
		key: "FRUIT_SKIN_COLOUR",
	},
	{
		"@source": "6313",
		value: "AF",
		name: "Angle of bend",
		description: "The measured angle of bend.",
		key: "ANGLE_OF_BEND",
	},
	{
		"@source": "6313",
		value: "AFA",
		name: "Fixed incremental measurement",
		description: "The measurement of the fixed increment.",
		key: "FIXED_INCREMENTAL_MEASUREMENT",
	},
	{
		"@source": "6313",
		value: "AFB",
		name: "Durofel D10",
		description:
			"Measure of the elastic force of the pulp of a fruit. It is measured with a penetrating stamp with diameter 10.",
		key: "DUROFEL_D10",
	},
	{
		"@source": "6313",
		value: "AFC",
		name: "Durofel D25",
		description:
			"Measure of the elastic force of the pulp of a fruit. It is measured with a penetrating stamp with diameter 25.",
		key: "DUROFEL_D25",
	},
	{
		"@source": "6313",
		value: "AFD",
		name: "Durofel D50",
		description:
			"Measure of the elastic force of the pulp of a fruit. It is measured with a penetrating stamp with diameter 50.",
		key: "DUROFEL_D50",
	},
	{
		"@source": "6313",
		value: "AFE",
		name: "Maximum stacking weight",
		description:
			"The maximum weight which may be stacked upon a product or package without the product or packaging being crushed.",
		key: "MAXIMUM_STACKING_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AFF",
		name: "Gross measure cube",
		description:
			"The total cubic space occupied by an item, taking into account any protruding components, arrived at by multiplying the maximum length, width and height.",
		key: "GROSS_MEASURE_CUBE",
	},
	{
		"@source": "6313",
		value: "AFG",
		name: "Percentage fat content in dry matter",
		description: "The percentage of fat content in dry matter.",
		key: "PERCENTAGE_FAT_CONTENT_IN_DRY_MATTER",
	},
	{
		"@source": "6313",
		value: "AFH",
		name: "Saccharometric content",
		description: "Measurement of the sugar content of a solution.",
		key: "SACCHAROMETRIC_CONTENT",
	},
	{
		"@source": "6313",
		value: "AFI",
		name: "Hydrate content of an alcoholic product after bottling",
		description:
			"The hydrate content which occurs in an alcoholic product after bottling.",
		key: "HYDRATE_CONTENT_OF_AN_ALCOHOLIC_PRODUCT_AFTER_BOTTLING",
	},
	{
		"@source": "6313",
		value: "AFJ",
		name: "Anhydrous content",
		description: "The non-water content.",
		key: "ANHYDROUS_CONTENT",
	},
	{
		"@source": "6313",
		value: "AFK",
		name: "Certified weight",
		description: "Weight which has been certified.",
		key: "CERTIFIED_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AFL",
		name: "Freeboard",
		description:
			"The vertical distance between the waterline and the upper edge of the deck line.",
		key: "FREEBOARD",
	},
	{
		"@source": "6313",
		value: "AFM",
		name: "Maximum vessel draught",
		description:
			"The depth of water needed to float the ship (Maximum vessel draught according to Load Line Certificate IMO, MSC/Circ. 920 15 June 1999).",
		key: "MAXIMUM_VESSEL_DRAUGHT",
	},
	{
		"@source": "6313",
		value: "AFN",
		name: "Net explosive weight",
		description:
			"Mass of the explosive part or substance of goods without any packing.",
		key: "NET_EXPLOSIVE_WEIGHT",
	},
	{
		"@source": "6313",
		value: "AFO",
		name: "Radioactive criticality safety index",
		description:
			"A number, assigned to fissile material i.e. material capable of sustaining a nuclear chain reaction, which is used to provide control over the accumulation of packages containing such material.",
		key: "RADIOACTIVE_CRITICALITY_SAFETY_INDEX",
	},
	{
		"@source": "6313",
		value: "AFP",
		name: "Waste currently on board",
		description: "Amount of waste on board at the moment of the notification.",
		key: "WASTE_CURRENTLY_ON_BOARD",
	},
	{
		"@source": "6313",
		value: "AFQ",
		name: "Waste to be delivered at waste reception facility",
		description:
			"Amount of waste to be delivered to a waste reception facility, e.g. in the port of call.",
		key: "WASTE_TO_BE_DELIVERED_AT_WASTE_RECEPTION_FACILITY",
	},
	{
		"@source": "6313",
		value: "AFR",
		name: "Waste to be generated until next port of call, estimated",
		description:
			"Estimated amount of waste to be generated between creation of the current notification and arrival in the next port of call, irrespective of use of incinerator or compactor or disposal at sea.",
		key: "WASTE_TO_BE_GENERATED_UNTIL_NEXT_PORT_OF_CALL_ESTIMATED",
	},
	{
		"@source": "6313",
		value: "AFS",
		name: "Waste remaining on board at departure",
		description:
			"Amount of waste remaining on board when leaving the port of call.",
		key: "WASTE_REMAINING_ON_BOARD_AT_DEPARTURE",
	},
	{
		"@source": "6313",
		value: "AFT",
		name: "Colour depth",
		description:
			"The number of distinct colours represented, e.g. in an image or in a display.",
		key: "COLOUR_DEPTH",
	},
	{
		"@source": "6313",
		value: "AFU",
		name: "Colour depth, maximum",
		description:
			"The maximum number of distinct colours that can be represented, e.g. in an image or in a display.",
		key: "COLOUR_DEPTH_MAXIMUM",
	},
	{
		"@source": "6313",
		value: "AFV",
		name: "Image resolution",
		description: "The level of detail of an image.",
		key: "IMAGE_RESOLUTION",
	},
	{
		"@source": "6313",
		value: "AFW",
		name: "Device resolution, maximum",
		description: "The maximum level of detail produced by a device.",
		key: "DEVICE_RESOLUTION_MAXIMUM",
	},
	{
		"@source": "6313",
		value: "AFX",
		name: "Acoustic absorption coefficient",
		description:
			"The portion of sound energy a surface absorbs, measured at different frequencies.",
		key: "ACOUSTIC_ABSORPTION_COEFFICIENT",
	},
	{
		"@source": "6313",
		value: "B",
		name: "Billed weight",
		description: "The measured billed weight.",
		key: "BILLED_WEIGHT",
	},
	{
		"@source": "6313",
		value: "BL",
		name: "Breaking load",
		description: "The measured breaking load.",
		key: "BREAKING_LOAD",
	},
	{
		"@source": "6313",
		value: "BMY",
		name: "Platinum",
		description: "The measurement of the platinum component.",
		key: "PLATINUM",
	},
	{
		"@source": "6313",
		value: "BMZ",
		name: "Silver",
		description: "The measurement of the silver component.",
		key: "SILVER",
	},
	{
		"@source": "6313",
		value: "BNA",
		name: "List",
		description:
			"The leaning or inclination of a vessel expressed in degrees port or starboard.",
		key: "LIST",
	},
	{
		"@source": "6313",
		value: "BNB",
		name: "Trim",
		description:
			"The condition of a vessel with reference to its longitudinal axis.",
		key: "TRIM",
	},
	{
		"@source": "6313",
		value: "BNC",
		name: "Free water",
		description:
			"The volume of water present in a container that is not in suspension in the contained liquid.",
		key: "FREE_WATER",
	},
	{
		"@source": "6313",
		value: "BND",
		name: "Bands",
		description: "The measured bands.",
		key: "BANDS",
	},
	{
		"@source": "6313",
		value: "BNE",
		name: "API (American Petroleum Institute) gravity",
		description:
			"The relative density of petroleum liquids as specified by a standard developed by the API.",
		key: "API_AMERICAN_PETROLEUM_INSTITUTE_GRAVITY",
	},
	{
		"@source": "6313",
		value: "BNF",
		name: "Petroleum gross observed volume",
		description:
			"The total volume of all petroleum liquids and sediment and water, excluding free water, at observed temperature and pressure.",
		key: "PETROLEUM_GROSS_OBSERVED_VOLUME",
	},
	{
		"@source": "6313",
		value: "BNG",
		name: "Petroleum gross standard volume",
		description:
			"The total volume of all petroleum liquids, sediment, and water excluding free water, corrected by the appropriate volume correction factor for the observed temperature and American Petroleum Institute relative density, or density to a standard temperature.",
		key: "PETROLEUM_GROSS_STANDARD_VOLUME",
	},
	{
		"@source": "6313",
		value: "BNH",
		name: "Volume variance",
		description: "The change in the volume measurement.",
		key: "VOLUME_VARIANCE",
	},
	{
		"@source": "6313",
		value: "BNI",
		name: "Petroleum net standard volume",
		description:
			"The total volume of all petroleum liquids, excluding sediment and water and free water, corrected by the appropriate volume correction factor for the observed temperature and American Petroleum Institute gravity relative to density or to a standard temperature.",
		key: "PETROLEUM_NET_STANDARD_VOLUME",
	},
	{
		"@source": "6313",
		value: "BNJ",
		name: "Material on-board quantity, after discharge",
		description:
			"The material in vessel tanks, void spaces, and pipelines after discharge.",
		key: "MATERIAL_ON_BOARD_QUANTITY_AFTER_DISCHARGE",
	},
	{
		"@source": "6313",
		value: "BNK",
		name: "Petroleum total calculated volume",
		description:
			"The total volume of all petroleum liquids, sediment and water corrected by the appropriate volume correction factor for the observed temperature and American Petroleum Institute (API) gravity, relative density, or density to a standard temperature.",
		key: "PETROLEUM_TOTAL_CALCULATED_VOLUME",
	},
	{
		"@source": "6313",
		value: "BNL",
		name: "Petroleum total observed volume",
		description:
			"The total volume of all petroleum liquids, sediment and water and free water at observed temperature and pressure.",
		key: "PETROLEUM_TOTAL_OBSERVED_VOLUME",
	},
	{
		"@source": "6313",
		value: "BNM",
		name: "Innage gauge distance",
		description:
			"The measured distance from the surface of the liquid to a fixed datum plate or to the tank bottom.",
		key: "INNAGE_GAUGE_DISTANCE",
	},
	{
		"@source": "6313",
		value: "BNN",
		name: "Petroleum net standard weight",
		description:
			"The total weight of all petroleum liquids excluding sediments, water and free water.",
		key: "PETROLEUM_NET_STANDARD_WEIGHT",
	},
	{
		"@source": "6313",
		value: "BNO",
		name: "Sediment and water in petroleum",
		description:
			"The measurement of non-hydrocarbon solid material and water in suspension in petroleum liquid.",
		key: "SEDIMENT_AND_WATER_IN_PETROLEUM",
	},
	{
		"@source": "6313",
		value: "BNP",
		name: "Observed reference height, tank",
		description:
			"The observed distance from the tank bottom or datum plate to the established reference point.",
		key: "OBSERVED_REFERENCE_HEIGHT_TANK",
	},
	{
		"@source": "6313",
		value: "BNQ",
		name: "Reference height, tank",
		description:
			"The measured distance from the tank bottom or datum plate to the established reference point.",
		key: "REFERENCE_HEIGHT_TANK",
	},
	{
		"@source": "6313",
		value: "BNR",
		name: "Ullage gauge distance",
		description:
			"The measured distance from the cargo liquid surface to the reference point.",
		key: "ULLAGE_GAUGE_DISTANCE",
	},
	{
		"@source": "6313",
		value: "BNS",
		name: "Trim correction",
		description:
			"The correction applied to the observed gauge or observed volume when a vessel is not on an even keel.",
		key: "TRIM_CORRECTION",
	},
	{
		"@source": "6313",
		value: "BNT",
		name: "Bow to bridge distance",
		description: "The distance between the bow and the bridge of a vessel.",
		key: "BOW_TO_BRIDGE_DISTANCE",
	},
	{
		"@source": "6313",
		value: "BNU",
		name: "Peg hole number",
		description:
			"Used to identify the peg hole if more than one hole is present in the product or packaging.",
		key: "PEG_HOLE_NUMBER",
	},
	{
		"@source": "6313",
		value: "BNV",
		name: "Number of inner packs",
		description:
			"Indicates the number of non coded physical groupings (inner packs) of next lower level trade items within the current trade item level.",
		key: "NUMBER_OF_INNER_PACKS",
	},
	{
		"@source": "6313",
		value: "BNW",
		name: "Number of next level trade items within inner pack",
		description:
			"The number of next lower level trade items contained within the physical non-coded grouping (inner pack).",
		key: "NUMBER_OF_NEXT_LEVEL_TRADE_ITEMS_WITHIN_INNER_PACK",
	},
	{
		"@source": "6313",
		value: "BNX",
		name: "Number of trade items per pallet layer",
		description:
			"The number of trade items contained on a single layer of a pallet.",
		key: "NUMBER_OF_TRADE_ITEMS_PER_PALLET_LAYER",
	},
	{
		"@source": "6313",
		value: "BNY",
		name: "Packed items layer height",
		description: "The height of a single layer of packed items.",
		key: "PACKED_ITEMS_LAYER_HEIGHT",
	},
	{
		"@source": "6313",
		value: "BNZ",
		name: "Packing material weight, skin tight covering",
		description:
			"The weight measurement of the packing material used for skin tight covering (e.g. when packaging prepared meats, poultry, cheese, and other food products).",
		key: "PACKING_MATERIAL_WEIGHT_SKIN_TIGHT_COVERING",
	},
	{
		"@source": "6313",
		value: "BR",
		name: "Brightness",
		description: "The measured brightness.",
		key: "BRIGHTNESS",
	},
	{
		"@source": "6313",
		value: "BRA",
		name: "Brakes",
		description: "The measured brakes.",
		key: "BRAKES",
	},
	{
		"@source": "6313",
		value: "BRB",
		name: "Components labelled for recycling percentage",
		description:
			"Percentage of trade item components that clearly label how to facilitate product disassembly and recycling.",
		key: "COMPONENTS_LABELLED_FOR_RECYCLING_PERCENTAGE",
	},
	{
		"@source": "6313",
		value: "BRC",
		name: "Renewable plastic components percentage, by net weight",
		description:
			"The percentage of the plastic components only made from rapidly renewable plant-based material by net weight of product.",
		key: "RENEWABLE_PLASTIC_COMPONENTS_PERCENTAGE_BY_NET_WEIGHT",
	},
	{
		"@source": "6313",
		value: "BRD",
		name: "Clamp pressure, required",
		description: "The pressure that should be applied by a clamp.",
		key: "CLAMP_PRESSURE_REQUIRED",
	},
	{
		"@source": "6313",
		value: "BRE",
		name: "Break",
		description: "The measured break.",
		key: "BREAK",
	},
	{
		"@source": "6313",
		value: "BRF",
		name: "Ascertained volume",
		description: "Endorsement of the true volume as ascertained or verified.",
		key: "ASCERTAINED_VOLUME",
	},
	{
		"@source": "6313",
		value: "BRG",
		name: "Unit weight",
		description: "The weight of a unit.",
		key: "UNIT_WEIGHT",
	},
	{
		"@source": "6313",
		value: "BRH",
		name: "Total volume",
		description: "Total volume of goods and/or parcels.",
		key: "TOTAL_VOLUME",
	},
	{
		"@source": "6313",
		value: "BRI",
		name: "Unit volume",
		description: "The volume of a unit.",
		key: "UNIT_VOLUME",
	},
	{
		"@source": "6313",
		value: "BRJ",
		name: "Vertical center of gravity",
		description:
			"Distance of vertical center of gravity relative to item's base.",
		key: "VERTICAL_CENTER_OF_GRAVITY",
	},
	{
		"@source": "6313",
		value: "BRK",
		name: "Maximum allowable transport stacking weight",
		description:
			"Maximum weight allowed to be stowed on top of an item during transport.",
		key: "MAXIMUM_ALLOWABLE_TRANSPORT_STACKING_WEIGHT",
	},
	{
		"@source": "6313",
		value: "BRL",
		name: "Carbon Dioxide",
		description: "Measurement of the carbon dioxide (C02) component.",
		key: "CARBON_DIOXIDE",
	},
	{
		"@source": "6313",
		value: "BRM",
		name: "Number of base units per pallet",
		description: "The number of base units contained on a pallet.",
		key: "NUMBER_OF_BASE_UNITS_PER_PALLET",
	},
	{
		"@source": "6313",
		value: "BRN",
		name: "Colony forming unit",
		description:
			"Micro-organism colonies that are to be counted under determined conditions.",
		key: "COLONY_FORMING_UNIT",
	},
	{
		"@source": "6313",
		value: "BRO",
		name: "Diluted liquid volume",
		description:
			"The volume of liquid which results after a dilution agent has been added, e.g. undiluted orange juice of 200ml, after dilution with water the volume of diluted liquid equals 1 litre.",
		key: "DILUTED_LIQUID_VOLUME",
	},
	{
		"@source": "6313",
		value: "BRP",
		name: "Energy efficiency",
		description: "A measurement of the energy efficiency of an article.",
		key: "ENERGY_EFFICIENCY",
	},
	{
		"@source": "6313",
		value: "BRQ",
		name: "Number of layers",
		description:
			"Number of layers of a product or products within a package, container, etc.",
		key: "NUMBER_OF_LAYERS",
	},
	{
		"@source": "6313",
		value: "BRR",
		name: "Maximum demand",
		description:
			"The highest demand recorded during the period of recording of usage of the supply.",
		key: "MAXIMUM_DEMAND",
	},
	{
		"@source": "6313",
		value: "BRS",
		name: "Number of pallet places",
		description:
			"The number of pallet places needed to store or to transport pallets (can be stacked).",
		key: "NUMBER_OF_PALLET_PLACES",
	},
	{
		"@source": "6313",
		value: "BRT",
		name: "Package net measurement, cubed",
		description: "An indication of the net cubed measurement of a package.",
		key: "PACKAGE_NET_MEASUREMENT_CUBED",
	},
	{
		"@source": "6313",
		value: "BRU",
		name: "Power factor",
		description:
			"The ratio of the power dissipated (active power in kW) to the total power (which is the product of the input volts times amps given in kVa). When equipment which uses reactive power is being operated the power factor will be less than one.",
		key: "POWER_FACTOR",
	},
	{
		"@source": "6313",
		value: "BRV",
		name: "Stacking factor excluding bottom item",
		description: "Maximum number of identical items stackable on top of item.",
		key: "STACKING_FACTOR_EXCLUDING_BOTTOM_ITEM",
	},
	{
		"@source": "6313",
		value: "BS",
		name: "Breaking strength",
		description: "The measured breaking strength.",
		key: "BREAKING_STRENGTH",
	},
	{
		"@source": "6313",
		value: "BSW",
		name: "Breaking strength wet",
		description: "The measured breaking strength when wet.",
		key: "BREAKING_STRENGTH_WET",
	},
	{
		"@source": "6313",
		value: "BSX",
		name: "Step size",
		description:
			"An indication of measurements in which options contained within a Customer Specific Article are available, e.g. 10 metre planks of wood may be sold in step sizes of 2 metres.",
		key: "STEP_SIZE",
	},
	{
		"@source": "6313",
		value: "BSY",
		name: "Number of units per package",
		description: "The number of identified units per package.",
		key: "NUMBER_OF_UNITS_PER_PACKAGE",
	},
	{
		"@source": "6313",
		value: "BSZ",
		name: "Number of units per layer",
		description:
			"Number of units of a product or package within one layer of a package, container, etc.",
		key: "NUMBER_OF_UNITS_PER_LAYER",
	},
	{
		"@source": "6313",
		value: "BTA",
		name: "Weight per running metre",
		description:
			"A code used to indicate the weight per running metre of floor coverings over floor area.",
		key: "WEIGHT_PER_RUNNING_METRE",
	},
	{
		"@source": "6313",
		value: "BTB",
		name: "Weight per square metre",
		description:
			"A code used to indicate the weight per square metre of floor coverings over floor area.",
		key: "WEIGHT_PER_SQUARE_METRE",
	},
	{
		"@source": "6313",
		value: "BTC",
		name: "Acidity of meat",
		description: "The meat's acid quality or condition.",
		key: "ACIDITY_OF_MEAT",
	},
	{
		"@source": "6313",
		value: "BTD",
		name: "Slaughtering weight",
		description: "Weight immediately after slaughter.",
		key: "SLAUGHTERING_WEIGHT",
	},
	{
		"@source": "6313",
		value: "BTE",
		name: "Stacking factor including bottom item",
		description:
			"Maximum number of items stackable upon each other, including the bottom item.",
		key: "STACKING_FACTOR_INCLUDING_BOTTOM_ITEM",
	},
	{
		"@source": "6313",
		value: "BTF",
		name: "Number of units in the width of a layer",
		description:
			"Number of units of a product or package which make up the width of a layer in a package, container, pallet, etc.",
		key: "NUMBER_OF_UNITS_IN_THE_WIDTH_OF_A_LAYER",
	},
	{
		"@source": "6313",
		value: "BTG",
		name: "Number of units in the depth of a layer",
		description:
			"Number of units of a product or package which make up the depth of a layer in a package, container, pallet, etc.",
		key: "NUMBER_OF_UNITS_IN_THE_DEPTH_OF_A_LAYER",
	},
	{
		"@source": "6313",
		value: "BTH",
		name: "Nestable percentage",
		description:
			"Extent expressed as a percentage to which an item can be nested within an identical item, e.g. paper cups.",
		key: "NESTABLE_PERCENTAGE",
	},
	{
		"@source": "6313",
		value: "BTI",
		name: "Gross weight including carrier's equipment",
		description:
			"Weight (mass) of goods including packaging and the carrier's equipment. In this context 'carrier's equipment' means any material resources necessary to facilitate the transport and handling of the goods without having the ability to move by its own propulsion, e.g. pallet, container, etc.",
		key: "GROSS_WEIGHT_INCLUDING_CARRIER_S_EQUIPMENT",
	},
	{
		"@source": "6313",
		value: "BTJ",
		name: "Sugar content",
		description: "The rate of sugar.",
		key: "SUGAR_CONTENT",
	},
	{
		"@source": "6313",
		value: "BTK",
		name: "Self-accelerating polymerization temperature (SAPT)",
		description:
			"The lowest temperature at which polymerization may occur for a substance as packed for transport.",
		key: "SELF_ACCELERATING_POLYMERIZATION_TEMPERATURE_SAPT",
	},
	{
		"@source": "6313",
		value: "BTL",
		name: "Self-accelerating decomposition temperature (SADT)",
		description:
			"The lowest temperature at which self-accelerating decomposition may occur for a substance as packed for transport.",
		key: "SELF_ACCELERATING_DECOMPOSITION_TEMPERATURE_SADT",
	},
	{
		"@source": "6313",
		value: "BTM",
		name: "Control temperature",
		description:
			"The controlled transport temperature to avoid decomposition of self-reactive substances and organic peroxides.",
		key: "CONTROL_TEMPERATURE",
	},
	{
		"@source": "6313",
		value: "BW",
		name: "Basis weight",
		description: "The measured basis weight.",
		key: "BASIS_WEIGHT",
	},
	{
		"@source": "6313",
		value: "CHN",
		name: "Change",
		description: "The measured change.",
		key: "CHANGE",
	},
	{
		"@source": "6313",
		value: "CHO",
		name: "Emergency temperature",
		description:
			"The temperature at which emergency response is required for self-reactive substances and organic peroxides.",
		key: "EMERGENCY_TEMPERATURE",
	},
	{
		"@source": "6313",
		value: "CM",
		name: "Colour",
		description: "The measured colour.",
		key: "COLOUR",
	},
	{
		"@source": "6313",
		value: "CT",
		name: "Contents of package",
		description:
			"In combination with the other data elements of the actual segment this code indicates the measured content of a package.",
		key: "CONTENTS_OF_PACKAGE",
	},
	{
		"@source": "6313",
		value: "CV",
		name: "Commercial weight",
		description: "Item weight considering its maximum possible humidity.",
		key: "COMMERCIAL_WEIGHT",
	},
	{
		"@source": "6313",
		value: "CZ",
		name: "Core length",
		description: "To specify length of core on which product is to be placed.",
		key: "CORE_LENGTH",
	},
	{
		"@source": "6313",
		value: "D",
		name: "Destination weight agreement",
		description:
			"The agreed weight of despatched goods whose weight may change during transport.",
		key: "DESTINATION_WEIGHT_AGREEMENT",
	},
	{
		"@source": "6313",
		value: "DI",
		name: "Diameter",
		description: "Diameter of an article.",
		key: "DIAMETER",
	},
	{
		"@source": "6313",
		value: "DL",
		name: "Delta value L",
		description: "The measured delta value L.",
		key: "DELTA_VALUE_L",
	},
	{
		"@source": "6313",
		value: "DN",
		name: "Density",
		description: "The measured density.",
		key: "DENSITY",
	},
	{
		"@source": "6313",
		value: "DP",
		name: "Depth",
		description: "The measured depth.",
		key: "DEPTH",
	},
	{
		"@source": "6313",
		value: "DR",
		name: "Denier",
		description: "The measured fineness of a material.",
		key: "DENIER",
	},
	{
		"@source": "6313",
		value: "DS",
		name: "Distance between points",
		description: "The measured distance between points.",
		key: "DISTANCE_BETWEEN_POINTS",
	},
	{
		"@source": "6313",
		value: "DW",
		name: "Width, boxcar door",
		description: "The measured width of a boxcar door.",
		key: "WIDTH_BOXCAR_DOOR",
	},
	{
		"@source": "6313",
		value: "E",
		name: "Estimated new weight",
		description: "The measured estimated new weight.",
		key: "ESTIMATED_NEW_WEIGHT",
	},
	{
		"@source": "6313",
		value: "EA",
		name: "Elongation",
		description: "The measured elongation.",
		key: "ELONGATION",
	},
	{
		"@source": "6313",
		value: "F",
		name: "Deficit weight",
		description: "The measured deficit weight.",
		key: "DEFICIT_WEIGHT",
	},
	{
		"@source": "6313",
		value: "FI",
		name: "Filament count",
		description: "Used e.g. in textile, print industries.",
		key: "FILAMENT_COUNT",
	},
	{
		"@source": "6313",
		value: "FL",
		name: "Longitudinal flatness",
		description: "The measured longitudinal flatness.",
		key: "LONGITUDINAL_FLATNESS",
	},
	{
		"@source": "6313",
		value: "FN",
		name: "Flatness",
		description: "The measured flatness.",
		key: "FLATNESS",
	},
	{
		"@source": "6313",
		value: "FV",
		name: "Transverse flatness",
		description: "The measured transverse flatness.",
		key: "TRANSVERSE_FLATNESS",
	},
	{
		"@source": "6313",
		value: "GG",
		name: "Gauge",
		description: "The measured gauge.",
		key: "GAUGE",
	},
	{
		"@source": "6313",
		value: "GW",
		name: "Gross weight, maximum",
		description: "The measured maximum gross weight.",
		key: "GROSS_WEIGHT_MAXIMUM",
	},
	{
		"@source": "6313",
		value: "HF",
		name: "Hardness",
		description: "The measured hardness.",
		key: "HARDNESS",
	},
	{
		"@source": "6313",
		value: "HM",
		name: "Height, maximum",
		description: "The measured maximum height.",
		key: "HEIGHT_MAXIMUM",
	},
	{
		"@source": "6313",
		value: "HT",
		name: "Height dimension",
		description: "Numeric value of height.",
		key: "HEIGHT_DIMENSION",
	},
	{
		"@source": "6313",
		value: "IB",
		name: "Impact energy",
		description: "The measured impact energy.",
		key: "IMPACT_ENERGY",
	},
	{
		"@source": "6313",
		value: "ID",
		name: "Inside diameter",
		description: "The measured inside diameter.",
		key: "INSIDE_DIAMETER",
	},
	{
		"@source": "6313",
		value: "L",
		name: "Legal weight",
		description: "The measured legal weight.",
		key: "LEGAL_WEIGHT",
	},
	{
		"@source": "6313",
		value: "LM",
		name: "Length, maximum",
		description: "The measured maximum length.",
		key: "LENGTH_MAXIMUM",
	},
	{
		"@source": "6313",
		value: "LN",
		name: "Length",
		description: "To specify the value of a length dimension.",
		key: "LENGTH",
	},
	{
		"@source": "6313",
		value: "LND",
		name: "Lost end",
		description: "The measured lost end.",
		key: "LOST_END",
	},
	{
		"@source": "6313",
		value: "M",
		name: "Minimum weight",
		description: "The measured minimum weight.",
		key: "MINIMUM_WEIGHT",
	},
	{
		"@source": "6313",
		value: "MO",
		name: "Moisture",
		description: "Measurement application is the moisture content of the item.",
		key: "MOISTURE",
	},
	{
		"@source": "6313",
		value: "MW",
		name: "Maximum weight",
		description: "The measured maximum weight.",
		key: "MAXIMUM_WEIGHT",
	},
	{
		"@source": "6313",
		value: "N",
		name: "Actual net weight",
		description: "The actual weight of the goods excluding packaging.",
		key: "ACTUAL_NET_WEIGHT",
	},
	{
		"@source": "6313",
		value: "OD",
		name: "Outside diameter",
		description: "The measured outside diameter.",
		key: "OUTSIDE_DIAMETER",
	},
	{
		"@source": "6313",
		value: "PRS",
		name: "Pre stretch",
		description:
			"Measurement identifying the amount an item has been stretched prior to use.",
		key: "PRE_STRETCH",
	},
	{
		"@source": "6313",
		value: "PTN",
		name: "Per tonne",
		description: "A measurement per tonne.",
		key: "PER_TONNE",
	},
	{
		"@source": "6313",
		value: "RA",
		name: "Relative humidity",
		description: "The measured relative humidity.",
		key: "RELATIVE_HUMIDITY",
	},
	{
		"@source": "6313",
		value: "RF",
		name: "Resistivity",
		description: "The measured resistivity.",
		key: "RESISTIVITY",
	},
	{
		"@source": "6313",
		value: "RJ",
		name: "Rockwell C",
		description: "Hardness in the Rockwell C scale.",
		key: "ROCKWELL_C",
	},
	{
		"@source": "6313",
		value: "RMW",
		name: "Ream weight",
		description: "Measurement indication for paper.",
		key: "REAM_WEIGHT",
	},
	{
		"@source": "6313",
		value: "RP",
		name: "Reduction of area",
		description: "The measured reduction of area.",
		key: "REDUCTION_OF_AREA",
	},
	{
		"@source": "6313",
		value: "RUN",
		name: "Run (process)",
		description: "The measured run (process).",
		key: "RUN_PROCESS",
	},
	{
		"@source": "6313",
		value: "RY",
		name: "Ratio",
		description: "The measured ratio.",
		key: "RATIO",
	},
	{
		"@source": "6313",
		value: "SQ",
		name: "Shipped quantity",
		description: "The measured shipped quantity.",
		key: "SHIPPED_QUANTITY",
	},
	{
		"@source": "6313",
		value: "T",
		name: "Tare weight",
		description: "Weight excluding goods and loose accessories.",
		key: "TARE_WEIGHT",
	},
	{
		"@source": "6313",
		value: "TC",
		name: "Temperature",
		description: "A measurement in relation to temperature.",
		key: "TEMPERATURE",
	},
	{
		"@source": "6313",
		value: "TH",
		name: "Thickness",
		description: "The measured thickness.",
		key: "THICKNESS",
	},
	{
		"@source": "6313",
		value: "TN",
		name: "Time period",
		description: "Measurement of a specific length of time.",
		key: "TIME_PERIOD",
	},
	{
		"@source": "6313",
		value: "TT",
		name: "Time",
		description: "The measured time.",
		key: "TIME",
	},
	{
		"@source": "6313",
		value: "VGM",
		name: "Transport equipment verified gross mass (weight)",
		description:
			"The gross mass (weight) of the transport equipment verified according to SOLAS Chapter VI, Regulation 2, paragraphs 4-6.",
		key: "TRANSPORT_EQUIPMENT_VERIFIED_GROSS_MASS_WEIGHT",
	},
	{
		"@source": "6313",
		value: "VH",
		name: "Height, van door",
		description: "The height of the door of a van or container.",
		key: "HEIGHT_VAN_DOOR",
	},
	{
		"@source": "6313",
		value: "VW",
		name: "Width, van door",
		description: "The width of the door of a van or container.",
		key: "WIDTH_VAN_DOOR",
	},
	{
		"@source": "6313",
		value: "WA",
		name: "Weight per unit of area",
		description: "The weight per unit of an area.",
		key: "WEIGHT_PER_UNIT_OF_AREA",
	},
	{
		"@source": "6313",
		value: "WD",
		name: "Width dimension",
		description: "Numeric value of width.",
		key: "WIDTH_DIMENSION",
	},
	{
		"@source": "6313",
		value: "WM",
		name: "Width, maximum",
		description: "The maximum distance from side to side.",
		key: "WIDTH_MAXIMUM",
	},
	{
		"@source": "6313",
		value: "WU",
		name: "Weight per unit of length",
		description: "The weight per unit of length.",
		key: "WEIGHT_PER_UNIT_OF_LENGTH",
	},
	{
		"@source": "6313",
		value: "XH",
		name: "Side height, flat bed with removable sides",
		description: "The height of the removable sides of a flat bed truck.",
		key: "SIDE_HEIGHT_FLAT_BED_WITH_REMOVABLE_SIDES",
	},
	{
		"@source": "6313",
		value: "XQ",
		name: "Squareness",
		description: "The measured squareness.",
		key: "SQUARENESS",
	},
	{
		"@source": "6313",
		value: "XZ",
		name: "Spool size",
		description: "The measured spool size.",
		key: "SPOOL_SIZE",
	},
	{
		"@source": "6313",
		value: "YS",
		name: "Yield stress",
		description: "The measured yield stress.",
		key: "YIELD_STRESS",
	},
	{
		"@source": "6313",
		value: "ZAL",
		name: "Aluminium",
		description: "The measured chemical element aluminium.",
		key: "ALUMINIUM",
	},
	{
		"@source": "6313",
		value: "ZAS",
		name: "Arsenic",
		description: "The measured chemical element arsenic.",
		key: "ARSENIC",
	},
	{
		"@source": "6313",
		value: "ZB",
		name: "Boron",
		description: "The measured chemical element boron.",
		key: "BORON",
	},
	{
		"@source": "6313",
		value: "ZBI",
		name: "Bismuth",
		description: "The measured chemical element bismuth.",
		key: "BISMUTH",
	},
	{
		"@source": "6313",
		value: "ZC",
		name: "Carbon",
		description: "The measured chemical element carbon.",
		key: "CARBON",
	},
	{
		"@source": "6313",
		value: "ZCA",
		name: "Calcium",
		description: "The measured chemical element calcium.",
		key: "CALCIUM",
	},
	{
		"@source": "6313",
		value: "ZCB",
		name: "Columbium",
		description: "The measured chemical element columbium.",
		key: "COLUMBIUM",
	},
	{
		"@source": "6313",
		value: "ZCE",
		name: "Cerium",
		description: "The measured chemical element cerium.",
		key: "CERIUM",
	},
	{
		"@source": "6313",
		value: "ZCL",
		name: "Chlorine",
		description: "The measured chemical element chlorine.",
		key: "CHLORINE",
	},
	{
		"@source": "6313",
		value: "ZCO",
		name: "Cobalt",
		description: "The measured chemical element cobalt.",
		key: "COBALT",
	},
	{
		"@source": "6313",
		value: "ZCR",
		name: "Chromium",
		description: "The measured chemical element chromium.",
		key: "CHROMIUM",
	},
	{
		"@source": "6313",
		value: "ZCU",
		name: "Copper",
		description: "The measured chemical element copper.",
		key: "COPPER",
	},
	{
		"@source": "6313",
		value: "ZFE",
		name: "Iron",
		description: "The measured chemical element iron.",
		key: "IRON",
	},
	{
		"@source": "6313",
		value: "ZFS",
		name: "Iron plus silicon",
		description: "The measured substance iron plus silicon.",
		key: "IRON_PLUS_SILICON",
	},
	{
		"@source": "6313",
		value: "ZGE",
		name: "Germanium",
		description: "The measured chemical element germanium.",
		key: "GERMANIUM",
	},
	{
		"@source": "6313",
		value: "ZH",
		name: "Hydrogen",
		description: "The measured chemical element hydrogen.",
		key: "HYDROGEN",
	},
	{
		"@source": "6313",
		value: "ZK",
		name: "Potassium",
		description: "The measured chemical element potassium.",
		key: "POTASSIUM",
	},
	{
		"@source": "6313",
		value: "ZMG",
		name: "Magnesium",
		description: "The measured chemical element magnesium.",
		key: "MAGNESIUM",
	},
	{
		"@source": "6313",
		value: "ZMN",
		name: "Manganese",
		description: "The measured chemical element manganese.",
		key: "MANGANESE",
	},
	{
		"@source": "6313",
		value: "ZMO",
		name: "Molybdenum",
		description: "The measured chemical element molybdenum.",
		key: "MOLYBDENUM",
	},
	{
		"@source": "6313",
		value: "ZN",
		name: "Nitrogen",
		description: "The measured chemical element nitrogen.",
		key: "NITROGEN",
	},
	{
		"@source": "6313",
		value: "ZNA",
		name: "Sodium",
		description: "The measured chemical element sodium.",
		key: "SODIUM",
	},
	{
		"@source": "6313",
		value: "ZNB",
		name: "Niobium",
		description: "The chemical element niobium.",
		key: "NIOBIUM",
	},
	{
		"@source": "6313",
		value: "ZNI",
		name: "Nickel",
		description: "The measured chemical element nickel.",
		key: "NICKEL",
	},
	{
		"@source": "6313",
		value: "ZO",
		name: "Oxygen",
		description: "The measured chemical element oxygen.",
		key: "OXYGEN",
	},
	{
		"@source": "6313",
		value: "ZP",
		name: "Phosphorus",
		description: "The measured chemical element phosphorus.",
		key: "PHOSPHORUS",
	},
	{
		"@source": "6313",
		value: "ZPB",
		name: "Lead",
		description: "The measured chemical element lead.",
		key: "LEAD",
	},
	{
		"@source": "6313",
		value: "ZS",
		name: "Sulphur",
		description: "The measured chemical element sulphur.",
		key: "SULPHUR",
	},
	{
		"@source": "6313",
		value: "ZSB",
		name: "Antimony",
		description: "The measured chemical element antimony.",
		key: "ANTIMONY",
	},
	{
		"@source": "6313",
		value: "ZSE",
		name: "Selenium",
		description: "The measured chemical element selenium.",
		key: "SELENIUM",
	},
	{
		"@source": "6313",
		value: "ZSI",
		name: "Silicon",
		description: "The measured chemical element silicon.",
		key: "SILICON",
	},
	{
		"@source": "6313",
		value: "ZSL",
		name: "Silicium oxyd",
		description: "The measured substance silicium oxyd.",
		key: "SILICIUM_OXYD",
	},
	{
		"@source": "6313",
		value: "ZSN",
		name: "Tin",
		description: "The measured chemical element tin.",
		key: "TIN",
	},
	{
		"@source": "6313",
		value: "ZTA",
		name: "Tantalium",
		description: "The measured chemical element tantalium.",
		key: "TANTALIUM",
	},
	{
		"@source": "6313",
		value: "ZTE",
		name: "Tellurium",
		description: "The measured chemical element tellurium.",
		key: "TELLURIUM",
	},
	{
		"@source": "6313",
		value: "ZTI",
		name: "Titanium",
		description: "The measured chemical element titanium.",
		key: "TITANIUM",
	},
	{
		"@source": "6313",
		value: "ZV",
		name: "Vanadium",
		description: "The measured chemical element vanadium.",
		key: "VANADIUM",
	},
	{
		"@source": "6313",
		value: "ZW",
		name: "Tungsten",
		description: "The measured chemical element tungsten.",
		key: "TUNGSTEN",
	},
	{
		"@source": "6313",
		value: "ZWA",
		name: "Waste content",
		description: "The measured waste content.",
		key: "WASTE_CONTENT",
	},
	{
		"@source": "6313",
		value: "ZZN",
		name: "Zinc",
		description: "The measured chemical element zinc.",
		key: "ZINC",
	},
	{
		"@source": "6313",
		value: "ZZR",
		name: "Zirconium",
		description: "The measured chemical element zirconium.",
		key: "ZIRCONIUM",
	},
	{
		"@source": "6313",
		value: "ZZZ",
		name: "Mutually defined",
		description:
			"A code assigned within a code list to be used on an interim basis and as defined among trading partners until a precise code can be assigned to the code list.",
		key: "MUTUALLY_DEFINED",
	},
	{
		"@source": "Factur-X",
		value: "BEST_BEFORE_DATE",
		name: "Best before date",
		key: "BEST_BEFORE_DATE",
	},
	{
		"@source": "Factur-X",
		value: "COLOR_TEXT",
		name: "Colour as text",
		key: "COLOUR_AS_TEXT",
	},
	{
		"@source": "Factur-X",
		value: "COMMISSION",
		name: "Commission indicator",
		description: "true / false",
		key: "COMMISSION_INDICATOR",
	},
	{
		"@source": "Factur-X",
		value: "DEPOSIT_SYSTEM",
		name: "Deposit system",
		description: "Permitted values:\n\nDISPOSABLE\nRETURNABLE",
		key: "DEPOSIT_SYSTEM",
	},
	{
		"@source": "Factur-X",
		value: "DEPOSIT_TYPE",
		name: "Deposit type",
		description: "Permitted values:\n\nPRODUCT_PACKAGING\nTRANSPORT_EQUIPMENT",
		key: "DEPOSIT_TYPE",
	},
	{
		"@source": "Factur-X",
		value: "ENERGY_CLASS",
		name: "Energy efficiency class",
		key: "ENERGY_EFFICIENCY_CLASS",
	},
	{
		"@source": "Factur-X",
		value: "EXPIRATION_DATE",
		name: "Expiration date",
		key: "EXPIRATION_DATE",
	},
	{
		"@source": "Factur-X",
		value: "FEE",
		name: "Fee indicator",
		description: "true = item is a fee",
		key: "FEE_INDICATOR",
	},
	{
		"@source": "Factur-X",
		value: "KIND_OF_ARTICLE",
		name: "Type of article",
		description: "Allowed values:\nGOODS\nOTHER_SERVICES",
		key: "TYPE_OF_ARTICLE",
	},
	{
		"@source": "Factur-X",
		value: "MATERIAL",
		name: "Material of the product",
		key: "MATERIAL_OF_THE_PRODUCT",
	},
	{
		"@source": "Factur-X",
		value: "METER_LOCATION",
		name: "Metering point designation, e.g. for electricity or gas",
		key: "METERING_POINT_DESIGNATION_E_G_FOR_ELECTRICITY_OR_GAS",
	},
	{
		"@source": "Factur-X",
		value: "METER_NUMBER",
		name: "Meter number, e.g. for electricity or gas",
		key: "METER_NUMBER_E_G_FOR_ELECTRICITY_OR_GAS",
	},
	{
		"@source": "Factur-X",
		value: "ORGANIC_CONTROL_BODY",
		name: "Organic control body number",
		key: "ORGANIC_CONTROL_BODY_NUMBER",
	},
	{
		"@source": "Factur-X",
		value: "PACKAGING_MATERIAL",
		name: "Packaging material",
		key: "PACKAGING_MATERIAL",
	},
	{
		"@source": "Factur-X",
		value: "PACKAGING_TYPE",
		name: "Type of packaging (code)",
		description:
			"Type of packaging in coded form. The packaging units from Rec 20 / Rec 21 are used as the code list. Example XBO=bottle",
		key: "TYPE_OF_PACKAGING_CODE",
	},
	{
		"@source": "Factur-X",
		value: "PROMOTIONAL_VARIANT",
		name: "Number of the action variant",
		key: "NUMBER_OF_THE_ACTION_VARIANT",
	},
	{
		"@source": "Factur-X",
		value: "SEAL_NUMBER",
		name: "Seal number",
		key: "SEAL_NUMBER",
	},
	{
		"@source": "Factur-X",
		value: "SIZE_CODE",
		name: "Size code",
		description: "Size information in coded form",
		key: "SIZE_CODE",
	},
	{
		"@source": "Factur-X",
		value: "SIZE_TEXT",
		name: "Size designation",
		description: "Size specifications in text form",
		key: "SIZE_DESIGNATION",
	},
	{
		"@source": "Factur-X",
		value: "TRADING_UNIT",
		name: "Type of trading unit",
		description:
			"Permitted values:\nMIXED_ASSORTMENT = Assortment\nUNMIXED_UNIT = Container",
		key: "TYPE_OF_TRADING_UNIT",
	},
	{
		"@source": "Factur-X",
		value: "WASTE_CODE",
		name: "Waste code (EWC)",
		description: "Waste code according to the European Waste Catalogue (EWC)",
		key: "WASTE_CODE_EWC",
	},
	{
		"@source": "Factur-X",
		value: "WASTE_FRACTION",
		name: "Waste fraction",
		key: "WASTE_FRACTION",
	},
	{
		"@source": "Factur-X",
		value: "WEEE_NUMBER",
		name: "WEEE registration number",
		description: "WEEE registration number of the manufacturer of the product",
		key: "WEEE_REGISTRATION_NUMBER",
	},
] as const satisfies Codelist;

declare module "@node-zugferd/core" {
	interface ZugferdCodelistRegistry {
		characteristic: typeof characteristic;
	}
}
registerCodelist("characteristic", characteristic);

export default characteristic;
