import type { Codelist } from "@node-zugferd/core";
import { registerCodelist } from "@node-zugferd/data-types";

const country = [
	{ name: "Andorra", value: "AD", key: "ANDORRA" },
	{
		name: "United Arab Emirates (the)",
		value: "AE",
		key: "UNITED_ARAB_EMIRATES_THE",
	},
	{ name: "Afghanistan", value: "AF", key: "AFGHANISTAN" },
	{ name: "Antigua and Barbuda", value: "AG", key: "ANTIGUA_AND_BARBUDA" },
	{ name: "Anguilla", value: "AI", key: "ANGUILLA" },
	{ name: "Albania", value: "AL", key: "ALBANIA" },
	{ name: "Armenia", value: "AM", key: "ARMENIA" },
	{ name: "Angola", value: "AO", key: "ANGOLA" },
	{ name: "Antarctica", value: "AQ", key: "ANTARCTICA" },
	{ name: "Argentina", value: "AR", key: "ARGENTINA" },
	{ name: "American Samoa", value: "AS", key: "AMERICAN_SAMOA" },
	{ name: "Austria", value: "AT", key: "AUSTRIA" },
	{ name: "Australia", value: "AU", key: "AUSTRALIA" },
	{ name: "Aruba", value: "AW", key: "ARUBA" },
	{ name: "Åland Islands", value: "AX", key: "A_LAND_ISLANDS" },
	{ name: "Azerbaijan", value: "AZ", key: "AZERBAIJAN" },
	{
		name: "Bosnia and Herzegovina",
		value: "BA",
		key: "BOSNIA_AND_HERZEGOVINA",
	},
	{ name: "Barbados", value: "BB", key: "BARBADOS" },
	{ name: "Bangladesh", value: "BD", key: "BANGLADESH" },
	{ name: "Belgium", value: "BE", key: "BELGIUM" },
	{ name: "Burkina Faso", value: "BF", key: "BURKINA_FASO" },
	{ name: "Bulgaria", value: "BG", key: "BULGARIA" },
	{ name: "Bahrain", value: "BH", key: "BAHRAIN" },
	{ name: "Burundi", value: "BI", key: "BURUNDI" },
	{ name: "Benin", value: "BJ", key: "BENIN" },
	{ name: "Saint Barthélemy", value: "BL", key: "SAINT_BARTHE_LEMY" },
	{ name: "Bermuda", value: "BM", key: "BERMUDA" },
	{ name: "Brunei Darussalam", value: "BN", key: "BRUNEI_DARUSSALAM" },
	{
		name: "Bolivia (Plurinational State of)",
		value: "BO",
		key: "BOLIVIA_PLURINATIONAL_STATE_OF",
	},
	{
		name: "Bonaire, Sint Eustatius and Saba",
		value: "BQ",
		key: "BONAIRE_SINT_EUSTATIUS_AND_SABA",
	},
	{ name: "Brazil", value: "BR", key: "BRAZIL" },
	{ name: "Bahamas (the)", value: "BS", key: "BAHAMAS_THE" },
	{ name: "Bhutan", value: "BT", key: "BHUTAN" },
	{ name: "Bouvet Island", value: "BV", key: "BOUVET_ISLAND" },
	{ name: "Botswana", value: "BW", key: "BOTSWANA" },
	{ name: "Belarus", value: "BY", key: "BELARUS" },
	{ name: "Belize", value: "BZ", key: "BELIZE" },
	{ name: "Canada", value: "CA", key: "CANADA" },
	{
		name: "Cocos (Keeling) Islands (the)",
		value: "CC",
		key: "COCOS_KEELING_ISLANDS_THE",
	},
	{
		name: "Congo (the Democratic Republic of the)",
		value: "CD",
		key: "CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE",
	},
	{
		name: "Central African Republic (the)",
		value: "CF",
		key: "CENTRAL_AFRICAN_REPUBLIC_THE",
	},
	{ name: "Congo (the)", value: "CG", key: "CONGO_THE" },
	{ name: "Switzerland", value: "CH", key: "SWITZERLAND" },
	{ name: "Côte d'Ivoire", value: "CI", key: "CO_TE_D_IVOIRE" },
	{ name: "Cook Islands (the)", value: "CK", key: "COOK_ISLANDS_THE" },
	{ name: "Chile", value: "CL", key: "CHILE" },
	{ name: "Cameroon", value: "CM", key: "CAMEROON" },
	{ name: "China", value: "CN", key: "CHINA" },
	{ name: "Colombia", value: "CO", key: "COLOMBIA" },
	{ name: "Costa Rica", value: "CR", key: "COSTA_RICA" },
	{ name: "Cuba", value: "CU", key: "CUBA" },
	{ name: "Cabo Verde", value: "CV", key: "CABO_VERDE" },
	{ name: "Curaçao", value: "CW", key: "CURAC_AO" },
	{ name: "Christmas Island", value: "CX", key: "CHRISTMAS_ISLAND" },
	{ name: "Cyprus", value: "CY", key: "CYPRUS" },
	{ name: "Czechia", value: "CZ", key: "CZECHIA" },
	{ name: "Germany", value: "DE", key: "GERMANY" },
	{ name: "Djibouti", value: "DJ", key: "DJIBOUTI" },
	{ name: "Denmark", value: "DK", key: "DENMARK" },
	{ name: "Dominica", value: "DM", key: "DOMINICA" },
	{
		name: "Dominican Republic (the)",
		value: "DO",
		key: "DOMINICAN_REPUBLIC_THE",
	},
	{ name: "Algeria", value: "DZ", key: "ALGERIA" },
	{ name: "Ecuador", value: "EC", key: "ECUADOR" },
	{ name: "Estonia", value: "EE", key: "ESTONIA" },
	{ name: "Egypt", value: "EG", key: "EGYPT" },
	{ name: "Western Sahara*", value: "EH", key: "WESTERN_SAHARA" },
	{ name: "Eritrea", value: "ER", key: "ERITREA" },
	{ name: "Spain", value: "ES", key: "SPAIN" },
	{ name: "Ethiopia", value: "ET", key: "ETHIOPIA" },
	{ name: "Finland", value: "FI", key: "FINLAND" },
	{ name: "Fiji", value: "FJ", key: "FIJI" },
	{
		name: "Falkland Islands (the) [Malvinas]",
		value: "FK",
		key: "FALKLAND_ISLANDS_THE_MALVINAS",
	},
	{
		name: "Micronesia (Federated States of)",
		value: "FM",
		key: "MICRONESIA_FEDERATED_STATES_OF",
	},
	{ name: "Faroe Islands (the)", value: "FO", key: "FAROE_ISLANDS_THE" },
	{ name: "France", value: "FR", key: "FRANCE" },
	{ name: "Gabon", value: "GA", key: "GABON" },
	{
		name: "United Kingdom of Great Britain and Northern Ireland (the)",
		value: "GB",
		key: "UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND_THE",
	},
	{ name: "Grenada", value: "GD", key: "GRENADA" },
	{ name: "Georgia", value: "GE", key: "GEORGIA" },
	{ name: "French Guiana", value: "GF", key: "FRENCH_GUIANA" },
	{ name: "Guernsey", value: "GG", key: "GUERNSEY" },
	{ name: "Ghana", value: "GH", key: "GHANA" },
	{ name: "Gibraltar", value: "GI", key: "GIBRALTAR" },
	{ name: "Greenland", value: "GL", key: "GREENLAND" },
	{ name: "Gambia (the)", value: "GM", key: "GAMBIA_THE" },
	{ name: "Guinea", value: "GN", key: "GUINEA" },
	{ name: "Guadeloupe", value: "GP", key: "GUADELOUPE" },
	{ name: "Equatorial Guinea", value: "GQ", key: "EQUATORIAL_GUINEA" },
	{ name: "Greece", value: "GR", key: "GREECE" },
	{
		name: "South Georgia and the South Sandwich Islands",
		value: "GS",
		key: "SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS",
	},
	{ name: "Guatemala", value: "GT", key: "GUATEMALA" },
	{ name: "Guam", value: "GU", key: "GUAM" },
	{ name: "Guinea-Bissau", value: "GW", key: "GUINEA_BISSAU" },
	{ name: "Guyana", value: "GY", key: "GUYANA" },
	{ name: "Hong Kong", value: "HK", key: "HONG_KONG" },
	{
		name: "Heard Island and McDonald Islands",
		value: "HM",
		key: "HEARD_ISLAND_AND_MC_DONALD_ISLANDS",
	},
	{ name: "Honduras", value: "HN", key: "HONDURAS" },
	{ name: "Croatia", value: "HR", key: "CROATIA" },
	{ name: "Haiti", value: "HT", key: "HAITI" },
	{ name: "Hungary", value: "HU", key: "HUNGARY" },
	{ name: "Indonesia", value: "ID", key: "INDONESIA" },
	{ name: "Ireland", value: "IE", key: "IRELAND" },
	{ name: "Israel", value: "IL", key: "ISRAEL" },
	{ name: "Isle of Man", value: "IM", key: "ISLE_OF_MAN" },
	{ name: "India", value: "IN", key: "INDIA" },
	{
		name: "British Indian Ocean Territory (the)",
		value: "IO",
		key: "BRITISH_INDIAN_OCEAN_TERRITORY_THE",
	},
	{ name: "Iraq", value: "IQ", key: "IRAQ" },
	{
		name: "Iran (Islamic Republic of)",
		value: "IR",
		key: "IRAN_ISLAMIC_REPUBLIC_OF",
	},
	{ name: "Iceland", value: "IS", key: "ICELAND" },
	{ name: "Italy", value: "IT", key: "ITALY" },
	{ name: "Jersey", value: "JE", key: "JERSEY" },
	{ name: "Jamaica", value: "JM", key: "JAMAICA" },
	{ name: "Jordan", value: "JO", key: "JORDAN" },
	{ name: "Japan", value: "JP", key: "JAPAN" },
	{ name: "Kenya", value: "KE", key: "KENYA" },
	{ name: "Kyrgyzstan", value: "KG", key: "KYRGYZSTAN" },
	{ name: "Cambodia", value: "KH", key: "CAMBODIA" },
	{ name: "Kiribati", value: "KI", key: "KIRIBATI" },
	{ name: "Comoros (the)", value: "KM", key: "COMOROS_THE" },
	{ name: "Saint Kitts and Nevis", value: "KN", key: "SAINT_KITTS_AND_NEVIS" },
	{
		name: "Korea (the Democratic People's Republic of)",
		value: "KP",
		key: "KOREA_THE_DEMOCRATIC_PEOPLE_S_REPUBLIC_OF",
	},
	{
		name: "Korea (the Republic of)",
		value: "KR",
		key: "KOREA_THE_REPUBLIC_OF",
	},
	{ name: "Kuwait", value: "KW", key: "KUWAIT" },
	{ name: "Cayman Islands (the)", value: "KY", key: "CAYMAN_ISLANDS_THE" },
	{ name: "Kazakhstan", value: "KZ", key: "KAZAKHSTAN" },
	{
		name: "Lao People's Democratic Republic (the)",
		value: "LA",
		key: "LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC_THE",
	},
	{ name: "Lebanon", value: "LB", key: "LEBANON" },
	{ name: "Saint Lucia", value: "LC", key: "SAINT_LUCIA" },
	{ name: "Liechtenstein", value: "LI", key: "LIECHTENSTEIN" },
	{ name: "Sri Lanka", value: "LK", key: "SRI_LANKA" },
	{ name: "Liberia", value: "LR", key: "LIBERIA" },
	{ name: "Lesotho", value: "LS", key: "LESOTHO" },
	{ name: "Lithuania", value: "LT", key: "LITHUANIA" },
	{ name: "Luxembourg", value: "LU", key: "LUXEMBOURG" },
	{ name: "Latvia", value: "LV", key: "LATVIA" },
	{ name: "Libya", value: "LY", key: "LIBYA" },
	{ name: "Morocco", value: "MA", key: "MOROCCO" },
	{ name: "Monaco", value: "MC", key: "MONACO" },
	{
		name: "Moldova (the Republic of)",
		value: "MD",
		key: "MOLDOVA_THE_REPUBLIC_OF",
	},
	{ name: "Montenegro", value: "ME", key: "MONTENEGRO" },
	{
		name: "Saint Martin (French part)",
		value: "MF",
		key: "SAINT_MARTIN_FRENCH_PART",
	},
	{ name: "Madagascar", value: "MG", key: "MADAGASCAR" },
	{ name: "Marshall Islands (the)", value: "MH", key: "MARSHALL_ISLANDS_THE" },
	{ name: "North Macedonia", value: "MK", key: "NORTH_MACEDONIA" },
	{ name: "Mali", value: "ML", key: "MALI" },
	{ name: "Myanmar", value: "MM", key: "MYANMAR" },
	{ name: "Mongolia", value: "MN", key: "MONGOLIA" },
	{ name: "Macao", value: "MO", key: "MACAO" },
	{
		name: "Northern Mariana Islands (the)",
		value: "MP",
		key: "NORTHERN_MARIANA_ISLANDS_THE",
	},
	{ name: "Martinique", value: "MQ", key: "MARTINIQUE" },
	{ name: "Mauritania", value: "MR", key: "MAURITANIA" },
	{ name: "Montserrat", value: "MS", key: "MONTSERRAT" },
	{ name: "Malta", value: "MT", key: "MALTA" },
	{ name: "Mauritius", value: "MU", key: "MAURITIUS" },
	{ name: "Maldives", value: "MV", key: "MALDIVES" },
	{ name: "Malawi", value: "MW", key: "MALAWI" },
	{ name: "Mexico", value: "MX", key: "MEXICO" },
	{ name: "Malaysia", value: "MY", key: "MALAYSIA" },
	{ name: "Mozambique", value: "MZ", key: "MOZAMBIQUE" },
	{ name: "Namibia", value: "NA", key: "NAMIBIA" },
	{ name: "New Caledonia", value: "NC", key: "NEW_CALEDONIA" },
	{ name: "Niger (the)", value: "NE", key: "NIGER_THE" },
	{ name: "Norfolk Island", value: "NF", key: "NORFOLK_ISLAND" },
	{ name: "Nigeria", value: "NG", key: "NIGERIA" },
	{ name: "Nicaragua", value: "NI", key: "NICARAGUA" },
	{ name: "Netherlands (the)", value: "NL", key: "NETHERLANDS_THE" },
	{ name: "Norway", value: "NO", key: "NORWAY" },
	{ name: "Nepal", value: "NP", key: "NEPAL" },
	{ name: "Nauru", value: "NR", key: "NAURU" },
	{ name: "Niue", value: "NU", key: "NIUE" },
	{ name: "New Zealand", value: "NZ", key: "NEW_ZEALAND" },
	{ name: "Oman", value: "OM", key: "OMAN" },
	{ name: "Panama", value: "PA", key: "PANAMA" },
	{ name: "Peru", value: "PE", key: "PERU" },
	{ name: "French Polynesia", value: "PF", key: "FRENCH_POLYNESIA" },
	{ name: "Papua New Guinea", value: "PG", key: "PAPUA_NEW_GUINEA" },
	{ name: "Philippines (the)", value: "PH", key: "PHILIPPINES_THE" },
	{ name: "Pakistan", value: "PK", key: "PAKISTAN" },
	{ name: "Poland", value: "PL", key: "POLAND" },
	{
		name: "Saint Pierre and Miquelon",
		value: "PM",
		key: "SAINT_PIERRE_AND_MIQUELON",
	},
	{ name: "Pitcairn", value: "PN", key: "PITCAIRN" },
	{ name: "Puerto Rico", value: "PR", key: "PUERTO_RICO" },
	{ name: "Palestine, State of", value: "PS", key: "PALESTINE_STATE_OF" },
	{ name: "Portugal", value: "PT", key: "PORTUGAL" },
	{ name: "Palau", value: "PW", key: "PALAU" },
	{ name: "Paraguay", value: "PY", key: "PARAGUAY" },
	{ name: "Qatar", value: "QA", key: "QATAR" },
	{ name: "Réunion", value: "RE", key: "RE_UNION" },
	{ name: "Romania", value: "RO", key: "ROMANIA" },
	{ name: "Serbia", value: "RS", key: "SERBIA" },
	{
		name: "Russian Federation (the)",
		value: "RU",
		key: "RUSSIAN_FEDERATION_THE",
	},
	{ name: "Rwanda", value: "RW", key: "RWANDA" },
	{ name: "Saudi Arabia", value: "SA", key: "SAUDI_ARABIA" },
	{ name: "Solomon Islands", value: "SB", key: "SOLOMON_ISLANDS" },
	{ name: "Seychelles", value: "SC", key: "SEYCHELLES" },
	{ name: "Sudan (the)", value: "SD", key: "SUDAN_THE" },
	{ name: "Sweden", value: "SE", key: "SWEDEN" },
	{ name: "Singapore", value: "SG", key: "SINGAPORE" },
	{
		name: "Saint Helena, Ascension and Tristan da Cunha",
		value: "SH",
		key: "SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA",
	},
	{ name: "Slovenia", value: "SI", key: "SLOVENIA" },
	{
		name: "Svalbard and Jan Mayen",
		value: "SJ",
		key: "SVALBARD_AND_JAN_MAYEN",
	},
	{ name: "Slovakia", value: "SK", key: "SLOVAKIA" },
	{ name: "Sierra Leone", value: "SL", key: "SIERRA_LEONE" },
	{ name: "San Marino", value: "SM", key: "SAN_MARINO" },
	{ name: "Senegal", value: "SN", key: "SENEGAL" },
	{ name: "Somalia", value: "SO", key: "SOMALIA" },
	{ name: "Suriname", value: "SR", key: "SURINAME" },
	{ name: "South Sudan", value: "SS", key: "SOUTH_SUDAN" },
	{ name: "Sao Tome and Principe", value: "ST", key: "SAO_TOME_AND_PRINCIPE" },
	{ name: "El Salvador", value: "SV", key: "EL_SALVADOR" },
	{
		name: "Sint Maarten (Dutch part)",
		value: "SX",
		key: "SINT_MAARTEN_DUTCH_PART",
	},
	{
		name: "Syrian Arab Republic (the)",
		value: "SY",
		key: "SYRIAN_ARAB_REPUBLIC_THE",
	},
	{ name: "Eswatini", value: "SZ", key: "ESWATINI" },
	{
		name: "Turks and Caicos Islands (the)",
		value: "TC",
		key: "TURKS_AND_CAICOS_ISLANDS_THE",
	},
	{ name: "Chad", value: "TD", key: "CHAD" },
	{
		name: "French Southern Territories (the)",
		value: "TF",
		key: "FRENCH_SOUTHERN_TERRITORIES_THE",
	},
	{ name: "Togo", value: "TG", key: "TOGO" },
	{ name: "Thailand", value: "TH", key: "THAILAND" },
	{ name: "Tajikistan", value: "TJ", key: "TAJIKISTAN" },
	{ name: "Tokelau", value: "TK", key: "TOKELAU" },
	{ name: "Timor-Leste", value: "TL", key: "TIMOR_LESTE" },
	{ name: "Turkmenistan", value: "TM", key: "TURKMENISTAN" },
	{ name: "Tunisia", value: "TN", key: "TUNISIA" },
	{ name: "Tonga", value: "TO", key: "TONGA" },
	{ name: "Türkiye", value: "TR", key: "TU_RKIYE" },
	{ name: "Trinidad and Tobago", value: "TT", key: "TRINIDAD_AND_TOBAGO" },
	{ name: "Tuvalu", value: "TV", key: "TUVALU" },
	{
		name: "Taiwan (Province of China)",
		value: "TW",
		key: "TAIWAN_PROVINCE_OF_CHINA",
	},
	{
		name: "Tanzania, the United Republic of",
		value: "TZ",
		key: "TANZANIA_THE_UNITED_REPUBLIC_OF",
	},
	{ name: "Ukraine", value: "UA", key: "UKRAINE" },
	{ name: "Uganda", value: "UG", key: "UGANDA" },
	{
		name: "United States Minor Outlying Islands (the)",
		value: "UM",
		key: "UNITED_STATES_MINOR_OUTLYING_ISLANDS_THE",
	},
	{
		name: "United States of America (the)",
		value: "US",
		key: "UNITED_STATES_OF_AMERICA_THE",
	},
	{ name: "Uruguay", value: "UY", key: "URUGUAY" },
	{ name: "Uzbekistan", value: "UZ", key: "UZBEKISTAN" },
	{ name: "Holy See (the)", value: "VA", key: "HOLY_SEE_THE" },
	{
		name: "Saint Vincent and the Grenadines",
		value: "VC",
		key: "SAINT_VINCENT_AND_THE_GRENADINES",
	},
	{
		name: "Venezuela (Bolivarian Republic of)",
		value: "VE",
		key: "VENEZUELA_BOLIVARIAN_REPUBLIC_OF",
	},
	{
		name: "Virgin Islands (British)",
		value: "VG",
		key: "VIRGIN_ISLANDS_BRITISH",
	},
	{ name: "Virgin Islands (U.S.)", value: "VI", key: "VIRGIN_ISLANDS_U_S" },
	{ name: "Viet Nam", value: "VN", key: "VIET_NAM" },
	{ name: "Vanuatu", value: "VU", key: "VANUATU" },
	{ name: "Wallis and Futuna", value: "WF", key: "WALLIS_AND_FUTUNA" },
	{ name: "Samoa", value: "WS", key: "SAMOA" },
	{ name: "Yemen", value: "YE", key: "YEMEN" },
	{ name: "Mayotte", value: "YT", key: "MAYOTTE" },
	{ name: "South Africa", value: "ZA", key: "SOUTH_AFRICA" },
	{ name: "Zambia", value: "ZM", key: "ZAMBIA" },
	{ name: "Zimbabwe", value: "ZW", key: "ZIMBABWE" },
	{ name: "Kosovo", value: "1A", key: "KOSOVO" },
	{
		name: "United Kingdom (Northern Ireland)",
		value: "XI",
		key: "UNITED_KINGDOM_NORTHERN_IRELAND",
	},
] as const satisfies Codelist;

declare module "@node-zugferd/core" {
	interface ZugferdCodelistRegistry {
		country: typeof country;
	}
}
registerCodelist("country", country);

export default country;
