import type { Codelist } from "@node-zugferd/core";
import { registerCodelist } from "@node-zugferd/data-types";

const untdid1153 = [
	{
		value: "AAA",
		name: "Order acknowledgement document identifier",
		key: "ORDER_ACKNOWLEDGEMENT_DOCUMENT_IDENTIFIER",
	},
	{
		value: "AAB",
		name: "Proforma invoice document identifier",
		key: "PROFORMA_INVOICE_DOCUMENT_IDENTIFIER",
	},
	{
		value: "AAC",
		name: "Documentary credit identifier",
		key: "DOCUMENTARY_CREDIT_IDENTIFIER",
	},
	{
		value: "AAD",
		name: "Contract document addendum identifier",
		key: "CONTRACT_DOCUMENT_ADDENDUM_IDENTIFIER",
	},
	{
		value: "AAE",
		name: "Goods declaration number",
		key: "GOODS_DECLARATION_NUMBER",
	},
	{ value: "AAF", name: "Debit card number", key: "DEBIT_CARD_NUMBER" },
	{ value: "AAG", name: "Offer number", key: "OFFER_NUMBER" },
	{
		value: "AAH",
		name: "Bank's batch interbank transaction reference number",
		key: "BANK_S_BATCH_INTERBANK_TRANSACTION_REFERENCE_NUMBER",
	},
	{
		value: "AAI",
		name: "Bank's individual interbank transaction reference number",
		key: "BANK_S_INDIVIDUAL_INTERBANK_TRANSACTION_REFERENCE_NUMBER",
	},
	{ value: "AAJ", name: "Delivery order number", key: "DELIVERY_ORDER_NUMBER" },
	{
		value: "AAK",
		name: "Despatch advice number",
		key: "DESPATCH_ADVICE_NUMBER",
	},
	{ value: "AAL", name: "Drawing number", key: "DRAWING_NUMBER" },
	{ value: "AAM", name: "Waybill number", key: "WAYBILL_NUMBER" },
	{
		value: "AAN",
		name: "Delivery schedule number",
		key: "DELIVERY_SCHEDULE_NUMBER",
	},
	{
		value: "AAO",
		name: "Consignment identifier, consignee assigned",
		key: "CONSIGNMENT_IDENTIFIER_CONSIGNEE_ASSIGNED",
	},
	{
		value: "AAP",
		name: "Partial shipment identifier",
		key: "PARTIAL_SHIPMENT_IDENTIFIER",
	},
	{
		value: "AAQ",
		name: "Transport equipment identifier",
		key: "TRANSPORT_EQUIPMENT_IDENTIFIER",
	},
	{
		value: "AAR",
		name: "Municipality assigned business registry number",
		key: "MUNICIPALITY_ASSIGNED_BUSINESS_REGISTRY_NUMBER",
	},
	{
		value: "AAS",
		name: "Transport contract document identifier",
		key: "TRANSPORT_CONTRACT_DOCUMENT_IDENTIFIER",
	},
	{ value: "AAT", name: "Master label number", key: "MASTER_LABEL_NUMBER" },
	{
		value: "AAU",
		name: "Despatch note document identifier",
		key: "DESPATCH_NOTE_DOCUMENT_IDENTIFIER",
	},
	{ value: "AAV", name: "Enquiry number", key: "ENQUIRY_NUMBER" },
	{ value: "AAW", name: "Docket number", key: "DOCKET_NUMBER" },
	{ value: "AAX", name: "Civil action number", key: "CIVIL_ACTION_NUMBER" },
	{
		value: "AAY",
		name: "Carrier's agent reference number",
		key: "CARRIER_S_AGENT_REFERENCE_NUMBER",
	},
	{
		value: "AAZ",
		name: "Standard Carrier Alpha Code (SCAC) number",
		key: "STANDARD_CARRIER_ALPHA_CODE_SCAC_NUMBER",
	},
	{
		value: "ABA",
		name: "Customs valuation decision number",
		key: "CUSTOMS_VALUATION_DECISION_NUMBER",
	},
	{
		value: "ABB",
		name: "End use authorization number",
		key: "END_USE_AUTHORIZATION_NUMBER",
	},
	{
		value: "ABC",
		name: "Anti-dumping case number",
		key: "ANTI_DUMPING_CASE_NUMBER",
	},
	{ value: "ABD", name: "Customs tariff number", key: "CUSTOMS_TARIFF_NUMBER" },
	{
		value: "ABE",
		name: "Declarant's reference number",
		key: "DECLARANT_S_REFERENCE_NUMBER",
	},
	{
		value: "ABF",
		name: "Repair estimate number",
		key: "REPAIR_ESTIMATE_NUMBER",
	},
	{
		value: "ABG",
		name: "Customs decision request number",
		key: "CUSTOMS_DECISION_REQUEST_NUMBER",
	},
	{
		value: "ABH",
		name: "Sub-house bill of lading number",
		key: "SUB_HOUSE_BILL_OF_LADING_NUMBER",
	},
	{
		value: "ABI",
		name: "Tax payment identifier",
		key: "TAX_PAYMENT_IDENTIFIER",
	},
	{ value: "ABJ", name: "Quota number", key: "QUOTA_NUMBER" },
	{
		value: "ABK",
		name: "Transit (onward carriage) guarantee (bond) number",
		key: "TRANSIT_ONWARD_CARRIAGE_GUARANTEE_BOND_NUMBER",
	},
	{
		value: "ABL",
		name: "Customs guarantee number",
		key: "CUSTOMS_GUARANTEE_NUMBER",
	},
	{ value: "ABM", name: "Replacing part number", key: "REPLACING_PART_NUMBER" },
	{
		value: "ABN",
		name: "Seller's catalogue number",
		key: "SELLER_S_CATALOGUE_NUMBER",
	},
	{
		value: "ABO",
		name: "Originator's reference",
		key: "ORIGINATOR_S_REFERENCE",
	},
	{
		value: "ABP",
		name: "Declarant's Customs identity number",
		key: "DECLARANT_S_CUSTOMS_IDENTITY_NUMBER",
	},
	{
		value: "ABQ",
		name: "Importer reference number",
		key: "IMPORTER_REFERENCE_NUMBER",
	},
	{
		value: "ABR",
		name: "Export clearance instruction reference number",
		key: "EXPORT_CLEARANCE_INSTRUCTION_REFERENCE_NUMBER",
	},
	{
		value: "ABS",
		name: "Import clearance instruction reference number",
		key: "IMPORT_CLEARANCE_INSTRUCTION_REFERENCE_NUMBER",
	},
	{
		value: "ABT",
		name: "Goods declaration document identifier, Customs",
		key: "GOODS_DECLARATION_DOCUMENT_IDENTIFIER_CUSTOMS",
	},
	{ value: "ABU", name: "Article number", key: "ARTICLE_NUMBER" },
	{ value: "ABV", name: "Intra-plant routing", key: "INTRA_PLANT_ROUTING" },
	{
		value: "ABW",
		name: "Stock keeping unit number",
		key: "STOCK_KEEPING_UNIT_NUMBER",
	},
	{
		value: "ABX",
		name: "Text Element Identifier deletion reference",
		key: "TEXT_ELEMENT_IDENTIFIER_DELETION_REFERENCE",
	},
	{
		value: "ABY",
		name: "Allotment identification (Air)",
		key: "ALLOTMENT_IDENTIFICATION_AIR",
	},
	{
		value: "ABZ",
		name: "Vehicle licence number",
		key: "VEHICLE_LICENCE_NUMBER",
	},
	{
		value: "AC",
		name: " Air cargo transfer manifest",
		key: "AIR_CARGO_TRANSFER_MANIFEST",
	},
	{
		value: "ACA",
		name: "Cargo acceptance order reference number",
		key: "CARGO_ACCEPTANCE_ORDER_REFERENCE_NUMBER",
	},
	{
		value: "ACB",
		name: "US government agency number",
		key: "US_GOVERNMENT_AGENCY_NUMBER",
	},
	{
		value: "ACC",
		name: "Shipping unit identification",
		key: "SHIPPING_UNIT_IDENTIFICATION",
	},
	{
		value: "ACD",
		name: "Additional reference number",
		key: "ADDITIONAL_REFERENCE_NUMBER",
	},
	{
		value: "ACE",
		name: "Related document number",
		key: "RELATED_DOCUMENT_NUMBER",
	},
	{ value: "ACF", name: "Addressee reference", key: "ADDRESSEE_REFERENCE" },
	{ value: "ACG", name: "ATA carnet number", key: "ATA_CARNET_NUMBER" },
	{
		value: "ACH",
		name: "Packaging unit identification",
		key: "PACKAGING_UNIT_IDENTIFICATION",
	},
	{
		value: "ACI",
		name: "Outerpackaging unit identification",
		key: "OUTERPACKAGING_UNIT_IDENTIFICATION",
	},
	{
		value: "ACJ",
		name: "Customer material specification number",
		key: "CUSTOMER_MATERIAL_SPECIFICATION_NUMBER",
	},
	{ value: "ACK", name: "Bank reference", key: "BANK_REFERENCE" },
	{
		value: "ACL",
		name: "Principal reference number",
		key: "PRINCIPAL_REFERENCE_NUMBER",
	},
	{
		value: "ACN",
		name: "Collection advice document identifier",
		key: "COLLECTION_ADVICE_DOCUMENT_IDENTIFIER",
	},
	{ value: "ACO", name: "Iron charge number", key: "IRON_CHARGE_NUMBER" },
	{ value: "ACP", name: "Hot roll number", key: "HOT_ROLL_NUMBER" },
	{ value: "ACQ", name: "Cold roll number", key: "COLD_ROLL_NUMBER" },
	{ value: "ACR", name: "Railway wagon number", key: "RAILWAY_WAGON_NUMBER" },
	{
		value: "ACT",
		name: "Unique claims reference number of the sender",
		key: "UNIQUE_CLAIMS_REFERENCE_NUMBER_OF_THE_SENDER",
	},
	{ value: "ACU", name: "Loss/event number", key: "LOSS_EVENT_NUMBER" },
	{
		value: "ACV",
		name: "Estimate order reference number",
		key: "ESTIMATE_ORDER_REFERENCE_NUMBER",
	},
	{
		value: "ACW",
		name: "Reference number to previous message",
		key: "REFERENCE_NUMBER_TO_PREVIOUS_MESSAGE",
	},
	{ value: "ACX", name: "Banker's acceptance", key: "BANKER_S_ACCEPTANCE" },
	{ value: "ACY", name: "Duty memo number", key: "DUTY_MEMO_NUMBER" },
	{
		value: "ACZ",
		name: "Equipment transport charge number",
		key: "EQUIPMENT_TRANSPORT_CHARGE_NUMBER",
	},
	{ value: "ADA", name: "Buyer's item number", key: "BUYER_S_ITEM_NUMBER" },
	{
		value: "ADB",
		name: "Matured certificate of deposit",
		key: "MATURED_CERTIFICATE_OF_DEPOSIT",
	},
	{ value: "ADC", name: "Loan", key: "LOAN" },
	{
		value: "ADD",
		name: "Analysis number/test number",
		key: "ANALYSIS_NUMBER_TEST_NUMBER",
	},
	{ value: "ADE", name: "Account number", key: "ACCOUNT_NUMBER" },
	{ value: "ADF", name: "Treaty number", key: "TREATY_NUMBER" },
	{ value: "ADG", name: "Catastrophe number", key: "CATASTROPHE_NUMBER" },
	{
		value: "ADI",
		name: "Bureau signing (statement reference)",
		key: "BUREAU_SIGNING_STATEMENT_REFERENCE",
	},
	{
		value: "ADJ",
		name: "Company / syndicate reference 1",
		key: "COMPANY_SYNDICATE_REFERENCE_1",
	},
	{
		value: "ADK",
		name: "Company / syndicate reference 2",
		key: "COMPANY_SYNDICATE_REFERENCE_2",
	},
	{
		value: "ADL",
		name: "Ordering customer consignment reference number",
		key: "ORDERING_CUSTOMER_CONSIGNMENT_REFERENCE_NUMBER",
	},
	{
		value: "ADM",
		name: "Shipowner's authorization number",
		key: "SHIPOWNER_S_AUTHORIZATION_NUMBER",
	},
	{
		value: "ADN",
		name: "Inland transport order number",
		key: "INLAND_TRANSPORT_ORDER_NUMBER",
	},
	{
		value: "ADO",
		name: "Container work order reference number",
		key: "CONTAINER_WORK_ORDER_REFERENCE_NUMBER",
	},
	{ value: "ADP", name: "Statement number", key: "STATEMENT_NUMBER" },
	{
		value: "ADQ",
		name: "Unique market reference",
		key: "UNIQUE_MARKET_REFERENCE",
	},
	{ value: "ADT", name: "Group accounting", key: "GROUP_ACCOUNTING" },
	{ value: "ADU", name: "Broker reference 1", key: "BROKER_REFERENCE_1" },
	{ value: "ADV", name: "Broker reference 2", key: "BROKER_REFERENCE_2" },
	{
		value: "ADW",
		name: "Lloyd's claims office reference",
		key: "LLOYD_S_CLAIMS_OFFICE_REFERENCE",
	},
	{
		value: "ADX",
		name: "Secure delivery terms and conditions agreement reference",
		key: "SECURE_DELIVERY_TERMS_AND_CONDITIONS_AGREEMENT_REFERENCE",
	},
	{ value: "ADY", name: "Report number", key: "REPORT_NUMBER" },
	{ value: "ADZ", name: "Trader account number", key: "TRADER_ACCOUNT_NUMBER" },
	{
		value: "AE",
		name: " Authorization for expense (AFE) number",
		key: "AUTHORIZATION_FOR_EXPENSE_AFE_NUMBER",
	},
	{
		value: "AEA",
		name: "Government agency reference number",
		key: "GOVERNMENT_AGENCY_REFERENCE_NUMBER",
	},
	{ value: "AEB", name: "Assembly number", key: "ASSEMBLY_NUMBER" },
	{ value: "AEC", name: "Symbol number", key: "SYMBOL_NUMBER" },
	{ value: "AED", name: "Commodity number", key: "COMMODITY_NUMBER" },
	{
		value: "AEE",
		name: "Eur 1 certificate number",
		key: "EUR_1_CERTIFICATE_NUMBER",
	},
	{
		value: "AEF",
		name: "Customer process specification number",
		key: "CUSTOMER_PROCESS_SPECIFICATION_NUMBER",
	},
	{
		value: "AEG",
		name: "Customer specification number",
		key: "CUSTOMER_SPECIFICATION_NUMBER",
	},
	{
		value: "AEH",
		name: "Applicable instructions or standards",
		key: "APPLICABLE_INSTRUCTIONS_OR_STANDARDS",
	},
	{
		value: "AEI",
		name: "Registration number of previous Customs declaration",
		key: "REGISTRATION_NUMBER_OF_PREVIOUS_CUSTOMS_DECLARATION",
	},
	{ value: "AEJ", name: "Post-entry reference", key: "POST_ENTRY_REFERENCE" },
	{ value: "AEK", name: "Payment order number", key: "PAYMENT_ORDER_NUMBER" },
	{
		value: "AEL",
		name: "Delivery number (transport)",
		key: "DELIVERY_NUMBER_TRANSPORT",
	},
	{ value: "AEM", name: "Transport route", key: "TRANSPORT_ROUTE" },
	{
		value: "AEN",
		name: "Customer's unit inventory number",
		key: "CUSTOMER_S_UNIT_INVENTORY_NUMBER",
	},
	{
		value: "AEO",
		name: "Product reservation number",
		key: "PRODUCT_RESERVATION_NUMBER",
	},
	{ value: "AEP", name: "Project number", key: "PROJECT_NUMBER" },
	{ value: "AEQ", name: "Drawing list number", key: "DRAWING_LIST_NUMBER" },
	{
		value: "AER",
		name: "Project specification number",
		key: "PROJECT_SPECIFICATION_NUMBER",
	},
	{ value: "AES", name: "Primary reference", key: "PRIMARY_REFERENCE" },
	{
		value: "AET",
		name: "Request for cancellation number",
		key: "REQUEST_FOR_CANCELLATION_NUMBER",
	},
	{
		value: "AEU",
		name: "Supplier's control number",
		key: "SUPPLIER_S_CONTROL_NUMBER",
	},
	{ value: "AEV", name: "Shipping note number", key: "SHIPPING_NOTE_NUMBER" },
	{
		value: "AEW",
		name: "Empty container bill number",
		key: "EMPTY_CONTAINER_BILL_NUMBER",
	},
	{
		value: "AEX",
		name: "Non-negotiable maritime transport document number",
		key: "NON_NEGOTIABLE_MARITIME_TRANSPORT_DOCUMENT_NUMBER",
	},
	{
		value: "AEY",
		name: "Substitute air waybill number",
		key: "SUBSTITUTE_AIR_WAYBILL_NUMBER",
	},
	{
		value: "AEZ",
		name: "Despatch note (post parcels) number",
		key: "DESPATCH_NOTE_POST_PARCELS_NUMBER",
	},
	{
		value: "AF",
		name: " Airlines flight identification number",
		key: "AIRLINES_FLIGHT_IDENTIFICATION_NUMBER",
	},
	{
		value: "AFA",
		name: "Through bill of lading number",
		key: "THROUGH_BILL_OF_LADING_NUMBER",
	},
	{ value: "AFB", name: "Cargo manifest number", key: "CARGO_MANIFEST_NUMBER" },
	{ value: "AFC", name: "Bordereau number", key: "BORDEREAU_NUMBER" },
	{ value: "AFD", name: "Customs item number", key: "CUSTOMS_ITEM_NUMBER" },
	{
		value: "AFE",
		name: "Export Control Commodity number (ECCN)",
		key: "EXPORT_CONTROL_COMMODITY_NUMBER_ECCN",
	},
	{
		value: "AFF",
		name: "Marking/label reference",
		key: "MARKING_LABEL_REFERENCE",
	},
	{ value: "AFG", name: "Tariff number", key: "TARIFF_NUMBER" },
	{
		value: "AFH",
		name: "Replenishment purchase order number",
		key: "REPLENISHMENT_PURCHASE_ORDER_NUMBER",
	},
	{
		value: "AFI",
		name: "Immediate transportation no. for in bond movement",
		key: "IMMEDIATE_TRANSPORTATION_NO_FOR_IN_BOND_MOVEMENT",
	},
	{
		value: "AFJ",
		name: "Transportation exportation no. for in bond movement",
		key: "TRANSPORTATION_EXPORTATION_NO_FOR_IN_BOND_MOVEMENT",
	},
	{
		value: "AFK",
		name: "Immediate exportation no. for in bond movement",
		key: "IMMEDIATE_EXPORTATION_NO_FOR_IN_BOND_MOVEMENT",
	},
	{ value: "AFL", name: "Associated invoices", key: "ASSOCIATED_INVOICES" },
	{
		value: "AFM",
		name: "Secondary Customs reference",
		key: "SECONDARY_CUSTOMS_REFERENCE",
	},
	{
		value: "AFN",
		name: "Account party's reference",
		key: "ACCOUNT_PARTY_S_REFERENCE",
	},
	{
		value: "AFO",
		name: "Beneficiary's reference",
		key: "BENEFICIARY_S_REFERENCE",
	},
	{
		value: "AFP",
		name: "Second beneficiary's reference",
		key: "SECOND_BENEFICIARY_S_REFERENCE",
	},
	{
		value: "AFQ",
		name: "Applicant's bank reference",
		key: "APPLICANT_S_BANK_REFERENCE",
	},
	{
		value: "AFR",
		name: "Issuing bank's reference",
		key: "ISSUING_BANK_S_REFERENCE",
	},
	{
		value: "AFS",
		name: "Beneficiary's bank reference",
		key: "BENEFICIARY_S_BANK_REFERENCE",
	},
	{
		value: "AFT",
		name: "Direct payment valuation number",
		key: "DIRECT_PAYMENT_VALUATION_NUMBER",
	},
	{
		value: "AFU",
		name: "Direct payment valuation request number",
		key: "DIRECT_PAYMENT_VALUATION_REQUEST_NUMBER",
	},
	{
		value: "AFV",
		name: "Quantity valuation number",
		key: "QUANTITY_VALUATION_NUMBER",
	},
	{
		value: "AFW",
		name: "Quantity valuation request number",
		key: "QUANTITY_VALUATION_REQUEST_NUMBER",
	},
	{
		value: "AFX",
		name: "Bill of quantities number",
		key: "BILL_OF_QUANTITIES_NUMBER",
	},
	{
		value: "AFY",
		name: "Payment valuation number",
		key: "PAYMENT_VALUATION_NUMBER",
	},
	{ value: "AFZ", name: "Situation number", key: "SITUATION_NUMBER" },
	{
		value: "AGA",
		name: "Agreement to pay number",
		key: "AGREEMENT_TO_PAY_NUMBER",
	},
	{
		value: "AGB",
		name: "Contract party reference number",
		key: "CONTRACT_PARTY_REFERENCE_NUMBER",
	},
	{
		value: "AGC",
		name: "Account party's bank reference",
		key: "ACCOUNT_PARTY_S_BANK_REFERENCE",
	},
	{
		value: "AGD",
		name: "Agent's bank reference",
		key: "AGENT_S_BANK_REFERENCE",
	},
	{ value: "AGE", name: "Agent's reference", key: "AGENT_S_REFERENCE" },
	{ value: "AGF", name: "Applicant's reference", key: "APPLICANT_S_REFERENCE" },
	{ value: "AGG", name: "Dispute number", key: "DISPUTE_NUMBER" },
	{
		value: "AGH",
		name: "Credit rating agency's reference number",
		key: "CREDIT_RATING_AGENCY_S_REFERENCE_NUMBER",
	},
	{ value: "AGI", name: "Request number", key: "REQUEST_NUMBER" },
	{
		value: "AGJ",
		name: "Single transaction sequence number",
		key: "SINGLE_TRANSACTION_SEQUENCE_NUMBER",
	},
	{
		value: "AGK",
		name: "Application reference number",
		key: "APPLICATION_REFERENCE_NUMBER",
	},
	{
		value: "AGL",
		name: "Delivery verification certificate",
		key: "DELIVERY_VERIFICATION_CERTIFICATE",
	},
	{
		value: "AGM",
		name: "Number of temporary importation document",
		key: "NUMBER_OF_TEMPORARY_IMPORTATION_DOCUMENT",
	},
	{
		value: "AGN",
		name: "Reference number quoted on statement",
		key: "REFERENCE_NUMBER_QUOTED_ON_STATEMENT",
	},
	{
		value: "AGO",
		name: "Sender's reference to the original message",
		key: "SENDER_S_REFERENCE_TO_THE_ORIGINAL_MESSAGE",
	},
	{
		value: "AGP",
		name: "Company issued equipment ID",
		key: "COMPANY_ISSUED_EQUIPMENT_ID",
	},
	{
		value: "AGQ",
		name: "Domestic flight number",
		key: "DOMESTIC_FLIGHT_NUMBER",
	},
	{
		value: "AGR",
		name: "International flight number",
		key: "INTERNATIONAL_FLIGHT_NUMBER",
	},
	{
		value: "AGS",
		name: "Employer identification number of service bureau",
		key: "EMPLOYER_IDENTIFICATION_NUMBER_OF_SERVICE_BUREAU",
	},
	{
		value: "AGT",
		name: "Service group identification number",
		key: "SERVICE_GROUP_IDENTIFICATION_NUMBER",
	},
	{ value: "AGU", name: "Member number", key: "MEMBER_NUMBER" },
	{
		value: "AGV",
		name: "Previous member number",
		key: "PREVIOUS_MEMBER_NUMBER",
	},
	{ value: "AGW", name: "Scheme/plan number", key: "SCHEME_PLAN_NUMBER" },
	{
		value: "AGX",
		name: "Previous scheme/plan number",
		key: "PREVIOUS_SCHEME_PLAN_NUMBER",
	},
	{
		value: "AGY",
		name: "Receiving party's member identification",
		key: "RECEIVING_PARTY_S_MEMBER_IDENTIFICATION",
	},
	{ value: "AGZ", name: "Payroll number", key: "PAYROLL_NUMBER" },
	{
		value: "AHA",
		name: "Packaging specification number",
		key: "PACKAGING_SPECIFICATION_NUMBER",
	},
	{
		value: "AHB",
		name: "Authority issued equipment identification",
		key: "AUTHORITY_ISSUED_EQUIPMENT_IDENTIFICATION",
	},
	{
		value: "AHC",
		name: "Training flight number",
		key: "TRAINING_FLIGHT_NUMBER",
	},
	{ value: "AHD", name: "Fund code number", key: "FUND_CODE_NUMBER" },
	{ value: "AHE", name: "Signal code number", key: "SIGNAL_CODE_NUMBER" },
	{
		value: "AHF",
		name: "Major force program number",
		key: "MAJOR_FORCE_PROGRAM_NUMBER",
	},
	{ value: "AHG", name: "Nomination number", key: "NOMINATION_NUMBER" },
	{
		value: "AHH",
		name: "Laboratory registration number",
		key: "LABORATORY_REGISTRATION_NUMBER",
	},
	{
		value: "AHI",
		name: "Transport contract reference number",
		key: "TRANSPORT_CONTRACT_REFERENCE_NUMBER",
	},
	{
		value: "AHJ",
		name: "Payee's reference number",
		key: "PAYEE_S_REFERENCE_NUMBER",
	},
	{
		value: "AHK",
		name: "Payer's reference number",
		key: "PAYER_S_REFERENCE_NUMBER",
	},
	{
		value: "AHL",
		name: "Creditor's reference number",
		key: "CREDITOR_S_REFERENCE_NUMBER",
	},
	{
		value: "AHM",
		name: "Debtor's reference number",
		key: "DEBTOR_S_REFERENCE_NUMBER",
	},
	{
		value: "AHN",
		name: "Joint venture reference number",
		key: "JOINT_VENTURE_REFERENCE_NUMBER",
	},
	{
		value: "AHO",
		name: "Chamber of Commerce registration number",
		key: "CHAMBER_OF_COMMERCE_REGISTRATION_NUMBER",
	},
	{
		value: "AHP",
		name: "Tax registration number",
		key: "TAX_REGISTRATION_NUMBER",
	},
	{
		value: "AHQ",
		name: "Wool identification number",
		key: "WOOL_IDENTIFICATION_NUMBER",
	},
	{
		value: "AHR",
		name: "Wool tax reference number",
		key: "WOOL_TAX_REFERENCE_NUMBER",
	},
	{
		value: "AHS",
		name: "Meat processing establishment registration number",
		key: "MEAT_PROCESSING_ESTABLISHMENT_REGISTRATION_NUMBER",
	},
	{
		value: "AHT",
		name: "Quarantine/treatment status reference number",
		key: "QUARANTINE_TREATMENT_STATUS_REFERENCE_NUMBER",
	},
	{
		value: "AHU",
		name: "Request for quote number",
		key: "REQUEST_FOR_QUOTE_NUMBER",
	},
	{
		value: "AHV",
		name: "Manual processing authority number",
		key: "MANUAL_PROCESSING_AUTHORITY_NUMBER",
	},
	{ value: "AHX", name: "Rate note number", key: "RATE_NOTE_NUMBER" },
	{
		value: "AHY",
		name: "Freight Forwarder number",
		key: "FREIGHT_FORWARDER_NUMBER",
	},
	{ value: "AHZ", name: "Customs release code", key: "CUSTOMS_RELEASE_CODE" },
	{
		value: "AIA",
		name: "Compliance code number",
		key: "COMPLIANCE_CODE_NUMBER",
	},
	{
		value: "AIB",
		name: "Department of transportation bond number",
		key: "DEPARTMENT_OF_TRANSPORTATION_BOND_NUMBER",
	},
	{
		value: "AIC",
		name: "Export establishment number",
		key: "EXPORT_ESTABLISHMENT_NUMBER",
	},
	{
		value: "AID",
		name: "Certificate of conformity",
		key: "CERTIFICATE_OF_CONFORMITY",
	},
	{
		value: "AIE",
		name: "Ministerial certificate of homologation",
		key: "MINISTERIAL_CERTIFICATE_OF_HOMOLOGATION",
	},
	{
		value: "AIF",
		name: "Previous delivery instruction number",
		key: "PREVIOUS_DELIVERY_INSTRUCTION_NUMBER",
	},
	{ value: "AIG", name: "Passport number", key: "PASSPORT_NUMBER" },
	{
		value: "AIH",
		name: "Common transaction reference number",
		key: "COMMON_TRANSACTION_REFERENCE_NUMBER",
	},
	{
		value: "AII",
		name: "Bank's common transaction reference number",
		key: "BANK_S_COMMON_TRANSACTION_REFERENCE_NUMBER",
	},
	{
		value: "AIJ",
		name: "Customer's individual transaction reference number",
		key: "CUSTOMER_S_INDIVIDUAL_TRANSACTION_REFERENCE_NUMBER",
	},
	{
		value: "AIK",
		name: "Bank's individual transaction reference number",
		key: "BANK_S_INDIVIDUAL_TRANSACTION_REFERENCE_NUMBER",
	},
	{
		value: "AIL",
		name: "Customer's common transaction reference number",
		key: "CUSTOMER_S_COMMON_TRANSACTION_REFERENCE_NUMBER",
	},
	{
		value: "AIM",
		name: "Individual transaction reference number",
		key: "INDIVIDUAL_TRANSACTION_REFERENCE_NUMBER",
	},
	{
		value: "AIN",
		name: "Product sourcing agreement number",
		key: "PRODUCT_SOURCING_AGREEMENT_NUMBER",
	},
	{
		value: "AIO",
		name: "Customs transhipment number",
		key: "CUSTOMS_TRANSHIPMENT_NUMBER",
	},
	{
		value: "AIP",
		name: "Customs preference inquiry number",
		key: "CUSTOMS_PREFERENCE_INQUIRY_NUMBER",
	},
	{ value: "AIQ", name: "Packing plant number", key: "PACKING_PLANT_NUMBER" },
	{
		value: "AIR",
		name: "Original certificate number",
		key: "ORIGINAL_CERTIFICATE_NUMBER",
	},
	{
		value: "AIS",
		name: "Processing plant number",
		key: "PROCESSING_PLANT_NUMBER",
	},
	{
		value: "AIT",
		name: "Slaughter plant number",
		key: "SLAUGHTER_PLANT_NUMBER",
	},
	{
		value: "AIU",
		name: "Charge card account number",
		key: "CHARGE_CARD_ACCOUNT_NUMBER",
	},
	{
		value: "AIV",
		name: "Event reference number",
		key: "EVENT_REFERENCE_NUMBER",
	},
	{
		value: "AIW",
		name: "Transport section reference number",
		key: "TRANSPORT_SECTION_REFERENCE_NUMBER",
	},
	{
		value: "AIX",
		name: "Referred product for mechanical analysis",
		key: "REFERRED_PRODUCT_FOR_MECHANICAL_ANALYSIS",
	},
	{
		value: "AIY",
		name: "Referred product for chemical analysis",
		key: "REFERRED_PRODUCT_FOR_CHEMICAL_ANALYSIS",
	},
	{
		value: "AIZ",
		name: "Consolidated invoice number",
		key: "CONSOLIDATED_INVOICE_NUMBER",
	},
	{
		value: "AJA",
		name: "Part reference indicator in a drawing",
		key: "PART_REFERENCE_INDICATOR_IN_A_DRAWING",
	},
	{
		value: "AJB",
		name: "U.S. Code of Federal Regulations (CFR)",
		key: "U_S_CODE_OF_FEDERAL_REGULATIONS_CFR",
	},
	{
		value: "AJC",
		name: "Purchasing activity clause number",
		key: "PURCHASING_ACTIVITY_CLAUSE_NUMBER",
	},
	{
		value: "AJD",
		name: "U.S. Defense Federal Acquisition Regulation Supplement",
		key: "U_S_DEFENSE_FEDERAL_ACQUISITION_REGULATION_SUPPLEMENT",
	},
	{ value: "AJE", name: "Agency clause number", key: "AGENCY_CLAUSE_NUMBER" },
	{
		value: "AJF",
		name: "Circular publication number",
		key: "CIRCULAR_PUBLICATION_NUMBER",
	},
	{
		value: "AJG",
		name: "U.S. Federal Acquisition Regulation",
		key: "U_S_FEDERAL_ACQUISITION_REGULATION",
	},
	{
		value: "AJH",
		name: "U.S. General Services Administration Regulation",
		key: "U_S_GENERAL_SERVICES_ADMINISTRATION_REGULATION",
	},
	{
		value: "AJI",
		name: "U.S. Federal Information Resources Management Regulation",
		key: "U_S_FEDERAL_INFORMATION_RESOURCES_MANAGEMENT_REGULATION",
	},
	{ value: "AJJ", name: "Paragraph", key: "PARAGRAPH" },
	{
		value: "AJK",
		name: "Special instructions number",
		key: "SPECIAL_INSTRUCTIONS_NUMBER",
	},
	{
		value: "AJL",
		name: "Site specific procedures, terms, and conditions number",
		key: "SITE_SPECIFIC_PROCEDURES_TERMS_AND_CONDITIONS_NUMBER",
	},
	{
		value: "AJM",
		name: "Master solicitation procedures, terms, and conditions",
		key: "MASTER_SOLICITATION_PROCEDURES_TERMS_AND_CONDITIONS",
	},
	{
		value: "AJN",
		name: "U.S. Department of Veterans Affairs Acquisition Regulation",
		key: "U_S_DEPARTMENT_OF_VETERANS_AFFAIRS_ACQUISITION_REGULATION",
	},
	{
		value: "AJO",
		name: "Military Interdepartmental Purchase Request (MIPR) number",
		key: "MILITARY_INTERDEPARTMENTAL_PURCHASE_REQUEST_MIPR_NUMBER",
	},
	{
		value: "AJP",
		name: "Foreign military sales number",
		key: "FOREIGN_MILITARY_SALES_NUMBER",
	},
	{
		value: "AJQ",
		name: "Defense priorities allocation system priority rating",
		key: "DEFENSE_PRIORITIES_ALLOCATION_SYSTEM_PRIORITY_RATING",
	},
	{
		value: "AJR",
		name: "Wage determination number",
		key: "WAGE_DETERMINATION_NUMBER",
	},
	{ value: "AJS", name: "Agreement number", key: "AGREEMENT_NUMBER" },
	{
		value: "AJT",
		name: "Standard Industry Classification (SIC) number",
		key: "STANDARD_INDUSTRY_CLASSIFICATION_SIC_NUMBER",
	},
	{ value: "AJU", name: "End item number", key: "END_ITEM_NUMBER" },
	{
		value: "AJV",
		name: "Federal supply schedule item number",
		key: "FEDERAL_SUPPLY_SCHEDULE_ITEM_NUMBER",
	},
	{
		value: "AJW",
		name: "Technical document number",
		key: "TECHNICAL_DOCUMENT_NUMBER",
	},
	{
		value: "AJX",
		name: "Technical order number",
		key: "TECHNICAL_ORDER_NUMBER",
	},
	{ value: "AJY", name: "Suffix", key: "SUFFIX" },
	{
		value: "AJZ",
		name: "Transportation account number",
		key: "TRANSPORTATION_ACCOUNT_NUMBER",
	},
	{
		value: "AKA",
		name: "Container disposition order reference number",
		key: "CONTAINER_DISPOSITION_ORDER_REFERENCE_NUMBER",
	},
	{ value: "AKB", name: "Container prefix", key: "CONTAINER_PREFIX" },
	{
		value: "AKC",
		name: "Transport equipment return reference",
		key: "TRANSPORT_EQUIPMENT_RETURN_REFERENCE",
	},
	{
		value: "AKD",
		name: "Transport equipment survey reference",
		key: "TRANSPORT_EQUIPMENT_SURVEY_REFERENCE",
	},
	{
		value: "AKE",
		name: "Transport equipment survey report number",
		key: "TRANSPORT_EQUIPMENT_SURVEY_REPORT_NUMBER",
	},
	{
		value: "AKF",
		name: "Transport equipment stuffing order",
		key: "TRANSPORT_EQUIPMENT_STUFFING_ORDER",
	},
	{
		value: "AKG",
		name: "Vehicle Identification Number (VIN)",
		key: "VEHICLE_IDENTIFICATION_NUMBER_VIN",
	},
	{
		value: "AKH",
		name: "Government bill of lading",
		key: "GOVERNMENT_BILL_OF_LADING",
	},
	{
		value: "AKI",
		name: "Ordering customer's second reference number",
		key: "ORDERING_CUSTOMER_S_SECOND_REFERENCE_NUMBER",
	},
	{
		value: "AKJ",
		name: "Direct debit reference",
		key: "DIRECT_DEBIT_REFERENCE",
	},
	{
		value: "AKK",
		name: "Meter reading at the beginning of the delivery",
		key: "METER_READING_AT_THE_BEGINNING_OF_THE_DELIVERY",
	},
	{
		value: "AKL",
		name: "Meter reading at the end of delivery",
		key: "METER_READING_AT_THE_END_OF_DELIVERY",
	},
	{
		value: "AKM",
		name: "Replenishment purchase order range start number",
		key: "REPLENISHMENT_PURCHASE_ORDER_RANGE_START_NUMBER",
	},
	{
		value: "AKN",
		name: "Third bank's reference",
		key: "THIRD_BANK_S_REFERENCE",
	},
	{
		value: "AKO",
		name: "Action authorization number",
		key: "ACTION_AUTHORIZATION_NUMBER",
	},
	{ value: "AKP", name: "Appropriation number", key: "APPROPRIATION_NUMBER" },
	{
		value: "AKQ",
		name: "Product change authority number",
		key: "PRODUCT_CHANGE_AUTHORITY_NUMBER",
	},
	{
		value: "AKR",
		name: "General cargo consignment reference number",
		key: "GENERAL_CARGO_CONSIGNMENT_REFERENCE_NUMBER",
	},
	{
		value: "AKS",
		name: "Catalogue sequence number",
		key: "CATALOGUE_SEQUENCE_NUMBER",
	},
	{
		value: "AKT",
		name: "Forwarding order number",
		key: "FORWARDING_ORDER_NUMBER",
	},
	{
		value: "AKU",
		name: "Transport equipment survey reference number",
		key: "TRANSPORT_EQUIPMENT_SURVEY_REFERENCE_NUMBER",
	},
	{
		value: "AKV",
		name: "Lease contract reference",
		key: "LEASE_CONTRACT_REFERENCE",
	},
	{
		value: "AKW",
		name: "Transport costs reference number",
		key: "TRANSPORT_COSTS_REFERENCE_NUMBER",
	},
	{
		value: "AKX",
		name: "Transport equipment stripping order",
		key: "TRANSPORT_EQUIPMENT_STRIPPING_ORDER",
	},
	{ value: "AKY", name: "Prior policy number", key: "PRIOR_POLICY_NUMBER" },
	{ value: "AKZ", name: "Policy number", key: "POLICY_NUMBER" },
	{
		value: "ALA",
		name: "Procurement budget number",
		key: "PROCUREMENT_BUDGET_NUMBER",
	},
	{
		value: "ALB",
		name: "Domestic inventory management code",
		key: "DOMESTIC_INVENTORY_MANAGEMENT_CODE",
	},
	{
		value: "ALC",
		name: "Customer reference number assigned to previous balance of",
		key: "CUSTOMER_REFERENCE_NUMBER_ASSIGNED_TO_PREVIOUS_BALANCE_OF",
	},
	{
		value: "ALD",
		name: "Previous credit advice reference number",
		key: "PREVIOUS_CREDIT_ADVICE_REFERENCE_NUMBER",
	},
	{ value: "ALE", name: "Reporting form number", key: "REPORTING_FORM_NUMBER" },
	{
		value: "ALF",
		name: "Authorization number for exception to dangerous goods",
		key: "AUTHORIZATION_NUMBER_FOR_EXCEPTION_TO_DANGEROUS_GOODS",
	},
	{
		value: "ALG",
		name: "Dangerous goods security number",
		key: "DANGEROUS_GOODS_SECURITY_NUMBER",
	},
	{
		value: "ALH",
		name: "Dangerous goods transport licence number",
		key: "DANGEROUS_GOODS_TRANSPORT_LICENCE_NUMBER",
	},
	{
		value: "ALI",
		name: "Previous rental agreement number",
		key: "PREVIOUS_RENTAL_AGREEMENT_NUMBER",
	},
	{
		value: "ALJ",
		name: "Next rental agreement reason number",
		key: "NEXT_RENTAL_AGREEMENT_REASON_NUMBER",
	},
	{
		value: "ALK",
		name: "Consignee's invoice number",
		key: "CONSIGNEE_S_INVOICE_NUMBER",
	},
	{ value: "ALL", name: "Message batch number", key: "MESSAGE_BATCH_NUMBER" },
	{
		value: "ALM",
		name: "Previous delivery schedule number",
		key: "PREVIOUS_DELIVERY_SCHEDULE_NUMBER",
	},
	{
		value: "ALN",
		name: "Physical inventory recount reference number",
		key: "PHYSICAL_INVENTORY_RECOUNT_REFERENCE_NUMBER",
	},
	{
		value: "ALO",
		name: "Receiving advice number",
		key: "RECEIVING_ADVICE_NUMBER",
	},
	{
		value: "ALP",
		name: "Returnable container reference number",
		key: "RETURNABLE_CONTAINER_REFERENCE_NUMBER",
	},
	{ value: "ALQ", name: "Returns notice number", key: "RETURNS_NOTICE_NUMBER" },
	{ value: "ALR", name: "Sales forecast number", key: "SALES_FORECAST_NUMBER" },
	{ value: "ALS", name: "Sales report number", key: "SALES_REPORT_NUMBER" },
	{
		value: "ALT",
		name: "Previous tax control number",
		key: "PREVIOUS_TAX_CONTROL_NUMBER",
	},
	{
		value: "ALU",
		name: "AGERD (Aerospace Ground Equipment Requirement Data) number",
		key: "AGERD_AEROSPACE_GROUND_EQUIPMENT_REQUIREMENT_DATA_NUMBER",
	},
	{
		value: "ALV",
		name: "Registered capital reference",
		key: "REGISTERED_CAPITAL_REFERENCE",
	},
	{
		value: "ALW",
		name: "Standard number of inspection document",
		key: "STANDARD_NUMBER_OF_INSPECTION_DOCUMENT",
	},
	{ value: "ALX", name: "Model", key: "MODEL" },
	{
		value: "ALY",
		name: "Financial management reference",
		key: "FINANCIAL_MANAGEMENT_REFERENCE",
	},
	{
		value: "ALZ",
		name: "NOTIfication for COLlection number (NOTICOL)",
		key: "NOT_IFICATION_FOR_CO_LLECTION_NUMBER_NOTICOL",
	},
	{
		value: "AMA",
		name: "Previous request for metered reading reference number",
		key: "PREVIOUS_REQUEST_FOR_METERED_READING_REFERENCE_NUMBER",
	},
	{
		value: "AMB",
		name: "Next rental agreement number",
		key: "NEXT_RENTAL_AGREEMENT_NUMBER",
	},
	{
		value: "AMC",
		name: "Reference number of a request for metered reading",
		key: "REFERENCE_NUMBER_OF_A_REQUEST_FOR_METERED_READING",
	},
	{ value: "AMD", name: "Hastening number", key: "HASTENING_NUMBER" },
	{
		value: "AME",
		name: "Repair data request number",
		key: "REPAIR_DATA_REQUEST_NUMBER",
	},
	{
		value: "AMF",
		name: "Consumption data request number",
		key: "CONSUMPTION_DATA_REQUEST_NUMBER",
	},
	{ value: "AMG", name: "Profile number", key: "PROFILE_NUMBER" },
	{ value: "AMH", name: "Case number", key: "CASE_NUMBER" },
	{
		value: "AMI",
		name: "Government quality assurance and control level Number",
		key: "GOVERNMENT_QUALITY_ASSURANCE_AND_CONTROL_LEVEL_NUMBER",
	},
	{
		value: "AMJ",
		name: "Payment plan reference",
		key: "PAYMENT_PLAN_REFERENCE",
	},
	{
		value: "AMK",
		name: "Replaced meter unit number",
		key: "REPLACED_METER_UNIT_NUMBER",
	},
	{
		value: "AML",
		name: "Replenishment purchase order range end number",
		key: "REPLENISHMENT_PURCHASE_ORDER_RANGE_END_NUMBER",
	},
	{
		value: "AMM",
		name: "Insurer assigned reference number",
		key: "INSURER_ASSIGNED_REFERENCE_NUMBER",
	},
	{
		value: "AMN",
		name: "Canadian excise entry number",
		key: "CANADIAN_EXCISE_ENTRY_NUMBER",
	},
	{ value: "AMO", name: "Premium rate table", key: "PREMIUM_RATE_TABLE" },
	{
		value: "AMP",
		name: "Advise through bank's reference",
		key: "ADVISE_THROUGH_BANK_S_REFERENCE",
	},
	{
		value: "AMQ",
		name: "US, Department of Transportation bond surety code",
		key: "US_DEPARTMENT_OF_TRANSPORTATION_BOND_SURETY_CODE",
	},
	{
		value: "AMR",
		name: "US, Food and Drug Administration establishment indicator",
		key: "US_FOOD_AND_DRUG_ADMINISTRATION_ESTABLISHMENT_INDICATOR",
	},
	{
		value: "AMS",
		name: "US, Federal Communications Commission (FCC) import",
		key: "US_FEDERAL_COMMUNICATIONS_COMMISSION_FCC_IMPORT",
	},
	{
		value: "AMT",
		name: "Goods and Services Tax identification number",
		key: "GOODS_AND_SERVICES_TAX_IDENTIFICATION_NUMBER",
	},
	{
		value: "AMU",
		name: "Integrated logistic support cross reference number",
		key: "INTEGRATED_LOGISTIC_SUPPORT_CROSS_REFERENCE_NUMBER",
	},
	{ value: "AMV", name: "Department number", key: "DEPARTMENT_NUMBER" },
	{
		value: "AMW",
		name: "Buyer's catalogue number",
		key: "BUYER_S_CATALOGUE_NUMBER",
	},
	{
		value: "AMX",
		name: "Financial settlement party's reference number",
		key: "FINANCIAL_SETTLEMENT_PARTY_S_REFERENCE_NUMBER",
	},
	{
		value: "AMY",
		name: "Standard's version number",
		key: "STANDARD_S_VERSION_NUMBER",
	},
	{ value: "AMZ", name: "Pipeline number", key: "PIPELINE_NUMBER" },
	{
		value: "ANA",
		name: "Account servicing bank's reference number",
		key: "ACCOUNT_SERVICING_BANK_S_REFERENCE_NUMBER",
	},
	{
		value: "ANB",
		name: "Completed units payment request reference",
		key: "COMPLETED_UNITS_PAYMENT_REQUEST_REFERENCE",
	},
	{
		value: "ANC",
		name: "Payment in advance request reference",
		key: "PAYMENT_IN_ADVANCE_REQUEST_REFERENCE",
	},
	{ value: "AND", name: "Parent file", key: "PARENT_FILE" },
	{ value: "ANE", name: "Sub file", key: "SUB_FILE" },
	{
		value: "ANF",
		name: "CAD file layer convention",
		key: "CAD_FILE_LAYER_CONVENTION",
	},
	{ value: "ANG", name: "Technical regulation", key: "TECHNICAL_REGULATION" },
	{ value: "ANH", name: "Plot file", key: "PLOT_FILE" },
	{
		value: "ANI",
		name: "File conversion journal",
		key: "FILE_CONVERSION_JOURNAL",
	},
	{ value: "ANJ", name: "Authorization number", key: "AUTHORIZATION_NUMBER" },
	{
		value: "ANK",
		name: "Reference number assigned by third party",
		key: "REFERENCE_NUMBER_ASSIGNED_BY_THIRD_PARTY",
	},
	{
		value: "ANL",
		name: "Deposit reference number",
		key: "DEPOSIT_REFERENCE_NUMBER",
	},
	{
		value: "ANM",
		name: "Named bank's reference",
		key: "NAMED_BANK_S_REFERENCE",
	},
	{ value: "ANN", name: "Drawee's reference", key: "DRAWEE_S_REFERENCE" },
	{
		value: "ANO",
		name: "Case of need party's reference",
		key: "CASE_OF_NEED_PARTY_S_REFERENCE",
	},
	{
		value: "ANP",
		name: "Collecting bank's reference",
		key: "COLLECTING_BANK_S_REFERENCE",
	},
	{
		value: "ANQ",
		name: "Remitting bank's reference",
		key: "REMITTING_BANK_S_REFERENCE",
	},
	{
		value: "ANR",
		name: "Principal's bank reference",
		key: "PRINCIPAL_S_BANK_REFERENCE",
	},
	{
		value: "ANS",
		name: "Presenting bank's reference",
		key: "PRESENTING_BANK_S_REFERENCE",
	},
	{ value: "ANT", name: "Consignee's reference", key: "CONSIGNEE_S_REFERENCE" },
	{
		value: "ANU",
		name: "Financial transaction reference number",
		key: "FINANCIAL_TRANSACTION_REFERENCE_NUMBER",
	},
	{
		value: "ANV",
		name: "Credit reference number",
		key: "CREDIT_REFERENCE_NUMBER",
	},
	{
		value: "ANW",
		name: "Receiving bank's authorization number",
		key: "RECEIVING_BANK_S_AUTHORIZATION_NUMBER",
	},
	{ value: "ANX", name: "Clearing reference", key: "CLEARING_REFERENCE" },
	{
		value: "ANY",
		name: "Sending bank's reference number",
		key: "SENDING_BANK_S_REFERENCE_NUMBER",
	},
	{
		value: "AOA",
		name: "Documentary payment reference",
		key: "DOCUMENTARY_PAYMENT_REFERENCE",
	},
	{
		value: "AOD",
		name: "Accounting file reference",
		key: "ACCOUNTING_FILE_REFERENCE",
	},
	{
		value: "AOE",
		name: "Sender's file reference number",
		key: "SENDER_S_FILE_REFERENCE_NUMBER",
	},
	{
		value: "AOF",
		name: "Receiver's file reference number",
		key: "RECEIVER_S_FILE_REFERENCE_NUMBER",
	},
	{
		value: "AOG",
		name: "Source document internal reference",
		key: "SOURCE_DOCUMENT_INTERNAL_REFERENCE",
	},
	{ value: "AOH", name: "Principal's reference", key: "PRINCIPAL_S_REFERENCE" },
	{
		value: "AOI",
		name: "Debit reference number",
		key: "DEBIT_REFERENCE_NUMBER",
	},
	{ value: "AOJ", name: "Calendar", key: "CALENDAR" },
	{ value: "AOK", name: "Work shift", key: "WORK_SHIFT" },
	{
		value: "AOL",
		name: "Work breakdown structure",
		key: "WORK_BREAKDOWN_STRUCTURE",
	},
	{
		value: "AOM",
		name: "Organisation breakdown structure",
		key: "ORGANISATION_BREAKDOWN_STRUCTURE",
	},
	{
		value: "AON",
		name: "Work task charge number",
		key: "WORK_TASK_CHARGE_NUMBER",
	},
	{ value: "AOO", name: "Functional work group", key: "FUNCTIONAL_WORK_GROUP" },
	{ value: "AOP", name: "Work team", key: "WORK_TEAM" },
	{ value: "AOQ", name: "Department", key: "DEPARTMENT" },
	{ value: "AOR", name: "Statement of work", key: "STATEMENT_OF_WORK" },
	{ value: "AOS", name: "Work package", key: "WORK_PACKAGE" },
	{ value: "AOT", name: "Planning package", key: "PLANNING_PACKAGE" },
	{ value: "AOU", name: "Cost account", key: "COST_ACCOUNT" },
	{ value: "AOV", name: "Work order", key: "WORK_ORDER" },
	{
		value: "AOW",
		name: "Transportation Control Number (TCN)",
		key: "TRANSPORTATION_CONTROL_NUMBER_TCN",
	},
	{ value: "AOX", name: "Constraint notation", key: "CONSTRAINT_NOTATION" },
	{ value: "AOY", name: "ETERMS reference", key: "ETERMS_REFERENCE" },
	{
		value: "AOZ",
		name: "Implementation version number",
		key: "IMPLEMENTATION_VERSION_NUMBER",
	},
	{
		value: "AP",
		name: " Accounts receivable number",
		key: "ACCOUNTS_RECEIVABLE_NUMBER",
	},
	{
		value: "APA",
		name: "Incorporated legal reference",
		key: "INCORPORATED_LEGAL_REFERENCE",
	},
	{
		value: "APB",
		name: "Payment instalment reference number",
		key: "PAYMENT_INSTALMENT_REFERENCE_NUMBER",
	},
	{
		value: "APC",
		name: "Equipment owner reference number",
		key: "EQUIPMENT_OWNER_REFERENCE_NUMBER",
	},
	{ value: "APD", name: "Cedent's claim number", key: "CEDENT_S_CLAIM_NUMBER" },
	{
		value: "APE",
		name: "Reinsurer's claim number",
		key: "REINSURER_S_CLAIM_NUMBER",
	},
	{
		value: "APF",
		name: "Price/sales catalogue response reference number",
		key: "PRICE_SALES_CATALOGUE_RESPONSE_REFERENCE_NUMBER",
	},
	{
		value: "APG",
		name: "General purpose message reference number",
		key: "GENERAL_PURPOSE_MESSAGE_REFERENCE_NUMBER",
	},
	{
		value: "APH",
		name: "Invoicing data sheet reference number",
		key: "INVOICING_DATA_SHEET_REFERENCE_NUMBER",
	},
	{
		value: "API",
		name: "Inventory report reference number",
		key: "INVENTORY_REPORT_REFERENCE_NUMBER",
	},
	{
		value: "APJ",
		name: "Ceiling formula reference number",
		key: "CEILING_FORMULA_REFERENCE_NUMBER",
	},
	{
		value: "APK",
		name: "Price variation formula reference number",
		key: "PRICE_VARIATION_FORMULA_REFERENCE_NUMBER",
	},
	{
		value: "APL",
		name: "Reference to account servicing bank's message",
		key: "REFERENCE_TO_ACCOUNT_SERVICING_BANK_S_MESSAGE",
	},
	{ value: "APM", name: "Party sequence number", key: "PARTY_SEQUENCE_NUMBER" },
	{
		value: "APN",
		name: "Purchaser's request reference",
		key: "PURCHASER_S_REQUEST_REFERENCE",
	},
	{
		value: "APO",
		name: "Contractor request reference",
		key: "CONTRACTOR_REQUEST_REFERENCE",
	},
	{
		value: "APP",
		name: "Accident reference number",
		key: "ACCIDENT_REFERENCE_NUMBER",
	},
	{
		value: "APQ",
		name: "Commercial account summary reference number",
		key: "COMMERCIAL_ACCOUNT_SUMMARY_REFERENCE_NUMBER",
	},
	{
		value: "APR",
		name: "Contract breakdown reference",
		key: "CONTRACT_BREAKDOWN_REFERENCE",
	},
	{
		value: "APS",
		name: "Contractor registration number",
		key: "CONTRACTOR_REGISTRATION_NUMBER",
	},
	{
		value: "APT",
		name: "Applicable coefficient identification number",
		key: "APPLICABLE_COEFFICIENT_IDENTIFICATION_NUMBER",
	},
	{
		value: "APU",
		name: "Special budget account number",
		key: "SPECIAL_BUDGET_ACCOUNT_NUMBER",
	},
	{
		value: "APV",
		name: "Authorisation for repair reference",
		key: "AUTHORISATION_FOR_REPAIR_REFERENCE",
	},
	{
		value: "APW",
		name: "Manufacturer defined repair rates reference",
		key: "MANUFACTURER_DEFINED_REPAIR_RATES_REFERENCE",
	},
	{
		value: "APX",
		name: "Original submitter log number",
		key: "ORIGINAL_SUBMITTER_LOG_NUMBER",
	},
	{
		value: "APY",
		name: "Original submitter, parent Data Maintenance Request (DMR)",
		key: "ORIGINAL_SUBMITTER_PARENT_DATA_MAINTENANCE_REQUEST_DMR",
	},
	{
		value: "APZ",
		name: "Original submitter, child Data Maintenance Request (DMR)",
		key: "ORIGINAL_SUBMITTER_CHILD_DATA_MAINTENANCE_REQUEST_DMR",
	},
	{
		value: "AQA",
		name: "Entry point assessment log number",
		key: "ENTRY_POINT_ASSESSMENT_LOG_NUMBER",
	},
	{
		value: "AQB",
		name: "Entry point assessment log number, parent DMR",
		key: "ENTRY_POINT_ASSESSMENT_LOG_NUMBER_PARENT_DMR",
	},
	{
		value: "AQC",
		name: "Entry point assessment log number, child DMR",
		key: "ENTRY_POINT_ASSESSMENT_LOG_NUMBER_CHILD_DMR",
	},
	{ value: "AQD", name: "Data structure tag", key: "DATA_STRUCTURE_TAG" },
	{
		value: "AQE",
		name: "Central secretariat log number",
		key: "CENTRAL_SECRETARIAT_LOG_NUMBER",
	},
	{
		value: "AQF",
		name: "Central secretariat log number, parent Data Maintenance",
		key: "CENTRAL_SECRETARIAT_LOG_NUMBER_PARENT_DATA_MAINTENANCE",
	},
	{
		value: "AQG",
		name: "Central secretariat log number, child Data Maintenance",
		key: "CENTRAL_SECRETARIAT_LOG_NUMBER_CHILD_DATA_MAINTENANCE",
	},
	{
		value: "AQH",
		name: "International assessment log number",
		key: "INTERNATIONAL_ASSESSMENT_LOG_NUMBER",
	},
	{
		value: "AQI",
		name: "International assessment log number, parent Data",
		key: "INTERNATIONAL_ASSESSMENT_LOG_NUMBER_PARENT_DATA",
	},
	{
		value: "AQJ",
		name: "International assessment log number, child Data Maintenance",
		key: "INTERNATIONAL_ASSESSMENT_LOG_NUMBER_CHILD_DATA_MAINTENANCE",
	},
	{ value: "AQK", name: "Status report number", key: "STATUS_REPORT_NUMBER" },
	{
		value: "AQL",
		name: "Message design group number",
		key: "MESSAGE_DESIGN_GROUP_NUMBER",
	},
	{
		value: "AQM",
		name: "US Customs Service (USCS) entry code",
		key: "US_CUSTOMS_SERVICE_USCS_ENTRY_CODE",
	},
	{
		value: "AQN",
		name: "Beginning job sequence number",
		key: "BEGINNING_JOB_SEQUENCE_NUMBER",
	},
	{
		value: "AQO",
		name: "Sender's clause number",
		key: "SENDER_S_CLAUSE_NUMBER",
	},
	{
		value: "AQP",
		name: "Dun and Bradstreet Canada's 8 digit Standard Industrial",
		key: "DUN_AND_BRADSTREET_CANADA_S_8_DIGIT_STANDARD_INDUSTRIAL",
	},
	{
		value: "AQQ",
		name: "Activite Principale Exercee (APE) identifier",
		key: "ACTIVITE_PRINCIPALE_EXERCEE_APE_IDENTIFIER",
	},
	{
		value: "AQR",
		name: "Dun and Bradstreet US 8 digit Standard Industrial",
		key: "DUN_AND_BRADSTREET_US_8_DIGIT_STANDARD_INDUSTRIAL",
	},
	{
		value: "AQS",
		name: "Nomenclature Activity Classification Economy (NACE)",
		key: "NOMENCLATURE_ACTIVITY_CLASSIFICATION_ECONOMY_NACE",
	},
	{
		value: "AQT",
		name: "Norme Activite Francaise (NAF) identifier",
		key: "NORME_ACTIVITE_FRANCAISE_NAF_IDENTIFIER",
	},
	{
		value: "AQU",
		name: "Registered contractor activity type",
		key: "REGISTERED_CONTRACTOR_ACTIVITY_TYPE",
	},
	{
		value: "AQV",
		name: "Statistic Bundes Amt (SBA) identifier",
		key: "STATISTIC_BUNDES_AMT_SBA_IDENTIFIER",
	},
	{
		value: "AQW",
		name: "State or province assigned entity identification",
		key: "STATE_OR_PROVINCE_ASSIGNED_ENTITY_IDENTIFICATION",
	},
	{
		value: "AQX",
		name: "Institute of Security and Future Market Development (ISFMD)",
		key: "INSTITUTE_OF_SECURITY_AND_FUTURE_MARKET_DEVELOPMENT_ISFMD",
	},
	{
		value: "AQY",
		name: "File identification number",
		key: "FILE_IDENTIFICATION_NUMBER",
	},
	{
		value: "AQZ",
		name: "Bankruptcy procedure number",
		key: "BANKRUPTCY_PROCEDURE_NUMBER",
	},
	{
		value: "ARA",
		name: "National government business identification number",
		key: "NATIONAL_GOVERNMENT_BUSINESS_IDENTIFICATION_NUMBER",
	},
	{
		value: "ARB",
		name: "Prior Data Universal Number System (DUNS) number",
		key: "PRIOR_DATA_UNIVERSAL_NUMBER_SYSTEM_DUNS_NUMBER",
	},
	{
		value: "ARC",
		name: "Companies Registry Office (CRO) number",
		key: "COMPANIES_REGISTRY_OFFICE_CRO_NUMBER",
	},
	{
		value: "ARD",
		name: "Costa Rican judicial number",
		key: "COSTA_RICAN_JUDICIAL_NUMBER",
	},
	{
		value: "ARE",
		name: "Numero de Identificacion Tributaria (NIT)",
		key: "NUMERO_DE_IDENTIFICACION_TRIBUTARIA_NIT",
	},
	{ value: "ARF", name: "Patron number", key: "PATRON_NUMBER" },
	{
		value: "ARG",
		name: "Registro Informacion Fiscal (RIF) number",
		key: "REGISTRO_INFORMACION_FISCAL_RIF_NUMBER",
	},
	{
		value: "ARH",
		name: "Registro Unico de Contribuyente (RUC) number",
		key: "REGISTRO_UNICO_DE_CONTRIBUYENTE_RUC_NUMBER",
	},
	{
		value: "ARI",
		name: "Tokyo SHOKO Research (TSR) business identifier",
		key: "TOKYO_SHOKO_RESEARCH_TSR_BUSINESS_IDENTIFIER",
	},
	{
		value: "ARJ",
		name: "Personal identity card number",
		key: "PERSONAL_IDENTITY_CARD_NUMBER",
	},
	{
		value: "ARK",
		name: "Systeme Informatique pour le Repertoire des ENtreprises",
		key: "SYSTEME_INFORMATIQUE_POUR_LE_REPERTOIRE_DES_E_NTREPRISES",
	},
	{
		value: "ARL",
		name: "Systeme Informatique pour le Repertoire des ETablissements",
		key: "SYSTEME_INFORMATIQUE_POUR_LE_REPERTOIRE_DES_E_TABLISSEMENTS",
	},
	{
		value: "ARM",
		name: "Publication issue number",
		key: "PUBLICATION_ISSUE_NUMBER",
	},
	{
		value: "ARN",
		name: "Original filing number",
		key: "ORIGINAL_FILING_NUMBER",
	},
	{
		value: "ARO",
		name: "Document page identifier",
		key: "DOCUMENT_PAGE_IDENTIFIER",
	},
	{
		value: "ARP",
		name: "Public filing registration number",
		key: "PUBLIC_FILING_REGISTRATION_NUMBER",
	},
	{
		value: "ARQ",
		name: "Regiristo Federal de Contribuyentes",
		key: "REGIRISTO_FEDERAL_DE_CONTRIBUYENTES",
	},
	{
		value: "ARR",
		name: "Social security number",
		key: "SOCIAL_SECURITY_NUMBER",
	},
	{
		value: "ARS",
		name: "Document volume number",
		key: "DOCUMENT_VOLUME_NUMBER",
	},
	{ value: "ART", name: "Book number", key: "BOOK_NUMBER" },
	{
		value: "ARU",
		name: "Stock exchange company identifier",
		key: "STOCK_EXCHANGE_COMPANY_IDENTIFIER",
	},
	{ value: "ARV", name: "Imputation account", key: "IMPUTATION_ACCOUNT" },
	{
		value: "ARW",
		name: "Financial phase reference",
		key: "FINANCIAL_PHASE_REFERENCE",
	},
	{
		value: "ARX",
		name: "Technical phase reference",
		key: "TECHNICAL_PHASE_REFERENCE",
	},
	{
		value: "ARY",
		name: "Prior contractor registration number",
		key: "PRIOR_CONTRACTOR_REGISTRATION_NUMBER",
	},
	{
		value: "ARZ",
		name: "Stock adjustment number",
		key: "STOCK_ADJUSTMENT_NUMBER",
	},
	{
		value: "ASA",
		name: "Dispensation reference",
		key: "DISPENSATION_REFERENCE",
	},
	{
		value: "ASB",
		name: "Investment reference number",
		key: "INVESTMENT_REFERENCE_NUMBER",
	},
	{ value: "ASC", name: "Assuming company", key: "ASSUMING_COMPANY" },
	{ value: "ASD", name: "Budget chapter", key: "BUDGET_CHAPTER" },
	{
		value: "ASE",
		name: "Duty free products security number",
		key: "DUTY_FREE_PRODUCTS_SECURITY_NUMBER",
	},
	{
		value: "ASF",
		name: "Duty free products receipt authorisation number",
		key: "DUTY_FREE_PRODUCTS_RECEIPT_AUTHORISATION_NUMBER",
	},
	{
		value: "ASG",
		name: "Party information message reference",
		key: "PARTY_INFORMATION_MESSAGE_REFERENCE",
	},
	{
		value: "ASH",
		name: "Formal statement reference",
		key: "FORMAL_STATEMENT_REFERENCE",
	},
	{
		value: "ASI",
		name: "Proof of delivery reference number",
		key: "PROOF_OF_DELIVERY_REFERENCE_NUMBER",
	},
	{
		value: "ASJ",
		name: "Supplier's credit claim reference number",
		key: "SUPPLIER_S_CREDIT_CLAIM_REFERENCE_NUMBER",
	},
	{
		value: "ASK",
		name: "Picture of actual product",
		key: "PICTURE_OF_ACTUAL_PRODUCT",
	},
	{
		value: "ASL",
		name: "Picture of a generic product",
		key: "PICTURE_OF_A_GENERIC_PRODUCT",
	},
	{
		value: "ASM",
		name: "Trading partner identification number",
		key: "TRADING_PARTNER_IDENTIFICATION_NUMBER",
	},
	{
		value: "ASN",
		name: "Prior trading partner identification number",
		key: "PRIOR_TRADING_PARTNER_IDENTIFICATION_NUMBER",
	},
	{ value: "ASO", name: "Password", key: "PASSWORD" },
	{ value: "ASP", name: "Formal report number", key: "FORMAL_REPORT_NUMBER" },
	{ value: "ASQ", name: "Fund account number", key: "FUND_ACCOUNT_NUMBER" },
	{ value: "ASR", name: "Safe custody number", key: "SAFE_CUSTODY_NUMBER" },
	{ value: "ASS", name: "Master account number", key: "MASTER_ACCOUNT_NUMBER" },
	{
		value: "AST",
		name: "Group reference number",
		key: "GROUP_REFERENCE_NUMBER",
	},
	{
		value: "ASU",
		name: "Accounting transmission number",
		key: "ACCOUNTING_TRANSMISSION_NUMBER",
	},
	{
		value: "ASV",
		name: "Product data file number",
		key: "PRODUCT_DATA_FILE_NUMBER",
	},
	{
		value: "ASW",
		name: "Cadastro Geral do Contribuinte (CGC)",
		key: "CADASTRO_GERAL_DO_CONTRIBUINTE_CGC",
	},
	{
		value: "ASX",
		name: "Foreign resident identification number",
		key: "FOREIGN_RESIDENT_IDENTIFICATION_NUMBER",
	},
	{ value: "ASY", name: "CD-ROM", key: "CD_ROM" },
	{ value: "ASZ", name: "Physical medium", key: "PHYSICAL_MEDIUM" },
	{
		value: "ATA",
		name: "Financial cancellation reference number",
		key: "FINANCIAL_CANCELLATION_REFERENCE_NUMBER",
	},
	{
		value: "ATB",
		name: "Purchase for export Customs agreement number",
		key: "PURCHASE_FOR_EXPORT_CUSTOMS_AGREEMENT_NUMBER",
	},
	{ value: "ATC", name: "Judgment number", key: "JUDGMENT_NUMBER" },
	{ value: "ATD", name: "Secretariat number", key: "SECRETARIAT_NUMBER" },
	{
		value: "ATE",
		name: "Previous banking status message reference",
		key: "PREVIOUS_BANKING_STATUS_MESSAGE_REFERENCE",
	},
	{
		value: "ATF",
		name: "Last received banking status message reference",
		key: "LAST_RECEIVED_BANKING_STATUS_MESSAGE_REFERENCE",
	},
	{
		value: "ATG",
		name: "Bank's documentary procedure reference",
		key: "BANK_S_DOCUMENTARY_PROCEDURE_REFERENCE",
	},
	{
		value: "ATH",
		name: "Customer's documentary procedure reference",
		key: "CUSTOMER_S_DOCUMENTARY_PROCEDURE_REFERENCE",
	},
	{
		value: "ATI",
		name: "Safe deposit box number",
		key: "SAFE_DEPOSIT_BOX_NUMBER",
	},
	{
		value: "ATJ",
		name: "Receiving Bankgiro number",
		key: "RECEIVING_BANKGIRO_NUMBER",
	},
	{
		value: "ATK",
		name: "Sending Bankgiro number",
		key: "SENDING_BANKGIRO_NUMBER",
	},
	{ value: "ATL", name: "Bankgiro reference", key: "BANKGIRO_REFERENCE" },
	{ value: "ATM", name: "Guarantee number", key: "GUARANTEE_NUMBER" },
	{
		value: "ATN",
		name: "Collection instrument number",
		key: "COLLECTION_INSTRUMENT_NUMBER",
	},
	{
		value: "ATO",
		name: "Converted Postgiro number",
		key: "CONVERTED_POSTGIRO_NUMBER",
	},
	{
		value: "ATP",
		name: "Cost centre alignment number",
		key: "COST_CENTRE_ALIGNMENT_NUMBER",
	},
	{
		value: "ATQ",
		name: "Kamer Van Koophandel (KVK) number",
		key: "KAMER_VAN_KOOPHANDEL_KVK_NUMBER",
	},
	{
		value: "ATR",
		name: "Institut Belgo-Luxembourgeois de Codification (IBLC) number",
		key: "INSTITUT_BELGO_LUXEMBOURGEOIS_DE_CODIFICATION_IBLC_NUMBER",
	},
	{
		value: "ATS",
		name: "External object reference",
		key: "EXTERNAL_OBJECT_REFERENCE",
	},
	{
		value: "ATT",
		name: "Exceptional transport authorisation number",
		key: "EXCEPTIONAL_TRANSPORT_AUTHORISATION_NUMBER",
	},
	{
		value: "ATU",
		name: "Clave Unica de Identificacion Tributaria (CUIT)",
		key: "CLAVE_UNICA_DE_IDENTIFICACION_TRIBUTARIA_CUIT",
	},
	{
		value: "ATV",
		name: "Registro Unico Tributario (RUT)",
		key: "REGISTRO_UNICO_TRIBUTARIO_RUT",
	},
	{
		value: "ATW",
		name: "Flat rack container bundle identification number",
		key: "FLAT_RACK_CONTAINER_BUNDLE_IDENTIFICATION_NUMBER",
	},
	{
		value: "ATX",
		name: "Transport equipment acceptance order reference",
		key: "TRANSPORT_EQUIPMENT_ACCEPTANCE_ORDER_REFERENCE",
	},
	{
		value: "ATY",
		name: "Transport equipment release order reference",
		key: "TRANSPORT_EQUIPMENT_RELEASE_ORDER_REFERENCE",
	},
	{
		value: "ATZ",
		name: "Ship's stay reference number",
		key: "SHIP_S_STAY_REFERENCE_NUMBER",
	},
	{
		value: "AU",
		name: " Authorization to meet competition number",
		key: "AUTHORIZATION_TO_MEET_COMPETITION_NUMBER",
	},
	{
		value: "AUA",
		name: "Place of positioning reference",
		key: "PLACE_OF_POSITIONING_REFERENCE",
	},
	{ value: "AUB", name: "Party reference", key: "PARTY_REFERENCE" },
	{
		value: "AUC",
		name: "Issued prescription identification",
		key: "ISSUED_PRESCRIPTION_IDENTIFICATION",
	},
	{ value: "AUD", name: "Collection reference", key: "COLLECTION_REFERENCE" },
	{ value: "AUE", name: "Travel service", key: "TRAVEL_SERVICE" },
	{
		value: "AUF",
		name: "Consignment stock contract",
		key: "CONSIGNMENT_STOCK_CONTRACT",
	},
	{
		value: "AUG",
		name: "Importer's letter of credit reference",
		key: "IMPORTER_S_LETTER_OF_CREDIT_REFERENCE",
	},
	{
		value: "AUH",
		name: "Performed prescription identification",
		key: "PERFORMED_PRESCRIPTION_IDENTIFICATION",
	},
	{ value: "AUI", name: "Image reference", key: "IMAGE_REFERENCE" },
	{
		value: "AUJ",
		name: "Proposed purchase order reference number",
		key: "PROPOSED_PURCHASE_ORDER_REFERENCE_NUMBER",
	},
	{
		value: "AUK",
		name: "Application for financial support reference number",
		key: "APPLICATION_FOR_FINANCIAL_SUPPORT_REFERENCE_NUMBER",
	},
	{
		value: "AUL",
		name: "Manufacturing quality agreement number",
		key: "MANUFACTURING_QUALITY_AGREEMENT_NUMBER",
	},
	{
		value: "AUM",
		name: "Software editor reference",
		key: "SOFTWARE_EDITOR_REFERENCE",
	},
	{ value: "AUN", name: "Software reference", key: "SOFTWARE_REFERENCE" },
	{
		value: "AUO",
		name: "Software quality reference",
		key: "SOFTWARE_QUALITY_REFERENCE",
	},
	{
		value: "AUP",
		name: "Consolidated orders' reference",
		key: "CONSOLIDATED_ORDERS_REFERENCE",
	},
	{
		value: "AUQ",
		name: "Customs binding ruling number",
		key: "CUSTOMS_BINDING_RULING_NUMBER",
	},
	{
		value: "AUR",
		name: "Customs non-binding ruling number",
		key: "CUSTOMS_NON_BINDING_RULING_NUMBER",
	},
	{
		value: "AUS",
		name: "Delivery route reference",
		key: "DELIVERY_ROUTE_REFERENCE",
	},
	{
		value: "AUT",
		name: "Net area supplier reference",
		key: "NET_AREA_SUPPLIER_REFERENCE",
	},
	{ value: "AUU", name: "Time series reference", key: "TIME_SERIES_REFERENCE" },
	{
		value: "AUV",
		name: "Connecting point to central grid",
		key: "CONNECTING_POINT_TO_CENTRAL_GRID",
	},
	{
		value: "AUW",
		name: "Marketing plan identification number (MPIN)",
		key: "MARKETING_PLAN_IDENTIFICATION_NUMBER_MPIN",
	},
	{
		value: "AUX",
		name: "Entity reference number, previous",
		key: "ENTITY_REFERENCE_NUMBER_PREVIOUS",
	},
	{
		value: "AUY",
		name: "International Standard Industrial Classification (ISIC)",
		key: "INTERNATIONAL_STANDARD_INDUSTRIAL_CLASSIFICATION_ISIC",
	},
	{
		value: "AUZ",
		name: "Customs pre-approval ruling number",
		key: "CUSTOMS_PRE_APPROVAL_RULING_NUMBER",
	},
	{
		value: "AV",
		name: " Account payable number",
		key: "ACCOUNT_PAYABLE_NUMBER",
	},
	{
		value: "AVA",
		name: "First financial institution's transaction reference",
		key: "FIRST_FINANCIAL_INSTITUTION_S_TRANSACTION_REFERENCE",
	},
	{
		value: "AVB",
		name: "Product characteristics directory",
		key: "PRODUCT_CHARACTERISTICS_DIRECTORY",
	},
	{
		value: "AVC",
		name: "Supplier's customer reference number",
		key: "SUPPLIER_S_CUSTOMER_REFERENCE_NUMBER",
	},
	{
		value: "AVD",
		name: "Inventory report request number",
		key: "INVENTORY_REPORT_REQUEST_NUMBER",
	},
	{ value: "AVE", name: "Metering point", key: "METERING_POINT" },
	{
		value: "AVF",
		name: "Passenger reservation number",
		key: "PASSENGER_RESERVATION_NUMBER",
	},
	{
		value: "AVG",
		name: "Slaughterhouse approval number",
		key: "SLAUGHTERHOUSE_APPROVAL_NUMBER",
	},
	{
		value: "AVH",
		name: "Meat cutting plant approval number",
		key: "MEAT_CUTTING_PLANT_APPROVAL_NUMBER",
	},
	{
		value: "AVI",
		name: "Customer travel service identifier",
		key: "CUSTOMER_TRAVEL_SERVICE_IDENTIFIER",
	},
	{
		value: "AVJ",
		name: "Export control classification number",
		key: "EXPORT_CONTROL_CLASSIFICATION_NUMBER",
	},
	{ value: "AVK", name: "Broker reference 3", key: "BROKER_REFERENCE_3" },
	{
		value: "AVL",
		name: "Consignment information",
		key: "CONSIGNMENT_INFORMATION",
	},
	{
		value: "AVM",
		name: "Goods item information",
		key: "GOODS_ITEM_INFORMATION",
	},
	{
		value: "AVN",
		name: "Dangerous Goods information",
		key: "DANGEROUS_GOODS_INFORMATION",
	},
	{
		value: "AVO",
		name: "Pilotage services exemption number",
		key: "PILOTAGE_SERVICES_EXEMPTION_NUMBER",
	},
	{
		value: "AVP",
		name: "Person registration number",
		key: "PERSON_REGISTRATION_NUMBER",
	},
	{
		value: "AVQ",
		name: "Place of packing approval number",
		key: "PLACE_OF_PACKING_APPROVAL_NUMBER",
	},
	{
		value: "AVR",
		name: "Original Mandate Reference",
		key: "ORIGINAL_MANDATE_REFERENCE",
	},
	{ value: "AVS", name: "Mandate Reference", key: "MANDATE_REFERENCE" },
	{
		value: "AVT",
		name: "Reservation station indentifier",
		key: "RESERVATION_STATION_INDENTIFIER",
	},
	{
		value: "AVU",
		name: "Unique goods shipment identifier",
		key: "UNIQUE_GOODS_SHIPMENT_IDENTIFIER",
	},
	{
		value: "AVV",
		name: "Framework Agreement Number",
		key: "FRAMEWORK_AGREEMENT_NUMBER",
	},
	{ value: "AVW", name: "Hash value", key: "HASH_VALUE" },
	{
		value: "AVX",
		name: "Movement reference number",
		key: "MOVEMENT_REFERENCE_NUMBER",
	},
	{
		value: "AVY",
		name: "Economic Operators Registration and Identification Number",
		key: "ECONOMIC_OPERATORS_REGISTRATION_AND_IDENTIFICATION_NUMBER",
	},
	{
		value: "AVZ",
		name: "Local Reference Number",
		key: "LOCAL_REFERENCE_NUMBER",
	},
	{ value: "AWA", name: "Rate code number", key: "RATE_CODE_NUMBER" },
	{ value: "AWB", name: "Air waybill number", key: "AIR_WAYBILL_NUMBER" },
	{
		value: "AWC",
		name: "Documentary credit amendment number",
		key: "DOCUMENTARY_CREDIT_AMENDMENT_NUMBER",
	},
	{
		value: "AWD",
		name: "Advising bank's reference",
		key: "ADVISING_BANK_S_REFERENCE",
	},
	{ value: "AWE", name: "Cost centre", key: "COST_CENTRE" },
	{
		value: "AWF",
		name: "Work item quantity determination",
		key: "WORK_ITEM_QUANTITY_DETERMINATION",
	},
	{
		value: "AWG",
		name: "Internal data process number",
		key: "INTERNAL_DATA_PROCESS_NUMBER",
	},
	{
		value: "AWH",
		name: "Category of work reference",
		key: "CATEGORY_OF_WORK_REFERENCE",
	},
	{ value: "AWI", name: "Policy form number", key: "POLICY_FORM_NUMBER" },
	{ value: "AWJ", name: "Net area", key: "NET_AREA" },
	{ value: "AWK", name: "Service provider", key: "SERVICE_PROVIDER" },
	{ value: "AWL", name: "Error position", key: "ERROR_POSITION" },
	{
		value: "AWM",
		name: "Service category reference",
		key: "SERVICE_CATEGORY_REFERENCE",
	},
	{ value: "AWN", name: "Connected location", key: "CONNECTED_LOCATION" },
	{ value: "AWO", name: "Related party", key: "RELATED_PARTY" },
	{
		value: "AWP",
		name: "Latest accounting entry record reference",
		key: "LATEST_ACCOUNTING_ENTRY_RECORD_REFERENCE",
	},
	{ value: "AWQ", name: "Accounting entry", key: "ACCOUNTING_ENTRY" },
	{
		value: "AWR",
		name: "Document reference, original",
		key: "DOCUMENT_REFERENCE_ORIGINAL",
	},
	{
		value: "AWS",
		name: "Hygienic Certificate number, national",
		key: "HYGIENIC_CERTIFICATE_NUMBER_NATIONAL",
	},
	{
		value: "AWT",
		name: "Administrative Reference Code",
		key: "ADMINISTRATIVE_REFERENCE_CODE",
	},
	{ value: "AWU", name: "Pick-up sheet number", key: "PICK_UP_SHEET_NUMBER" },
	{ value: "AWV", name: "Phone number", key: "PHONE_NUMBER" },
	{ value: "AWW", name: "Buyer's fund number", key: "BUYER_S_FUND_NUMBER" },
	{
		value: "AWX",
		name: "Company trading account number",
		key: "COMPANY_TRADING_ACCOUNT_NUMBER",
	},
	{
		value: "AWY",
		name: "Reserved goods identifier",
		key: "RESERVED_GOODS_IDENTIFIER",
	},
	{
		value: "AWZ",
		name: "Handling and movement reference number",
		key: "HANDLING_AND_MOVEMENT_REFERENCE_NUMBER",
	},
	{
		value: "AXA",
		name: "Instruction to despatch reference number",
		key: "INSTRUCTION_TO_DESPATCH_REFERENCE_NUMBER",
	},
	{
		value: "AXB",
		name: "Instruction for returns number",
		key: "INSTRUCTION_FOR_RETURNS_NUMBER",
	},
	{
		value: "AXC",
		name: "Metered services consumption report number",
		key: "METERED_SERVICES_CONSUMPTION_REPORT_NUMBER",
	},
	{
		value: "AXD",
		name: "Order status enquiry number",
		key: "ORDER_STATUS_ENQUIRY_NUMBER",
	},
	{
		value: "AXE",
		name: "Firm booking reference number",
		key: "FIRM_BOOKING_REFERENCE_NUMBER",
	},
	{
		value: "AXF",
		name: "Product inquiry number",
		key: "PRODUCT_INQUIRY_NUMBER",
	},
	{ value: "AXG", name: "Split delivery number", key: "SPLIT_DELIVERY_NUMBER" },
	{
		value: "AXH",
		name: "Service relation number",
		key: "SERVICE_RELATION_NUMBER",
	},
	{
		value: "AXI",
		name: "Serial shipping container code",
		key: "SERIAL_SHIPPING_CONTAINER_CODE",
	},
	{
		value: "AXJ",
		name: "Test specification number",
		key: "TEST_SPECIFICATION_NUMBER",
	},
	{
		value: "AXK",
		name: "Transport status report number",
		key: "TRANSPORT_STATUS_REPORT_NUMBER",
	},
	{
		value: "AXL",
		name: "Tooling contract number",
		key: "TOOLING_CONTRACT_NUMBER",
	},
	{
		value: "AXM",
		name: "Formula reference number",
		key: "FORMULA_REFERENCE_NUMBER",
	},
	{ value: "AXN", name: "Pre-agreement number", key: "PRE_AGREEMENT_NUMBER" },
	{
		value: "AXO",
		name: "Product certification number",
		key: "PRODUCT_CERTIFICATION_NUMBER",
	},
	{
		value: "AXP",
		name: "Consignment contract number",
		key: "CONSIGNMENT_CONTRACT_NUMBER",
	},
	{
		value: "AXQ",
		name: "Product specification reference number",
		key: "PRODUCT_SPECIFICATION_REFERENCE_NUMBER",
	},
	{
		value: "AXR",
		name: "Payroll deduction advice reference",
		key: "PAYROLL_DEDUCTION_ADVICE_REFERENCE",
	},
	{
		value: "AXS",
		name: "TRACES party identification",
		key: "TRACES_PARTY_IDENTIFICATION",
	},
	{
		value: "AXU",
		name: "Block Stowage Reference",
		key: "BLOCK_STOWAGE_REFERENCE",
	},
	{
		value: "BA",
		name: " Beginning meter reading actual",
		key: "BEGINNING_METER_READING_ACTUAL",
	},
	{
		value: "BC",
		name: " Buyer's contract number",
		key: "BUYER_S_CONTRACT_NUMBER",
	},
	{ value: "BD", name: " Bid number", key: "BID_NUMBER" },
	{
		value: "BE",
		name: " Beginning meter reading estimated",
		key: "BEGINNING_METER_READING_ESTIMATED",
	},
	{
		value: "BH",
		name: " House bill of lading number",
		key: "HOUSE_BILL_OF_LADING_NUMBER",
	},
	{ value: "BM", name: " Bill of lading number", key: "BILL_OF_LADING_NUMBER" },
	{
		value: "BN",
		name: " Consignment identifier, carrier assigned",
		key: "CONSIGNMENT_IDENTIFIER_CARRIER_ASSIGNED",
	},
	{ value: "BO", name: " Blanket order number", key: "BLANKET_ORDER_NUMBER" },
	{
		value: "BR",
		name: " Broker or sales office number",
		key: "BROKER_OR_SALES_OFFICE_NUMBER",
	},
	{
		value: "BT",
		name: " Batch number/lot number",
		key: "BATCH_NUMBER_LOT_NUMBER",
	},
	{
		value: "BTP",
		name: "Battery and accumulator producer registration number",
		key: "BATTERY_AND_ACCUMULATOR_PRODUCER_REGISTRATION_NUMBER",
	},
	{ value: "BW", name: " Blended with number", key: "BLENDED_WITH_NUMBER" },
	{
		value: "CAS",
		name: "IATA Cargo Agent CASS Address number",
		key: "IATA_CARGO_AGENT_CASS_ADDRESS_NUMBER",
	},
	{
		value: "CAT",
		name: "Matching of entries, balanced",
		key: "MATCHING_OF_ENTRIES_BALANCED",
	},
	{ value: "CAU", name: "Entry flagging", key: "ENTRY_FLAGGING" },
	{
		value: "CAV",
		name: "Matching of entries, unbalanced",
		key: "MATCHING_OF_ENTRIES_UNBALANCED",
	},
	{
		value: "CAW",
		name: "Document reference, internal",
		key: "DOCUMENT_REFERENCE_INTERNAL",
	},
	{
		value: "CAX",
		name: "European Value Added Tax identification",
		key: "EUROPEAN_VALUE_ADDED_TAX_IDENTIFICATION",
	},
	{
		value: "CAY",
		name: "Cost accounting document",
		key: "COST_ACCOUNTING_DOCUMENT",
	},
	{
		value: "CAZ",
		name: "Grid operator's customer reference number",
		key: "GRID_OPERATOR_S_CUSTOMER_REFERENCE_NUMBER",
	},
	{ value: "CBA", name: "Ticket control number", key: "TICKET_CONTROL_NUMBER" },
	{
		value: "CBB",
		name: "Order shipment grouping reference",
		key: "ORDER_SHIPMENT_GROUPING_REFERENCE",
	},
	{ value: "CD", name: " Credit note number", key: "CREDIT_NOTE_NUMBER" },
	{ value: "CEC", name: "Ceding company", key: "CEDING_COMPANY" },
	{ value: "CED", name: "Debit letter number", key: "DEBIT_LETTER_NUMBER" },
	{
		value: "CFE",
		name: "Consignee's further order",
		key: "CONSIGNEE_S_FURTHER_ORDER",
	},
	{
		value: "CFF",
		name: "Animal farm licence number",
		key: "ANIMAL_FARM_LICENCE_NUMBER",
	},
	{
		value: "CFO",
		name: "Consignor's further order",
		key: "CONSIGNOR_S_FURTHER_ORDER",
	},
	{
		value: "CG",
		name: " Consignee's order number",
		key: "CONSIGNEE_S_ORDER_NUMBER",
	},
	{
		value: "CH",
		name: " Customer catalogue number",
		key: "CUSTOMER_CATALOGUE_NUMBER",
	},
	{ value: "CK", name: " Cheque number", key: "CHEQUE_NUMBER" },
	{ value: "CKN", name: "Checking number", key: "CHECKING_NUMBER" },
	{ value: "CM", name: " Credit memo number", key: "CREDIT_MEMO_NUMBER" },
	{
		value: "CMR",
		name: "Road consignment note number",
		key: "ROAD_CONSIGNMENT_NOTE_NUMBER",
	},
	{
		value: "CN",
		name: " Carrier's reference number",
		key: "CARRIER_S_REFERENCE_NUMBER",
	},
	{
		value: "CNO",
		name: "Charges note document attachment indicator",
		key: "CHARGES_NOTE_DOCUMENT_ATTACHMENT_INDICATOR",
	},
	{ value: "COF", name: "Call off order number", key: "CALL_OFF_ORDER_NUMBER" },
	{
		value: "CP",
		name: " Condition of purchase document number",
		key: "CONDITION_OF_PURCHASE_DOCUMENT_NUMBER",
	},
	{
		value: "CR",
		name: " Customer reference number",
		key: "CUSTOMER_REFERENCE_NUMBER",
	},
	{
		value: "CRN",
		name: "Transport means journey identifier",
		key: "TRANSPORT_MEANS_JOURNEY_IDENTIFIER",
	},
	{
		value: "CS",
		name: " Condition of sale document number",
		key: "CONDITION_OF_SALE_DOCUMENT_NUMBER",
	},
	{
		value: "CST",
		name: "Team assignment number",
		key: "TEAM_ASSIGNMENT_NUMBER",
	},
	{ value: "CT", name: " Contract number", key: "CONTRACT_NUMBER" },
	{
		value: "CU",
		name: " Consignment identifier, consignor assigned",
		key: "CONSIGNMENT_IDENTIFIER_CONSIGNOR_ASSIGNED",
	},
	{
		value: "CV",
		name: " Container operators reference number",
		key: "CONTAINER_OPERATORS_REFERENCE_NUMBER",
	},
	{ value: "CW", name: " Package number", key: "PACKAGE_NUMBER" },
	{
		value: "CZ",
		name: " Cooperation contract number",
		key: "COOPERATION_CONTRACT_NUMBER",
	},
	{
		value: "DA",
		name: " Deferment approval number",
		key: "DEFERMENT_APPROVAL_NUMBER",
	},
	{ value: "DAN", name: "Debit account number", key: "DEBIT_ACCOUNT_NUMBER" },
	{ value: "DB", name: " Buyer's debtor number", key: "BUYER_S_DEBTOR_NUMBER" },
	{
		value: "DI",
		name: " Distributor invoice number",
		key: "DISTRIBUTOR_INVOICE_NUMBER",
	},
	{ value: "DL", name: " Debit note number", key: "DEBIT_NOTE_NUMBER" },
	{ value: "DM", name: " Document identifier", key: "DOCUMENT_IDENTIFIER" },
	{ value: "DQ", name: " Delivery note number", key: "DELIVERY_NOTE_NUMBER" },
	{ value: "DR", name: " Dock receipt number", key: "DOCK_RECEIPT_NUMBER" },
	{
		value: "EA",
		name: " Ending meter reading actual",
		key: "ENDING_METER_READING_ACTUAL",
	},
	{ value: "EB", name: " Embargo permit number", key: "EMBARGO_PERMIT_NUMBER" },
	{ value: "ED", name: " Export declaration", key: "EXPORT_DECLARATION" },
	{
		value: "EE",
		name: " Ending meter reading estimated",
		key: "ENDING_METER_READING_ESTIMATED",
	},
	{
		value: "EEP",
		name: "Electrical and electronic equipment producer registration",
		key: "ELECTRICAL_AND_ELECTRONIC_EQUIPMENT_PRODUCER_REGISTRATION",
	},
	{
		value: "EI",
		name: " Employer's identification number",
		key: "EMPLOYER_S_IDENTIFICATION_NUMBER",
	},
	{ value: "EN", name: " Embargo number", key: "EMBARGO_NUMBER" },
	{ value: "EQ", name: " Equipment number", key: "EQUIPMENT_NUMBER" },
	{
		value: "ER",
		name: " Container/equipment receipt number",
		key: "CONTAINER_EQUIPMENT_RECEIPT_NUMBER",
	},
	{
		value: "ERN",
		name: "Exporter's reference number",
		key: "EXPORTER_S_REFERENCE_NUMBER",
	},
	{
		value: "ET",
		name: " Excess transportation number",
		key: "EXCESS_TRANSPORTATION_NUMBER",
	},
	{
		value: "EX",
		name: " Export permit identifier",
		key: "EXPORT_PERMIT_IDENTIFIER",
	},
	{ value: "FC", name: " Fiscal number", key: "FISCAL_NUMBER" },
	{
		value: "FF",
		name: " Consignment identifier, freight forwarder assigned",
		key: "CONSIGNMENT_IDENTIFIER_FREIGHT_FORWARDER_ASSIGNED",
	},
	{ value: "FI", name: " File line identifier", key: "FILE_LINE_IDENTIFIER" },
	{ value: "FLW", name: "Flow reference number", key: "FLOW_REFERENCE_NUMBER" },
	{ value: "FN", name: " Freight bill number", key: "FREIGHT_BILL_NUMBER" },
	{ value: "FO", name: " Foreign exchange", key: "FOREIGN_EXCHANGE" },
	{ value: "FS", name: " Final sequence number", key: "FINAL_SEQUENCE_NUMBER" },
	{ value: "FT", name: " Free zone identifier", key: "FREE_ZONE_IDENTIFIER" },
	{ value: "FV", name: " File version number", key: "FILE_VERSION_NUMBER" },
	{
		value: "FX",
		name: " Foreign exchange contract number",
		key: "FOREIGN_EXCHANGE_CONTRACT_NUMBER",
	},
	{ value: "GA", name: " Standard's number", key: "STANDARD_S_NUMBER" },
	{
		value: "GC",
		name: " Government contract number",
		key: "GOVERNMENT_CONTRACT_NUMBER",
	},
	{
		value: "GD",
		name: " Standard's code number",
		key: "STANDARD_S_CODE_NUMBER",
	},
	{
		value: "GDN",
		name: "General declaration number",
		key: "GENERAL_DECLARATION_NUMBER",
	},
	{
		value: "GN",
		name: " Government reference number",
		key: "GOVERNMENT_REFERENCE_NUMBER",
	},
	{
		value: "HS",
		name: " Harmonised system number",
		key: "HARMONISED_SYSTEM_NUMBER",
	},
	{ value: "HWB", name: "House waybill number", key: "HOUSE_WAYBILL_NUMBER" },
	{
		value: "IA",
		name: " Internal vendor number",
		key: "INTERNAL_VENDOR_NUMBER",
	},
	{ value: "IB", name: " In bond number", key: "IN_BOND_NUMBER" },
	{
		value: "ICA",
		name: "IATA cargo agent code number",
		key: "IATA_CARGO_AGENT_CODE_NUMBER",
	},
	{
		value: "ICE",
		name: "Insurance certificate reference number",
		key: "INSURANCE_CERTIFICATE_REFERENCE_NUMBER",
	},
	{
		value: "ICO",
		name: "Insurance contract reference number",
		key: "INSURANCE_CONTRACT_REFERENCE_NUMBER",
	},
	{
		value: "II",
		name: " Initial sample inspection report number",
		key: "INITIAL_SAMPLE_INSPECTION_REPORT_NUMBER",
	},
	{ value: "IL", name: " Internal order number", key: "INTERNAL_ORDER_NUMBER" },
	{ value: "INB", name: "Intermediary broker", key: "INTERMEDIARY_BROKER" },
	{
		value: "INN",
		name: "Interchange number new",
		key: "INTERCHANGE_NUMBER_NEW",
	},
	{
		value: "INO",
		name: "Interchange number old",
		key: "INTERCHANGE_NUMBER_OLD",
	},
	{
		value: "IP",
		name: " Import permit identifier",
		key: "IMPORT_PERMIT_IDENTIFIER",
	},
	{ value: "IS", name: " Invoice number suffix", key: "INVOICE_NUMBER_SUFFIX" },
	{
		value: "IT",
		name: " Internal customer number",
		key: "INTERNAL_CUSTOMER_NUMBER",
	},
	{
		value: "IV",
		name: " Invoice document identifier",
		key: "INVOICE_DOCUMENT_IDENTIFIER",
	},
	{ value: "JB", name: " Job number", key: "JOB_NUMBER" },
	{
		value: "JE",
		name: " Ending job sequence number",
		key: "ENDING_JOB_SEQUENCE_NUMBER",
	},
	{
		value: "LA",
		name: " Shipping label serial number",
		key: "SHIPPING_LABEL_SERIAL_NUMBER",
	},
	{
		value: "LAN",
		name: "Loading authorisation identifier",
		key: "LOADING_AUTHORISATION_IDENTIFIER",
	},
	{ value: "LAR", name: "Lower number in range", key: "LOWER_NUMBER_IN_RANGE" },
	{ value: "LB", name: " Lockbox", key: "LOCKBOX" },
	{
		value: "LC",
		name: " Letter of credit number",
		key: "LETTER_OF_CREDIT_NUMBER",
	},
	{
		value: "LI",
		name: " Document line identifier",
		key: "DOCUMENT_LINE_IDENTIFIER",
	},
	{ value: "LO", name: " Load planning number", key: "LOAD_PLANNING_NUMBER" },
	{
		value: "LRC",
		name: "Reservation office identifier",
		key: "RESERVATION_OFFICE_IDENTIFIER",
	},
	{
		value: "LS",
		name: " Bar coded label serial number",
		key: "BAR_CODED_LABEL_SERIAL_NUMBER",
	},
	{
		value: "MA",
		name: " Ship notice/manifest number",
		key: "SHIP_NOTICE_MANIFEST_NUMBER",
	},
	{
		value: "MB",
		name: " Master bill of lading number",
		key: "MASTER_BILL_OF_LADING_NUMBER",
	},
	{
		value: "MF",
		name: " Manufacturer's part number",
		key: "MANUFACTURER_S_PART_NUMBER",
	},
	{ value: "MG", name: " Meter unit number", key: "METER_UNIT_NUMBER" },
	{
		value: "MH",
		name: " Manufacturing order number",
		key: "MANUFACTURING_ORDER_NUMBER",
	},
	{ value: "MR", name: " Message recipient", key: "MESSAGE_RECIPIENT" },
	{
		value: "MRN",
		name: "Mailing reference number",
		key: "MAILING_REFERENCE_NUMBER",
	},
	{ value: "MS", name: " Message sender", key: "MESSAGE_SENDER" },
	{
		value: "MSS",
		name: "Manufacturer's material safety data sheet number",
		key: "MANUFACTURER_S_MATERIAL_SAFETY_DATA_SHEET_NUMBER",
	},
	{
		value: "MWB",
		name: "Master air waybill number",
		key: "MASTER_AIR_WAYBILL_NUMBER",
	},
	{
		value: "NA",
		name: " North American hazardous goods classification number",
		key: "NORTH_AMERICAN_HAZARDOUS_GOODS_CLASSIFICATION_NUMBER",
	},
	{ value: "NF", name: " Nota Fiscal", key: "NOTA_FISCAL" },
	{
		value: "OH",
		name: " Current invoice number",
		key: "CURRENT_INVOICE_NUMBER",
	},
	{
		value: "OI",
		name: " Previous invoice number",
		key: "PREVIOUS_INVOICE_NUMBER",
	},
	{
		value: "ON",
		name: " Order document identifier, buyer assigned",
		key: "ORDER_DOCUMENT_IDENTIFIER_BUYER_ASSIGNED",
	},
	{
		value: "OP",
		name: " Original purchase order",
		key: "ORIGINAL_PURCHASE_ORDER",
	},
	{ value: "OR", name: " General order number", key: "GENERAL_ORDER_NUMBER" },
	{
		value: "PB",
		name: " Payer's financial institution account number",
		key: "PAYER_S_FINANCIAL_INSTITUTION_ACCOUNT_NUMBER",
	},
	{ value: "PC", name: " Production code", key: "PRODUCTION_CODE" },
	{ value: "PD", name: " Promotion deal number", key: "PROMOTION_DEAL_NUMBER" },
	{ value: "PE", name: " Plant number", key: "PLANT_NUMBER" },
	{
		value: "PF",
		name: " Prime contractor contract number",
		key: "PRIME_CONTRACTOR_CONTRACT_NUMBER",
	},
	{
		value: "PI",
		name: " Price list version number",
		key: "PRICE_LIST_VERSION_NUMBER",
	},
	{ value: "PK", name: " Packing list number", key: "PACKING_LIST_NUMBER" },
	{ value: "PL", name: " Price list number", key: "PRICE_LIST_NUMBER" },
	{
		value: "POR",
		name: "Purchase order response number",
		key: "PURCHASE_ORDER_RESPONSE_NUMBER",
	},
	{
		value: "PP",
		name: " Purchase order change number",
		key: "PURCHASE_ORDER_CHANGE_NUMBER",
	},
	{ value: "PQ", name: " Payment reference", key: "PAYMENT_REFERENCE" },
	{ value: "PR", name: " Price quote number", key: "PRICE_QUOTE_NUMBER" },
	{
		value: "PS",
		name: " Purchase order number suffix",
		key: "PURCHASE_ORDER_NUMBER_SUFFIX",
	},
	{
		value: "PW",
		name: " Prior purchase order number",
		key: "PRIOR_PURCHASE_ORDER_NUMBER",
	},
	{
		value: "PY",
		name: " Payee's financial institution account number",
		key: "PAYEE_S_FINANCIAL_INSTITUTION_ACCOUNT_NUMBER",
	},
	{
		value: "RA",
		name: " Remittance advice number",
		key: "REMITTANCE_ADVICE_NUMBER",
	},
	{
		value: "RC",
		name: " Rail/road routing code",
		key: "RAIL_ROAD_ROUTING_CODE",
	},
	{
		value: "RCN",
		name: "Railway consignment note number",
		key: "RAILWAY_CONSIGNMENT_NOTE_NUMBER",
	},
	{ value: "RE", name: " Release number", key: "RELEASE_NUMBER" },
	{
		value: "REN",
		name: "Consignment receipt identifier",
		key: "CONSIGNMENT_RECEIPT_IDENTIFIER",
	},
	{
		value: "RF",
		name: " Export reference number",
		key: "EXPORT_REFERENCE_NUMBER",
	},
	{
		value: "RR",
		name: " Payer's financial institution transit routing No.(ACH",
		key: "PAYER_S_FINANCIAL_INSTITUTION_TRANSIT_ROUTING_NO_ACH",
	},
	{
		value: "RT",
		name: " Payee's financial institution transit routing No.",
		key: "PAYEE_S_FINANCIAL_INSTITUTION_TRANSIT_ROUTING_NO",
	},
	{ value: "SA", name: " Sales person number", key: "SALES_PERSON_NUMBER" },
	{ value: "SB", name: " Sales region number", key: "SALES_REGION_NUMBER" },
	{
		value: "SD",
		name: " Sales department number",
		key: "SALES_DEPARTMENT_NUMBER",
	},
	{ value: "SE", name: " Serial number", key: "SERIAL_NUMBER" },
	{ value: "SEA", name: "Allocated seat", key: "ALLOCATED_SEAT" },
	{ value: "SF", name: " Ship from", key: "SHIP_FROM" },
	{
		value: "SH",
		name: " Previous highest schedule number",
		key: "PREVIOUS_HIGHEST_SCHEDULE_NUMBER",
	},
	{
		value: "SI",
		name: " SID (Shipper's identifying number for shipment)",
		key: "SID_SHIPPER_S_IDENTIFYING_NUMBER_FOR_SHIPMENT",
	},
	{ value: "SM", name: " Sales office number", key: "SALES_OFFICE_NUMBER" },
	{
		value: "SN",
		name: " Transport equipment seal identifier",
		key: "TRANSPORT_EQUIPMENT_SEAL_IDENTIFIER",
	},
	{ value: "SP", name: " Scan line", key: "SCAN_LINE" },
	{
		value: "SQ",
		name: " Equipment sequence number",
		key: "EQUIPMENT_SEQUENCE_NUMBER",
	},
	{
		value: "SRN",
		name: "Shipment reference number",
		key: "SHIPMENT_REFERENCE_NUMBER",
	},
	{
		value: "SS",
		name: " Sellers reference number",
		key: "SELLERS_REFERENCE_NUMBER",
	},
	{
		value: "STA",
		name: "Station reference number",
		key: "STATION_REFERENCE_NUMBER",
	},
	{ value: "SW", name: " Swap order number", key: "SWAP_ORDER_NUMBER" },
	{ value: "SZ", name: " Specification number", key: "SPECIFICATION_NUMBER" },
	{
		value: "TB",
		name: " Trucker's bill of lading",
		key: "TRUCKER_S_BILL_OF_LADING",
	},
	{
		value: "TCR",
		name: "Terminal operator's consignment reference",
		key: "TERMINAL_OPERATOR_S_CONSIGNMENT_REFERENCE",
	},
	{ value: "TE", name: " Telex message number", key: "TELEX_MESSAGE_NUMBER" },
	{ value: "TF", name: " Transfer number", key: "TRANSFER_NUMBER" },
	{ value: "TI", name: " TIR carnet number", key: "TIR_CARNET_NUMBER" },
	{
		value: "TIN",
		name: "Transport instruction number",
		key: "TRANSPORT_INSTRUCTION_NUMBER",
	},
	{
		value: "TL",
		name: " Tax exemption licence number",
		key: "TAX_EXEMPTION_LICENCE_NUMBER",
	},
	{
		value: "TN",
		name: " Transaction reference number",
		key: "TRANSACTION_REFERENCE_NUMBER",
	},
	{ value: "TP", name: " Test report number", key: "TEST_REPORT_NUMBER" },
	{ value: "UAR", name: "Upper number of range", key: "UPPER_NUMBER_OF_RANGE" },
	{
		value: "UC",
		name: " Ultimate customer's reference number",
		key: "ULTIMATE_CUSTOMER_S_REFERENCE_NUMBER",
	},
	{
		value: "UCN",
		name: "Unique consignment reference number",
		key: "UNIQUE_CONSIGNMENT_REFERENCE_NUMBER",
	},
	{
		value: "UN",
		name: " United Nations Dangerous Goods identifier",
		key: "UNITED_NATIONS_DANGEROUS_GOODS_IDENTIFIER",
	},
	{
		value: "UO",
		name: " Ultimate customer's order number",
		key: "ULTIMATE_CUSTOMER_S_ORDER_NUMBER",
	},
	{
		value: "URI",
		name: "Uniform Resource Identifier",
		key: "UNIFORM_RESOURCE_IDENTIFIER",
	},
	{
		value: "VA",
		name: " VAT registration number",
		key: "VAT_REGISTRATION_NUMBER",
	},
	{
		value: "VC",
		name: " Vendor contract number",
		key: "VENDOR_CONTRACT_NUMBER",
	},
	{
		value: "VGR",
		name: "Transport equipment gross mass verification reference",
		key: "TRANSPORT_EQUIPMENT_GROSS_MASS_VERIFICATION_REFERENCE",
	},
	{ value: "VM", name: " Vessel identifier", key: "VESSEL_IDENTIFIER" },
	{ value: "VN", name: " Order number (vendor)", key: "ORDER_NUMBER_VENDOR" },
	{ value: "VON", name: "Voyage number", key: "VOYAGE_NUMBER" },
	{
		value: "VOR",
		name: "Transport equipment gross mass verification order reference",
		key: "TRANSPORT_EQUIPMENT_GROSS_MASS_VERIFICATION_ORDER_REFERENCE",
	},
	{ value: "VP", name: " Vendor product number", key: "VENDOR_PRODUCT_NUMBER" },
	{ value: "VR", name: " Vendor ID number", key: "VENDOR_ID_NUMBER" },
	{
		value: "VS",
		name: " Vendor order number suffix",
		key: "VENDOR_ORDER_NUMBER_SUFFIX",
	},
	{
		value: "VT",
		name: " Motor vehicle identification number",
		key: "MOTOR_VEHICLE_IDENTIFICATION_NUMBER",
	},
	{ value: "VV", name: " Voucher number", key: "VOUCHER_NUMBER" },
	{
		value: "WE",
		name: " Warehouse entry number",
		key: "WAREHOUSE_ENTRY_NUMBER",
	},
	{
		value: "WM",
		name: " Weight agreement number",
		key: "WEIGHT_AGREEMENT_NUMBER",
	},
	{ value: "WN", name: " Well number", key: "WELL_NUMBER" },
	{
		value: "WR",
		name: " Warehouse receipt number",
		key: "WAREHOUSE_RECEIPT_NUMBER",
	},
	{
		value: "WS",
		name: " Warehouse storage location number",
		key: "WAREHOUSE_STORAGE_LOCATION_NUMBER",
	},
	{ value: "WY", name: " Rail waybill number", key: "RAIL_WAYBILL_NUMBER" },
	{
		value: "XA",
		name: " Company/place registration number",
		key: "COMPANY_PLACE_REGISTRATION_NUMBER",
	},
	{ value: "XC", name: " Cargo control number", key: "CARGO_CONTROL_NUMBER" },
	{
		value: "XP",
		name: " Previous cargo control number",
		key: "PREVIOUS_CARGO_CONTROL_NUMBER",
	},
	{
		value: "ZZZ",
		name: "Mutually defined reference number",
		key: "MUTUALLY_DEFINED_REFERENCE_NUMBER",
	},
] as const satisfies Codelist;

declare module "@node-zugferd/core" {
	interface ZugferdCodelistRegistry {
		untdid1153: typeof untdid1153;
	}
}
registerCodelist("untdid1153", untdid1153);

export default untdid1153;
