/**
 * Generated by `scripts/untdid/update.js` on Mon, 28 Jul 2025 10:43:00 GMT
 *
 * @see https://www.xrepository.de/details/urn:xoev-de:kosit:codeliste:untdid.4451
 */

export type Untdid4451Definition = {
	code: string;
	name?: string;
	description?: string;
};

export type Untdid4451Code = (typeof UNTDID_4451)[number]["code"];

export const UNTDID_4451_IDENTIFIER =
	"urn:xoev-de:kosit:codeliste:untdid.4451" as const;
export const UNTDID_4451_VERSION = "4" as const;

export const UNTDID_4451 = [
	{
		code: "AAA",
		name: "Goods item description",
		description:
			"[7002] Plain language description of the nature of a goods item sufficient to identify it for customs, statistical or transport purposes.",
	},
	{
		code: "AAB",
		name: "Payment term",
		description:
			"[4276] Free form description of the conditions of payment between the parties to a transaction.",
	},
	{
		code: "AAC",
		name: "Dangerous goods additional information",
		description:
			"[7488] Additional information concerning dangerous substances and/or article in a consignment.",
	},
	{
		code: "AAD",
		name: "Dangerous goods technical name",
		description:
			"[7254] Proper shipping name, supplemented as necessary with the correct technical name, by which a dangerous substance or article may be correctly identified, or which is sufficiently informative to permit identification by reference to generally available literature.",
	},
	{
		code: "AAE",
		name: "Acknowledgement description",
		description: "The content of an acknowledgement.",
	},
	{
		code: "AAF",
		name: "Rate additional information",
		description: "Specific details applying to rates.",
	},
	{
		code: "AAG",
		name: "Party instructions",
		description:
			"Indicates that the segment contains instructions to be passed on to the identified party.",
	},
	{
		code: "AAI",
		name: "General information",
		description: "The text contains general information.",
	},
	{
		code: "AAJ",
		name: "Additional conditions of sale/purchase",
		description: "Additional conditions specific to this order or project.",
	},
	{
		code: "AAK",
		name: "Price conditions",
		description:
			"Information on the price conditions that are expected or given.",
	},
	{
		code: "AAL",
		name: "Goods dimensions in characters",
		description:
			"Expression of a number in characters as length of ten meters.",
	},
	{
		code: "AAM",
		name: "Equipment re-usage restrictions",
		description:
			"Technical or commercial reasons why a piece of equipment may not be re-used after the current transport terminates.",
	},
	{
		code: "AAN",
		name: "Handling restriction",
		description:
			"Restrictions in handling depending on the technical characteristics of the piece of equipment or on the nature of the goods.",
	},
	{
		code: "AAO",
		name: "Error description (free text)",
		description: "Error described by a free text.",
	},
	{
		code: "AAP",
		name: "Response (free text)",
		description: "Free text of the response to a communication.",
	},
	{
		code: "AAQ",
		name: "Package content's description",
		description: "A description of the contents of a package.",
	},
	{
		code: "AAR",
		name: "Terms of delivery",
		description:
			"(4053) Free text of the non Incoterms terms of delivery. For Incoterms, use: 4053.",
	},
	{
		code: "AAS",
		name: "Bill of lading remarks",
		description: "The remarks printed or to be printed on a bill of lading.",
	},
	{
		code: "AAT",
		name: "Mode of settlement information",
		description:
			"Free text information on an IATA Air Waybill to indicate means by which account is to be settled.",
	},
	{
		code: "AAU",
		name: "Consignment invoice information",
		description:
			"Information pertaining to the invoice covering the consignment.",
	},
	{
		code: "AAV",
		name: "Clearance invoice information",
		description:
			"Information pertaining to the invoice covering clearance of the cargo.",
	},
	{
		code: "AAW",
		name: "Letter of credit information",
		description: "Information pertaining to the letter of credit.",
	},
	{
		code: "AAX",
		name: "License information",
		description: "Information pertaining to a license.",
	},
	{
		code: "AAY",
		name: "Certification statements",
		description: "The text contains certification statements.",
	},
	{
		code: "AAZ",
		name: "Additional export information",
		description: "The text contains additional export information.",
	},
	{
		code: "ABA",
		name: "Tariff statements",
		description: "Description of parameters relating to a tariff.",
	},
	{
		code: "ABB",
		name: "Medical history",
		description: "Historical details of a patients medical events.",
	},
	{
		code: "ABC",
		name: "Conditions of sale or purchase",
		description:
			"(4490) (4372) Additional information regarding terms and conditions which apply to the transaction.",
	},
	{
		code: "ABD",
		name: "Contract document type",
		description: "[4422] Textual representation of the type of contract.",
	},
	{
		code: "ABE",
		name: "Additional terms and/or conditions (documentary credit)",
		description:
			"(4260) Additional terms and/or conditions to the documentary credit.",
	},
	{
		code: "ABF",
		name: "Instructions or information about standby documentary credit",
		description:
			"Instruction or information about a standby documentary credit.",
	},
	{
		code: "ABG",
		name: "Instructions or information about partial shipment(s)",
		description: "Instructions or information about partial shipment(s).",
	},
	{
		code: "ABH",
		name: "Instructions or information about transhipment(s)",
		description: "Instructions or information about transhipment(s).",
	},
	{
		code: "ABI",
		name: "Additional handling instructions documentary credit",
		description: "Additional handling instructions for a documentary credit.",
	},
	{
		code: "ABJ",
		name: "Domestic routing information",
		description: "Information regarding the domestic routing.",
	},
	{
		code: "ABK",
		name: "Chargeable category of equipment",
		description:
			"Equipment types are coded by category for financial purposes.",
	},
	{
		code: "ABL",
		name: "Government information",
		description: "Information pertaining to government.",
	},
	{
		code: "ABM",
		name: "Onward routing information",
		description: "The text contains onward routing information.",
	},
	{
		code: "ABN",
		name: "Accounting information",
		description: "[4410] The text contains information related to accounting.",
	},
	{
		code: "ABO",
		name: "Discrepancy information",
		description:
			"Free text or coded information to indicate a specific discrepancy.",
	},
	{
		code: "ABP",
		name: "Confirmation instructions",
		description: "Documentary credit confirmation instructions.",
	},
	{
		code: "ABQ",
		name: "Method of issuance",
		description: "Method of issuance of documentary credit.",
	},
	{
		code: "ABR",
		name: "Documents delivery instructions",
		description:
			"Delivery instructions for documents required under a documentary credit.",
	},
	{
		code: "ABS",
		name: "Additional conditions",
		description:
			"Additional conditions to the issuance of a documentary credit.",
	},
	{
		code: "ABT",
		name: "Information/instructions about additional amounts covered",
		description: "Additional amounts information/instruction.",
	},
	{
		code: "ABU",
		name: "Deferred payment termed additional",
		description: "Additional terms concerning deferred payment.",
	},
	{
		code: "ABV",
		name: "Acceptance terms additional",
		description: "Additional terms concerning acceptance.",
	},
	{
		code: "ABW",
		name: "Negotiation terms additional",
		description: "Additional terms concerning negotiation.",
	},
	{
		code: "ABX",
		name: "Document name and documentary requirements",
		description: "Document name and documentary requirements.",
	},
	{
		code: "ABZ",
		name: "Instructions/information about revolving documentary credit",
		description:
			"Instructions/information about a revolving documentary credit.",
	},
	{
		code: "ACA",
		name: "Documentary requirements",
		description: "Specification of the documentary requirements.",
	},
	{
		code: "ACB",
		name: "Additional information",
		description: "(4270) The text contains additional information.",
	},
	{
		code: "ACC",
		name: "Factor assignment clause",
		description: "Assignment based on an agreement between seller and factor.",
	},
	{
		code: "ACD",
		name: "Reason",
		description: "Reason for a request or response.",
	},
	{
		code: "ACE",
		name: "Dispute",
		description:
			"A notice, usually from buyer to seller, that something was found wrong with goods delivered or the services rendered, or with the related invoice.",
	},
	{
		code: "ACF",
		name: "Additional attribute information",
		description:
			"The text refers to information about an additional attribute not otherwise specified.",
	},
	{
		code: "ACG",
		name: "Absence declaration",
		description: "A declaration on the reason of the absence.",
	},
	{
		code: "ACH",
		name: "Aggregation statement",
		description:
			"A statement on the way a specific variable or set of variables has been aggregated.",
	},
	{
		code: "ACI",
		name: "Compilation statement",
		description:
			"A statement on the compilation status of an array or other set of figures or calculations.",
	},
	{
		code: "ACJ",
		name: "Definitional exception",
		description:
			"An exception to the agreed definition of a term, concept, formula or other object.",
	},
	{
		code: "ACK",
		name: "Privacy statement",
		description:
			"A statement on the privacy or confidential nature of an object.",
	},
	{
		code: "ACL",
		name: "Quality statement",
		description: "A statement on the quality of an object.",
	},
	{
		code: "ACM",
		name: "Statistical description",
		description:
			"The description of a statistical object such as a value list, concept, or structure definition.",
	},
	{
		code: "ACN",
		name: "Statistical definition",
		description:
			"The definition of a statistical object such as a value list, concept, or structure definition.",
	},
	{
		code: "ACO",
		name: "Statistical name",
		description:
			"The name of a statistical object such as a value list, concept or structure definition.",
	},
	{
		code: "ACP",
		name: "Statistical title",
		description:
			"The title of a statistical object such as a value list, concept, or structure definition.",
	},
	{
		code: "ACQ",
		name: "Off-dimension information",
		description:
			"Information relating to differences between the actual transport dimensions and the normally applicable dimensions.",
	},
	{
		code: "ACR",
		name: "Unexpected stops information",
		description:
			"Information relating to unexpected stops during a conveyance.",
	},
	{
		code: "ACS",
		name: "Principles",
		description:
			"Text subject is principles section of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		code: "ACT",
		name: "Terms and definition",
		description:
			"Text subject is terms and definition section of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		code: "ACU",
		name: "Segment name",
		description: "Text subject is segment name.",
	},
	{
		code: "ACV",
		name: "Simple data element name",
		description: "Text subject is name of simple data element.",
	},
	{
		code: "ACW",
		name: "Scope",
		description:
			"Text subject is scope section of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		code: "ACX",
		name: "Message type name",
		description: "Text subject is name of message type.",
	},
	{
		code: "ACY",
		name: "Introduction",
		description:
			"Text subject is introduction section of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		code: "ACZ",
		name: "Glossary",
		description:
			"Text subject is glossary section of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		code: "ADA",
		name: "Functional definition",
		description:
			"Text subject is functional definition section of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		code: "ADB",
		name: "Examples",
		description:
			"Text subject is examples as given in the example(s) section of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		code: "ADC",
		name: "Cover page",
		description:
			"Text subject is cover page of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		code: "ADD",
		name: "Dependency (syntax) notes",
		description:
			"Denotes that the associated text is a dependency (syntax) note.",
	},
	{
		code: "ADE",
		name: "Code value name",
		description: "Text subject is name of code value.",
	},
	{
		code: "ADF",
		name: "Code list name",
		description: "Text subject is name of code list.",
	},
	{
		code: "ADG",
		name: "Clarification of usage",
		description:
			"Text subject is an explanation of the intended usage of a segment or segment group.",
	},
	{
		code: "ADH",
		name: "Composite data element name",
		description: "Text subject is name of composite data element.",
	},
	{
		code: "ADI",
		name: "Field of application",
		description:
			"Text subject is field of application of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		code: "ADJ",
		name: "Type of assets and liabilities",
		description: "Information describing the type of assets and liabilities.",
	},
	{
		code: "ADK",
		name: "Promotion information",
		description: "The text contains information about a promotion.",
	},
	{
		code: "ADL",
		name: "Meter condition",
		description: "Description of the condition of a meter.",
	},
	{
		code: "ADM",
		name: "Meter reading information",
		description: "Information related to a particular reading of a meter.",
	},
	{
		code: "ADN",
		name: "Type of transaction reason",
		description:
			"Information describing the type of the reason of transaction.",
	},
	{
		code: "ADO",
		name: "Type of survey question",
		description: "Type of survey question.",
	},
	{
		code: "ADP",
		name: "Carrier's agent counter information",
		description: "Information for use at the counter of the carrier's agent.",
	},
	{
		code: "ADQ",
		name: "Description of work item on equipment",
		description:
			"Description or code for the operation to be executed on the equipment.",
	},
	{
		code: "ADR",
		name: "Message definition",
		description: "Text subject is message definition.",
	},
	{
		code: "ADS",
		name: "Booked item information",
		description: "Information pertaining to a booked item.",
	},
	{
		code: "ADT",
		name: "Source of document",
		description: "Text subject is source of document.",
	},
	{ code: "ADU", name: "Note", description: "Text subject is note." },
	{
		code: "ADV",
		name: "Fixed part of segment clarification text",
		description: "Text subject is fixed part of segment clarification text.",
	},
	{
		code: "ADW",
		name: "Characteristics of goods",
		description:
			"Description of the characteristic of goods in addition to the description of the goods.",
	},
	{
		code: "ADX",
		name: "Additional discharge instructions",
		description: "Special discharge instructions concerning the goods.",
	},
	{
		code: "ADY",
		name: "Container stripping instructions",
		description: "Instructions regarding the stripping of container(s).",
	},
	{
		code: "ADZ",
		name: "CSC (Container Safety Convention) plate information",
		description:
			"Information on the CSC (Container Safety Convention) plate that is attached to the container.",
	},
	{
		code: "AEA",
		name: "Cargo remarks",
		description: "Additional remarks concerning the cargo.",
	},
	{
		code: "AEB",
		name: "Temperature control instructions",
		description: "Instruction regarding the temperature control of the cargo.",
	},
	{
		code: "AEC",
		name: "Text refers to expected data",
		description: "Remarks refer to data that was expected.",
	},
	{
		code: "AED",
		name: "Text refers to received data",
		description: "Remarks refer to data that was received.",
	},
	{
		code: "AEE",
		name: "Section clarification text",
		description: "Text subject is section clarification text.",
	},
	{
		code: "AEF",
		name: "Information to the beneficiary",
		description: "Information given to the beneficiary.",
	},
	{
		code: "AEG",
		name: "Information to the applicant",
		description: "Information given to the applicant.",
	},
	{
		code: "AEH",
		name: "Instructions to the beneficiary",
		description: "Instructions made to the beneficiary.",
	},
	{
		code: "AEI",
		name: "Instructions to the applicant",
		description: "Instructions given to the applicant.",
	},
	{
		code: "AEJ",
		name: "Controlled atmosphere",
		description: "Information about the controlled atmosphere.",
	},
	{
		code: "AEK",
		name: "Take off annotation",
		description:
			"Additional information in plain text to support a take off annotation. Taking off is the process of assessing the quantity work from extracting the measurement from construction documentation.",
	},
	{
		code: "AEL",
		name: "Price variation narrative",
		description:
			"Additional information in plain language to support a price variation.",
	},
	{
		code: "AEM",
		name: "Documentary credit amendment instructions",
		description: "Documentary credit amendment instructions.",
	},
	{
		code: "AEN",
		name: "Standard method narrative",
		description:
			"Additional information in plain language to support a standard method.",
	},
	{
		code: "AEO",
		name: "Project narrative",
		description:
			"Additional information in plain language to support the project.",
	},
	{
		code: "AEP",
		name: "Radioactive goods, additional information",
		description: "Additional information related to radioactive goods.",
	},
	{
		code: "AEQ",
		name: "Bank-to-bank information",
		description: "Information given from one bank to another.",
	},
	{
		code: "AER",
		name: "Reimbursement instructions",
		description: "Instructions given for reimbursement purposes.",
	},
	{
		code: "AES",
		name: "Reason for amending a message",
		description: "Identification of the reason for amending a message.",
	},
	{
		code: "AET",
		name: "Instructions to the paying and/or accepting and/or negotiating bank",
		description:
			"Instructions to the paying and/or accepting and/or negotiating bank.",
	},
	{
		code: "AEU",
		name: "Interest instructions",
		description: "Instructions given about the interest.",
	},
	{
		code: "AEV",
		name: "Agent commission",
		description: "Instructions about agent commission.",
	},
	{
		code: "AEW",
		name: "Remitting bank instructions",
		description: "Instructions to the remitting bank.",
	},
	{
		code: "AEX",
		name: "Instructions to the collecting bank",
		description:
			"Instructions to the bank, other than the remitting bank, involved in processing the collection.",
	},
	{
		code: "AEY",
		name: "Collection amount instructions",
		description: "Instructions about the collection amount.",
	},
	{
		code: "AEZ",
		name: "Internal auditing information",
		description: "Text relating to internal auditing information.",
	},
	{
		code: "AFA",
		name: "Constraint",
		description: "Denotes that the associated text is a constraint.",
	},
	{
		code: "AFB",
		name: "Comment",
		description: "Denotes that the associated text is a comment.",
	},
	{
		code: "AFC",
		name: "Semantic note",
		description: "Denotes that the associated text is a semantic note.",
	},
	{
		code: "AFD",
		name: "Help text",
		description: "Denotes that the associated text is an item of help text.",
	},
	{
		code: "AFE",
		name: "Legend",
		description: "Denotes that the associated text is a legend.",
	},
	{
		code: "AFF",
		name: "Batch code structure",
		description: "A description of the structure of a batch code.",
	},
	{
		code: "AFG",
		name: "Product application",
		description: "A general description of the application of a product.",
	},
	{
		code: "AFH",
		name: "Customer complaint",
		description: "Complaint of customer.",
	},
	{
		code: "AFI",
		name: "Probable cause of fault",
		description: "The probable cause of fault.",
	},
	{
		code: "AFJ",
		name: "Defect description",
		description: "Description of the defect.",
	},
	{
		code: "AFK",
		name: "Repair description",
		description: "The description of the work performed during the repair.",
	},
	{
		code: "AFL",
		name: "Review comments",
		description: "Comments relevant to a review.",
	},
	{
		code: "AFM",
		name: "Title",
		description: "Denotes that the associated text is a title.",
	},
	{
		code: "AFN",
		name: "Description of amount",
		description: "An amount description in clear text.",
	},
	{
		code: "AFO",
		name: "Responsibilities",
		description: "Information describing the responsibilities.",
	},
	{
		code: "AFP",
		name: "Supplier",
		description: "Information concerning suppliers.",
	},
	{
		code: "AFQ",
		name: "Purchase region",
		description:
			"Information concerning the region(s) where purchases are made.",
	},
	{
		code: "AFR",
		name: "Affiliation",
		description:
			"Information concerning an association of one party with another party(ies).",
	},
	{
		code: "AFS",
		name: "Borrower",
		description: "Information concerning the borrower.",
	},
	{
		code: "AFT",
		name: "Line of business",
		description: "Information concerning an entity's line of business.",
	},
	{
		code: "AFU",
		name: "Financial institution",
		description: "Description of financial institution(s) used by an entity.",
	},
	{
		code: "AFV",
		name: "Business founder",
		description: "Information about the business founder.",
	},
	{
		code: "AFW",
		name: "Business history",
		description: "Description of the business history.",
	},
	{
		code: "AFX",
		name: "Banking arrangements",
		description: "Information concerning the general banking arrangements.",
	},
	{
		code: "AFY",
		name: "Business origin",
		description: "Description of the business origin.",
	},
	{
		code: "AFZ",
		name: "Brand names' description",
		description: "Description of the entity's brands.",
	},
	{
		code: "AGA",
		name: "Business financing details",
		description: "Details about the financing of the business.",
	},
	{
		code: "AGB",
		name: "Competition",
		description: "Information concerning an entity's competition.",
	},
	{
		code: "AGC",
		name: "Construction process details",
		description: "Details about the construction process.",
	},
	{
		code: "AGD",
		name: "Construction specialty",
		description:
			"Information concerning the line of business of a construction entity.",
	},
	{
		code: "AGE",
		name: "Contract information",
		description: "Details about contract(s).",
	},
	{
		code: "AGF",
		name: "Corporate filing",
		description: "Details about a corporate filing.",
	},
	{
		code: "AGG",
		name: "Customer information",
		description: "Description of customers.",
	},
	{
		code: "AGH",
		name: "Copyright notice",
		description: "Information concerning the copyright notice.",
	},
	{
		code: "AGI",
		name: "Contingent debt",
		description: "Details about the contingent debt.",
	},
	{
		code: "AGJ",
		name: "Conviction details",
		description:
			"Details about the law or penal codes that resulted in conviction.",
	},
	{ code: "AGK", name: "Equipment", description: "Description of equipment." },
	{
		code: "AGL",
		name: "Workforce description",
		description: "Comments about the workforce.",
	},
	{
		code: "AGM",
		name: "Exemption",
		description: "Description about exemptions.",
	},
	{
		code: "AGN",
		name: "Future plans",
		description: "Information on future plans.",
	},
	{
		code: "AGO",
		name: "Interviewee conversation information",
		description: "Information concerning the interviewee conversation.",
	},
	{
		code: "AGP",
		name: "Intangible asset",
		description: "Description of intangible asset(s).",
	},
	{
		code: "AGQ",
		name: "Inventory",
		description: "Description of the inventory.",
	},
	{
		code: "AGR",
		name: "Investment",
		description: "Description of the investments.",
	},
	{
		code: "AGS",
		name: "Intercompany relations information",
		description: "Description of the intercompany relations.",
	},
	{
		code: "AGT",
		name: "Joint venture",
		description: "Description of the joint venture.",
	},
	{ code: "AGU", name: "Loan", description: "Description of a loan." },
	{
		code: "AGV",
		name: "Long term debt",
		description: "Description of the long term debt.",
	},
	{ code: "AGW", name: "Location", description: "Description of a location." },
	{
		code: "AGX",
		name: "Current legal structure",
		description: "Details on the current legal structure.",
	},
	{
		code: "AGY",
		name: "Marital contract",
		description: "Details on a marital contract.",
	},
	{
		code: "AGZ",
		name: "Marketing activities",
		description: "Information concerning marketing activities.",
	},
	{ code: "AHA", name: "Merger", description: "Description of a merger." },
	{
		code: "AHB",
		name: "Marketable securities",
		description: "Description of the marketable securities.",
	},
	{
		code: "AHC",
		name: "Business debt",
		description: "Description of the business debt(s).",
	},
	{
		code: "AHD",
		name: "Original legal structure",
		description: "Information concerning the original legal structure.",
	},
	{
		code: "AHE",
		name: "Employee sharing arrangements",
		description:
			"Information describing how a company uses employees from another company.",
	},
	{
		code: "AHF",
		name: "Organization details",
		description: "Description about the organization of a company.",
	},
	{
		code: "AHG",
		name: "Public record details",
		description: "Information concerning public records.",
	},
	{
		code: "AHH",
		name: "Price range",
		description:
			"Information concerning the price range of products made or sold.",
	},
	{
		code: "AHI",
		name: "Qualifications",
		description:
			"Information on the accomplishments fitting a party for a position.",
	},
	{
		code: "AHJ",
		name: "Registered activity",
		description: "Information concerning the registered activity.",
	},
	{
		code: "AHK",
		name: "Criminal sentence",
		description:
			"Description of the sentence imposed in a criminal proceeding.",
	},
	{
		code: "AHL",
		name: "Sales method",
		description: "Description of the selling means.",
	},
	{
		code: "AHM",
		name: "Educational institution information",
		description: "Free form description relating to the school(s) attended.",
	},
	{
		code: "AHN",
		name: "Status details",
		description: "Describes the status details.",
	},
	{ code: "AHO", name: "Sales", description: "Description of the sales." },
	{
		code: "AHP",
		name: "Spouse information",
		description: "Information about the spouse.",
	},
	{
		code: "AHQ",
		name: "Educational degree information",
		description: "Details about the educational degree received from a school.",
	},
	{
		code: "AHR",
		name: "Shareholding information",
		description: "General description of shareholding.",
	},
	{
		code: "AHS",
		name: "Sales territory",
		description: "Information on the sales territory.",
	},
	{
		code: "AHT",
		name: "Accountant's comments",
		description:
			"Comments made by an accountant regarding a financial statement.",
	},
	{
		code: "AHU",
		name: "Exemption law location",
		description:
			"Description of the exemption provided to a location by a law.",
	},
	{
		code: "AHV",
		name: "Share classifications",
		description: "Information about the classes or categories of shares.",
	},
	{
		code: "AHW",
		name: "Forecast",
		description: "Description of a prediction.",
	},
	{
		code: "AHX",
		name: "Event location",
		description: "Description of the location of an event.",
	},
	{
		code: "AHY",
		name: "Facility occupancy",
		description: "Information related to occupancy of a facility.",
	},
	{
		code: "AHZ",
		name: "Import and export details",
		description:
			"Specific information provided about the importation and exportation of goods.",
	},
	{
		code: "AIA",
		name: "Additional facility information",
		description: "Additional information about a facility.",
	},
	{
		code: "AIB",
		name: "Inventory value",
		description: "Description of the value of inventory.",
	},
	{
		code: "AIC",
		name: "Education",
		description: "Description of the education of a person.",
	},
	{
		code: "AID",
		name: "Event",
		description: "Description of a thing that happens or takes place.",
	},
	{
		code: "AIE",
		name: "Agent",
		description: "Information about agents the entity uses.",
	},
	{
		code: "AIF",
		name: "Domestically agreed financial statement details",
		description: "Details of domestically agreed financial statement.",
	},
	{
		code: "AIG",
		name: "Other current asset description",
		description: "Description of other current asset.",
	},
	{
		code: "AIH",
		name: "Other current liability description",
		description: "Description of other current liability.",
	},
	{
		code: "AII",
		name: "Former business activity",
		description: "Description of the former line of business.",
	},
	{
		code: "AIJ",
		name: "Trade name use",
		description: "Description of how a trading name is used.",
	},
	{
		code: "AIK",
		name: "Signing authority",
		description: "Description of the authorized signatory.",
	},
	{
		code: "AIL",
		name: "Guarantee",
		description: "[4376] Description of guarantee.",
	},
	{
		code: "AIM",
		name: "Holding company operation",
		description: "Description of the operation of a holding company.",
	},
	{
		code: "AIN",
		name: "Consignment routing",
		description: "Information on routing of the consignment.",
	},
	{
		code: "AIO",
		name: "Letter of protest",
		description: "A letter citing any condition in dispute.",
	},
	{ code: "AIP", name: "Question", description: "A free text question." },
	{
		code: "AIQ",
		name: "Party information",
		description: "Free text information related to a party.",
	},
	{
		code: "AIR",
		name: "Area boundaries description",
		description: "Description of the boundaries of a geographical area.",
	},
	{
		code: "AIS",
		name: "Advertisement information",
		description: "The free text contains advertisement information.",
	},
	{
		code: "AIT",
		name: "Financial statement details",
		description: "Details regarding the financial statement in free text.",
	},
	{
		code: "AIU",
		name: "Access instructions",
		description: "Description of how to access an entity.",
	},
	{
		code: "AIV",
		name: "Liquidity",
		description: "Description of an entity's liquidity.",
	},
	{
		code: "AIW",
		name: "Credit line",
		description: "Description of the line of credit available to an entity.",
	},
	{
		code: "AIX",
		name: "Warranty terms",
		description:
			"Text describing the terms of warranty which apply to a product or service.",
	},
	{
		code: "AIY",
		name: "Division description",
		description: "Plain language description of a division of an entity.",
	},
	{
		code: "AIZ",
		name: "Reporting instruction",
		description: "Instruction on how to report.",
	},
	{
		code: "AJA",
		name: "Examination result",
		description: "The result of an examination.",
	},
	{
		code: "AJB",
		name: "Laboratory result",
		description: "The result of a laboratory investigation.",
	},
	{
		code: "ALC",
		name: "Allowance/charge information",
		description: "Information referring to allowance/charge.",
	},
	{
		code: "ALD",
		name: "X-ray result",
		description: "The result of an X-ray examination.",
	},
	{
		code: "ALE",
		name: "Pathology result",
		description: "The result of a pathology investigation.",
	},
	{
		code: "ALF",
		name: "Intervention description",
		description: "Details of an intervention.",
	},
	{
		code: "ALG",
		name: "Summary of admittance",
		description: "Summary description of admittance.",
	},
	{
		code: "ALH",
		name: "Medical treatment course detail",
		description: "Details of a course of medical treatment.",
	},
	{ code: "ALI", name: "Prognosis", description: "Details of a prognosis." },
	{
		code: "ALJ",
		name: "Instruction to patient",
		description: "Instruction given to a patient.",
	},
	{
		code: "ALK",
		name: "Instruction to physician",
		description: "Instruction given to a physician.",
	},
	{
		code: "ALL",
		name: "All documents",
		description: "The note implies to all documents.",
	},
	{
		code: "ALM",
		name: "Medicine treatment",
		description: "Details of medicine treatment.",
	},
	{
		code: "ALN",
		name: "Medicine dosage and administration",
		description: "Details of medicine dosage and method of administration.",
	},
	{
		code: "ALO",
		name: "Availability of patient",
		description: "Details of when and/or where the patient is available.",
	},
	{
		code: "ALP",
		name: "Reason for service request",
		description: "Details of the reason for a requested service.",
	},
	{
		code: "ALQ",
		name: "Purpose of service",
		description: "Details of the purpose of a service.",
	},
	{
		code: "ARR",
		name: "Arrival conditions",
		description: "Conditions under which arrival takes place.",
	},
	{
		code: "ARS",
		name: "Service requester's comment",
		description: "Comment by the requester of a service.",
	},
	{
		code: "AUT",
		name: "Authentication",
		description:
			"(4130) (4136) (4426) Name, code, password etc. given for authentication purposes.",
	},
	{
		code: "AUU",
		name: "Requested location description",
		description: "The description of the location requested.",
	},
	{
		code: "AUV",
		name: "Medicine administration condition",
		description:
			"The event or condition that initiates the administration of a single dose of medicine or a period of treatment.",
	},
	{
		code: "AUW",
		name: "Patient information",
		description: "Information concerning a patient.",
	},
	{
		code: "AUX",
		name: "Precautionary measure",
		description: "Action to be taken to avert possible harmful affects.",
	},
	{
		code: "AUY",
		name: "Service characteristic",
		description:
			"Free text description is related to a service characteristic.",
	},
	{
		code: "AUZ",
		name: "Planned event comment",
		description: "Comment about an event that is planned.",
	},
	{
		code: "AVA",
		name: "Expected delay comment",
		description: "Comment about the expected delay.",
	},
	{
		code: "AVB",
		name: "Transport requirements comment",
		description: "Comment about the requirements for transport.",
	},
	{
		code: "AVC",
		name: "Temporary approval condition",
		description: "The condition under which the approval is considered.",
	},
	{
		code: "AVD",
		name: "Customs Valuation Information",
		description:
			"Information provided in this category will be used by the trader to make certain declarations in relation to Customs Valuation.",
	},
	{
		code: "AVE",
		name: "Value Added Tax (VAT) margin scheme",
		description: "Description of the VAT margin scheme applied.",
	},
	{
		code: "AVF",
		name: "Maritime Declaration of Health",
		description: "Information about Maritime Declaration of Health.",
	},
	{
		code: "BAG",
		name: "Passenger baggage information",
		description:
			"Information related to baggage tendered by a passenger, such as odd size indication, tag.",
	},
	{
		code: "BAH",
		name: "Maritime Declaration of Health",
		description: "Information about Maritime Declaration of Health.",
	},
	{
		code: "BAI",
		name: "Additional product information address",
		description:
			"Address at which additional information on the product can be found.",
	},
	{
		code: "BAJ",
		name: "Information to be printed on despatch advice",
		description:
			"Specification of free text information which is to be printed on a despatch advice.",
	},
	{
		code: "BAK",
		name: "Missing goods remarks",
		description: "Remarks concerning missing goods.",
	},
	{
		code: "BAL",
		name: "Non-acceptance information",
		description:
			"Information related to the non-acceptance of an order, goods or a consignment.",
	},
	{
		code: "BAM",
		name: "Returns information",
		description: "Information related to the return of items.",
	},
	{
		code: "BAN",
		name: "Sub-line item information",
		description: "Note contains information related to sub-line item data.",
	},
	{
		code: "BAO",
		name: "Test information",
		description: "Information related to a test.",
	},
	{
		code: "BAP",
		name: "External link",
		description: "The external link to a digital document (e.g.: URL).",
	},
	{
		code: "BAQ",
		name: "VAT exemption reason",
		description: "Reason for Value Added Tax (VAT) exemption.",
	},
	{
		code: "BAR",
		name: "Processing Instructions",
		description: "Instructions for processing.",
	},
	{
		code: "BAS",
		name: "Relay Instructions",
		description: "Instructions for relaying.",
	},
	{
		code: "BAT",
		name: "SIMA applicable",
		description: "Identifies that Special Import Measures Act applies",
	},
	{
		code: "BAU",
		name: "Appeals program code",
		description: "Identifies information related to an appeals program.",
	},
	{
		code: "BAV",
		name: "SIMA subject",
		description:
			"Identifies if the goods are subject to a Special Import Measures Act measure.",
	},
	{
		code: "BAW",
		name: "Surtax applicable",
		description: "Identifies that surtax applies",
	},
	{
		code: "BAX",
		name: "SIMA security bond",
		description:
			"Identifies that there is a security bond in hand that could theoretically be used to cover Special Import Measures Act charges",
	},
	{
		code: "BAY",
		name: "Surtax subject",
		description: "Identifies if the goods are subject to a surtax measure",
	},
	{
		code: "BAZ",
		name: "Safeguard applicable",
		description: "Identifies safeguard applies",
	},
	{
		code: "BBA",
		name: "Safeguard applicable",
		description: "Identifies safeguard applies",
	},
	{
		code: "BBB",
		name: "Safeguard subject",
		description: "Identifies if the goods are subject to a safeguard measure",
	},
	{
		code: "BLC",
		name: "Transport contract document clause",
		description:
			"[4180] Clause on a transport document regarding the cargo being consigned. Synonym: Bill of Lading clause.",
	},
	{
		code: "BLD",
		name: "Instruction to prepare the patient",
		description: "Instruction with the purpose of preparing the patient.",
	},
	{
		code: "BLE",
		name: "Medicine treatment comment",
		description: "Comment about treatment with medicine.",
	},
	{
		code: "BLF",
		name: "Examination result comment",
		description: "Comment about the result of an examination.",
	},
	{
		code: "BLG",
		name: "Service request comment",
		description: "Comment about the requested service.",
	},
	{
		code: "BLH",
		name: "Prescription reason",
		description: "Details of the reason for a prescription.",
	},
	{
		code: "BLI",
		name: "Prescription comment",
		description: "Comment concerning a specified prescription.",
	},
	{
		code: "BLJ",
		name: "Clinical investigation comment",
		description: "Comment concerning a clinical investigation.",
	},
	{
		code: "BLK",
		name: "Medicinal specification comment",
		description: "Comment concerning the specification of a medicinal product.",
	},
	{
		code: "BLL",
		name: "Economic contribution comment",
		description: "Comment concerning economic contribution.",
	},
	{
		code: "BLM",
		name: "Status of a plan",
		description: "Comment about the status of a plan.",
	},
	{
		code: "BLN",
		name: "Random sample test information",
		description: "Information regarding a random sample test.",
	},
	{
		code: "BLO",
		name: "Period of time",
		description: "Text subject is a period of time.",
	},
	{
		code: "BLP",
		name: "Legislation",
		description: "Information about legislation.",
	},
	{
		code: "BLQ",
		name: "Security measures requested",
		description:
			"Text describing security measures that are requested to be executed (e.g. access controls, supervision of ship's stores).",
	},
	{
		code: "BLR",
		name: "Transport contract document remark",
		description:
			"[4244] Remarks concerning the complete consignment to be printed on the transport document. Synonym: Bill of Lading remark.",
	},
	{
		code: "BLS",
		name: "Previous port of call security information",
		description:
			"Text describing the security information as applicable at the port facility in the previous port where a ship/port interface was conducted.",
	},
	{
		code: "BLT",
		name: "Security information",
		description:
			"Text describing security related information (e.g security measures currently in force on a vessel).",
	},
	{
		code: "BLU",
		name: "Waste information",
		description: "Text describing waste related information.",
	},
	{
		code: "BLV",
		name: "B2C marketing information, short description",
		description: "Consumer marketing information, short description.",
	},
	{
		code: "BLW",
		name: "B2B marketing information, long description",
		description: "Trading partner marketing information, long description.",
	},
	{
		code: "BLX",
		name: "B2C marketing information, long description",
		description: "Consumer marketing information, long description.",
	},
	{
		code: "BLY",
		name: "Product ingredients",
		description: "Information on the ingredient make up of the product.",
	},
	{
		code: "BLZ",
		name: "Location short name",
		description:
			"Short name of a location e.g. for display or printing purposes.",
	},
	{
		code: "BMA",
		name: "Packaging material information",
		description:
			"The text contains a description of the material used for packaging.",
	},
	{
		code: "BMB",
		name: "Filler material information",
		description: "Text contains information on the material used for stuffing.",
	},
	{
		code: "BMC",
		name: "Ship-to-ship activity information",
		description: "Text contains information on ship-to-ship activities.",
	},
	{
		code: "BMD",
		name: "Package material description",
		description:
			"A description of the type of material for packaging beyond the level covered by standards such as UN Recommendation 21.",
	},
	{
		code: "BME",
		name: "Consumer level package marking",
		description:
			"Textual representation of the markings on a consumer level package.",
	},
	{
		code: "BMF",
		name: "SIMA measure in force",
		description:
			"Identifies the specific Special Import Measures Act measure related to the goods",
	},
	{
		code: "BMG",
		name: "Pre-CARM",
		description:
			"Identifiication of how the transmission should be processed regarding submissions transmitted prior to implementation of Canada Border Services Agency’s Assessment and Revenue Management (CARM) project",
	},
	{
		code: "BMH",
		name: "SIMA measure type",
		description:
			"Identification of the type of Special Import Measures Act measure",
	},
	{
		code: "CCI",
		name: "Customs clearance instructions",
		description:
			"Any coded or clear instruction agreed by customer and carrier regarding the declaration of the goods.",
	},
	{
		code: "CCJ",
		name: "Sub Type Code",
		description: "Code which identifies a secondary form type",
	},
	{
		code: "CCK",
		name: "SIMA information",
		description:
			"Additional information detailing Special Import Measures Act information",
	},
	{
		code: "CCL",
		name: "Time limit end",
		description: "The date the goods exited the economy or warehouse",
	},
	{
		code: "CCM",
		name: "Time limit start",
		description: "The date the goods entered the economy or warehouse",
	},
	{
		code: "CCN",
		name: "Warehouse time limit",
		description: "The amount of time goods may remain in the warehouse",
	},
	{
		code: "CCO",
		name: "Value for duty information",
		description:
			"Additional information detailing the basis on which the value for duty was determined",
	},
	{
		code: "CEX",
		name: "Customs clearance instructions export",
		description:
			"Any coded or clear instruction agreed by customer and carrier regarding the export declaration of the goods.",
	},
	{
		code: "CHG",
		name: "Change information",
		description: "Note contains change information.",
	},
	{
		code: "CIP",
		name: "Customs clearance instruction import",
		description:
			"Any coded or clear instruction agreed by customer and carrier regarding the import declaration of the goods.",
	},
	{
		code: "CLP",
		name: "Clearance place requested",
		description:
			"Name of the place where Customs clearance is asked to be executed as requested by the consignee/consignor.",
	},
	{
		code: "CLR",
		name: "Loading remarks",
		description: "Instructions concerning the loading of the container.",
	},
	{
		code: "COI",
		name: "Order information",
		description: "Additional information related to an order.",
	},
	{
		code: "CUR",
		name: "Customer remarks",
		description: "Remarks from or for a supplier of goods or services.",
	},
	{
		code: "CUS",
		name: "Customs declaration information",
		description: "(4034) Note contains customs declaration information.",
	},
	{
		code: "DAR",
		name: "Damage remarks",
		description: "Remarks concerning damage on the cargo.",
	},
	{
		code: "DCL",
		name: "Document issuer declaration",
		description:
			"[4020] Text of a declaration made by the issuer of a document.",
	},
	{
		code: "DEL",
		name: "Delivery information",
		description: "Information about delivery.",
	},
	{
		code: "DIN",
		name: "Delivery instructions",
		description: "[4492] Instructions regarding the delivery of the cargo.",
	},
	{
		code: "DOC",
		name: "Documentation instructions",
		description: "Instructions pertaining to the documentation.",
	},
	{
		code: "DUT",
		name: "Duty declaration",
		description:
			"The text contains a statement constituting a duty declaration.",
	},
	{
		code: "EUR",
		name: "Effective used routing",
		description:
			"Physical route effectively used for the movement of the means of transport.",
	},
	{
		code: "FBC",
		name: "First block to be printed on the transport contract",
		description:
			"The first block of text to be printed on the transport contract.",
	},
	{
		code: "GBL",
		name: "Government bill of lading information",
		description:
			"Free text information on a transport document to indicate payment information by Government Bill of Lading.",
	},
	{
		code: "GEN",
		name: "Entire transaction set",
		description:
			"Note is general in nature, applies to entire transaction segment.",
	},
	{
		code: "GS7",
		name: "Further information concerning GGVS par. 7",
		description:
			"Special permission for road transport of certain goods in the German dangerous goods regulation for road transport.",
	},
	{
		code: "HAN",
		name: "Consignment handling instruction",
		description:
			"[4078] Free form description of a set of handling instructions. For example how specified goods, packages or transport equipment (container) should be handled.",
	},
	{
		code: "HAZ",
		name: "Hazard information",
		description: "Information pertaining to a hazard.",
	},
	{
		code: "ICN",
		name: "Consignment information for consignee",
		description:
			"[4070] Any remarks given for the information of the consignee.",
	},
	{
		code: "IIN",
		name: "Insurance instructions",
		description: "(4112) Instructions regarding the cargo insurance.",
	},
	{
		code: "IMI",
		name: "Invoice mailing instructions",
		description:
			"Instructions as to which freight and charges components have to be mailed to whom.",
	},
	{
		code: "IND",
		name: "Commercial invoice item description",
		description: "Free text describing goods on a commercial invoice line.",
	},
	{
		code: "INS",
		name: "Insurance information",
		description: "Specific note contains insurance information.",
	},
	{
		code: "INV",
		name: "Invoice instruction",
		description: "Note contains invoice instructions.",
	},
	{
		code: "IRP",
		name: "Information for railway purpose",
		description:
			"Data entered by railway stations when required, e.g. specified trains, additional sheets for freight calculations, special measures, etc.",
	},
	{
		code: "ITR",
		name: "Inland transport details",
		description:
			"Information concerning the pre-carriage to the port of discharge if by other means than a vessel.",
	},
	{
		code: "ITS",
		name: "Testing instructions",
		description:
			"Instructions regarding the testing that is required to be carried out on the items in the transaction.",
	},
	{
		code: "LAN",
		name: "Location Alias",
		description: "Alternative name for a location.",
	},
	{
		code: "LIN",
		name: "Line item",
		description: "Note contains line item information.",
	},
	{
		code: "LOI",
		name: "Loading instruction",
		description:
			"[4080] Instructions where specified packages or containers are to be loaded on a means of transport.",
	},
	{
		code: "MCO",
		name: "Miscellaneous charge order",
		description:
			"Free text accounting information on an IATA Air Waybill to indicate payment information by Miscellaneous charge order.",
	},
	{
		code: "MDH",
		name: "Maritime Declaration of Health",
		description: "Information about Maritime Declaration of Health.",
	},
	{
		code: "MKS",
		name: "Additional marks/numbers information",
		description: "Additional information regarding the marks and numbers.",
	},
	{
		code: "ORI",
		name: "Order instruction",
		description: "Free text contains order instructions.",
	},
	{
		code: "OSI",
		name: "Other service information",
		description:
			"General information created by the sender of general or specific value.",
	},
	{
		code: "PAC",
		name: "Packing/marking information",
		description: "Information regarding the packaging and/or marking of goods.",
	},
	{
		code: "PAI",
		name: "Payment instructions information",
		description:
			"The free text contains payment instructions information relevant to the message.",
	},
	{
		code: "PAY",
		name: "Payables information",
		description: "Note contains payables information.",
	},
	{
		code: "PKG",
		name: "Packaging information",
		description: "Note contains packaging information.",
	},
	{
		code: "PKT",
		name: "Packaging terms information",
		description: "The text contains packaging terms information.",
	},
	{
		code: "PMD",
		name: "Payment detail/remittance information",
		description: "The free text contains payment details.",
	},
	{
		code: "PMT",
		name: "Payment information",
		description: "(4438) Note contains payments information.",
	},
	{
		code: "PRD",
		name: "Product information",
		description: "The text contains product information.",
	},
	{
		code: "PRF",
		name: "Price calculation formula",
		description:
			"Additional information regarding the price formula used for calculating the item price.",
	},
	{
		code: "PRI",
		name: "Priority information",
		description: "(4218) Note contains priority information.",
	},
	{
		code: "PUR",
		name: "Purchasing information",
		description: "Note contains purchasing information.",
	},
	{
		code: "QIN",
		name: "Quarantine instructions",
		description:
			"Instructions regarding quarantine, i.e. the period during which an arriving vessel, including its equipment, cargo, crew or passengers, suspected to carry or carrying a contagious disease is detained in strict isolation to prevent the spread of such a disease.",
	},
	{
		code: "QQD",
		name: "Quality demands/requirements",
		description:
			"Specification of the quality/performance expectations or standards to which the items must conform.",
	},
	{
		code: "QUT",
		name: "Quotation instruction/information",
		description: "Note contains quotation information.",
	},
	{
		code: "RAH",
		name: "Risk and handling information",
		description:
			"Information concerning risks induced by the goods and/or handling instruction.",
	},
	{
		code: "REG",
		name: "Regulatory information",
		description: "The free text contains information for regulatory authority.",
	},
	{
		code: "RET",
		name: "Return to origin information",
		description:
			"Free text information on an IATA Air Waybill to indicate consignment returned because of non delivery.",
	},
	{
		code: "REV",
		name: "Receivables",
		description: "The text contains receivables information.",
	},
	{
		code: "RQR",
		name: "Consignment route",
		description:
			"[3050] Description of a route to be used for the transport of goods.",
	},
	{
		code: "SAF",
		name: "Safety information",
		description: "The text contains safety information.",
	},
	{
		code: "SIC",
		name: "Consignment documentary instruction",
		description:
			"[4284] Instructions given and declarations made by the sender to the carrier concerning Customs, insurance, and other formalities.",
	},
	{
		code: "SIN",
		name: "Special instructions",
		description:
			"Special instructions like licence no, high value, handle with care, glass.",
	},
	{
		code: "SLR",
		name: "Ship line requested",
		description:
			"Shipping line requested to be used for traffic between European continent and U.K. for Ireland.",
	},
	{
		code: "SPA",
		name: "Special permission for transport, generally",
		description:
			"Statement that a special permission has been obtained for the transport (and/or routing) in general, and reference to such permission.",
	},
	{
		code: "SPG",
		name: "Special permission concerning the goods to be transported",
		description:
			"Statement that a special permission has been obtained for the transport (and/or routing) of the goods specified, and reference to such permission.",
	},
	{
		code: "SPH",
		name: "Special handling",
		description: "Note contains special handling information.",
	},
	{
		code: "SPP",
		name: "Special permission concerning package",
		description:
			"Statement that a special permission has been obtained for the packaging, and reference to such permission.",
	},
	{
		code: "SPT",
		name: "Special permission concerning transport means",
		description:
			"Statement that a special permission has been obtained for the use of the means transport, and reference to such permission.",
	},
	{
		code: "SRN",
		name: "Subsidiary risk number (IATA/DGR)",
		description:
			"Number(s) of subsidiary risks, induced by the goods, according to the valid classification.",
	},
	{
		code: "SSR",
		name: "Special service request",
		description:
			"Request for a special service concerning the transport of the goods.",
	},
	{
		code: "SUR",
		name: "Supplier remarks",
		description: "Remarks from or for a supplier of goods or services.",
	},
	{
		code: "TCA",
		name: "Consignment tariff",
		description:
			"[5430] Free text specification of tariff applied to a consignment.",
	},
	{
		code: "TDT",
		name: "Consignment transport",
		description:
			"[8012] Transport information for commercial purposes (generic term).",
	},
	{
		code: "TRA",
		name: "Transportation information",
		description: "General information regarding the transport of the cargo.",
	},
	{
		code: "TRR",
		name: "Requested tariff",
		description:
			"Stipulation of the tariffs to be applied showing, where applicable, special agreement numbers or references.",
	},
	{
		code: "TXD",
		name: "Tax declaration",
		description:
			"The text contains a statement constituting a tax declaration.",
	},
	{
		code: "WHI",
		name: "Warehouse instruction/information",
		description: "Note contains warehouse information.",
	},
	{
		code: "ZZZ",
		name: "Mutually defined",
		description:
			"Note contains information mutually defined by trading partners.",
	},
] as const satisfies Untdid4451Definition[];
