/**
 * Generated by `scripts/untdid/update.js` on Mon, 28 Jul 2025 11:56:26 GMT
 *
 * @see https://www.xrepository.de/details/urn:xoev-de:kosit:codeliste:untdid.4451
 */

export type Untdid4451Definition = {
	key: string;
	code: string;
	name?: string;
	description?: string;
};

export type Untdid4451Code = (typeof UNTDID_4451)[number]["code"];

export const UNTDID_4451_IDENTIFIER =
	"urn:xoev-de:kosit:codeliste:untdid.4451" as const;
export const UNTDID_4451_VERSION = "4" as const;

export const UNTDID_4451 = [
	{
		key: "GOODS_ITEM_DESCRIPTION",
		code: "AAA",
		name: "Goods item description",
		description:
			"[7002] Plain language description of the nature of a goods item sufficient to identify it for customs, statistical or transport purposes.",
	},
	{
		key: "PAYMENT_TERM",
		code: "AAB",
		name: "Payment term",
		description:
			"[4276] Free form description of the conditions of payment between the parties to a transaction.",
	},
	{
		key: "DANGEROUS_GOODS_ADDITIONAL_INFORMATION",
		code: "AAC",
		name: "Dangerous goods additional information",
		description:
			"[7488] Additional information concerning dangerous substances and/or article in a consignment.",
	},
	{
		key: "DANGEROUS_GOODS_TECHNICAL_NAME",
		code: "AAD",
		name: "Dangerous goods technical name",
		description:
			"[7254] Proper shipping name, supplemented as necessary with the correct technical name, by which a dangerous substance or article may be correctly identified, or which is sufficiently informative to permit identification by reference to generally available literature.",
	},
	{
		key: "ACKNOWLEDGEMENT_DESCRIPTION",
		code: "AAE",
		name: "Acknowledgement description",
		description: "The content of an acknowledgement.",
	},
	{
		key: "RATE_ADDITIONAL_INFORMATION",
		code: "AAF",
		name: "Rate additional information",
		description: "Specific details applying to rates.",
	},
	{
		key: "PARTY_INSTRUCTIONS",
		code: "AAG",
		name: "Party instructions",
		description:
			"Indicates that the segment contains instructions to be passed on to the identified party.",
	},
	{
		key: "GENERAL_INFORMATION",
		code: "AAI",
		name: "General information",
		description: "The text contains general information.",
	},
	{
		key: "ADDITIONAL_CONDITIONS_OF_SALEPURCHASE",
		code: "AAJ",
		name: "Additional conditions of sale/purchase",
		description: "Additional conditions specific to this order or project.",
	},
	{
		key: "PRICE_CONDITIONS",
		code: "AAK",
		name: "Price conditions",
		description:
			"Information on the price conditions that are expected or given.",
	},
	{
		key: "GOODS_DIMENSIONS_IN_CHARACTERS",
		code: "AAL",
		name: "Goods dimensions in characters",
		description:
			"Expression of a number in characters as length of ten meters.",
	},
	{
		key: "EQUIPMENT_RE_USAGE_RESTRICTIONS",
		code: "AAM",
		name: "Equipment re-usage restrictions",
		description:
			"Technical or commercial reasons why a piece of equipment may not be re-used after the current transport terminates.",
	},
	{
		key: "HANDLING_RESTRICTION",
		code: "AAN",
		name: "Handling restriction",
		description:
			"Restrictions in handling depending on the technical characteristics of the piece of equipment or on the nature of the goods.",
	},
	{
		key: "ERROR_DESCRIPTION_FREE_TEXT",
		code: "AAO",
		name: "Error description (free text)",
		description: "Error described by a free text.",
	},
	{
		key: "RESPONSE_FREE_TEXT",
		code: "AAP",
		name: "Response (free text)",
		description: "Free text of the response to a communication.",
	},
	{
		key: "PACKAGE_CONTENTS_DESCRIPTION",
		code: "AAQ",
		name: "Package content's description",
		description: "A description of the contents of a package.",
	},
	{
		key: "TERMS_OF_DELIVERY",
		code: "AAR",
		name: "Terms of delivery",
		description:
			"(4053) Free text of the non Incoterms terms of delivery. For Incoterms, use: 4053.",
	},
	{
		key: "BILL_OF_LADING_REMARKS",
		code: "AAS",
		name: "Bill of lading remarks",
		description: "The remarks printed or to be printed on a bill of lading.",
	},
	{
		key: "MODE_OF_SETTLEMENT_INFORMATION",
		code: "AAT",
		name: "Mode of settlement information",
		description:
			"Free text information on an IATA Air Waybill to indicate means by which account is to be settled.",
	},
	{
		key: "CONSIGNMENT_INVOICE_INFORMATION",
		code: "AAU",
		name: "Consignment invoice information",
		description:
			"Information pertaining to the invoice covering the consignment.",
	},
	{
		key: "CLEARANCE_INVOICE_INFORMATION",
		code: "AAV",
		name: "Clearance invoice information",
		description:
			"Information pertaining to the invoice covering clearance of the cargo.",
	},
	{
		key: "LETTER_OF_CREDIT_INFORMATION",
		code: "AAW",
		name: "Letter of credit information",
		description: "Information pertaining to the letter of credit.",
	},
	{
		key: "LICENSE_INFORMATION",
		code: "AAX",
		name: "License information",
		description: "Information pertaining to a license.",
	},
	{
		key: "CERTIFICATION_STATEMENTS",
		code: "AAY",
		name: "Certification statements",
		description: "The text contains certification statements.",
	},
	{
		key: "ADDITIONAL_EXPORT_INFORMATION",
		code: "AAZ",
		name: "Additional export information",
		description: "The text contains additional export information.",
	},
	{
		key: "TARIFF_STATEMENTS",
		code: "ABA",
		name: "Tariff statements",
		description: "Description of parameters relating to a tariff.",
	},
	{
		key: "MEDICAL_HISTORY",
		code: "ABB",
		name: "Medical history",
		description: "Historical details of a patients medical events.",
	},
	{
		key: "CONDITIONS_OF_SALE_OR_PURCHASE",
		code: "ABC",
		name: "Conditions of sale or purchase",
		description:
			"(4490) (4372) Additional information regarding terms and conditions which apply to the transaction.",
	},
	{
		key: "CONTRACT_DOCUMENT_TYPE",
		code: "ABD",
		name: "Contract document type",
		description: "[4422] Textual representation of the type of contract.",
	},
	{
		key: "ADDITIONAL_TERMS_ANDOR_CONDITIONS_DOCUMENTARY_CREDIT",
		code: "ABE",
		name: "Additional terms and/or conditions (documentary credit)",
		description:
			"(4260) Additional terms and/or conditions to the documentary credit.",
	},
	{
		key: "INSTRUCTIONS_OR_INFORMATION_ABOUT_STANDBY_DOCUMENTARY_CREDIT",
		code: "ABF",
		name: "Instructions or information about standby documentary credit",
		description:
			"Instruction or information about a standby documentary credit.",
	},
	{
		key: "INSTRUCTIONS_OR_INFORMATION_ABOUT_PARTIAL_SHIPMENTS",
		code: "ABG",
		name: "Instructions or information about partial shipment(s)",
		description: "Instructions or information about partial shipment(s).",
	},
	{
		key: "INSTRUCTIONS_OR_INFORMATION_ABOUT_TRANSHIPMENTS",
		code: "ABH",
		name: "Instructions or information about transhipment(s)",
		description: "Instructions or information about transhipment(s).",
	},
	{
		key: "ADDITIONAL_HANDLING_INSTRUCTIONS_DOCUMENTARY_CREDIT",
		code: "ABI",
		name: "Additional handling instructions documentary credit",
		description: "Additional handling instructions for a documentary credit.",
	},
	{
		key: "DOMESTIC_ROUTING_INFORMATION",
		code: "ABJ",
		name: "Domestic routing information",
		description: "Information regarding the domestic routing.",
	},
	{
		key: "CHARGEABLE_CATEGORY_OF_EQUIPMENT",
		code: "ABK",
		name: "Chargeable category of equipment",
		description:
			"Equipment types are coded by category for financial purposes.",
	},
	{
		key: "GOVERNMENT_INFORMATION",
		code: "ABL",
		name: "Government information",
		description: "Information pertaining to government.",
	},
	{
		key: "ONWARD_ROUTING_INFORMATION",
		code: "ABM",
		name: "Onward routing information",
		description: "The text contains onward routing information.",
	},
	{
		key: "ACCOUNTING_INFORMATION",
		code: "ABN",
		name: "Accounting information",
		description: "[4410] The text contains information related to accounting.",
	},
	{
		key: "DISCREPANCY_INFORMATION",
		code: "ABO",
		name: "Discrepancy information",
		description:
			"Free text or coded information to indicate a specific discrepancy.",
	},
	{
		key: "CONFIRMATION_INSTRUCTIONS",
		code: "ABP",
		name: "Confirmation instructions",
		description: "Documentary credit confirmation instructions.",
	},
	{
		key: "METHOD_OF_ISSUANCE",
		code: "ABQ",
		name: "Method of issuance",
		description: "Method of issuance of documentary credit.",
	},
	{
		key: "DOCUMENTS_DELIVERY_INSTRUCTIONS",
		code: "ABR",
		name: "Documents delivery instructions",
		description:
			"Delivery instructions for documents required under a documentary credit.",
	},
	{
		key: "ADDITIONAL_CONDITIONS",
		code: "ABS",
		name: "Additional conditions",
		description:
			"Additional conditions to the issuance of a documentary credit.",
	},
	{
		key: "INFORMATIONINSTRUCTIONS_ABOUT_ADDITIONAL_AMOUNTS_COVERED",
		code: "ABT",
		name: "Information/instructions about additional amounts covered",
		description: "Additional amounts information/instruction.",
	},
	{
		key: "DEFERRED_PAYMENT_TERMED_ADDITIONAL",
		code: "ABU",
		name: "Deferred payment termed additional",
		description: "Additional terms concerning deferred payment.",
	},
	{
		key: "ACCEPTANCE_TERMS_ADDITIONAL",
		code: "ABV",
		name: "Acceptance terms additional",
		description: "Additional terms concerning acceptance.",
	},
	{
		key: "NEGOTIATION_TERMS_ADDITIONAL",
		code: "ABW",
		name: "Negotiation terms additional",
		description: "Additional terms concerning negotiation.",
	},
	{
		key: "DOCUMENT_NAME_AND_DOCUMENTARY_REQUIREMENTS",
		code: "ABX",
		name: "Document name and documentary requirements",
		description: "Document name and documentary requirements.",
	},
	{
		key: "INSTRUCTIONSINFORMATION_ABOUT_REVOLVING_DOCUMENTARY_CREDIT",
		code: "ABZ",
		name: "Instructions/information about revolving documentary credit",
		description:
			"Instructions/information about a revolving documentary credit.",
	},
	{
		key: "DOCUMENTARY_REQUIREMENTS",
		code: "ACA",
		name: "Documentary requirements",
		description: "Specification of the documentary requirements.",
	},
	{
		key: "ADDITIONAL_INFORMATION",
		code: "ACB",
		name: "Additional information",
		description: "(4270) The text contains additional information.",
	},
	{
		key: "FACTOR_ASSIGNMENT_CLAUSE",
		code: "ACC",
		name: "Factor assignment clause",
		description: "Assignment based on an agreement between seller and factor.",
	},
	{
		key: "REASON",
		code: "ACD",
		name: "Reason",
		description: "Reason for a request or response.",
	},
	{
		key: "DISPUTE",
		code: "ACE",
		name: "Dispute",
		description:
			"A notice, usually from buyer to seller, that something was found wrong with goods delivered or the services rendered, or with the related invoice.",
	},
	{
		key: "ADDITIONAL_ATTRIBUTE_INFORMATION",
		code: "ACF",
		name: "Additional attribute information",
		description:
			"The text refers to information about an additional attribute not otherwise specified.",
	},
	{
		key: "ABSENCE_DECLARATION",
		code: "ACG",
		name: "Absence declaration",
		description: "A declaration on the reason of the absence.",
	},
	{
		key: "AGGREGATION_STATEMENT",
		code: "ACH",
		name: "Aggregation statement",
		description:
			"A statement on the way a specific variable or set of variables has been aggregated.",
	},
	{
		key: "COMPILATION_STATEMENT",
		code: "ACI",
		name: "Compilation statement",
		description:
			"A statement on the compilation status of an array or other set of figures or calculations.",
	},
	{
		key: "DEFINITIONAL_EXCEPTION",
		code: "ACJ",
		name: "Definitional exception",
		description:
			"An exception to the agreed definition of a term, concept, formula or other object.",
	},
	{
		key: "PRIVACY_STATEMENT",
		code: "ACK",
		name: "Privacy statement",
		description:
			"A statement on the privacy or confidential nature of an object.",
	},
	{
		key: "QUALITY_STATEMENT",
		code: "ACL",
		name: "Quality statement",
		description: "A statement on the quality of an object.",
	},
	{
		key: "STATISTICAL_DESCRIPTION",
		code: "ACM",
		name: "Statistical description",
		description:
			"The description of a statistical object such as a value list, concept, or structure definition.",
	},
	{
		key: "STATISTICAL_DEFINITION",
		code: "ACN",
		name: "Statistical definition",
		description:
			"The definition of a statistical object such as a value list, concept, or structure definition.",
	},
	{
		key: "STATISTICAL_NAME",
		code: "ACO",
		name: "Statistical name",
		description:
			"The name of a statistical object such as a value list, concept or structure definition.",
	},
	{
		key: "STATISTICAL_TITLE",
		code: "ACP",
		name: "Statistical title",
		description:
			"The title of a statistical object such as a value list, concept, or structure definition.",
	},
	{
		key: "OFF_DIMENSION_INFORMATION",
		code: "ACQ",
		name: "Off-dimension information",
		description:
			"Information relating to differences between the actual transport dimensions and the normally applicable dimensions.",
	},
	{
		key: "UNEXPECTED_STOPS_INFORMATION",
		code: "ACR",
		name: "Unexpected stops information",
		description:
			"Information relating to unexpected stops during a conveyance.",
	},
	{
		key: "PRINCIPLES",
		code: "ACS",
		name: "Principles",
		description:
			"Text subject is principles section of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		key: "TERMS_AND_DEFINITION",
		code: "ACT",
		name: "Terms and definition",
		description:
			"Text subject is terms and definition section of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		key: "SEGMENT_NAME",
		code: "ACU",
		name: "Segment name",
		description: "Text subject is segment name.",
	},
	{
		key: "SIMPLE_DATA_ELEMENT_NAME",
		code: "ACV",
		name: "Simple data element name",
		description: "Text subject is name of simple data element.",
	},
	{
		key: "SCOPE",
		code: "ACW",
		name: "Scope",
		description:
			"Text subject is scope section of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		key: "MESSAGE_TYPE_NAME",
		code: "ACX",
		name: "Message type name",
		description: "Text subject is name of message type.",
	},
	{
		key: "INTRODUCTION",
		code: "ACY",
		name: "Introduction",
		description:
			"Text subject is introduction section of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		key: "GLOSSARY",
		code: "ACZ",
		name: "Glossary",
		description:
			"Text subject is glossary section of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		key: "FUNCTIONAL_DEFINITION",
		code: "ADA",
		name: "Functional definition",
		description:
			"Text subject is functional definition section of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		key: "EXAMPLES",
		code: "ADB",
		name: "Examples",
		description:
			"Text subject is examples as given in the example(s) section of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		key: "COVER_PAGE",
		code: "ADC",
		name: "Cover page",
		description:
			"Text subject is cover page of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		key: "DEPENDENCY_SYNTAX_NOTES",
		code: "ADD",
		name: "Dependency (syntax) notes",
		description:
			"Denotes that the associated text is a dependency (syntax) note.",
	},
	{
		key: "CODE_VALUE_NAME",
		code: "ADE",
		name: "Code value name",
		description: "Text subject is name of code value.",
	},
	{
		key: "CODE_LIST_NAME",
		code: "ADF",
		name: "Code list name",
		description: "Text subject is name of code list.",
	},
	{
		key: "CLARIFICATION_OF_USAGE",
		code: "ADG",
		name: "Clarification of usage",
		description:
			"Text subject is an explanation of the intended usage of a segment or segment group.",
	},
	{
		key: "COMPOSITE_DATA_ELEMENT_NAME",
		code: "ADH",
		name: "Composite data element name",
		description: "Text subject is name of composite data element.",
	},
	{
		key: "FIELD_OF_APPLICATION",
		code: "ADI",
		name: "Field of application",
		description:
			"Text subject is field of application of the UN/EDIFACT rules for presentation of standardized message and directories documentation.",
	},
	{
		key: "TYPE_OF_ASSETS_AND_LIABILITIES",
		code: "ADJ",
		name: "Type of assets and liabilities",
		description: "Information describing the type of assets and liabilities.",
	},
	{
		key: "PROMOTION_INFORMATION",
		code: "ADK",
		name: "Promotion information",
		description: "The text contains information about a promotion.",
	},
	{
		key: "METER_CONDITION",
		code: "ADL",
		name: "Meter condition",
		description: "Description of the condition of a meter.",
	},
	{
		key: "METER_READING_INFORMATION",
		code: "ADM",
		name: "Meter reading information",
		description: "Information related to a particular reading of a meter.",
	},
	{
		key: "TYPE_OF_TRANSACTION_REASON",
		code: "ADN",
		name: "Type of transaction reason",
		description:
			"Information describing the type of the reason of transaction.",
	},
	{
		key: "TYPE_OF_SURVEY_QUESTION",
		code: "ADO",
		name: "Type of survey question",
		description: "Type of survey question.",
	},
	{
		key: "CARRIERS_AGENT_COUNTER_INFORMATION",
		code: "ADP",
		name: "Carrier's agent counter information",
		description: "Information for use at the counter of the carrier's agent.",
	},
	{
		key: "DESCRIPTION_OF_WORK_ITEM_ON_EQUIPMENT",
		code: "ADQ",
		name: "Description of work item on equipment",
		description:
			"Description or code for the operation to be executed on the equipment.",
	},
	{
		key: "MESSAGE_DEFINITION",
		code: "ADR",
		name: "Message definition",
		description: "Text subject is message definition.",
	},
	{
		key: "BOOKED_ITEM_INFORMATION",
		code: "ADS",
		name: "Booked item information",
		description: "Information pertaining to a booked item.",
	},
	{
		key: "SOURCE_OF_DOCUMENT",
		code: "ADT",
		name: "Source of document",
		description: "Text subject is source of document.",
	},
	{
		key: "NOTE",
		code: "ADU",
		name: "Note",
		description: "Text subject is note.",
	},
	{
		key: "FIXED_PART_OF_SEGMENT_CLARIFICATION_TEXT",
		code: "ADV",
		name: "Fixed part of segment clarification text",
		description: "Text subject is fixed part of segment clarification text.",
	},
	{
		key: "CHARACTERISTICS_OF_GOODS",
		code: "ADW",
		name: "Characteristics of goods",
		description:
			"Description of the characteristic of goods in addition to the description of the goods.",
	},
	{
		key: "ADDITIONAL_DISCHARGE_INSTRUCTIONS",
		code: "ADX",
		name: "Additional discharge instructions",
		description: "Special discharge instructions concerning the goods.",
	},
	{
		key: "CONTAINER_STRIPPING_INSTRUCTIONS",
		code: "ADY",
		name: "Container stripping instructions",
		description: "Instructions regarding the stripping of container(s).",
	},
	{
		key: "CSC_CONTAINER_SAFETY_CONVENTION_PLATE_INFORMATION",
		code: "ADZ",
		name: "CSC (Container Safety Convention) plate information",
		description:
			"Information on the CSC (Container Safety Convention) plate that is attached to the container.",
	},
	{
		key: "CARGO_REMARKS",
		code: "AEA",
		name: "Cargo remarks",
		description: "Additional remarks concerning the cargo.",
	},
	{
		key: "TEMPERATURE_CONTROL_INSTRUCTIONS",
		code: "AEB",
		name: "Temperature control instructions",
		description: "Instruction regarding the temperature control of the cargo.",
	},
	{
		key: "TEXT_REFERS_TO_EXPECTED_DATA",
		code: "AEC",
		name: "Text refers to expected data",
		description: "Remarks refer to data that was expected.",
	},
	{
		key: "TEXT_REFERS_TO_RECEIVED_DATA",
		code: "AED",
		name: "Text refers to received data",
		description: "Remarks refer to data that was received.",
	},
	{
		key: "SECTION_CLARIFICATION_TEXT",
		code: "AEE",
		name: "Section clarification text",
		description: "Text subject is section clarification text.",
	},
	{
		key: "INFORMATION_TO_THE_BENEFICIARY",
		code: "AEF",
		name: "Information to the beneficiary",
		description: "Information given to the beneficiary.",
	},
	{
		key: "INFORMATION_TO_THE_APPLICANT",
		code: "AEG",
		name: "Information to the applicant",
		description: "Information given to the applicant.",
	},
	{
		key: "INSTRUCTIONS_TO_THE_BENEFICIARY",
		code: "AEH",
		name: "Instructions to the beneficiary",
		description: "Instructions made to the beneficiary.",
	},
	{
		key: "INSTRUCTIONS_TO_THE_APPLICANT",
		code: "AEI",
		name: "Instructions to the applicant",
		description: "Instructions given to the applicant.",
	},
	{
		key: "CONTROLLED_ATMOSPHERE",
		code: "AEJ",
		name: "Controlled atmosphere",
		description: "Information about the controlled atmosphere.",
	},
	{
		key: "TAKE_OFF_ANNOTATION",
		code: "AEK",
		name: "Take off annotation",
		description:
			"Additional information in plain text to support a take off annotation. Taking off is the process of assessing the quantity work from extracting the measurement from construction documentation.",
	},
	{
		key: "PRICE_VARIATION_NARRATIVE",
		code: "AEL",
		name: "Price variation narrative",
		description:
			"Additional information in plain language to support a price variation.",
	},
	{
		key: "DOCUMENTARY_CREDIT_AMENDMENT_INSTRUCTIONS",
		code: "AEM",
		name: "Documentary credit amendment instructions",
		description: "Documentary credit amendment instructions.",
	},
	{
		key: "STANDARD_METHOD_NARRATIVE",
		code: "AEN",
		name: "Standard method narrative",
		description:
			"Additional information in plain language to support a standard method.",
	},
	{
		key: "PROJECT_NARRATIVE",
		code: "AEO",
		name: "Project narrative",
		description:
			"Additional information in plain language to support the project.",
	},
	{
		key: "RADIOACTIVE_GOODS_ADDITIONAL_INFORMATION",
		code: "AEP",
		name: "Radioactive goods, additional information",
		description: "Additional information related to radioactive goods.",
	},
	{
		key: "BANK_TO_BANK_INFORMATION",
		code: "AEQ",
		name: "Bank-to-bank information",
		description: "Information given from one bank to another.",
	},
	{
		key: "REIMBURSEMENT_INSTRUCTIONS",
		code: "AER",
		name: "Reimbursement instructions",
		description: "Instructions given for reimbursement purposes.",
	},
	{
		key: "REASON_FOR_AMENDING_A_MESSAGE",
		code: "AES",
		name: "Reason for amending a message",
		description: "Identification of the reason for amending a message.",
	},
	{
		key: "INSTRUCTIONS_TO_THE_PAYING_ANDOR_ACCEPTING_ANDOR_NEGOTIATING_BANK",
		code: "AET",
		name: "Instructions to the paying and/or accepting and/or negotiating bank",
		description:
			"Instructions to the paying and/or accepting and/or negotiating bank.",
	},
	{
		key: "INTEREST_INSTRUCTIONS",
		code: "AEU",
		name: "Interest instructions",
		description: "Instructions given about the interest.",
	},
	{
		key: "AGENT_COMMISSION",
		code: "AEV",
		name: "Agent commission",
		description: "Instructions about agent commission.",
	},
	{
		key: "REMITTING_BANK_INSTRUCTIONS",
		code: "AEW",
		name: "Remitting bank instructions",
		description: "Instructions to the remitting bank.",
	},
	{
		key: "INSTRUCTIONS_TO_THE_COLLECTING_BANK",
		code: "AEX",
		name: "Instructions to the collecting bank",
		description:
			"Instructions to the bank, other than the remitting bank, involved in processing the collection.",
	},
	{
		key: "COLLECTION_AMOUNT_INSTRUCTIONS",
		code: "AEY",
		name: "Collection amount instructions",
		description: "Instructions about the collection amount.",
	},
	{
		key: "INTERNAL_AUDITING_INFORMATION",
		code: "AEZ",
		name: "Internal auditing information",
		description: "Text relating to internal auditing information.",
	},
	{
		key: "CONSTRAINT",
		code: "AFA",
		name: "Constraint",
		description: "Denotes that the associated text is a constraint.",
	},
	{
		key: "COMMENT",
		code: "AFB",
		name: "Comment",
		description: "Denotes that the associated text is a comment.",
	},
	{
		key: "SEMANTIC_NOTE",
		code: "AFC",
		name: "Semantic note",
		description: "Denotes that the associated text is a semantic note.",
	},
	{
		key: "HELP_TEXT",
		code: "AFD",
		name: "Help text",
		description: "Denotes that the associated text is an item of help text.",
	},
	{
		key: "LEGEND",
		code: "AFE",
		name: "Legend",
		description: "Denotes that the associated text is a legend.",
	},
	{
		key: "BATCH_CODE_STRUCTURE",
		code: "AFF",
		name: "Batch code structure",
		description: "A description of the structure of a batch code.",
	},
	{
		key: "PRODUCT_APPLICATION",
		code: "AFG",
		name: "Product application",
		description: "A general description of the application of a product.",
	},
	{
		key: "CUSTOMER_COMPLAINT",
		code: "AFH",
		name: "Customer complaint",
		description: "Complaint of customer.",
	},
	{
		key: "PROBABLE_CAUSE_OF_FAULT",
		code: "AFI",
		name: "Probable cause of fault",
		description: "The probable cause of fault.",
	},
	{
		key: "DEFECT_DESCRIPTION",
		code: "AFJ",
		name: "Defect description",
		description: "Description of the defect.",
	},
	{
		key: "REPAIR_DESCRIPTION",
		code: "AFK",
		name: "Repair description",
		description: "The description of the work performed during the repair.",
	},
	{
		key: "REVIEW_COMMENTS",
		code: "AFL",
		name: "Review comments",
		description: "Comments relevant to a review.",
	},
	{
		key: "TITLE",
		code: "AFM",
		name: "Title",
		description: "Denotes that the associated text is a title.",
	},
	{
		key: "DESCRIPTION_OF_AMOUNT",
		code: "AFN",
		name: "Description of amount",
		description: "An amount description in clear text.",
	},
	{
		key: "RESPONSIBILITIES",
		code: "AFO",
		name: "Responsibilities",
		description: "Information describing the responsibilities.",
	},
	{
		key: "SUPPLIER",
		code: "AFP",
		name: "Supplier",
		description: "Information concerning suppliers.",
	},
	{
		key: "PURCHASE_REGION",
		code: "AFQ",
		name: "Purchase region",
		description:
			"Information concerning the region(s) where purchases are made.",
	},
	{
		key: "AFFILIATION",
		code: "AFR",
		name: "Affiliation",
		description:
			"Information concerning an association of one party with another party(ies).",
	},
	{
		key: "BORROWER",
		code: "AFS",
		name: "Borrower",
		description: "Information concerning the borrower.",
	},
	{
		key: "LINE_OF_BUSINESS",
		code: "AFT",
		name: "Line of business",
		description: "Information concerning an entity's line of business.",
	},
	{
		key: "FINANCIAL_INSTITUTION",
		code: "AFU",
		name: "Financial institution",
		description: "Description of financial institution(s) used by an entity.",
	},
	{
		key: "BUSINESS_FOUNDER",
		code: "AFV",
		name: "Business founder",
		description: "Information about the business founder.",
	},
	{
		key: "BUSINESS_HISTORY",
		code: "AFW",
		name: "Business history",
		description: "Description of the business history.",
	},
	{
		key: "BANKING_ARRANGEMENTS",
		code: "AFX",
		name: "Banking arrangements",
		description: "Information concerning the general banking arrangements.",
	},
	{
		key: "BUSINESS_ORIGIN",
		code: "AFY",
		name: "Business origin",
		description: "Description of the business origin.",
	},
	{
		key: "BRAND_NAMES_DESCRIPTION",
		code: "AFZ",
		name: "Brand names' description",
		description: "Description of the entity's brands.",
	},
	{
		key: "BUSINESS_FINANCING_DETAILS",
		code: "AGA",
		name: "Business financing details",
		description: "Details about the financing of the business.",
	},
	{
		key: "COMPETITION",
		code: "AGB",
		name: "Competition",
		description: "Information concerning an entity's competition.",
	},
	{
		key: "CONSTRUCTION_PROCESS_DETAILS",
		code: "AGC",
		name: "Construction process details",
		description: "Details about the construction process.",
	},
	{
		key: "CONSTRUCTION_SPECIALTY",
		code: "AGD",
		name: "Construction specialty",
		description:
			"Information concerning the line of business of a construction entity.",
	},
	{
		key: "CONTRACT_INFORMATION",
		code: "AGE",
		name: "Contract information",
		description: "Details about contract(s).",
	},
	{
		key: "CORPORATE_FILING",
		code: "AGF",
		name: "Corporate filing",
		description: "Details about a corporate filing.",
	},
	{
		key: "CUSTOMER_INFORMATION",
		code: "AGG",
		name: "Customer information",
		description: "Description of customers.",
	},
	{
		key: "COPYRIGHT_NOTICE",
		code: "AGH",
		name: "Copyright notice",
		description: "Information concerning the copyright notice.",
	},
	{
		key: "CONTINGENT_DEBT",
		code: "AGI",
		name: "Contingent debt",
		description: "Details about the contingent debt.",
	},
	{
		key: "CONVICTION_DETAILS",
		code: "AGJ",
		name: "Conviction details",
		description:
			"Details about the law or penal codes that resulted in conviction.",
	},
	{
		key: "EQUIPMENT",
		code: "AGK",
		name: "Equipment",
		description: "Description of equipment.",
	},
	{
		key: "WORKFORCE_DESCRIPTION",
		code: "AGL",
		name: "Workforce description",
		description: "Comments about the workforce.",
	},
	{
		key: "EXEMPTION",
		code: "AGM",
		name: "Exemption",
		description: "Description about exemptions.",
	},
	{
		key: "FUTURE_PLANS",
		code: "AGN",
		name: "Future plans",
		description: "Information on future plans.",
	},
	{
		key: "INTERVIEWEE_CONVERSATION_INFORMATION",
		code: "AGO",
		name: "Interviewee conversation information",
		description: "Information concerning the interviewee conversation.",
	},
	{
		key: "INTANGIBLE_ASSET",
		code: "AGP",
		name: "Intangible asset",
		description: "Description of intangible asset(s).",
	},
	{
		key: "INVENTORY",
		code: "AGQ",
		name: "Inventory",
		description: "Description of the inventory.",
	},
	{
		key: "INVESTMENT",
		code: "AGR",
		name: "Investment",
		description: "Description of the investments.",
	},
	{
		key: "INTERCOMPANY_RELATIONS_INFORMATION",
		code: "AGS",
		name: "Intercompany relations information",
		description: "Description of the intercompany relations.",
	},
	{
		key: "JOINT_VENTURE",
		code: "AGT",
		name: "Joint venture",
		description: "Description of the joint venture.",
	},
	{
		key: "LOAN",
		code: "AGU",
		name: "Loan",
		description: "Description of a loan.",
	},
	{
		key: "LONG_TERM_DEBT",
		code: "AGV",
		name: "Long term debt",
		description: "Description of the long term debt.",
	},
	{
		key: "LOCATION",
		code: "AGW",
		name: "Location",
		description: "Description of a location.",
	},
	{
		key: "CURRENT_LEGAL_STRUCTURE",
		code: "AGX",
		name: "Current legal structure",
		description: "Details on the current legal structure.",
	},
	{
		key: "MARITAL_CONTRACT",
		code: "AGY",
		name: "Marital contract",
		description: "Details on a marital contract.",
	},
	{
		key: "MARKETING_ACTIVITIES",
		code: "AGZ",
		name: "Marketing activities",
		description: "Information concerning marketing activities.",
	},
	{
		key: "MERGER",
		code: "AHA",
		name: "Merger",
		description: "Description of a merger.",
	},
	{
		key: "MARKETABLE_SECURITIES",
		code: "AHB",
		name: "Marketable securities",
		description: "Description of the marketable securities.",
	},
	{
		key: "BUSINESS_DEBT",
		code: "AHC",
		name: "Business debt",
		description: "Description of the business debt(s).",
	},
	{
		key: "ORIGINAL_LEGAL_STRUCTURE",
		code: "AHD",
		name: "Original legal structure",
		description: "Information concerning the original legal structure.",
	},
	{
		key: "EMPLOYEE_SHARING_ARRANGEMENTS",
		code: "AHE",
		name: "Employee sharing arrangements",
		description:
			"Information describing how a company uses employees from another company.",
	},
	{
		key: "ORGANIZATION_DETAILS",
		code: "AHF",
		name: "Organization details",
		description: "Description about the organization of a company.",
	},
	{
		key: "PUBLIC_RECORD_DETAILS",
		code: "AHG",
		name: "Public record details",
		description: "Information concerning public records.",
	},
	{
		key: "PRICE_RANGE",
		code: "AHH",
		name: "Price range",
		description:
			"Information concerning the price range of products made or sold.",
	},
	{
		key: "QUALIFICATIONS",
		code: "AHI",
		name: "Qualifications",
		description:
			"Information on the accomplishments fitting a party for a position.",
	},
	{
		key: "REGISTERED_ACTIVITY",
		code: "AHJ",
		name: "Registered activity",
		description: "Information concerning the registered activity.",
	},
	{
		key: "CRIMINAL_SENTENCE",
		code: "AHK",
		name: "Criminal sentence",
		description:
			"Description of the sentence imposed in a criminal proceeding.",
	},
	{
		key: "SALES_METHOD",
		code: "AHL",
		name: "Sales method",
		description: "Description of the selling means.",
	},
	{
		key: "EDUCATIONAL_INSTITUTION_INFORMATION",
		code: "AHM",
		name: "Educational institution information",
		description: "Free form description relating to the school(s) attended.",
	},
	{
		key: "STATUS_DETAILS",
		code: "AHN",
		name: "Status details",
		description: "Describes the status details.",
	},
	{
		key: "SALES",
		code: "AHO",
		name: "Sales",
		description: "Description of the sales.",
	},
	{
		key: "SPOUSE_INFORMATION",
		code: "AHP",
		name: "Spouse information",
		description: "Information about the spouse.",
	},
	{
		key: "EDUCATIONAL_DEGREE_INFORMATION",
		code: "AHQ",
		name: "Educational degree information",
		description: "Details about the educational degree received from a school.",
	},
	{
		key: "SHAREHOLDING_INFORMATION",
		code: "AHR",
		name: "Shareholding information",
		description: "General description of shareholding.",
	},
	{
		key: "SALES_TERRITORY",
		code: "AHS",
		name: "Sales territory",
		description: "Information on the sales territory.",
	},
	{
		key: "ACCOUNTANTS_COMMENTS",
		code: "AHT",
		name: "Accountant's comments",
		description:
			"Comments made by an accountant regarding a financial statement.",
	},
	{
		key: "EXEMPTION_LAW_LOCATION",
		code: "AHU",
		name: "Exemption law location",
		description:
			"Description of the exemption provided to a location by a law.",
	},
	{
		key: "SHARE_CLASSIFICATIONS",
		code: "AHV",
		name: "Share classifications",
		description: "Information about the classes or categories of shares.",
	},
	{
		key: "FORECAST",
		code: "AHW",
		name: "Forecast",
		description: "Description of a prediction.",
	},
	{
		key: "EVENT_LOCATION",
		code: "AHX",
		name: "Event location",
		description: "Description of the location of an event.",
	},
	{
		key: "FACILITY_OCCUPANCY",
		code: "AHY",
		name: "Facility occupancy",
		description: "Information related to occupancy of a facility.",
	},
	{
		key: "IMPORT_AND_EXPORT_DETAILS",
		code: "AHZ",
		name: "Import and export details",
		description:
			"Specific information provided about the importation and exportation of goods.",
	},
	{
		key: "ADDITIONAL_FACILITY_INFORMATION",
		code: "AIA",
		name: "Additional facility information",
		description: "Additional information about a facility.",
	},
	{
		key: "INVENTORY_VALUE",
		code: "AIB",
		name: "Inventory value",
		description: "Description of the value of inventory.",
	},
	{
		key: "EDUCATION",
		code: "AIC",
		name: "Education",
		description: "Description of the education of a person.",
	},
	{
		key: "EVENT",
		code: "AID",
		name: "Event",
		description: "Description of a thing that happens or takes place.",
	},
	{
		key: "AGENT",
		code: "AIE",
		name: "Agent",
		description: "Information about agents the entity uses.",
	},
	{
		key: "DOMESTICALLY_AGREED_FINANCIAL_STATEMENT_DETAILS",
		code: "AIF",
		name: "Domestically agreed financial statement details",
		description: "Details of domestically agreed financial statement.",
	},
	{
		key: "OTHER_CURRENT_ASSET_DESCRIPTION",
		code: "AIG",
		name: "Other current asset description",
		description: "Description of other current asset.",
	},
	{
		key: "OTHER_CURRENT_LIABILITY_DESCRIPTION",
		code: "AIH",
		name: "Other current liability description",
		description: "Description of other current liability.",
	},
	{
		key: "FORMER_BUSINESS_ACTIVITY",
		code: "AII",
		name: "Former business activity",
		description: "Description of the former line of business.",
	},
	{
		key: "TRADE_NAME_USE",
		code: "AIJ",
		name: "Trade name use",
		description: "Description of how a trading name is used.",
	},
	{
		key: "SIGNING_AUTHORITY",
		code: "AIK",
		name: "Signing authority",
		description: "Description of the authorized signatory.",
	},
	{
		key: "GUARANTEE",
		code: "AIL",
		name: "Guarantee",
		description: "[4376] Description of guarantee.",
	},
	{
		key: "HOLDING_COMPANY_OPERATION",
		code: "AIM",
		name: "Holding company operation",
		description: "Description of the operation of a holding company.",
	},
	{
		key: "CONSIGNMENT_ROUTING",
		code: "AIN",
		name: "Consignment routing",
		description: "Information on routing of the consignment.",
	},
	{
		key: "LETTER_OF_PROTEST",
		code: "AIO",
		name: "Letter of protest",
		description: "A letter citing any condition in dispute.",
	},
	{
		key: "QUESTION",
		code: "AIP",
		name: "Question",
		description: "A free text question.",
	},
	{
		key: "PARTY_INFORMATION",
		code: "AIQ",
		name: "Party information",
		description: "Free text information related to a party.",
	},
	{
		key: "AREA_BOUNDARIES_DESCRIPTION",
		code: "AIR",
		name: "Area boundaries description",
		description: "Description of the boundaries of a geographical area.",
	},
	{
		key: "ADVERTISEMENT_INFORMATION",
		code: "AIS",
		name: "Advertisement information",
		description: "The free text contains advertisement information.",
	},
	{
		key: "FINANCIAL_STATEMENT_DETAILS",
		code: "AIT",
		name: "Financial statement details",
		description: "Details regarding the financial statement in free text.",
	},
	{
		key: "ACCESS_INSTRUCTIONS",
		code: "AIU",
		name: "Access instructions",
		description: "Description of how to access an entity.",
	},
	{
		key: "LIQUIDITY",
		code: "AIV",
		name: "Liquidity",
		description: "Description of an entity's liquidity.",
	},
	{
		key: "CREDIT_LINE",
		code: "AIW",
		name: "Credit line",
		description: "Description of the line of credit available to an entity.",
	},
	{
		key: "WARRANTY_TERMS",
		code: "AIX",
		name: "Warranty terms",
		description:
			"Text describing the terms of warranty which apply to a product or service.",
	},
	{
		key: "DIVISION_DESCRIPTION",
		code: "AIY",
		name: "Division description",
		description: "Plain language description of a division of an entity.",
	},
	{
		key: "REPORTING_INSTRUCTION",
		code: "AIZ",
		name: "Reporting instruction",
		description: "Instruction on how to report.",
	},
	{
		key: "EXAMINATION_RESULT",
		code: "AJA",
		name: "Examination result",
		description: "The result of an examination.",
	},
	{
		key: "LABORATORY_RESULT",
		code: "AJB",
		name: "Laboratory result",
		description: "The result of a laboratory investigation.",
	},
	{
		key: "ALLOWANCECHARGE_INFORMATION",
		code: "ALC",
		name: "Allowance/charge information",
		description: "Information referring to allowance/charge.",
	},
	{
		key: "X_RAY_RESULT",
		code: "ALD",
		name: "X-ray result",
		description: "The result of an X-ray examination.",
	},
	{
		key: "PATHOLOGY_RESULT",
		code: "ALE",
		name: "Pathology result",
		description: "The result of a pathology investigation.",
	},
	{
		key: "INTERVENTION_DESCRIPTION",
		code: "ALF",
		name: "Intervention description",
		description: "Details of an intervention.",
	},
	{
		key: "SUMMARY_OF_ADMITTANCE",
		code: "ALG",
		name: "Summary of admittance",
		description: "Summary description of admittance.",
	},
	{
		key: "MEDICAL_TREATMENT_COURSE_DETAIL",
		code: "ALH",
		name: "Medical treatment course detail",
		description: "Details of a course of medical treatment.",
	},
	{
		key: "PROGNOSIS",
		code: "ALI",
		name: "Prognosis",
		description: "Details of a prognosis.",
	},
	{
		key: "INSTRUCTION_TO_PATIENT",
		code: "ALJ",
		name: "Instruction to patient",
		description: "Instruction given to a patient.",
	},
	{
		key: "INSTRUCTION_TO_PHYSICIAN",
		code: "ALK",
		name: "Instruction to physician",
		description: "Instruction given to a physician.",
	},
	{
		key: "ALL_DOCUMENTS",
		code: "ALL",
		name: "All documents",
		description: "The note implies to all documents.",
	},
	{
		key: "MEDICINE_TREATMENT",
		code: "ALM",
		name: "Medicine treatment",
		description: "Details of medicine treatment.",
	},
	{
		key: "MEDICINE_DOSAGE_AND_ADMINISTRATION",
		code: "ALN",
		name: "Medicine dosage and administration",
		description: "Details of medicine dosage and method of administration.",
	},
	{
		key: "AVAILABILITY_OF_PATIENT",
		code: "ALO",
		name: "Availability of patient",
		description: "Details of when and/or where the patient is available.",
	},
	{
		key: "REASON_FOR_SERVICE_REQUEST",
		code: "ALP",
		name: "Reason for service request",
		description: "Details of the reason for a requested service.",
	},
	{
		key: "PURPOSE_OF_SERVICE",
		code: "ALQ",
		name: "Purpose of service",
		description: "Details of the purpose of a service.",
	},
	{
		key: "ARRIVAL_CONDITIONS",
		code: "ARR",
		name: "Arrival conditions",
		description: "Conditions under which arrival takes place.",
	},
	{
		key: "SERVICE_REQUESTERS_COMMENT",
		code: "ARS",
		name: "Service requester's comment",
		description: "Comment by the requester of a service.",
	},
	{
		key: "AUTHENTICATION",
		code: "AUT",
		name: "Authentication",
		description:
			"(4130) (4136) (4426) Name, code, password etc. given for authentication purposes.",
	},
	{
		key: "REQUESTED_LOCATION_DESCRIPTION",
		code: "AUU",
		name: "Requested location description",
		description: "The description of the location requested.",
	},
	{
		key: "MEDICINE_ADMINISTRATION_CONDITION",
		code: "AUV",
		name: "Medicine administration condition",
		description:
			"The event or condition that initiates the administration of a single dose of medicine or a period of treatment.",
	},
	{
		key: "PATIENT_INFORMATION",
		code: "AUW",
		name: "Patient information",
		description: "Information concerning a patient.",
	},
	{
		key: "PRECAUTIONARY_MEASURE",
		code: "AUX",
		name: "Precautionary measure",
		description: "Action to be taken to avert possible harmful affects.",
	},
	{
		key: "SERVICE_CHARACTERISTIC",
		code: "AUY",
		name: "Service characteristic",
		description:
			"Free text description is related to a service characteristic.",
	},
	{
		key: "PLANNED_EVENT_COMMENT",
		code: "AUZ",
		name: "Planned event comment",
		description: "Comment about an event that is planned.",
	},
	{
		key: "EXPECTED_DELAY_COMMENT",
		code: "AVA",
		name: "Expected delay comment",
		description: "Comment about the expected delay.",
	},
	{
		key: "TRANSPORT_REQUIREMENTS_COMMENT",
		code: "AVB",
		name: "Transport requirements comment",
		description: "Comment about the requirements for transport.",
	},
	{
		key: "TEMPORARY_APPROVAL_CONDITION",
		code: "AVC",
		name: "Temporary approval condition",
		description: "The condition under which the approval is considered.",
	},
	{
		key: "CUSTOMS_VALUATION_INFORMATION",
		code: "AVD",
		name: "Customs Valuation Information",
		description:
			"Information provided in this category will be used by the trader to make certain declarations in relation to Customs Valuation.",
	},
	{
		key: "VALUE_ADDED_TAX_VAT_MARGIN_SCHEME",
		code: "AVE",
		name: "Value Added Tax (VAT) margin scheme",
		description: "Description of the VAT margin scheme applied.",
	},
	{
		key: "MARITIME_DECLARATION_OF_HEALTH",
		code: "AVF",
		name: "Maritime Declaration of Health",
		description: "Information about Maritime Declaration of Health.",
	},
	{
		key: "PASSENGER_BAGGAGE_INFORMATION",
		code: "BAG",
		name: "Passenger baggage information",
		description:
			"Information related to baggage tendered by a passenger, such as odd size indication, tag.",
	},
	{
		key: "MARITIME_DECLARATION_OF_HEALTH",
		code: "BAH",
		name: "Maritime Declaration of Health",
		description: "Information about Maritime Declaration of Health.",
	},
	{
		key: "ADDITIONAL_PRODUCT_INFORMATION_ADDRESS",
		code: "BAI",
		name: "Additional product information address",
		description:
			"Address at which additional information on the product can be found.",
	},
	{
		key: "INFORMATION_TO_BE_PRINTED_ON_DESPATCH_ADVICE",
		code: "BAJ",
		name: "Information to be printed on despatch advice",
		description:
			"Specification of free text information which is to be printed on a despatch advice.",
	},
	{
		key: "MISSING_GOODS_REMARKS",
		code: "BAK",
		name: "Missing goods remarks",
		description: "Remarks concerning missing goods.",
	},
	{
		key: "NON_ACCEPTANCE_INFORMATION",
		code: "BAL",
		name: "Non-acceptance information",
		description:
			"Information related to the non-acceptance of an order, goods or a consignment.",
	},
	{
		key: "RETURNS_INFORMATION",
		code: "BAM",
		name: "Returns information",
		description: "Information related to the return of items.",
	},
	{
		key: "SUB_LINE_ITEM_INFORMATION",
		code: "BAN",
		name: "Sub-line item information",
		description: "Note contains information related to sub-line item data.",
	},
	{
		key: "TEST_INFORMATION",
		code: "BAO",
		name: "Test information",
		description: "Information related to a test.",
	},
	{
		key: "EXTERNAL_LINK",
		code: "BAP",
		name: "External link",
		description: "The external link to a digital document (e.g.: URL).",
	},
	{
		key: "VAT_EXEMPTION_REASON",
		code: "BAQ",
		name: "VAT exemption reason",
		description: "Reason for Value Added Tax (VAT) exemption.",
	},
	{
		key: "PROCESSING_INSTRUCTIONS",
		code: "BAR",
		name: "Processing Instructions",
		description: "Instructions for processing.",
	},
	{
		key: "RELAY_INSTRUCTIONS",
		code: "BAS",
		name: "Relay Instructions",
		description: "Instructions for relaying.",
	},
	{
		key: "SIMA_APPLICABLE",
		code: "BAT",
		name: "SIMA applicable",
		description: "Identifies that Special Import Measures Act applies",
	},
	{
		key: "APPEALS_PROGRAM_CODE",
		code: "BAU",
		name: "Appeals program code",
		description: "Identifies information related to an appeals program.",
	},
	{
		key: "SIMA_SUBJECT",
		code: "BAV",
		name: "SIMA subject",
		description:
			"Identifies if the goods are subject to a Special Import Measures Act measure.",
	},
	{
		key: "SURTAX_APPLICABLE",
		code: "BAW",
		name: "Surtax applicable",
		description: "Identifies that surtax applies",
	},
	{
		key: "SIMA_SECURITY_BOND",
		code: "BAX",
		name: "SIMA security bond",
		description:
			"Identifies that there is a security bond in hand that could theoretically be used to cover Special Import Measures Act charges",
	},
	{
		key: "SURTAX_SUBJECT",
		code: "BAY",
		name: "Surtax subject",
		description: "Identifies if the goods are subject to a surtax measure",
	},
	{
		key: "SAFEGUARD_APPLICABLE",
		code: "BAZ",
		name: "Safeguard applicable",
		description: "Identifies safeguard applies",
	},
	{
		key: "SAFEGUARD_APPLICABLE",
		code: "BBA",
		name: "Safeguard applicable",
		description: "Identifies safeguard applies",
	},
	{
		key: "SAFEGUARD_SUBJECT",
		code: "BBB",
		name: "Safeguard subject",
		description: "Identifies if the goods are subject to a safeguard measure",
	},
	{
		key: "TRANSPORT_CONTRACT_DOCUMENT_CLAUSE",
		code: "BLC",
		name: "Transport contract document clause",
		description:
			"[4180] Clause on a transport document regarding the cargo being consigned. Synonym: Bill of Lading clause.",
	},
	{
		key: "INSTRUCTION_TO_PREPARE_THE_PATIENT",
		code: "BLD",
		name: "Instruction to prepare the patient",
		description: "Instruction with the purpose of preparing the patient.",
	},
	{
		key: "MEDICINE_TREATMENT_COMMENT",
		code: "BLE",
		name: "Medicine treatment comment",
		description: "Comment about treatment with medicine.",
	},
	{
		key: "EXAMINATION_RESULT_COMMENT",
		code: "BLF",
		name: "Examination result comment",
		description: "Comment about the result of an examination.",
	},
	{
		key: "SERVICE_REQUEST_COMMENT",
		code: "BLG",
		name: "Service request comment",
		description: "Comment about the requested service.",
	},
	{
		key: "PRESCRIPTION_REASON",
		code: "BLH",
		name: "Prescription reason",
		description: "Details of the reason for a prescription.",
	},
	{
		key: "PRESCRIPTION_COMMENT",
		code: "BLI",
		name: "Prescription comment",
		description: "Comment concerning a specified prescription.",
	},
	{
		key: "CLINICAL_INVESTIGATION_COMMENT",
		code: "BLJ",
		name: "Clinical investigation comment",
		description: "Comment concerning a clinical investigation.",
	},
	{
		key: "MEDICINAL_SPECIFICATION_COMMENT",
		code: "BLK",
		name: "Medicinal specification comment",
		description: "Comment concerning the specification of a medicinal product.",
	},
	{
		key: "ECONOMIC_CONTRIBUTION_COMMENT",
		code: "BLL",
		name: "Economic contribution comment",
		description: "Comment concerning economic contribution.",
	},
	{
		key: "STATUS_OF_A_PLAN",
		code: "BLM",
		name: "Status of a plan",
		description: "Comment about the status of a plan.",
	},
	{
		key: "RANDOM_SAMPLE_TEST_INFORMATION",
		code: "BLN",
		name: "Random sample test information",
		description: "Information regarding a random sample test.",
	},
	{
		key: "PERIOD_OF_TIME",
		code: "BLO",
		name: "Period of time",
		description: "Text subject is a period of time.",
	},
	{
		key: "LEGISLATION",
		code: "BLP",
		name: "Legislation",
		description: "Information about legislation.",
	},
	{
		key: "SECURITY_MEASURES_REQUESTED",
		code: "BLQ",
		name: "Security measures requested",
		description:
			"Text describing security measures that are requested to be executed (e.g. access controls, supervision of ship's stores).",
	},
	{
		key: "TRANSPORT_CONTRACT_DOCUMENT_REMARK",
		code: "BLR",
		name: "Transport contract document remark",
		description:
			"[4244] Remarks concerning the complete consignment to be printed on the transport document. Synonym: Bill of Lading remark.",
	},
	{
		key: "PREVIOUS_PORT_OF_CALL_SECURITY_INFORMATION",
		code: "BLS",
		name: "Previous port of call security information",
		description:
			"Text describing the security information as applicable at the port facility in the previous port where a ship/port interface was conducted.",
	},
	{
		key: "SECURITY_INFORMATION",
		code: "BLT",
		name: "Security information",
		description:
			"Text describing security related information (e.g security measures currently in force on a vessel).",
	},
	{
		key: "WASTE_INFORMATION",
		code: "BLU",
		name: "Waste information",
		description: "Text describing waste related information.",
	},
	{
		key: "B2_C_MARKETING_INFORMATION_SHORT_DESCRIPTION",
		code: "BLV",
		name: "B2C marketing information, short description",
		description: "Consumer marketing information, short description.",
	},
	{
		key: "B2_B_MARKETING_INFORMATION_LONG_DESCRIPTION",
		code: "BLW",
		name: "B2B marketing information, long description",
		description: "Trading partner marketing information, long description.",
	},
	{
		key: "B2_C_MARKETING_INFORMATION_LONG_DESCRIPTION",
		code: "BLX",
		name: "B2C marketing information, long description",
		description: "Consumer marketing information, long description.",
	},
	{
		key: "PRODUCT_INGREDIENTS",
		code: "BLY",
		name: "Product ingredients",
		description: "Information on the ingredient make up of the product.",
	},
	{
		key: "LOCATION_SHORT_NAME",
		code: "BLZ",
		name: "Location short name",
		description:
			"Short name of a location e.g. for display or printing purposes.",
	},
	{
		key: "PACKAGING_MATERIAL_INFORMATION",
		code: "BMA",
		name: "Packaging material information",
		description:
			"The text contains a description of the material used for packaging.",
	},
	{
		key: "FILLER_MATERIAL_INFORMATION",
		code: "BMB",
		name: "Filler material information",
		description: "Text contains information on the material used for stuffing.",
	},
	{
		key: "SHIP_TO_SHIP_ACTIVITY_INFORMATION",
		code: "BMC",
		name: "Ship-to-ship activity information",
		description: "Text contains information on ship-to-ship activities.",
	},
	{
		key: "PACKAGE_MATERIAL_DESCRIPTION",
		code: "BMD",
		name: "Package material description",
		description:
			"A description of the type of material for packaging beyond the level covered by standards such as UN Recommendation 21.",
	},
	{
		key: "CONSUMER_LEVEL_PACKAGE_MARKING",
		code: "BME",
		name: "Consumer level package marking",
		description:
			"Textual representation of the markings on a consumer level package.",
	},
	{
		key: "SIMA_MEASURE_IN_FORCE",
		code: "BMF",
		name: "SIMA measure in force",
		description:
			"Identifies the specific Special Import Measures Act measure related to the goods",
	},
	{
		key: "PRE_CARM",
		code: "BMG",
		name: "Pre-CARM",
		description:
			"Identifiication of how the transmission should be processed regarding submissions transmitted prior to implementation of Canada Border Services Agency’s Assessment and Revenue Management (CARM) project",
	},
	{
		key: "SIMA_MEASURE_TYPE",
		code: "BMH",
		name: "SIMA measure type",
		description:
			"Identification of the type of Special Import Measures Act measure",
	},
	{
		key: "CUSTOMS_CLEARANCE_INSTRUCTIONS",
		code: "CCI",
		name: "Customs clearance instructions",
		description:
			"Any coded or clear instruction agreed by customer and carrier regarding the declaration of the goods.",
	},
	{
		key: "SUB_TYPE_CODE",
		code: "CCJ",
		name: "Sub Type Code",
		description: "Code which identifies a secondary form type",
	},
	{
		key: "SIMA_INFORMATION",
		code: "CCK",
		name: "SIMA information",
		description:
			"Additional information detailing Special Import Measures Act information",
	},
	{
		key: "TIME_LIMIT_END",
		code: "CCL",
		name: "Time limit end",
		description: "The date the goods exited the economy or warehouse",
	},
	{
		key: "TIME_LIMIT_START",
		code: "CCM",
		name: "Time limit start",
		description: "The date the goods entered the economy or warehouse",
	},
	{
		key: "WAREHOUSE_TIME_LIMIT",
		code: "CCN",
		name: "Warehouse time limit",
		description: "The amount of time goods may remain in the warehouse",
	},
	{
		key: "VALUE_FOR_DUTY_INFORMATION",
		code: "CCO",
		name: "Value for duty information",
		description:
			"Additional information detailing the basis on which the value for duty was determined",
	},
	{
		key: "CUSTOMS_CLEARANCE_INSTRUCTIONS_EXPORT",
		code: "CEX",
		name: "Customs clearance instructions export",
		description:
			"Any coded or clear instruction agreed by customer and carrier regarding the export declaration of the goods.",
	},
	{
		key: "CHANGE_INFORMATION",
		code: "CHG",
		name: "Change information",
		description: "Note contains change information.",
	},
	{
		key: "CUSTOMS_CLEARANCE_INSTRUCTION_IMPORT",
		code: "CIP",
		name: "Customs clearance instruction import",
		description:
			"Any coded or clear instruction agreed by customer and carrier regarding the import declaration of the goods.",
	},
	{
		key: "CLEARANCE_PLACE_REQUESTED",
		code: "CLP",
		name: "Clearance place requested",
		description:
			"Name of the place where Customs clearance is asked to be executed as requested by the consignee/consignor.",
	},
	{
		key: "LOADING_REMARKS",
		code: "CLR",
		name: "Loading remarks",
		description: "Instructions concerning the loading of the container.",
	},
	{
		key: "ORDER_INFORMATION",
		code: "COI",
		name: "Order information",
		description: "Additional information related to an order.",
	},
	{
		key: "CUSTOMER_REMARKS",
		code: "CUR",
		name: "Customer remarks",
		description: "Remarks from or for a supplier of goods or services.",
	},
	{
		key: "CUSTOMS_DECLARATION_INFORMATION",
		code: "CUS",
		name: "Customs declaration information",
		description: "(4034) Note contains customs declaration information.",
	},
	{
		key: "DAMAGE_REMARKS",
		code: "DAR",
		name: "Damage remarks",
		description: "Remarks concerning damage on the cargo.",
	},
	{
		key: "DOCUMENT_ISSUER_DECLARATION",
		code: "DCL",
		name: "Document issuer declaration",
		description:
			"[4020] Text of a declaration made by the issuer of a document.",
	},
	{
		key: "DELIVERY_INFORMATION",
		code: "DEL",
		name: "Delivery information",
		description: "Information about delivery.",
	},
	{
		key: "DELIVERY_INSTRUCTIONS",
		code: "DIN",
		name: "Delivery instructions",
		description: "[4492] Instructions regarding the delivery of the cargo.",
	},
	{
		key: "DOCUMENTATION_INSTRUCTIONS",
		code: "DOC",
		name: "Documentation instructions",
		description: "Instructions pertaining to the documentation.",
	},
	{
		key: "DUTY_DECLARATION",
		code: "DUT",
		name: "Duty declaration",
		description:
			"The text contains a statement constituting a duty declaration.",
	},
	{
		key: "EFFECTIVE_USED_ROUTING",
		code: "EUR",
		name: "Effective used routing",
		description:
			"Physical route effectively used for the movement of the means of transport.",
	},
	{
		key: "FIRST_BLOCK_TO_BE_PRINTED_ON_THE_TRANSPORT_CONTRACT",
		code: "FBC",
		name: "First block to be printed on the transport contract",
		description:
			"The first block of text to be printed on the transport contract.",
	},
	{
		key: "GOVERNMENT_BILL_OF_LADING_INFORMATION",
		code: "GBL",
		name: "Government bill of lading information",
		description:
			"Free text information on a transport document to indicate payment information by Government Bill of Lading.",
	},
	{
		key: "ENTIRE_TRANSACTION_SET",
		code: "GEN",
		name: "Entire transaction set",
		description:
			"Note is general in nature, applies to entire transaction segment.",
	},
	{
		key: "FURTHER_INFORMATION_CONCERNING_GGVS_PAR_7",
		code: "GS7",
		name: "Further information concerning GGVS par. 7",
		description:
			"Special permission for road transport of certain goods in the German dangerous goods regulation for road transport.",
	},
	{
		key: "CONSIGNMENT_HANDLING_INSTRUCTION",
		code: "HAN",
		name: "Consignment handling instruction",
		description:
			"[4078] Free form description of a set of handling instructions. For example how specified goods, packages or transport equipment (container) should be handled.",
	},
	{
		key: "HAZARD_INFORMATION",
		code: "HAZ",
		name: "Hazard information",
		description: "Information pertaining to a hazard.",
	},
	{
		key: "CONSIGNMENT_INFORMATION_FOR_CONSIGNEE",
		code: "ICN",
		name: "Consignment information for consignee",
		description:
			"[4070] Any remarks given for the information of the consignee.",
	},
	{
		key: "INSURANCE_INSTRUCTIONS",
		code: "IIN",
		name: "Insurance instructions",
		description: "(4112) Instructions regarding the cargo insurance.",
	},
	{
		key: "INVOICE_MAILING_INSTRUCTIONS",
		code: "IMI",
		name: "Invoice mailing instructions",
		description:
			"Instructions as to which freight and charges components have to be mailed to whom.",
	},
	{
		key: "COMMERCIAL_INVOICE_ITEM_DESCRIPTION",
		code: "IND",
		name: "Commercial invoice item description",
		description: "Free text describing goods on a commercial invoice line.",
	},
	{
		key: "INSURANCE_INFORMATION",
		code: "INS",
		name: "Insurance information",
		description: "Specific note contains insurance information.",
	},
	{
		key: "INVOICE_INSTRUCTION",
		code: "INV",
		name: "Invoice instruction",
		description: "Note contains invoice instructions.",
	},
	{
		key: "INFORMATION_FOR_RAILWAY_PURPOSE",
		code: "IRP",
		name: "Information for railway purpose",
		description:
			"Data entered by railway stations when required, e.g. specified trains, additional sheets for freight calculations, special measures, etc.",
	},
	{
		key: "INLAND_TRANSPORT_DETAILS",
		code: "ITR",
		name: "Inland transport details",
		description:
			"Information concerning the pre-carriage to the port of discharge if by other means than a vessel.",
	},
	{
		key: "TESTING_INSTRUCTIONS",
		code: "ITS",
		name: "Testing instructions",
		description:
			"Instructions regarding the testing that is required to be carried out on the items in the transaction.",
	},
	{
		key: "LOCATION_ALIAS",
		code: "LAN",
		name: "Location Alias",
		description: "Alternative name for a location.",
	},
	{
		key: "LINE_ITEM",
		code: "LIN",
		name: "Line item",
		description: "Note contains line item information.",
	},
	{
		key: "LOADING_INSTRUCTION",
		code: "LOI",
		name: "Loading instruction",
		description:
			"[4080] Instructions where specified packages or containers are to be loaded on a means of transport.",
	},
	{
		key: "MISCELLANEOUS_CHARGE_ORDER",
		code: "MCO",
		name: "Miscellaneous charge order",
		description:
			"Free text accounting information on an IATA Air Waybill to indicate payment information by Miscellaneous charge order.",
	},
	{
		key: "MARITIME_DECLARATION_OF_HEALTH",
		code: "MDH",
		name: "Maritime Declaration of Health",
		description: "Information about Maritime Declaration of Health.",
	},
	{
		key: "ADDITIONAL_MARKSNUMBERS_INFORMATION",
		code: "MKS",
		name: "Additional marks/numbers information",
		description: "Additional information regarding the marks and numbers.",
	},
	{
		key: "ORDER_INSTRUCTION",
		code: "ORI",
		name: "Order instruction",
		description: "Free text contains order instructions.",
	},
	{
		key: "OTHER_SERVICE_INFORMATION",
		code: "OSI",
		name: "Other service information",
		description:
			"General information created by the sender of general or specific value.",
	},
	{
		key: "PACKINGMARKING_INFORMATION",
		code: "PAC",
		name: "Packing/marking information",
		description: "Information regarding the packaging and/or marking of goods.",
	},
	{
		key: "PAYMENT_INSTRUCTIONS_INFORMATION",
		code: "PAI",
		name: "Payment instructions information",
		description:
			"The free text contains payment instructions information relevant to the message.",
	},
	{
		key: "PAYABLES_INFORMATION",
		code: "PAY",
		name: "Payables information",
		description: "Note contains payables information.",
	},
	{
		key: "PACKAGING_INFORMATION",
		code: "PKG",
		name: "Packaging information",
		description: "Note contains packaging information.",
	},
	{
		key: "PACKAGING_TERMS_INFORMATION",
		code: "PKT",
		name: "Packaging terms information",
		description: "The text contains packaging terms information.",
	},
	{
		key: "PAYMENT_DETAILREMITTANCE_INFORMATION",
		code: "PMD",
		name: "Payment detail/remittance information",
		description: "The free text contains payment details.",
	},
	{
		key: "PAYMENT_INFORMATION",
		code: "PMT",
		name: "Payment information",
		description: "(4438) Note contains payments information.",
	},
	{
		key: "PRODUCT_INFORMATION",
		code: "PRD",
		name: "Product information",
		description: "The text contains product information.",
	},
	{
		key: "PRICE_CALCULATION_FORMULA",
		code: "PRF",
		name: "Price calculation formula",
		description:
			"Additional information regarding the price formula used for calculating the item price.",
	},
	{
		key: "PRIORITY_INFORMATION",
		code: "PRI",
		name: "Priority information",
		description: "(4218) Note contains priority information.",
	},
	{
		key: "PURCHASING_INFORMATION",
		code: "PUR",
		name: "Purchasing information",
		description: "Note contains purchasing information.",
	},
	{
		key: "QUARANTINE_INSTRUCTIONS",
		code: "QIN",
		name: "Quarantine instructions",
		description:
			"Instructions regarding quarantine, i.e. the period during which an arriving vessel, including its equipment, cargo, crew or passengers, suspected to carry or carrying a contagious disease is detained in strict isolation to prevent the spread of such a disease.",
	},
	{
		key: "QUALITY_DEMANDSREQUIREMENTS",
		code: "QQD",
		name: "Quality demands/requirements",
		description:
			"Specification of the quality/performance expectations or standards to which the items must conform.",
	},
	{
		key: "QUOTATION_INSTRUCTIONINFORMATION",
		code: "QUT",
		name: "Quotation instruction/information",
		description: "Note contains quotation information.",
	},
	{
		key: "RISK_AND_HANDLING_INFORMATION",
		code: "RAH",
		name: "Risk and handling information",
		description:
			"Information concerning risks induced by the goods and/or handling instruction.",
	},
	{
		key: "REGULATORY_INFORMATION",
		code: "REG",
		name: "Regulatory information",
		description: "The free text contains information for regulatory authority.",
	},
	{
		key: "RETURN_TO_ORIGIN_INFORMATION",
		code: "RET",
		name: "Return to origin information",
		description:
			"Free text information on an IATA Air Waybill to indicate consignment returned because of non delivery.",
	},
	{
		key: "RECEIVABLES",
		code: "REV",
		name: "Receivables",
		description: "The text contains receivables information.",
	},
	{
		key: "CONSIGNMENT_ROUTE",
		code: "RQR",
		name: "Consignment route",
		description:
			"[3050] Description of a route to be used for the transport of goods.",
	},
	{
		key: "SAFETY_INFORMATION",
		code: "SAF",
		name: "Safety information",
		description: "The text contains safety information.",
	},
	{
		key: "CONSIGNMENT_DOCUMENTARY_INSTRUCTION",
		code: "SIC",
		name: "Consignment documentary instruction",
		description:
			"[4284] Instructions given and declarations made by the sender to the carrier concerning Customs, insurance, and other formalities.",
	},
	{
		key: "SPECIAL_INSTRUCTIONS",
		code: "SIN",
		name: "Special instructions",
		description:
			"Special instructions like licence no, high value, handle with care, glass.",
	},
	{
		key: "SHIP_LINE_REQUESTED",
		code: "SLR",
		name: "Ship line requested",
		description:
			"Shipping line requested to be used for traffic between European continent and U.K. for Ireland.",
	},
	{
		key: "SPECIAL_PERMISSION_FOR_TRANSPORT_GENERALLY",
		code: "SPA",
		name: "Special permission for transport, generally",
		description:
			"Statement that a special permission has been obtained for the transport (and/or routing) in general, and reference to such permission.",
	},
	{
		key: "SPECIAL_PERMISSION_CONCERNING_THE_GOODS_TO_BE_TRANSPORTED",
		code: "SPG",
		name: "Special permission concerning the goods to be transported",
		description:
			"Statement that a special permission has been obtained for the transport (and/or routing) of the goods specified, and reference to such permission.",
	},
	{
		key: "SPECIAL_HANDLING",
		code: "SPH",
		name: "Special handling",
		description: "Note contains special handling information.",
	},
	{
		key: "SPECIAL_PERMISSION_CONCERNING_PACKAGE",
		code: "SPP",
		name: "Special permission concerning package",
		description:
			"Statement that a special permission has been obtained for the packaging, and reference to such permission.",
	},
	{
		key: "SPECIAL_PERMISSION_CONCERNING_TRANSPORT_MEANS",
		code: "SPT",
		name: "Special permission concerning transport means",
		description:
			"Statement that a special permission has been obtained for the use of the means transport, and reference to such permission.",
	},
	{
		key: "SUBSIDIARY_RISK_NUMBER_IATADGR",
		code: "SRN",
		name: "Subsidiary risk number (IATA/DGR)",
		description:
			"Number(s) of subsidiary risks, induced by the goods, according to the valid classification.",
	},
	{
		key: "SPECIAL_SERVICE_REQUEST",
		code: "SSR",
		name: "Special service request",
		description:
			"Request for a special service concerning the transport of the goods.",
	},
	{
		key: "SUPPLIER_REMARKS",
		code: "SUR",
		name: "Supplier remarks",
		description: "Remarks from or for a supplier of goods or services.",
	},
	{
		key: "CONSIGNMENT_TARIFF",
		code: "TCA",
		name: "Consignment tariff",
		description:
			"[5430] Free text specification of tariff applied to a consignment.",
	},
	{
		key: "CONSIGNMENT_TRANSPORT",
		code: "TDT",
		name: "Consignment transport",
		description:
			"[8012] Transport information for commercial purposes (generic term).",
	},
	{
		key: "TRANSPORTATION_INFORMATION",
		code: "TRA",
		name: "Transportation information",
		description: "General information regarding the transport of the cargo.",
	},
	{
		key: "REQUESTED_TARIFF",
		code: "TRR",
		name: "Requested tariff",
		description:
			"Stipulation of the tariffs to be applied showing, where applicable, special agreement numbers or references.",
	},
	{
		key: "TAX_DECLARATION",
		code: "TXD",
		name: "Tax declaration",
		description:
			"The text contains a statement constituting a tax declaration.",
	},
	{
		key: "WAREHOUSE_INSTRUCTIONINFORMATION",
		code: "WHI",
		name: "Warehouse instruction/information",
		description: "Note contains warehouse information.",
	},
	{
		key: "MUTUALLY_DEFINED",
		code: "ZZZ",
		name: "Mutually defined",
		description:
			"Note contains information mutually defined by trading partners.",
	},
] as const satisfies Untdid4451Definition[];
