import type { Codelist } from "@node-zugferd/core";
import { registerCodelist } from "@node-zugferd/data-types";

const text = [
	{
		value: "AAA",
		name: "Goods item description",
		key: "GOODS_ITEM_DESCRIPTION",
	},
	{ value: "AAB", name: "Payment term", key: "PAYMENT_TERM" },
	{
		value: "AAC",
		name: "Dangerous goods additional information",
		key: "DANGEROUS_GOODS_ADDITIONAL_INFORMATION",
	},
	{
		value: "AAD",
		name: "Dangerous goods technical name",
		key: "DANGEROUS_GOODS_TECHNICAL_NAME",
	},
	{
		value: "AAE",
		name: "Acknowledgement description",
		key: "ACKNOWLEDGEMENT_DESCRIPTION",
	},
	{
		value: "AAF",
		name: "Rate additional information",
		key: "RATE_ADDITIONAL_INFORMATION",
	},
	{ value: "AAG", name: "Party instructions", key: "PARTY_INSTRUCTIONS" },
	{ value: "AAI", name: "General information", key: "GENERAL_INFORMATION" },
	{
		value: "AAJ",
		name: "Additional conditions of sale/purchase",
		key: "ADDITIONAL_CONDITIONS_OF_SALE_PURCHASE",
	},
	{ value: "AAK", name: "Price conditions", key: "PRICE_CONDITIONS" },
	{
		value: "AAL",
		name: "Goods dimensions in characters",
		key: "GOODS_DIMENSIONS_IN_CHARACTERS",
	},
	{
		value: "AAM",
		name: "Equipment re-usage restrictions",
		key: "EQUIPMENT_RE_USAGE_RESTRICTIONS",
	},
	{ value: "AAN", name: "Handling restriction", key: "HANDLING_RESTRICTION" },
	{
		value: "AAO",
		name: "Error description (free text)",
		key: "ERROR_DESCRIPTION_FREE_TEXT",
	},
	{ value: "AAP", name: "Response (free text)", key: "RESPONSE_FREE_TEXT" },
	{
		value: "AAQ",
		name: "Package content's description",
		key: "PACKAGE_CONTENT_S_DESCRIPTION",
	},
	{ value: "AAR", name: "Terms of delivery", key: "TERMS_OF_DELIVERY" },
	{
		value: "AAS",
		name: "Bill of lading remarks",
		key: "BILL_OF_LADING_REMARKS",
	},
	{
		value: "AAT",
		name: "Mode of settlement information",
		key: "MODE_OF_SETTLEMENT_INFORMATION",
	},
	{
		value: "AAU",
		name: "Consignment invoice information",
		key: "CONSIGNMENT_INVOICE_INFORMATION",
	},
	{
		value: "AAV",
		name: "Clearance invoice information",
		key: "CLEARANCE_INVOICE_INFORMATION",
	},
	{
		value: "AAW",
		name: "Letter of credit information",
		key: "LETTER_OF_CREDIT_INFORMATION",
	},
	{ value: "AAX", name: "License information", key: "LICENSE_INFORMATION" },
	{
		value: "AAY",
		name: "Certification statements",
		key: "CERTIFICATION_STATEMENTS",
	},
	{
		value: "AAZ",
		name: "Additional export information",
		key: "ADDITIONAL_EXPORT_INFORMATION",
	},
	{ value: "ABA", name: "Tariff statements", key: "TARIFF_STATEMENTS" },
	{ value: "ABB", name: "Medical history", key: "MEDICAL_HISTORY" },
	{
		value: "ABC",
		name: "Conditions of sale or purchase",
		key: "CONDITIONS_OF_SALE_OR_PURCHASE",
	},
	{
		value: "ABD",
		name: "Contract document type",
		key: "CONTRACT_DOCUMENT_TYPE",
	},
	{
		value: "ABE",
		name: "Additional terms and/or conditions (documentary credit)",
		key: "ADDITIONAL_TERMS_AND_OR_CONDITIONS_DOCUMENTARY_CREDIT",
	},
	{
		value: "ABF",
		name: "Instructions or information about standby documentary",
		key: "INSTRUCTIONS_OR_INFORMATION_ABOUT_STANDBY_DOCUMENTARY",
	},
	{
		value: "ABG",
		name: "Instructions or information about partial shipment(s)",
		key: "INSTRUCTIONS_OR_INFORMATION_ABOUT_PARTIAL_SHIPMENT_S",
	},
	{
		value: "ABH",
		name: "Instructions or information about transhipment(s)",
		key: "INSTRUCTIONS_OR_INFORMATION_ABOUT_TRANSHIPMENT_S",
	},
	{
		value: "ABI",
		name: "Additional handling instructions documentary credit",
		key: "ADDITIONAL_HANDLING_INSTRUCTIONS_DOCUMENTARY_CREDIT",
	},
	{
		value: "ABJ",
		name: "Domestic routing information",
		key: "DOMESTIC_ROUTING_INFORMATION",
	},
	{
		value: "ABK",
		name: "Chargeable category of equipment",
		key: "CHARGEABLE_CATEGORY_OF_EQUIPMENT",
	},
	{
		value: "ABL",
		name: "Government information",
		key: "GOVERNMENT_INFORMATION",
	},
	{
		value: "ABM",
		name: "Onward routing information",
		key: "ONWARD_ROUTING_INFORMATION",
	},
	{
		value: "ABN",
		name: "Accounting information",
		key: "ACCOUNTING_INFORMATION",
	},
	{
		value: "ABO",
		name: "Discrepancy information",
		key: "DISCREPANCY_INFORMATION",
	},
	{
		value: "ABP",
		name: "Confirmation instructions",
		key: "CONFIRMATION_INSTRUCTIONS",
	},
	{ value: "ABQ", name: "Method of issuance", key: "METHOD_OF_ISSUANCE" },
	{
		value: "ABR",
		name: "Documents delivery instructions",
		key: "DOCUMENTS_DELIVERY_INSTRUCTIONS",
	},
	{ value: "ABS", name: "Additional conditions", key: "ADDITIONAL_CONDITIONS" },
	{
		value: "ABT",
		name: "Information/instructions about additional amounts covered",
		key: "INFORMATION_INSTRUCTIONS_ABOUT_ADDITIONAL_AMOUNTS_COVERED",
	},
	{
		value: "ABU",
		name: "Deferred payment termed additional",
		key: "DEFERRED_PAYMENT_TERMED_ADDITIONAL",
	},
	{
		value: "ABV",
		name: "Acceptance terms additional",
		key: "ACCEPTANCE_TERMS_ADDITIONAL",
	},
	{
		value: "ABW",
		name: "Negotiation terms additional",
		key: "NEGOTIATION_TERMS_ADDITIONAL",
	},
	{
		value: "ABX",
		name: "Document name and documentary requirements",
		key: "DOCUMENT_NAME_AND_DOCUMENTARY_REQUIREMENTS",
	},
	{
		value: "ABZ",
		name: "Instructions/information about revolving documentary credit",
		key: "INSTRUCTIONS_INFORMATION_ABOUT_REVOLVING_DOCUMENTARY_CREDIT",
	},
	{
		value: "ACA",
		name: "Documentary requirements",
		key: "DOCUMENTARY_REQUIREMENTS",
	},
	{
		value: "ACB",
		name: "Additional information",
		key: "ADDITIONAL_INFORMATION",
	},
	{
		value: "ACC",
		name: "Factor assignment clause",
		key: "FACTOR_ASSIGNMENT_CLAUSE",
	},
	{ value: "ACD", name: "Reason", key: "REASON" },
	{ value: "ACE", name: "Dispute", key: "DISPUTE" },
	{
		value: "ACF",
		name: "Additional attribute information",
		key: "ADDITIONAL_ATTRIBUTE_INFORMATION",
	},
	{ value: "ACG", name: "Absence declaration", key: "ABSENCE_DECLARATION" },
	{ value: "ACH", name: "Aggregation statement", key: "AGGREGATION_STATEMENT" },
	{ value: "ACI", name: "Compilation statement", key: "COMPILATION_STATEMENT" },
	{
		value: "ACJ",
		name: "Definitional exception",
		key: "DEFINITIONAL_EXCEPTION",
	},
	{ value: "ACK", name: "Privacy statement", key: "PRIVACY_STATEMENT" },
	{ value: "ACL", name: "Quality statement", key: "QUALITY_STATEMENT" },
	{
		value: "ACM",
		name: "Statistical description",
		key: "STATISTICAL_DESCRIPTION",
	},
	{
		value: "ACN",
		name: "Statistical definition",
		key: "STATISTICAL_DEFINITION",
	},
	{ value: "ACO", name: "Statistical name", key: "STATISTICAL_NAME" },
	{ value: "ACP", name: "Statistical title", key: "STATISTICAL_TITLE" },
	{
		value: "ACQ",
		name: "Off-dimension information",
		key: "OFF_DIMENSION_INFORMATION",
	},
	{
		value: "ACR",
		name: "Unexpected stops information",
		key: "UNEXPECTED_STOPS_INFORMATION",
	},
	{ value: "ACS", name: "Principles", key: "PRINCIPLES" },
	{ value: "ACT", name: "Terms and definition", key: "TERMS_AND_DEFINITION" },
	{ value: "ACU", name: "Segment name", key: "SEGMENT_NAME" },
	{
		value: "ACV",
		name: "Simple data element name",
		key: "SIMPLE_DATA_ELEMENT_NAME",
	},
	{ value: "ACW", name: "Scope", key: "SCOPE" },
	{ value: "ACX", name: "Message type name", key: "MESSAGE_TYPE_NAME" },
	{ value: "ACY", name: "Introduction", key: "INTRODUCTION" },
	{ value: "ACZ", name: "Glossary", key: "GLOSSARY" },
	{ value: "ADA", name: "Functional definition", key: "FUNCTIONAL_DEFINITION" },
	{ value: "ADB", name: "Examples", key: "EXAMPLES" },
	{ value: "ADC", name: "Cover page", key: "COVER_PAGE" },
	{
		value: "ADD",
		name: "Dependency (syntax) notes",
		key: "DEPENDENCY_SYNTAX_NOTES",
	},
	{ value: "ADE", name: "Code value name", key: "CODE_VALUE_NAME" },
	{ value: "ADF", name: "Code list name", key: "CODE_LIST_NAME" },
	{
		value: "ADG",
		name: "Clarification of usage",
		key: "CLARIFICATION_OF_USAGE",
	},
	{
		value: "ADH",
		name: "Composite data element name",
		key: "COMPOSITE_DATA_ELEMENT_NAME",
	},
	{ value: "ADI", name: "Field of application", key: "FIELD_OF_APPLICATION" },
	{
		value: "ADJ",
		name: "Type of assets and liabilities",
		key: "TYPE_OF_ASSETS_AND_LIABILITIES",
	},
	{ value: "ADK", name: "Promotion information", key: "PROMOTION_INFORMATION" },
	{ value: "ADL", name: "Meter condition", key: "METER_CONDITION" },
	{
		value: "ADM",
		name: "Meter reading information",
		key: "METER_READING_INFORMATION",
	},
	{
		value: "ADN",
		name: "Type of transaction reason",
		key: "TYPE_OF_TRANSACTION_REASON",
	},
	{
		value: "ADO",
		name: "Type of survey question",
		key: "TYPE_OF_SURVEY_QUESTION",
	},
	{
		value: "ADP",
		name: "Carrier's agent counter information",
		key: "CARRIER_S_AGENT_COUNTER_INFORMATION",
	},
	{
		value: "ADQ",
		name: "Description of work item on equipment",
		key: "DESCRIPTION_OF_WORK_ITEM_ON_EQUIPMENT",
	},
	{ value: "ADR", name: "Message definition", key: "MESSAGE_DEFINITION" },
	{
		value: "ADS",
		name: "Booked item information",
		key: "BOOKED_ITEM_INFORMATION",
	},
	{ value: "ADT", name: "Source of document", key: "SOURCE_OF_DOCUMENT" },
	{ value: "ADU", name: "Note", key: "NOTE" },
	{
		value: "ADV",
		name: "Fixed part of segment clarification text",
		key: "FIXED_PART_OF_SEGMENT_CLARIFICATION_TEXT",
	},
	{
		value: "ADW",
		name: "Characteristics of goods",
		key: "CHARACTERISTICS_OF_GOODS",
	},
	{
		value: "ADX",
		name: "Additional discharge instructions",
		key: "ADDITIONAL_DISCHARGE_INSTRUCTIONS",
	},
	{
		value: "ADY",
		name: "Container stripping instructions",
		key: "CONTAINER_STRIPPING_INSTRUCTIONS",
	},
	{
		value: "ADZ",
		name: "CSC (Container Safety Convention) plate information",
		key: "CSC_CONTAINER_SAFETY_CONVENTION_PLATE_INFORMATION",
	},
	{ value: "AEA", name: "Cargo remarks", key: "CARGO_REMARKS" },
	{
		value: "AEB",
		name: "Temperature control instructions",
		key: "TEMPERATURE_CONTROL_INSTRUCTIONS",
	},
	{
		value: "AEC",
		name: "Text refers to expected data",
		key: "TEXT_REFERS_TO_EXPECTED_DATA",
	},
	{
		value: "AED",
		name: "Text refers to received data",
		key: "TEXT_REFERS_TO_RECEIVED_DATA",
	},
	{
		value: "AEE",
		name: "Section clarification text",
		key: "SECTION_CLARIFICATION_TEXT",
	},
	{
		value: "AEF",
		name: "Information to the beneficiary",
		key: "INFORMATION_TO_THE_BENEFICIARY",
	},
	{
		value: "AEG",
		name: "Information to the applicant",
		key: "INFORMATION_TO_THE_APPLICANT",
	},
	{
		value: "AEH",
		name: "Instructions to the beneficiary",
		key: "INSTRUCTIONS_TO_THE_BENEFICIARY",
	},
	{
		value: "AEI",
		name: "Instructions to the applicant",
		key: "INSTRUCTIONS_TO_THE_APPLICANT",
	},
	{ value: "AEJ", name: "Controlled atmosphere", key: "CONTROLLED_ATMOSPHERE" },
	{ value: "AEK", name: "Take off annotation", key: "TAKE_OFF_ANNOTATION" },
	{
		value: "AEL",
		name: "Price variation narrative",
		key: "PRICE_VARIATION_NARRATIVE",
	},
	{
		value: "AEM",
		name: "Documentary credit amendment instructions",
		key: "DOCUMENTARY_CREDIT_AMENDMENT_INSTRUCTIONS",
	},
	{
		value: "AEN",
		name: "Standard method narrative",
		key: "STANDARD_METHOD_NARRATIVE",
	},
	{ value: "AEO", name: "Project narrative", key: "PROJECT_NARRATIVE" },
	{
		value: "AEP",
		name: "Radioactive goods, additional information",
		key: "RADIOACTIVE_GOODS_ADDITIONAL_INFORMATION",
	},
	{
		value: "AEQ",
		name: "Bank-to-bank information",
		key: "BANK_TO_BANK_INFORMATION",
	},
	{
		value: "AER",
		name: "Reimbursement instructions",
		key: "REIMBURSEMENT_INSTRUCTIONS",
	},
	{
		value: "AES",
		name: "Reason for amending a message",
		key: "REASON_FOR_AMENDING_A_MESSAGE",
	},
	{
		value: "AET",
		name: "Instructions to the paying and/or accepting and/or",
		key: "INSTRUCTIONS_TO_THE_PAYING_AND_OR_ACCEPTING_AND_OR",
	},
	{ value: "AEU", name: "Interest instructions", key: "INTEREST_INSTRUCTIONS" },
	{ value: "AEV", name: "Agent commission", key: "AGENT_COMMISSION" },
	{
		value: "AEW",
		name: "Remitting bank instructions",
		key: "REMITTING_BANK_INSTRUCTIONS",
	},
	{
		value: "AEX",
		name: "Instructions to the collecting bank",
		key: "INSTRUCTIONS_TO_THE_COLLECTING_BANK",
	},
	{
		value: "AEY",
		name: "Collection amount instructions",
		key: "COLLECTION_AMOUNT_INSTRUCTIONS",
	},
	{
		value: "AEZ",
		name: "Internal auditing information",
		key: "INTERNAL_AUDITING_INFORMATION",
	},
	{ value: "AFA", name: "Constraint", key: "CONSTRAINT" },
	{ value: "AFB", name: "Comment", key: "COMMENT" },
	{ value: "AFC", name: "Semantic note", key: "SEMANTIC_NOTE" },
	{ value: "AFD", name: "Help text", key: "HELP_TEXT" },
	{ value: "AFE", name: "Legend", key: "LEGEND" },
	{ value: "AFF", name: "Batch code structure", key: "BATCH_CODE_STRUCTURE" },
	{ value: "AFG", name: "Product application", key: "PRODUCT_APPLICATION" },
	{ value: "AFH", name: "Customer complaint", key: "CUSTOMER_COMPLAINT" },
	{
		value: "AFI",
		name: "Probable cause of fault",
		key: "PROBABLE_CAUSE_OF_FAULT",
	},
	{ value: "AFJ", name: "Defect description", key: "DEFECT_DESCRIPTION" },
	{ value: "AFK", name: "Repair description", key: "REPAIR_DESCRIPTION" },
	{ value: "AFL", name: "Review comments", key: "REVIEW_COMMENTS" },
	{ value: "AFM", name: "Title", key: "TITLE" },
	{ value: "AFN", name: "Description of amount", key: "DESCRIPTION_OF_AMOUNT" },
	{ value: "AFO", name: "Responsibilities", key: "RESPONSIBILITIES" },
	{ value: "AFP", name: "Supplier", key: "SUPPLIER" },
	{ value: "AFQ", name: "Purchase region", key: "PURCHASE_REGION" },
	{ value: "AFR", name: "Affiliation", key: "AFFILIATION" },
	{ value: "AFS", name: "Borrower", key: "BORROWER" },
	{ value: "AFT", name: "Line of business", key: "LINE_OF_BUSINESS" },
	{ value: "AFU", name: "Financial institution", key: "FINANCIAL_INSTITUTION" },
	{ value: "AFV", name: "Business founder", key: "BUSINESS_FOUNDER" },
	{ value: "AFW", name: "Business history", key: "BUSINESS_HISTORY" },
	{ value: "AFX", name: "Banking arrangements", key: "BANKING_ARRANGEMENTS" },
	{ value: "AFY", name: "Business origin", key: "BUSINESS_ORIGIN" },
	{
		value: "AFZ",
		name: "Brand names' description",
		key: "BRAND_NAMES_DESCRIPTION",
	},
	{
		value: "AGA",
		name: "Business financing details",
		key: "BUSINESS_FINANCING_DETAILS",
	},
	{ value: "AGB", name: "Competition", key: "COMPETITION" },
	{
		value: "AGC",
		name: "Construction process details",
		key: "CONSTRUCTION_PROCESS_DETAILS",
	},
	{
		value: "AGD",
		name: "Construction specialty",
		key: "CONSTRUCTION_SPECIALTY",
	},
	{ value: "AGE", name: "Contract information", key: "CONTRACT_INFORMATION" },
	{ value: "AGF", name: "Corporate filing", key: "CORPORATE_FILING" },
	{ value: "AGG", name: "Customer information", key: "CUSTOMER_INFORMATION" },
	{ value: "AGH", name: "Copyright notice", key: "COPYRIGHT_NOTICE" },
	{ value: "AGI", name: "Contingent debt", key: "CONTINGENT_DEBT" },
	{ value: "AGJ", name: "Conviction details", key: "CONVICTION_DETAILS" },
	{ value: "AGK", name: "Equipment", key: "EQUIPMENT" },
	{ value: "AGL", name: "Workforce description", key: "WORKFORCE_DESCRIPTION" },
	{ value: "AGM", name: "Exemption", key: "EXEMPTION" },
	{ value: "AGN", name: "Future plans", key: "FUTURE_PLANS" },
	{
		value: "AGO",
		name: "Interviewee conversation information",
		key: "INTERVIEWEE_CONVERSATION_INFORMATION",
	},
	{ value: "AGP", name: "Intangible asset", key: "INTANGIBLE_ASSET" },
	{ value: "AGQ", name: "Inventory", key: "INVENTORY" },
	{ value: "AGR", name: "Investment", key: "INVESTMENT" },
	{
		value: "AGS",
		name: "Intercompany relations information",
		key: "INTERCOMPANY_RELATIONS_INFORMATION",
	},
	{ value: "AGT", name: "Joint venture", key: "JOINT_VENTURE" },
	{ value: "AGU", name: "Loan", key: "LOAN" },
	{ value: "AGV", name: "Long term debt", key: "LONG_TERM_DEBT" },
	{ value: "AGW", name: "Location", key: "LOCATION" },
	{
		value: "AGX",
		name: "Current legal structure",
		key: "CURRENT_LEGAL_STRUCTURE",
	},
	{ value: "AGY", name: "Marital contract", key: "MARITAL_CONTRACT" },
	{ value: "AGZ", name: "Marketing activities", key: "MARKETING_ACTIVITIES" },
	{ value: "AHA", name: "Merger", key: "MERGER" },
	{ value: "AHB", name: "Marketable securities", key: "MARKETABLE_SECURITIES" },
	{ value: "AHC", name: "Business debt", key: "BUSINESS_DEBT" },
	{
		value: "AHD",
		name: "Original legal structure",
		key: "ORIGINAL_LEGAL_STRUCTURE",
	},
	{
		value: "AHE",
		name: "Employee sharing arrangements",
		key: "EMPLOYEE_SHARING_ARRANGEMENTS",
	},
	{ value: "AHF", name: "Organization details", key: "ORGANIZATION_DETAILS" },
	{ value: "AHG", name: "Public record details", key: "PUBLIC_RECORD_DETAILS" },
	{ value: "AHH", name: "Price range", key: "PRICE_RANGE" },
	{ value: "AHI", name: "Qualifications", key: "QUALIFICATIONS" },
	{ value: "AHJ", name: "Registered activity", key: "REGISTERED_ACTIVITY" },
	{ value: "AHK", name: "Criminal sentence", key: "CRIMINAL_SENTENCE" },
	{ value: "AHL", name: "Sales method", key: "SALES_METHOD" },
	{
		value: "AHM",
		name: "Educational institution information",
		key: "EDUCATIONAL_INSTITUTION_INFORMATION",
	},
	{ value: "AHN", name: "Status details", key: "STATUS_DETAILS" },
	{ value: "AHO", name: "Sales", key: "SALES" },
	{ value: "AHP", name: "Spouse information", key: "SPOUSE_INFORMATION" },
	{
		value: "AHQ",
		name: "Educational degree information",
		key: "EDUCATIONAL_DEGREE_INFORMATION",
	},
	{
		value: "AHR",
		name: "Shareholding information",
		key: "SHAREHOLDING_INFORMATION",
	},
	{ value: "AHS", name: "Sales territory", key: "SALES_TERRITORY" },
	{ value: "AHT", name: "Accountant's comments", key: "ACCOUNTANT_S_COMMENTS" },
	{
		value: "AHU",
		name: "Exemption law location",
		key: "EXEMPTION_LAW_LOCATION",
	},
	{ value: "AHV", name: "Share classifications", key: "SHARE_CLASSIFICATIONS" },
	{ value: "AHW", name: "Forecast", key: "FORECAST" },
	{ value: "AHX", name: "Event location", key: "EVENT_LOCATION" },
	{ value: "AHY", name: "Facility occupancy", key: "FACILITY_OCCUPANCY" },
	{
		value: "AHZ",
		name: "Import and export details",
		key: "IMPORT_AND_EXPORT_DETAILS",
	},
	{
		value: "AIA",
		name: "Additional facility information",
		key: "ADDITIONAL_FACILITY_INFORMATION",
	},
	{ value: "AIB", name: "Inventory value", key: "INVENTORY_VALUE" },
	{ value: "AIC", name: "Education", key: "EDUCATION" },
	{ value: "AID", name: "Event", key: "EVENT" },
	{ value: "AIE", name: "Agent", key: "AGENT" },
	{
		value: "AIF",
		name: "Domestically agreed financial statement details",
		key: "DOMESTICALLY_AGREED_FINANCIAL_STATEMENT_DETAILS",
	},
	{
		value: "AIG",
		name: "Other current asset description",
		key: "OTHER_CURRENT_ASSET_DESCRIPTION",
	},
	{
		value: "AIH",
		name: "Other current liability description",
		key: "OTHER_CURRENT_LIABILITY_DESCRIPTION",
	},
	{
		value: "AII",
		name: "Former business activity",
		key: "FORMER_BUSINESS_ACTIVITY",
	},
	{ value: "AIJ", name: "Trade name use", key: "TRADE_NAME_USE" },
	{ value: "AIK", name: "Signing authority", key: "SIGNING_AUTHORITY" },
	{ value: "AIL", name: "Guarantee", key: "GUARANTEE" },
	{
		value: "AIM",
		name: "Holding company operation",
		key: "HOLDING_COMPANY_OPERATION",
	},
	{ value: "AIN", name: "Consignment routing", key: "CONSIGNMENT_ROUTING" },
	{ value: "AIO", name: "Letter of protest", key: "LETTER_OF_PROTEST" },
	{ value: "AIP", name: "Question", key: "QUESTION" },
	{ value: "AIQ", name: "Party information", key: "PARTY_INFORMATION" },
	{
		value: "AIR",
		name: "Area boundaries description",
		key: "AREA_BOUNDARIES_DESCRIPTION",
	},
	{
		value: "AIS",
		name: "Advertisement information",
		key: "ADVERTISEMENT_INFORMATION",
	},
	{
		value: "AIT",
		name: "Financial statement details",
		key: "FINANCIAL_STATEMENT_DETAILS",
	},
	{ value: "AIU", name: "Access instructions", key: "ACCESS_INSTRUCTIONS" },
	{ value: "AIV", name: "Liquidity", key: "LIQUIDITY" },
	{ value: "AIW", name: "Credit line", key: "CREDIT_LINE" },
	{ value: "AIX", name: "Warranty terms", key: "WARRANTY_TERMS" },
	{ value: "AIY", name: "Division description", key: "DIVISION_DESCRIPTION" },
	{ value: "AIZ", name: "Reporting instruction", key: "REPORTING_INSTRUCTION" },
	{ value: "AJA", name: "Examination result", key: "EXAMINATION_RESULT" },
	{ value: "AJB", name: "Laboratory result", key: "LABORATORY_RESULT" },
	{
		value: "ALC",
		name: "Allowance/charge information",
		key: "ALLOWANCE_CHARGE_INFORMATION",
	},
	{ value: "ALD", name: "X-ray result", key: "X_RAY_RESULT" },
	{ value: "ALE", name: "Pathology result", key: "PATHOLOGY_RESULT" },
	{
		value: "ALF",
		name: "Intervention description",
		key: "INTERVENTION_DESCRIPTION",
	},
	{ value: "ALG", name: "Summary of admittance", key: "SUMMARY_OF_ADMITTANCE" },
	{
		value: "ALH",
		name: "Medical treatment course detail",
		key: "MEDICAL_TREATMENT_COURSE_DETAIL",
	},
	{ value: "ALI", name: "Prognosis", key: "PROGNOSIS" },
	{
		value: "ALJ",
		name: "Instruction to patient",
		key: "INSTRUCTION_TO_PATIENT",
	},
	{
		value: "ALK",
		name: "Instruction to physician",
		key: "INSTRUCTION_TO_PHYSICIAN",
	},
	{ value: "ALL", name: "All documents", key: "ALL_DOCUMENTS" },
	{ value: "ALM", name: "Medicine treatment", key: "MEDICINE_TREATMENT" },
	{
		value: "ALN",
		name: "Medicine dosage and administration",
		key: "MEDICINE_DOSAGE_AND_ADMINISTRATION",
	},
	{
		value: "ALO",
		name: "Availability of patient",
		key: "AVAILABILITY_OF_PATIENT",
	},
	{
		value: "ALP",
		name: "Reason for service request",
		key: "REASON_FOR_SERVICE_REQUEST",
	},
	{ value: "ALQ", name: "Purpose of service", key: "PURPOSE_OF_SERVICE" },
	{ value: "ARR", name: "Arrival conditions", key: "ARRIVAL_CONDITIONS" },
	{
		value: "ARS",
		name: "Service requester's comment",
		key: "SERVICE_REQUESTER_S_COMMENT",
	},
	{ value: "AUT", name: "Authentication", key: "AUTHENTICATION" },
	{
		value: "AUU",
		name: "Requested location description",
		key: "REQUESTED_LOCATION_DESCRIPTION",
	},
	{
		value: "AUV",
		name: "Medicine administration condition",
		key: "MEDICINE_ADMINISTRATION_CONDITION",
	},
	{ value: "AUW", name: "Patient information", key: "PATIENT_INFORMATION" },
	{ value: "AUX", name: "Precautionary measure", key: "PRECAUTIONARY_MEASURE" },
	{
		value: "AUY",
		name: "Service characteristic",
		key: "SERVICE_CHARACTERISTIC",
	},
	{ value: "AUZ", name: "Planned event comment", key: "PLANNED_EVENT_COMMENT" },
	{
		value: "AVA",
		name: "Expected delay comment",
		key: "EXPECTED_DELAY_COMMENT",
	},
	{
		value: "AVB",
		name: "Transport requirements comment",
		key: "TRANSPORT_REQUIREMENTS_COMMENT",
	},
	{
		value: "AVC",
		name: "Temporary approval condition",
		key: "TEMPORARY_APPROVAL_CONDITION",
	},
	{
		value: "AVD",
		name: "Customs Valuation Information",
		key: "CUSTOMS_VALUATION_INFORMATION",
	},
	{
		value: "AVE",
		name: "Value Added Tax (VAT) margin scheme",
		key: "VALUE_ADDED_TAX_VAT_MARGIN_SCHEME",
	},
	{
		value: "AVF",
		name: "Maritime Declaration of Health",
		key: "MARITIME_DECLARATION_OF_HEALTH",
	},
	{
		value: "BAG",
		name: "Passenger baggage information",
		key: "PASSENGER_BAGGAGE_INFORMATION",
	},
	{
		value: "BAH",
		name: "Maritime Declaration of Health",
		key: "MARITIME_DECLARATION_OF_HEALTH",
	},
	{
		value: "BAI",
		name: "Additional product information address",
		key: "ADDITIONAL_PRODUCT_INFORMATION_ADDRESS",
	},
	{
		value: "BAJ",
		name: "Information to be printed on despatch advice",
		key: "INFORMATION_TO_BE_PRINTED_ON_DESPATCH_ADVICE",
	},
	{ value: "BAK", name: "Missing goods remarks", key: "MISSING_GOODS_REMARKS" },
	{
		value: "BAL",
		name: "Non-acceptance information",
		key: "NON_ACCEPTANCE_INFORMATION",
	},
	{ value: "BAM", name: "Returns information", key: "RETURNS_INFORMATION" },
	{
		value: "BAN",
		name: "Sub-line item information",
		key: "SUB_LINE_ITEM_INFORMATION",
	},
	{ value: "BAO", name: "Test information", key: "TEST_INFORMATION" },
	{ value: "BAP", name: "External link", key: "EXTERNAL_LINK" },
	{ value: "BAQ", name: "VAT exemption reason", key: "VAT_EXEMPTION_REASON" },
	{
		value: "BAR",
		name: "Processing Instructions",
		key: "PROCESSING_INSTRUCTIONS",
	},
	{ value: "BAS", name: "Relay Instructions", key: "RELAY_INSTRUCTIONS" },
	{ value: "BAT", name: "SIMA applicable", key: "SIMA_APPLICABLE" },
	{ value: "BAU", name: "Appeals program code", key: "APPEALS_PROGRAM_CODE" },
	{ value: "BAV", name: "SIMA subject", key: "SIMA_SUBJECT" },
	{ value: "BAW", name: "Surtax applicable", key: "SURTAX_APPLICABLE" },
	{ value: "BAX", name: "SIMA security bond", key: "SIMA_SECURITY_BOND" },
	{ value: "BAY", name: "Surtax subject", key: "SURTAX_SUBJECT" },
	{ value: "BAZ", name: "Safeguard applicable", key: "SAFEGUARD_APPLICABLE" },
	{ value: "BBA", name: "Safeguard applicable", key: "SAFEGUARD_APPLICABLE" },
	{ value: "BBB", name: "Safeguard subject", key: "SAFEGUARD_SUBJECT" },
	{
		value: "BLC",
		name: "Transport contract document clause",
		key: "TRANSPORT_CONTRACT_DOCUMENT_CLAUSE",
	},
	{
		value: "BLD",
		name: "Instruction to prepare the patient",
		key: "INSTRUCTION_TO_PREPARE_THE_PATIENT",
	},
	{
		value: "BLE",
		name: "Medicine treatment comment",
		key: "MEDICINE_TREATMENT_COMMENT",
	},
	{
		value: "BLF",
		name: "Examination result comment",
		key: "EXAMINATION_RESULT_COMMENT",
	},
	{
		value: "BLG",
		name: "Service request comment",
		key: "SERVICE_REQUEST_COMMENT",
	},
	{ value: "BLH", name: "Prescription reason", key: "PRESCRIPTION_REASON" },
	{ value: "BLI", name: "Prescription comment", key: "PRESCRIPTION_COMMENT" },
	{
		value: "BLJ",
		name: "Clinical investigation comment",
		key: "CLINICAL_INVESTIGATION_COMMENT",
	},
	{
		value: "BLK",
		name: "Medicinal specification comment",
		key: "MEDICINAL_SPECIFICATION_COMMENT",
	},
	{
		value: "BLL",
		name: "Economic contribution comment",
		key: "ECONOMIC_CONTRIBUTION_COMMENT",
	},
	{ value: "BLM", name: "Status of a plan", key: "STATUS_OF_A_PLAN" },
	{
		value: "BLN",
		name: "Random sample test information",
		key: "RANDOM_SAMPLE_TEST_INFORMATION",
	},
	{ value: "BLO", name: "Period of time", key: "PERIOD_OF_TIME" },
	{ value: "BLP", name: "Legislation", key: "LEGISLATION" },
	{
		value: "BLQ",
		name: "Security measures requested",
		key: "SECURITY_MEASURES_REQUESTED",
	},
	{
		value: "BLR",
		name: "Transport contract document remark",
		key: "TRANSPORT_CONTRACT_DOCUMENT_REMARK",
	},
	{
		value: "BLS",
		name: "Previous port of call security information",
		key: "PREVIOUS_PORT_OF_CALL_SECURITY_INFORMATION",
	},
	{ value: "BLT", name: "Security information", key: "SECURITY_INFORMATION" },
	{ value: "BLU", name: "Waste information", key: "WASTE_INFORMATION" },
	{
		value: "BLV",
		name: "B2C marketing information, short description",
		key: "B2_C_MARKETING_INFORMATION_SHORT_DESCRIPTION",
	},
	{
		value: "BLW",
		name: "B2B marketing information, long description",
		key: "B2_B_MARKETING_INFORMATION_LONG_DESCRIPTION",
	},
	{
		value: "BLX",
		name: "B2C marketing information, long description",
		key: "B2_C_MARKETING_INFORMATION_LONG_DESCRIPTION",
	},
	{ value: "BLY", name: "Product ingredients", key: "PRODUCT_INGREDIENTS" },
	{ value: "BLZ", name: "Location short name", key: "LOCATION_SHORT_NAME" },
	{
		value: "BMA",
		name: "Packaging material information",
		key: "PACKAGING_MATERIAL_INFORMATION",
	},
	{
		value: "BMB",
		name: "Filler material information",
		key: "FILLER_MATERIAL_INFORMATION",
	},
	{
		value: "BMC",
		name: "Ship-to-ship activity information",
		key: "SHIP_TO_SHIP_ACTIVITY_INFORMATION",
	},
	{
		value: "BMD",
		name: "Package material description",
		key: "PACKAGE_MATERIAL_DESCRIPTION",
	},
	{
		value: "BME",
		name: "Consumer level package marking",
		key: "CONSUMER_LEVEL_PACKAGE_MARKING",
	},
	{ value: "BMF", name: "SIMA measure in force", key: "SIMA_MEASURE_IN_FORCE" },
	{ value: "BMG", name: "Pre-CARM", key: "PRE_CARM" },
	{ value: "BMH", name: "SIMA measure type", key: "SIMA_MEASURE_TYPE" },
	{
		value: "CCI",
		name: "Customs clearance instructions",
		key: "CUSTOMS_CLEARANCE_INSTRUCTIONS",
	},
	{ value: "CCJ", name: "Sub Type Code", key: "SUB_TYPE_CODE" },
	{ value: "CCK", name: "SIMA information", key: "SIMA_INFORMATION" },
	{ value: "CCL", name: "Time limit end", key: "TIME_LIMIT_END" },
	{ value: "CCM", name: "Time limit start", key: "TIME_LIMIT_START" },
	{ value: "CCN", name: "Warehouse time limit", key: "WAREHOUSE_TIME_LIMIT" },
	{
		value: "CCO",
		name: "Value for duty information",
		key: "VALUE_FOR_DUTY_INFORMATION",
	},
	{
		value: "CEX",
		name: "Customs clearance instructions export",
		key: "CUSTOMS_CLEARANCE_INSTRUCTIONS_EXPORT",
	},
	{ value: "CHG", name: "Change information", key: "CHANGE_INFORMATION" },
	{
		value: "CIP",
		name: "Customs clearance instruction import",
		key: "CUSTOMS_CLEARANCE_INSTRUCTION_IMPORT",
	},
	{
		value: "CLP",
		name: "Clearance place requested",
		key: "CLEARANCE_PLACE_REQUESTED",
	},
	{ value: "CLR", name: "Loading remarks", key: "LOADING_REMARKS" },
	{ value: "COI", name: "Order information", key: "ORDER_INFORMATION" },
	{ value: "CUR", name: "Customer remarks", key: "CUSTOMER_REMARKS" },
	{
		value: "CUS",
		name: "Customs declaration information",
		key: "CUSTOMS_DECLARATION_INFORMATION",
	},
	{ value: "DAR", name: "Damage remarks", key: "DAMAGE_REMARKS" },
	{
		value: "DCL",
		name: "Document issuer declaration",
		key: "DOCUMENT_ISSUER_DECLARATION",
	},
	{ value: "DEL", name: "Delivery information", key: "DELIVERY_INFORMATION" },
	{ value: "DIN", name: "Delivery instructions", key: "DELIVERY_INSTRUCTIONS" },
	{
		value: "DOC",
		name: "Documentation instructions",
		key: "DOCUMENTATION_INSTRUCTIONS",
	},
	{ value: "DUT", name: "Duty declaration", key: "DUTY_DECLARATION" },
	{
		value: "EUR",
		name: "Effective used routing",
		key: "EFFECTIVE_USED_ROUTING",
	},
	{
		value: "FBC",
		name: "First block to be printed on the transport contract",
		key: "FIRST_BLOCK_TO_BE_PRINTED_ON_THE_TRANSPORT_CONTRACT",
	},
	{
		value: "GBL",
		name: "Government bill of lading information",
		key: "GOVERNMENT_BILL_OF_LADING_INFORMATION",
	},
	{
		value: "GEN",
		name: "Entire transaction set",
		key: "ENTIRE_TRANSACTION_SET",
	},
	{
		value: "GS7",
		name: "Further information concerning GGVS par. 7",
		key: "FURTHER_INFORMATION_CONCERNING_GGVS_PAR_7",
	},
	{
		value: "HAN",
		name: "Consignment handling instruction",
		key: "CONSIGNMENT_HANDLING_INSTRUCTION",
	},
	{ value: "HAZ", name: "Hazard information", key: "HAZARD_INFORMATION" },
	{
		value: "ICN",
		name: "Consignment information for consignee",
		key: "CONSIGNMENT_INFORMATION_FOR_CONSIGNEE",
	},
	{
		value: "IIN",
		name: "Insurance instructions",
		key: "INSURANCE_INSTRUCTIONS",
	},
	{
		value: "IMI",
		name: "Invoice mailing instructions",
		key: "INVOICE_MAILING_INSTRUCTIONS",
	},
	{
		value: "IND",
		name: "Commercial invoice item description",
		key: "COMMERCIAL_INVOICE_ITEM_DESCRIPTION",
	},
	{ value: "INS", name: "Insurance information", key: "INSURANCE_INFORMATION" },
	{ value: "INV", name: "Invoice instruction", key: "INVOICE_INSTRUCTION" },
	{
		value: "IRP",
		name: "Information for railway purpose",
		key: "INFORMATION_FOR_RAILWAY_PURPOSE",
	},
	{
		value: "ITR",
		name: "Inland transport details",
		key: "INLAND_TRANSPORT_DETAILS",
	},
	{ value: "ITS", name: "Testing instructions", key: "TESTING_INSTRUCTIONS" },
	{ value: "LAN", name: "Location Alias", key: "LOCATION_ALIAS" },
	{ value: "LIN", name: "Line item", key: "LINE_ITEM" },
	{ value: "LOI", name: "Loading instruction", key: "LOADING_INSTRUCTION" },
	{
		value: "MCO",
		name: "Miscellaneous charge order",
		key: "MISCELLANEOUS_CHARGE_ORDER",
	},
	{
		value: "MDH",
		name: "Maritime Declaration of Health",
		key: "MARITIME_DECLARATION_OF_HEALTH",
	},
	{
		value: "MKS",
		name: "Additional marks/numbers information",
		key: "ADDITIONAL_MARKS_NUMBERS_INFORMATION",
	},
	{ value: "ORI", name: "Order instruction", key: "ORDER_INSTRUCTION" },
	{
		value: "OSI",
		name: "Other service information",
		key: "OTHER_SERVICE_INFORMATION",
	},
	{
		value: "PAC",
		name: "Packing/marking information",
		key: "PACKING_MARKING_INFORMATION",
	},
	{
		value: "PAI",
		name: "Payment instructions information",
		key: "PAYMENT_INSTRUCTIONS_INFORMATION",
	},
	{ value: "PAY", name: "Payables information", key: "PAYABLES_INFORMATION" },
	{ value: "PKG", name: "Packaging information", key: "PACKAGING_INFORMATION" },
	{
		value: "PKT",
		name: "Packaging terms information",
		key: "PACKAGING_TERMS_INFORMATION",
	},
	{
		value: "PMD",
		name: "Payment detail/remittance information",
		key: "PAYMENT_DETAIL_REMITTANCE_INFORMATION",
	},
	{ value: "PMT", name: "Payment information", key: "PAYMENT_INFORMATION" },
	{ value: "PRD", name: "Product information", key: "PRODUCT_INFORMATION" },
	{
		value: "PRF",
		name: "Price calculation formula",
		key: "PRICE_CALCULATION_FORMULA",
	},
	{ value: "PRI", name: "Priority information", key: "PRIORITY_INFORMATION" },
	{
		value: "PUR",
		name: "Purchasing information",
		key: "PURCHASING_INFORMATION",
	},
	{
		value: "QIN",
		name: "Quarantine instructions",
		key: "QUARANTINE_INSTRUCTIONS",
	},
	{
		value: "QQD",
		name: "Quality demands/requirements",
		key: "QUALITY_DEMANDS_REQUIREMENTS",
	},
	{
		value: "QUT",
		name: "Quotation instruction/information",
		key: "QUOTATION_INSTRUCTION_INFORMATION",
	},
	{
		value: "RAH",
		name: "Risk and handling information",
		key: "RISK_AND_HANDLING_INFORMATION",
	},
	{
		value: "REG",
		name: "Regulatory information",
		key: "REGULATORY_INFORMATION",
	},
	{
		value: "RET",
		name: "Return to origin information",
		key: "RETURN_TO_ORIGIN_INFORMATION",
	},
	{ value: "REV", name: "Receivables", key: "RECEIVABLES" },
	{ value: "RQR", name: "Consignment route", key: "CONSIGNMENT_ROUTE" },
	{ value: "SAF", name: "Safety information", key: "SAFETY_INFORMATION" },
	{
		value: "SIC",
		name: "Consignment documentary instruction",
		key: "CONSIGNMENT_DOCUMENTARY_INSTRUCTION",
	},
	{ value: "SIN", name: "Special instructions", key: "SPECIAL_INSTRUCTIONS" },
	{ value: "SLR", name: "Ship line requested", key: "SHIP_LINE_REQUESTED" },
	{
		value: "SPA",
		name: "Special permission for transport, generally",
		key: "SPECIAL_PERMISSION_FOR_TRANSPORT_GENERALLY",
	},
	{
		value: "SPG",
		name: "Special permission concerning the goods to be transported",
		key: "SPECIAL_PERMISSION_CONCERNING_THE_GOODS_TO_BE_TRANSPORTED",
	},
	{ value: "SPH", name: "Special handling", key: "SPECIAL_HANDLING" },
	{
		value: "SPP",
		name: "Special permission concerning package",
		key: "SPECIAL_PERMISSION_CONCERNING_PACKAGE",
	},
	{
		value: "SPT",
		name: "Special permission concerning transport means",
		key: "SPECIAL_PERMISSION_CONCERNING_TRANSPORT_MEANS",
	},
	{
		value: "SRN",
		name: "Subsidiary risk number (IATA/DGR)",
		key: "SUBSIDIARY_RISK_NUMBER_IATA_DGR",
	},
	{
		value: "SSR",
		name: "Special service request",
		key: "SPECIAL_SERVICE_REQUEST",
	},
	{ value: "SUR", name: "Supplier remarks", key: "SUPPLIER_REMARKS" },
	{ value: "TCA", name: "Consignment tariff", key: "CONSIGNMENT_TARIFF" },
	{ value: "TDT", name: "Consignment transport", key: "CONSIGNMENT_TRANSPORT" },
	{
		value: "TRA",
		name: "Transportation information",
		key: "TRANSPORTATION_INFORMATION",
	},
	{ value: "TRR", name: "Requested tariff", key: "REQUESTED_TARIFF" },
	{ value: "TXD", name: "Tax declaration", key: "TAX_DECLARATION" },
	{
		value: "WHI",
		name: "Warehouse instruction/information",
		key: "WAREHOUSE_INSTRUCTION_INFORMATION",
	},
	{ value: "ZZZ", name: "Mutually defined", key: "MUTUALLY_DEFINED" },
] as const satisfies Codelist;

declare module "@node-zugferd/core" {
	interface ZugferdCodelistRegistry {
		text: typeof text;
	}
}
registerCodelist("text", text);

export default text;
