const fs = require("fs/promises");
const { Biome } = require("@biomejs/js-api/nodejs");
const { toScreamingSnakeCase } = require("../utils");

const source =
  "https://www.xrepository.de/api/xrepository/urn:xoev-de:kosit:codeliste:currency-codes_3/download/Currency_Codes_3.json";

const main = async () => {
  console.info(
    `
Updating CURRENCY_CODES
from ${source}
`
  );

  const res = await fetch(new URL(source).toString(), {
    method: "GET",
  });

  const data = await res.json();

  if (!data["daten"] || !data["metadaten"]) {
    throw new Error("Invalid response");
  }

  const identifier = data["metadaten"]["kennungInhalt"];
  const version = data["metadaten"]["version"];
  const mappedData = data["daten"].map(([code, currency]) => {
    const formattedCode = JSON.stringify(code);
    const formattedCurrency = currency !== null ? JSON.stringify(currency) : "undefined";

    return `{ key: ${JSON.stringify(toScreamingSnakeCase(currency))}, code: ${formattedCode}, currency:${formattedCurrency}, },`;
  });

  const biome = new Biome();
  const { projectKey } = biome.openProject(".");

  const content = `/**
 * Generated by ${"`"}scripts/currency-codes/update.js${"`"} on ${new Date().toUTCString()}
 * 
 * @see https://www.xrepository.de/details/urn:xoev-de:kosit:codeliste:currency-codes
 */

export type CurrencyCodesDefinition = {
  key: string;
  code: string;
  currency: string;
};

export type CurrencyCodesCode = (typeof CURRENCY_CODES)[number]["code"];

export const CURRENCY_CODES_IDENTIFIER = "${identifier}" as const;
export const CURRENCY_CODES_VERSION = "${version}" as const;

export const CURRENCY_CODES = [${mappedData.join("")}${
    mappedData.length > 0 ? "\n" : ""
  }] as const satisfies CurrencyCodesDefinition[];
`;

  const filename = "currency-codes.gen.ts"

  await fs.writeFile(`./packages/node-zugferd/src/codelists/${filename}`, biome.formatContent(projectKey, content, { filePath: filename }).content);

  console.log(`Finished Updating CURRENCY_CODES`);
};

void main();
