const fs = require("fs/promises");
const { Biome } = require("@biomejs/js-api/nodejs");
const { toScreamingSnakeCase } = require("../utils");

const source =
  "https://www.xrepository.de/api/xrepository/urn:xoev-de:kosit:codeliste:rec21_3/download/UN_ECE_Recommendation_N_21_3.json";

const main = async () => {
  console.info(
    `
Updating UN/ECE Recommendation N°21
from ${source}
`
  );

  const res = await fetch(new URL(source).toString(), {
    method: "GET",
  });

  const data = await res.json();

  if (!data["daten"] || !data["metadaten"]) {
    throw new Error("Invalid response");
  }

  const identifier = data["metadaten"]["kennungInhalt"];
  const version = data["metadaten"]["version"];
  const mappedData = data["daten"].map(([code, name, description]) => {
    const formattedCode = JSON.stringify(code);
    const formattedName = name !== null ? JSON.stringify(name) : "undefined";
    const formattedDescription =
      description !== null ? JSON.stringify(description) : "undefined";

    return `{ key:${JSON.stringify(toScreamingSnakeCase(name))}, code:${formattedCode}, name:${formattedName}, description:${formattedDescription}, },`;
  });

  const biome = new Biome();
  const { projectKey } = biome.openProject(".");

  const content = `/**
 * Generated by ${"`"}scripts/rec21/update.js${"`"} on ${new Date().toUTCString()}
 * 
 * @see https://www.xrepository.de/details/urn:xoev-de:kosit:codeliste:rec21
 */

import { createEnum } from ".";

export type Rec21Definition = {
  key: string;
  code: string;
  name: string;
  description?: string;
};

export type Rec21Code = (typeof REC21)[number]["code"];

export const REC21_IDENTIFIER = "${identifier}" as const;
export const REC21_VERSION = "${version}" as const;

export const REC21 = [${mappedData.join("")}${
    mappedData.length > 0 ? "\n" : ""
  }] as const satisfies Rec21Definition[];

export const Rec21 = createEnum(REC21, {
  keyProp: "key",
  valueProp: "code",
});
`;

  const filename = "rec21.gen.ts";
  await fs.writeFile(
    `./packages/node-zugferd/src/codelists/${filename}`,
    biome.formatContent(projectKey, content, { filePath: filename }).content
  );

  console.log(`Finished Updating UN/ECE Recommendation N°21`);
};

void main();
