import type { Codelist } from "@node-zugferd/core";
import { registerCodelist } from "@node-zugferd/data-types";

const charge = [
	{ value: "AA", name: "Advertising", key: "ADVERTISING" },
	{ value: "AAA", name: "Telecommunication", key: "TELECOMMUNICATION" },
	{
		value: "AAC",
		name: "Technical modification",
		key: "TECHNICAL_MODIFICATION",
	},
	{ value: "AAD", name: "Job-order production", key: "JOB_ORDER_PRODUCTION" },
	{ value: "AAE", name: "Outlays", key: "OUTLAYS" },
	{ value: "AAF", name: "Off-premises", key: "OFF_PREMISES" },
	{ value: "AAH", name: "Additional processing", key: "ADDITIONAL_PROCESSING" },
	{ value: "AAI", name: "Attesting", key: "ATTESTING" },
	{ value: "AAS", name: "Acceptance", key: "ACCEPTANCE" },
	{ value: "AAT", name: "Rush delivery", key: "RUSH_DELIVERY" },
	{ value: "AAV", name: "Special construction", key: "SPECIAL_CONSTRUCTION" },
	{ value: "AAY", name: "Airport facilities", key: "AIRPORT_FACILITIES" },
	{ value: "AAZ", name: "Concession", key: "CONCESSION" },
	{ value: "ABA", name: "Compulsory storage", key: "COMPULSORY_STORAGE" },
	{ value: "ABB", name: "Fuel removal", key: "FUEL_REMOVAL" },
	{ value: "ABC", name: "Into plane", key: "INTO_PLANE" },
	{ value: "ABD", name: "Overtime", key: "OVERTIME" },
	{ value: "ABF", name: "Tooling", key: "TOOLING" },
	{ value: "ABK", name: "Miscellaneous", key: "MISCELLANEOUS" },
	{ value: "ABL", name: "Additional packaging", key: "ADDITIONAL_PACKAGING" },
	{ value: "ABN", name: "Dunnage", key: "DUNNAGE" },
	{ value: "ABR", name: "Containerisation", key: "CONTAINERISATION" },
	{ value: "ABS", name: "Carton packing", key: "CARTON_PACKING" },
	{ value: "ABT", name: "Hessian wrapped", key: "HESSIAN_WRAPPED" },
	{
		value: "ABU",
		name: "Polyethylene wrap packing",
		key: "POLYETHYLENE_WRAP_PACKING",
	},
	{
		value: "ACF",
		name: "Miscellaneous treatment",
		key: "MISCELLANEOUS_TREATMENT",
	},
	{ value: "ACG", name: "Enamelling treatment", key: "ENAMELLING_TREATMENT" },
	{ value: "ACH", name: "Heat treatment", key: "HEAT_TREATMENT" },
	{ value: "ACI", name: "Plating treatment", key: "PLATING_TREATMENT" },
	{ value: "ACJ", name: "Painting", key: "PAINTING" },
	{ value: "ACK", name: "Polishing", key: "POLISHING" },
	{ value: "ACL", name: "Priming", key: "PRIMING" },
	{
		value: "ACM",
		name: "Preservation treatment",
		key: "PRESERVATION_TREATMENT",
	},
	{ value: "ACS", name: "Fitting", key: "FITTING" },
	{ value: "ADC", name: "Consolidation", key: "CONSOLIDATION" },
	{ value: "ADE", name: "Bill of lading", key: "BILL_OF_LADING" },
	{ value: "ADJ", name: "Airbag", key: "AIRBAG" },
	{ value: "ADK", name: "Transfer", key: "TRANSFER" },
	{ value: "ADL", name: "Slipsheet", key: "SLIPSHEET" },
	{ value: "ADM", name: "Binding", key: "BINDING" },
	{
		value: "ADN",
		name: "Repair or replacement of broken returnable package",
		key: "REPAIR_OR_REPLACEMENT_OF_BROKEN_RETURNABLE_PACKAGE",
	},
	{ value: "ADO", name: "Efficient logistics", key: "EFFICIENT_LOGISTICS" },
	{ value: "ADP", name: "Merchandising", key: "MERCHANDISING" },
	{ value: "ADQ", name: "Product mix", key: "PRODUCT_MIX" },
	{ value: "ADR", name: "Other services", key: "OTHER_SERVICES" },
	{ value: "ADT", name: "Pick-up", key: "PICK_UP" },
	{ value: "ADW", name: "Chronic illness", key: "CHRONIC_ILLNESS" },
	{
		value: "ADY",
		name: "New product introduction",
		key: "NEW_PRODUCT_INTRODUCTION",
	},
	{ value: "ADZ", name: "Direct delivery", key: "DIRECT_DELIVERY" },
	{ value: "AEA", name: "Diversion", key: "DIVERSION" },
	{ value: "AEB", name: "Disconnect", key: "DISCONNECT" },
	{ value: "AEC", name: "Distribution", key: "DISTRIBUTION" },
	{
		value: "AED",
		name: "Handling of hazardous cargo",
		key: "HANDLING_OF_HAZARDOUS_CARGO",
	},
	{ value: "AEF", name: "Rents and leases", key: "RENTS_AND_LEASES" },
	{ value: "AEH", name: "Location differential", key: "LOCATION_DIFFERENTIAL" },
	{ value: "AEI", name: "Aircraft refueling", key: "AIRCRAFT_REFUELING" },
	{
		value: "AEJ",
		name: "Fuel shipped into storage",
		key: "FUEL_SHIPPED_INTO_STORAGE",
	},
	{ value: "AEK", name: "Cash on delivery", key: "CASH_ON_DELIVERY" },
	{
		value: "AEL",
		name: "Small order processing service",
		key: "SMALL_ORDER_PROCESSING_SERVICE",
	},
	{
		value: "AEM",
		name: "Clerical or administrative services",
		key: "CLERICAL_OR_ADMINISTRATIVE_SERVICES",
	},
	{ value: "AEN", name: "Guarantee", key: "GUARANTEE" },
	{
		value: "AEO",
		name: "Collection and recycling",
		key: "COLLECTION_AND_RECYCLING",
	},
	{
		value: "AEP",
		name: "Copyright fee collection",
		key: "COPYRIGHT_FEE_COLLECTION",
	},
	{
		value: "AES",
		name: "Veterinary inspection service",
		key: "VETERINARY_INSPECTION_SERVICE",
	},
	{ value: "AET", name: "Pensioner service", key: "PENSIONER_SERVICE" },
	{
		value: "AEU",
		name: "Medicine free pass holder",
		key: "MEDICINE_FREE_PASS_HOLDER",
	},
	{
		value: "AEV",
		name: "Environmental protection service",
		key: "ENVIRONMENTAL_PROTECTION_SERVICE",
	},
	{
		value: "AEW",
		name: "Environmental clean-up service",
		key: "ENVIRONMENTAL_CLEAN_UP_SERVICE",
	},
	{
		value: "AEX",
		name: "National cheque processing service outside account area",
		key: "NATIONAL_CHEQUE_PROCESSING_SERVICE_OUTSIDE_ACCOUNT_AREA",
	},
	{
		value: "AEY",
		name: "National payment service outside account area",
		key: "NATIONAL_PAYMENT_SERVICE_OUTSIDE_ACCOUNT_AREA",
	},
	{
		value: "AEZ",
		name: "National payment service within account area",
		key: "NATIONAL_PAYMENT_SERVICE_WITHIN_ACCOUNT_AREA",
	},
	{ value: "AJ", name: "Adjustments", key: "ADJUSTMENTS" },
	{ value: "AU", name: "Authentication", key: "AUTHENTICATION" },
	{ value: "CA", name: "Cataloguing", key: "CATALOGUING" },
	{ value: "CAB", name: "Cartage", key: "CARTAGE" },
	{ value: "CAD", name: "Certification", key: "CERTIFICATION" },
	{
		value: "CAE",
		name: "Certificate of conformance",
		key: "CERTIFICATE_OF_CONFORMANCE",
	},
	{ value: "CAF", name: "Certificate of origin", key: "CERTIFICATE_OF_ORIGIN" },
	{ value: "CAI", name: "Cutting", key: "CUTTING" },
	{ value: "CAJ", name: "Consular service", key: "CONSULAR_SERVICE" },
	{ value: "CAK", name: "Customer collection", key: "CUSTOMER_COLLECTION" },
	{
		value: "CAL",
		name: "Payroll payment service",
		key: "PAYROLL_PAYMENT_SERVICE",
	},
	{ value: "CAM", name: "Cash transportation", key: "CASH_TRANSPORTATION" },
	{ value: "CAN", name: "Home banking service", key: "HOME_BANKING_SERVICE" },
	{
		value: "CAO",
		name: "Bilateral agreement service",
		key: "BILATERAL_AGREEMENT_SERVICE",
	},
	{
		value: "CAP",
		name: "Insurance brokerage service",
		key: "INSURANCE_BROKERAGE_SERVICE",
	},
	{ value: "CAQ", name: "Cheque generation", key: "CHEQUE_GENERATION" },
	{
		value: "CAR",
		name: "Preferential merchandising location",
		key: "PREFERENTIAL_MERCHANDISING_LOCATION",
	},
	{ value: "CAS", name: "Crane", key: "CRANE" },
	{
		value: "CAT",
		name: "Special colour service",
		key: "SPECIAL_COLOUR_SERVICE",
	},
	{ value: "CAU", name: "Sorting", key: "SORTING" },
	{
		value: "CAV",
		name: "Battery collection and recycling",
		key: "BATTERY_COLLECTION_AND_RECYCLING",
	},
	{ value: "CAW", name: "Product take back fee", key: "PRODUCT_TAKE_BACK_FEE" },
	{
		value: "CAX",
		name: "Quality control released",
		key: "QUALITY_CONTROL_RELEASED",
	},
	{ value: "CAY", name: "Quality control held", key: "QUALITY_CONTROL_HELD" },
	{
		value: "CAZ",
		name: "Quality control embargo",
		key: "QUALITY_CONTROL_EMBARGO",
	},
	{ value: "CD", name: "Car loading", key: "CAR_LOADING" },
	{ value: "CG", name: "Cleaning", key: "CLEANING" },
	{ value: "CS", name: "Cigarette stamping", key: "CIGARETTE_STAMPING" },
	{ value: "CT", name: "Count and recount", key: "COUNT_AND_RECOUNT" },
	{ value: "DAB", name: "Layout/design", key: "LAYOUT_DESIGN" },
	{ value: "DAC", name: "Assortment allowance", key: "ASSORTMENT_ALLOWANCE" },
	{
		value: "DAD",
		name: "Driver assigned unloading",
		key: "DRIVER_ASSIGNED_UNLOADING",
	},
	{ value: "DAF", name: "Debtor bound", key: "DEBTOR_BOUND" },
	{ value: "DAG", name: "Dealer allowance", key: "DEALER_ALLOWANCE" },
	{
		value: "DAH",
		name: "Allowance transferable to the consumer",
		key: "ALLOWANCE_TRANSFERABLE_TO_THE_CONSUMER",
	},
	{ value: "DAI", name: "Growth of business", key: "GROWTH_OF_BUSINESS" },
	{
		value: "DAJ",
		name: "Introduction allowance",
		key: "INTRODUCTION_ALLOWANCE",
	},
	{ value: "DAK", name: "Multi-buy promotion", key: "MULTI_BUY_PROMOTION" },
	{ value: "DAL", name: "Partnership", key: "PARTNERSHIP" },
	{ value: "DAM", name: "Return handling", key: "RETURN_HANDLING" },
	{
		value: "DAN",
		name: "Minimum order not fulfilled charge",
		key: "MINIMUM_ORDER_NOT_FULFILLED_CHARGE",
	},
	{
		value: "DAO",
		name: "Point of sales threshold allowance",
		key: "POINT_OF_SALES_THRESHOLD_ALLOWANCE",
	},
	{ value: "DAP", name: "Wholesaling discount", key: "WHOLESALING_DISCOUNT" },
	{
		value: "DAQ",
		name: "Documentary credits transfer commission",
		key: "DOCUMENTARY_CREDITS_TRANSFER_COMMISSION",
	},
	{ value: "DL", name: "Delivery", key: "DELIVERY" },
	{ value: "EG", name: "Engraving", key: "ENGRAVING" },
	{ value: "EP", name: "Expediting", key: "EXPEDITING" },
	{
		value: "ER",
		name: "Exchange rate guarantee",
		key: "EXCHANGE_RATE_GUARANTEE",
	},
	{ value: "FAA", name: "Fabrication", key: "FABRICATION" },
	{ value: "FAB", name: "Freight equalization", key: "FREIGHT_EQUALIZATION" },
	{
		value: "FAC",
		name: "Freight extraordinary handling",
		key: "FREIGHT_EXTRAORDINARY_HANDLING",
	},
	{ value: "FC", name: "Freight service", key: "FREIGHT_SERVICE" },
	{ value: "FH", name: "Filling/handling", key: "FILLING_HANDLING" },
	{ value: "FI", name: "Financing", key: "FINANCING" },
	{ value: "GAA", name: "Grinding", key: "GRINDING" },
	{ value: "HAA", name: "Hose", key: "HOSE" },
	{ value: "HD", name: "Handling", key: "HANDLING" },
	{ value: "HH", name: "Hoisting and hauling", key: "HOISTING_AND_HAULING" },
	{ value: "IAA", name: "Installation", key: "INSTALLATION" },
	{
		value: "IAB",
		name: "Installation and warranty",
		key: "INSTALLATION_AND_WARRANTY",
	},
	{ value: "ID", name: "Inside delivery", key: "INSIDE_DELIVERY" },
	{ value: "IF", name: "Inspection", key: "INSPECTION" },
	{
		value: "IR",
		name: "Installation and training",
		key: "INSTALLATION_AND_TRAINING",
	},
	{ value: "IS", name: "Invoicing", key: "INVOICING" },
	{ value: "KO", name: "Koshering", key: "KOSHERING" },
	{ value: "L1", name: "Carrier count", key: "CARRIER_COUNT" },
	{ value: "LA", name: "Labelling", key: "LABELLING" },
	{ value: "LAA", name: "Labour", key: "LABOUR" },
	{ value: "LAB", name: "Repair and return", key: "REPAIR_AND_RETURN" },
	{ value: "LF", name: "Legalisation", key: "LEGALISATION" },
	{ value: "MAE", name: "Mounting", key: "MOUNTING" },
	{ value: "MI", name: "Mail invoice", key: "MAIL_INVOICE" },
	{
		value: "ML",
		name: "Mail invoice to each location",
		key: "MAIL_INVOICE_TO_EACH_LOCATION",
	},
	{
		value: "NAA",
		name: "Non-returnable containers",
		key: "NON_RETURNABLE_CONTAINERS",
	},
	{
		value: "OA",
		name: "Outside cable connectors",
		key: "OUTSIDE_CABLE_CONNECTORS",
	},
	{ value: "PA", name: "Invoice with shipment", key: "INVOICE_WITH_SHIPMENT" },
	{
		value: "PAA",
		name: "Phosphatizing (steel treatment)",
		key: "PHOSPHATIZING_STEEL_TREATMENT",
	},
	{ value: "PC", name: "Packing", key: "PACKING" },
	{ value: "PL", name: "Palletizing", key: "PALLETIZING" },
	{ value: "PRV", name: "Price variation", key: "PRICE_VARIATION" },
	{ value: "RAB", name: "Repacking", key: "REPACKING" },
	{ value: "RAC", name: "Repair", key: "REPAIR" },
	{ value: "RAD", name: "Returnable container", key: "RETURNABLE_CONTAINER" },
	{ value: "RAF", name: "Restocking", key: "RESTOCKING" },
	{ value: "RE", name: "Re-delivery", key: "RE_DELIVERY" },
	{ value: "RF", name: "Refurbishing", key: "REFURBISHING" },
	{ value: "RH", name: "Rail wagon hire", key: "RAIL_WAGON_HIRE" },
	{ value: "RV", name: "Loading", key: "LOADING" },
	{ value: "SA", name: "Salvaging", key: "SALVAGING" },
	{ value: "SAA", name: "Shipping and handling", key: "SHIPPING_AND_HANDLING" },
	{ value: "SAD", name: "Special packaging", key: "SPECIAL_PACKAGING" },
	{ value: "SAE", name: "Stamping", key: "STAMPING" },
	{ value: "SAI", name: "Consignee unload", key: "CONSIGNEE_UNLOAD" },
	{ value: "SG", name: "Shrink-wrap", key: "SHRINK_WRAP" },
	{ value: "SH", name: "Special handling", key: "SPECIAL_HANDLING" },
	{ value: "SM", name: "Special finish", key: "SPECIAL_FINISH" },
	{ value: "SU", name: "Set-up", key: "SET_UP" },
	{ value: "TAB", name: "Tank renting", key: "TANK_RENTING" },
	{ value: "TAC", name: "Testing", key: "TESTING" },
	{
		value: "TT",
		name: "Transportation - third party billing",
		key: "TRANSPORTATION_THIRD_PARTY_BILLING",
	},
	{
		value: "TV",
		name: "Transportation by vendor",
		key: "TRANSPORTATION_BY_VENDOR",
	},
	{ value: "V1", name: "Drop yard", key: "DROP_YARD" },
	{ value: "V2", name: "Drop dock", key: "DROP_DOCK" },
	{ value: "WH", name: "Warehousing", key: "WAREHOUSING" },
	{
		value: "XAA",
		name: "Combine all same day shipment",
		key: "COMBINE_ALL_SAME_DAY_SHIPMENT",
	},
	{ value: "YY", name: "Split pick-up", key: "SPLIT_PICK_UP" },
	{ value: "ZZZ", name: "Mutually defined", key: "MUTUALLY_DEFINED" },
] as const satisfies Codelist;

declare module "@node-zugferd/core" {
	interface ZugferdCodelistRegistry {
		charge: typeof charge;
	}
}
registerCodelist("charge", charge);

export default charge;
