import type { Codelist } from "@node-zugferd/core";
import { registerCodelist } from "@node-zugferd/data-types";

const icd = [
	{
		value: "0002",
		name: "System Information et Repertoire des Entreprise et des Etablissements: SIRENE ",
		key: "SYSTEM_INFORMATION_ET_REPERTOIRE_DES_ENTREPRISE_ET_DES_ETABLISSEMENTS_SIRENE",
	},
	{
		value: "0003",
		name: "Codification Numerique des Etablissments Financiers En Belgique ",
		key: "CODIFICATION_NUMERIQUE_DES_ETABLISSMENTS_FINANCIERS_EN_BELGIQUE",
	},
	{ value: "0004", name: "NBS/OSI NETWORK ", key: "NBS_OSI_NETWORK" },
	{
		value: "0005",
		name: "USA FED GOV OSI NETWORK ",
		key: "USA_FED_GOV_OSI_NETWORK",
	},
	{ value: "0006", name: "USA DOD OSI NETWORK ", key: "USA_DOD_OSI_NETWORK" },
	{ value: "0007", name: "Organisationsnummer ", key: "ORGANISATIONSNUMMER" },
	{ value: "0008", name: "LE NUMERO NATIONAL ", key: "LE_NUMERO_NATIONAL" },
	{ value: "0009", name: "SIRET-CODE ", key: "SIRET_CODE" },
	{
		value: "0010",
		name: "Organizational Identifiers for Structured Names under ISO 9541 Part 2 ",
		key: "ORGANIZATIONAL_IDENTIFIERS_FOR_STRUCTURED_NAMES_UNDER_ISO_9541_PART_2",
	},
	{
		value: "0011",
		name: "International Code Designator for the Identification of OSI-based, Amateur Radio Organizations, Network Objects and Application Services. ",
		key: "INTERNATIONAL_CODE_DESIGNATOR_FOR_THE_IDENTIFICATION_OF_OSI_BASED_AMATEUR_RADIO_ORGANIZATIONS_NETWORK_OBJECTS_AND_APPLICATION_SERVICES",
	},
	{
		value: "0012",
		name: "European Computer Manufacturers Association: ECMA ",
		key: "EUROPEAN_COMPUTER_MANUFACTURERS_ASSOCIATION_ECMA",
	},
	{
		value: "0013",
		name: "VSA FTP CODE (FTP = File Transfer Protocol) ",
		key: "VSA_FTP_CODE_FTP_FILE_TRANSFER_PROTOCOL",
	},
	{
		value: "0014",
		name: "NIST/OSI Implememts' Workshop ",
		key: "NIST_OSI_IMPLEMEMTS_WORKSHOP",
	},
	{
		value: "0015",
		name: "Electronic Data Interchange: EDI ",
		key: "ELECTRONIC_DATA_INTERCHANGE_EDI",
	},
	{
		value: "0016",
		name: "EWOS Object Identifiers ",
		key: "EWOS_OBJECT_IDENTIFIERS",
	},
	{ value: "0017", name: "COMMON LANGUAGE ", key: "COMMON_LANGUAGE" },
	{ value: "0018", name: "SNA/OSI Network ", key: "SNA_OSI_NETWORK" },
	{
		value: "0019",
		name: "Air Transport Industry Services Communications Network ",
		key: "AIR_TRANSPORT_INDUSTRY_SERVICES_COMMUNICATIONS_NETWORK",
	},
	{
		value: "0020",
		name: "European Laboratory for Particle Physics: CERN ",
		key: "EUROPEAN_LABORATORY_FOR_PARTICLE_PHYSICS_CERN",
	},
	{
		value: "0021",
		name: "SOCIETY FOR WORLDWIDE INTERBANK FINANCIAL, TELECOMMUNICATION S.W.I.F.T. ",
		key: "SOCIETY_FOR_WORLDWIDE_INTERBANK_FINANCIAL_TELECOMMUNICATION_S_W_I_F_T",
	},
	{
		value: "0022",
		name: "OSF Distributed Computing Object Identification ",
		key: "OSF_DISTRIBUTED_COMPUTING_OBJECT_IDENTIFICATION",
	},
	{
		value: "0023",
		name: "Nordic University and Research Network: NORDUnet ",
		key: "NORDIC_UNIVERSITY_AND_RESEARCH_NETWORK_NORD_UNET",
	},
	{
		value: "0024",
		name: "Digital Equipment Corporation: DEC ",
		key: "DIGITAL_EQUIPMENT_CORPORATION_DEC",
	},
	{
		value: "0025",
		name: "OSI ASIA-OCEANIA WORKSHOP ",
		key: "OSI_ASIA_OCEANIA_WORKSHOP",
	},
	{
		value: "0026",
		name: "NATO ISO 6523 ICDE coding scheme ",
		key: "NATO_ISO_6523_ICDE_CODING_SCHEME",
	},
	{
		value: "0027",
		name: "Aeronautical Telecommunications Network (ATN) ",
		key: "AERONAUTICAL_TELECOMMUNICATIONS_NETWORK_ATN",
	},
	{
		value: "0028",
		name: "International Standard ISO 6523 ",
		key: "INTERNATIONAL_STANDARD_ISO_6523",
	},
	{
		value: "0029",
		name: "The All-Union Classifier of Enterprises and Organisations ",
		key: "THE_ALL_UNION_CLASSIFIER_OF_ENTERPRISES_AND_ORGANISATIONS",
	},
	{ value: "0030", name: "AT&amp;T/OSI Network ", key: "AT_AMP_T_OSI_NETWORK" },
	{
		value: "0031",
		name: "EDI Partner Identification Code ",
		key: "EDI_PARTNER_IDENTIFICATION_CODE",
	},
	{ value: "0032", name: "Telecom Australia ", key: "TELECOM_AUSTRALIA" },
	{
		value: "0033",
		name: "S G W OSI Internetwork ",
		key: "S_G_W_OSI_INTERNETWORK",
	},
	{
		value: "0034",
		name: "Reuter Open Address Standard ",
		key: "REUTER_OPEN_ADDRESS_STANDARD",
	},
	{ value: "0035", name: "ISO 6523 - ICD ", key: "ISO_6523_ICD" },
	{
		value: "0036",
		name: "TeleTrust Object Identifiers ",
		key: "TELE_TRUST_OBJECT_IDENTIFIERS",
	},
	{ value: "0037", name: "LY-tunnus ", key: "LY_TUNNUS" },
	{
		value: "0038",
		name: "The Australian GOSIP Network ",
		key: "THE_AUSTRALIAN_GOSIP_NETWORK",
	},
	{
		value: "0039",
		name: "The OZ DOD OSI Network ",
		key: "THE_OZ_DOD_OSI_NETWORK",
	},
	{
		value: "0040",
		name: "Unilever Group Companies ",
		key: "UNILEVER_GROUP_COMPANIES",
	},
	{
		value: "0041",
		name: "Citicorp Global Information Network ",
		key: "CITICORP_GLOBAL_INFORMATION_NETWORK",
	},
	{
		value: "0042",
		name: "DBP Telekom Object Identifiers ",
		key: "DBP_TELEKOM_OBJECT_IDENTIFIERS",
	},
	{ value: "0043", name: "HydroNETT ", key: "HYDRO_NETT" },
	{
		value: "0044",
		name: "Thai Industrial Standards Institute (TISI) ",
		key: "THAI_INDUSTRIAL_STANDARDS_INSTITUTE_TISI",
	},
	{
		value: "0045",
		name: "ICI Company Identification System ",
		key: "ICI_COMPANY_IDENTIFICATION_SYSTEM",
	},
	{ value: "0046", name: "FUNLOC ", key: "FUNLOC" },
	{
		value: "0047",
		name: "BULL ODI/DSA/UNIX Network ",
		key: "BULL_ODI_DSA_UNIX_NETWORK",
	},
	{ value: "0048", name: "OSINZ ", key: "OSINZ" },
	{ value: "0049", name: "Auckland Area Health ", key: "AUCKLAND_AREA_HEALTH" },
	{ value: "0050", name: "Firmenich ", key: "FIRMENICH" },
	{ value: "0051", name: "AGFA-DIS ", key: "AGFA_DIS" },
	{
		value: "0052",
		name: "Society of Motion Picture and Television Engineers (SMPTE) ",
		key: "SOCIETY_OF_MOTION_PICTURE_AND_TELEVISION_ENGINEERS_SMPTE",
	},
	{
		value: "0053",
		name: "Migros_Network M_NETOPZ ",
		key: "MIGROS_NETWORK_M_NETOPZ",
	},
	{ value: "0054", name: "ISO6523 - ICDPCR ", key: "ISO6523_ICDPCR" },
	{ value: "0055", name: "Energy Net ", key: "ENERGY_NET" },
	{
		value: "0056",
		name: "Nokia Object Identifiers (NOI) ",
		key: "NOKIA_OBJECT_IDENTIFIERS_NOI",
	},
	{ value: "0057", name: "Saint Gobain ", key: "SAINT_GOBAIN" },
	{
		value: "0058",
		name: "Siemens Corporate Network ",
		key: "SIEMENS_CORPORATE_NETWORK",
	},
	{ value: "0059", name: "DANZNET ", key: "DANZNET" },
	{
		value: "0060",
		name: "Data Universal Numbering System (D-U-N-S Number) ",
		key: "DATA_UNIVERSAL_NUMBERING_SYSTEM_D_U_N_S_NUMBER",
	},
	{ value: "0061", name: "SOFFEX OSI ", key: "SOFFEX_OSI" },
	{ value: "0062", name: "KPN OVN ", key: "KPN_OVN" },
	{ value: "0063", name: "ascomOSINet ", key: "ASCOM_OSI_NET" },
	{
		value: "0064",
		name: "UTC: Uniforme Transport Code ",
		key: "UTC_UNIFORME_TRANSPORT_CODE",
	},
	{ value: "0065", name: "SOLVAY OSI CODING ", key: "SOLVAY_OSI_CODING" },
	{
		value: "0066",
		name: "Roche Corporate Network ",
		key: "ROCHE_CORPORATE_NETWORK",
	},
	{ value: "0067", name: "ZellwegerOSINet ", key: "ZELLWEGER_OSI_NET" },
	{
		value: "0068",
		name: "Intel Corporation OSI ",
		key: "INTEL_CORPORATION_OSI",
	},
	{
		value: "0069",
		name: "SITA Object Identifier Tree ",
		key: "SITA_OBJECT_IDENTIFIER_TREE",
	},
	{
		value: "0070",
		name: "DaimlerChrysler Corporate Network ",
		key: "DAIMLER_CHRYSLER_CORPORATE_NETWORK",
	},
	{ value: "0071", name: "LEGO /OSI NETWORK ", key: "LEGO_OSI_NETWORK" },
	{ value: "0072", name: "NAVISTAR/OSI Network ", key: "NAVISTAR_OSI_NETWORK" },
	{
		value: "0073",
		name: "ICD Formatted ATM address ",
		key: "ICD_FORMATTED_ATM_ADDRESS",
	},
	{ value: "0074", name: "ARINC ", key: "ARINC" },
	{
		value: "0075",
		name: "Alcanet/Alcatel-Alsthom Corporate Network ",
		key: "ALCANET_ALCATEL_ALSTHOM_CORPORATE_NETWORK",
	},
	{
		value: "0076",
		name: "Sistema Italiano di Identificazione di ogetti gestito da UNINFO ",
		key: "SISTEMA_ITALIANO_DI_IDENTIFICAZIONE_DI_OGETTI_GESTITO_DA_UNINFO",
	},
	{
		value: "0077",
		name: "Sistema Italiano di Indirizzamento di Reti OSI Gestito da UNINFO ",
		key: "SISTEMA_ITALIANO_DI_INDIRIZZAMENTO_DI_RETI_OSI_GESTITO_DA_UNINFO",
	},
	{
		value: "0078",
		name: "Mitel terminal or switching equipment ",
		key: "MITEL_TERMINAL_OR_SWITCHING_EQUIPMENT",
	},
	{ value: "0079", name: "ATM Forum ", key: "ATM_FORUM" },
	{
		value: "0080",
		name: "UK National Health Service Scheme, (EDIRA compliant) ",
		key: "UK_NATIONAL_HEALTH_SERVICE_SCHEME_EDIRA_COMPLIANT",
	},
	{ value: "0081", name: "International NSAP ", key: "INTERNATIONAL_NSAP" },
	{
		value: "0082",
		name: "Norwegian Telecommunications Authority's, NTA'S, EDI, identifier scheme (EDIRA compliant) ",
		key: "NORWEGIAN_TELECOMMUNICATIONS_AUTHORITY_S_NTA_S_EDI_IDENTIFIER_SCHEME_EDIRA_COMPLIANT",
	},
	{
		value: "0083",
		name: "Advanced Telecommunications Modules Limited, Corporate Network ",
		key: "ADVANCED_TELECOMMUNICATIONS_MODULES_LIMITED_CORPORATE_NETWORK",
	},
	{
		value: "0084",
		name: "Athens Chamber of Commerce &amp; Industry Scheme (EDIRA compliant) ",
		key: "ATHENS_CHAMBER_OF_COMMERCE_AMP_INDUSTRY_SCHEME_EDIRA_COMPLIANT",
	},
	{
		value: "0085",
		name: "Swiss Chambers of Commerce Scheme (EDIRA) compliant ",
		key: "SWISS_CHAMBERS_OF_COMMERCE_SCHEME_EDIRA_COMPLIANT",
	},
	{
		value: "0086",
		name: "United States Council for International Business (USCIB) Scheme, (EDIRA compliant) ",
		key: "UNITED_STATES_COUNCIL_FOR_INTERNATIONAL_BUSINESS_USCIB_SCHEME_EDIRA_COMPLIANT",
	},
	{
		value: "0087",
		name: "National Federation of Chambers of Commerce &amp; Industry of Belgium, Scheme (EDIRA compliant) ",
		key: "NATIONAL_FEDERATION_OF_CHAMBERS_OF_COMMERCE_AMP_INDUSTRY_OF_BELGIUM_SCHEME_EDIRA_COMPLIANT",
	},
	{ value: "0088", name: "EAN Location Code ", key: "EAN_LOCATION_CODE" },
	{
		value: "0089",
		name: "The Association of British Chambers of Commerce Ltd. Scheme, (EDIRA compliant) ",
		key: "THE_ASSOCIATION_OF_BRITISH_CHAMBERS_OF_COMMERCE_LTD_SCHEME_EDIRA_COMPLIANT",
	},
	{
		value: "0090",
		name: "Internet IP addressing - ISO 6523 ICD encoding ",
		key: "INTERNET_IP_ADDRESSING_ISO_6523_ICD_ENCODING",
	},
	{
		value: "0091",
		name: "Cisco Sysytems / OSI Network ",
		key: "CISCO_SYSYTEMS_OSI_NETWORK",
	},
	{
		value: "0093",
		name: "Revenue Canada Business Number Registration (EDIRA compliant) ",
		key: "REVENUE_CANADA_BUSINESS_NUMBER_REGISTRATION_EDIRA_COMPLIANT",
	},
	{
		value: "0094",
		name: "DEUTSCHER INDUSTRIE- UND HANDELSTAG (DIHT) Scheme (EDIRA compliant) ",
		key: "DEUTSCHER_INDUSTRIE_UND_HANDELSTAG_DIHT_SCHEME_EDIRA_COMPLIANT",
	},
	{
		value: "0095",
		name: "Hewlett - Packard Company Internal AM Network ",
		key: "HEWLETT_PACKARD_COMPANY_INTERNAL_AM_NETWORK",
	},
	{
		value: "0096",
		name: "DANISH CHAMBER OF COMMERCE Scheme (EDIRA compliant) ",
		key: "DANISH_CHAMBER_OF_COMMERCE_SCHEME_EDIRA_COMPLIANT",
	},
	{
		value: "0097",
		name: "FTI - Ediforum Italia, (EDIRA compliant) ",
		key: "FTI_EDIFORUM_ITALIA_EDIRA_COMPLIANT",
	},
	{
		value: "0098",
		name: "CHAMBER OF COMMERCE TEL AVIV-JAFFA Scheme (EDIRA compliant) ",
		key: "CHAMBER_OF_COMMERCE_TEL_AVIV_JAFFA_SCHEME_EDIRA_COMPLIANT",
	},
	{
		value: "0099",
		name: "Siemens Supervisory Systems Network ",
		key: "SIEMENS_SUPERVISORY_SYSTEMS_NETWORK",
	},
	{ value: "0100", name: "PNG_ICD Scheme ", key: "PNG_ICD_SCHEME" },
	{
		value: "0101",
		name: "South African Code Allocation ",
		key: "SOUTH_AFRICAN_CODE_ALLOCATION",
	},
	{ value: "0102", name: "HEAG ", key: "HEAG" },
	{
		value: "0104",
		name: "BT - ICD Coding System ",
		key: "BT_ICD_CODING_SYSTEM",
	},
	{
		value: "0105",
		name: "Portuguese Chamber of Commerce and Industry Scheme (EDIRA compliant) ",
		key: "PORTUGUESE_CHAMBER_OF_COMMERCE_AND_INDUSTRY_SCHEME_EDIRA_COMPLIANT",
	},
	{
		value: "0106",
		name: "Vereniging van Kamers van Koophandel en Fabrieken in Nederland (Association of Chambers of Commerce and Industry in the Netherlands), Scheme (EDIRA compliant) ",
		key: "VERENIGING_VAN_KAMERS_VAN_KOOPHANDEL_EN_FABRIEKEN_IN_NEDERLAND_ASSOCIATION_OF_CHAMBERS_OF_COMMERCE_AND_INDUSTRY_IN_THE_NETHERLANDS_SCHEME_EDIRA_COMPLIANT",
	},
	{
		value: "0107",
		name: "Association of Swedish Chambers of Commerce and Industry Scheme (EDIRA compliant) ",
		key: "ASSOCIATION_OF_SWEDISH_CHAMBERS_OF_COMMERCE_AND_INDUSTRY_SCHEME_EDIRA_COMPLIANT",
	},
	{
		value: "0108",
		name: "Australian Chambers of Commerce and Industry Scheme (EDIRA compliant) ",
		key: "AUSTRALIAN_CHAMBERS_OF_COMMERCE_AND_INDUSTRY_SCHEME_EDIRA_COMPLIANT",
	},
	{
		value: "0109",
		name: "BellSouth ICD AESA (ATM End System Address) ",
		key: "BELL_SOUTH_ICD_AESA_ATM_END_SYSTEM_ADDRESS",
	},
	{ value: "0110", name: "Bell Atlantic ", key: "BELL_ATLANTIC" },
	{ value: "0111", name: "Object Identifiers ", key: "OBJECT_IDENTIFIERS" },
	{
		value: "0112",
		name: "ISO register for Standards producing Organizations ",
		key: "ISO_REGISTER_FOR_STANDARDS_PRODUCING_ORGANIZATIONS",
	},
	{ value: "0113", name: "OriginNet ", key: "ORIGIN_NET" },
	{
		value: "0114",
		name: "Check Point Software Technologies ",
		key: "CHECK_POINT_SOFTWARE_TECHNOLOGIES",
	},
	{
		value: "0115",
		name: "Pacific Bell Data Communications Network ",
		key: "PACIFIC_BELL_DATA_COMMUNICATIONS_NETWORK",
	},
	{
		value: "0116",
		name: "PSS Object Identifiers ",
		key: "PSS_OBJECT_IDENTIFIERS",
	},
	{
		value: "0117",
		name: "STENTOR-ICD CODING SYSTEM ",
		key: "STENTOR_ICD_CODING_SYSTEM",
	},
	{ value: "0118", name: "ATM-Network ZN'96 ", key: "ATM_NETWORK_ZN_96" },
	{ value: "0119", name: "MCI / OSI Network ", key: "MCI_OSI_NETWORK" },
	{ value: "0120", name: "Advantis ", key: "ADVANTIS" },
	{
		value: "0121",
		name: "Affable Software Data Interchange Codes ",
		key: "AFFABLE_SOFTWARE_DATA_INTERCHANGE_CODES",
	},
	{ value: "0122", name: "BB-DATA GmbH ", key: "BB_DATA_GMB_H" },
	{
		value: "0123",
		name: "BASF Company ATM-Network ",
		key: "BASF_COMPANY_ATM_NETWORK",
	},
	{
		value: "0124",
		name: "IOTA Identifiers for Organizations for Telecommunications Addressing using the ICD system format defined in ISO/IEC 8348 ",
		key: "IOTA_IDENTIFIERS_FOR_ORGANIZATIONS_FOR_TELECOMMUNICATIONS_ADDRESSING_USING_THE_ICD_SYSTEM_FORMAT_DEFINED_IN_ISO_IEC_8348",
	},
	{
		value: "0125",
		name: "Henkel Corporate Network (H-Net) ",
		key: "HENKEL_CORPORATE_NETWORK_H_NET",
	},
	{ value: "0126", name: "GTE/OSI Network ", key: "GTE_OSI_NETWORK" },
	{
		value: "0127",
		name: "Dresdner Bank Corporate Network ",
		key: "DRESDNER_BANK_CORPORATE_NETWORK",
	},
	{
		value: "0128",
		name: "BCNR (Swiss Clearing Bank Number) ",
		key: "BCNR_SWISS_CLEARING_BANK_NUMBER",
	},
	{
		value: "0129",
		name: "BPI (Swiss Business Partner Identification) code ",
		key: "BPI_SWISS_BUSINESS_PARTNER_IDENTIFICATION_CODE",
	},
	{
		value: "0130",
		name: "Directorates of the European Commission ",
		key: "DIRECTORATES_OF_THE_EUROPEAN_COMMISSION",
	},
	{
		value: "0131",
		name: "Code for the Identification of National Organizations ",
		key: "CODE_FOR_THE_IDENTIFICATION_OF_NATIONAL_ORGANIZATIONS",
	},
	{
		value: "0132",
		name: "Certicom Object Identifiers ",
		key: "CERTICOM_OBJECT_IDENTIFIERS",
	},
	{ value: "0133", name: "TC68 OID ", key: "TC68_OID" },
	{
		value: "0134",
		name: "Infonet Services Corporation ",
		key: "INFONET_SERVICES_CORPORATION",
	},
	{
		value: "0135",
		name: "SIA Object Identifiers ",
		key: "SIA_OBJECT_IDENTIFIERS",
	},
	{
		value: "0136",
		name: "Cable &amp; Wireless Global ATM End-System Address Plan ",
		key: "CABLE_AMP_WIRELESS_GLOBAL_ATM_END_SYSTEM_ADDRESS_PLAN",
	},
	{ value: "0137", name: "Global AESA scheme ", key: "GLOBAL_AESA_SCHEME" },
	{
		value: "0138",
		name: "France Telecom ATM End System Address Plan ",
		key: "FRANCE_TELECOM_ATM_END_SYSTEM_ADDRESS_PLAN",
	},
	{
		value: "0139",
		name: "Savvis Communications AESA:. ",
		key: "SAVVIS_COMMUNICATIONS_AESA",
	},
	{
		value: "0140",
		name: "Toshiba Organizations, Partners, And Suppliers' (TOPAS) Code ",
		key: "TOSHIBA_ORGANIZATIONS_PARTNERS_AND_SUPPLIERS_TOPAS_CODE",
	},
	{
		value: "0141",
		name: "NATO Commercial and Government Entity system ",
		key: "NATO_COMMERCIAL_AND_GOVERNMENT_ENTITY_SYSTEM",
	},
	{
		value: "0142",
		name: "SECETI Object Identifiers ",
		key: "SECETI_OBJECT_IDENTIFIERS",
	},
	{ value: "0143", name: "EINESTEINet AG ", key: "EINESTEI_NET_AG" },
	{
		value: "0144",
		name: "DoDAAC (Department of Defense Activity Address Code) ",
		key: "DO_DAAC_DEPARTMENT_OF_DEFENSE_ACTIVITY_ADDRESS_CODE",
	},
	{
		value: "0145",
		name: "DGCP (Direction Générale de la Comptabilité Publique)administrative accounting identification scheme ",
		key: "DGCP_DIRECTION_GE_NE_RALE_DE_LA_COMPTABILITE_PUBLIQUE_ADMINISTRATIVE_ACCOUNTING_IDENTIFICATION_SCHEME",
	},
	{
		value: "0146",
		name: "DGI (Direction Générale des Impots) code ",
		key: "DGI_DIRECTION_GE_NE_RALE_DES_IMPOTS_CODE",
	},
	{
		value: "0147",
		name: "Standard Company Code ",
		key: "STANDARD_COMPANY_CODE",
	},
	{
		value: "0148",
		name: "ITU (International Telecommunications Union)Data Network Identification Codes (DNIC) ",
		key: "ITU_INTERNATIONAL_TELECOMMUNICATIONS_UNION_DATA_NETWORK_IDENTIFICATION_CODES_DNIC",
	},
	{
		value: "0149",
		name: "Global Business Identifier ",
		key: "GLOBAL_BUSINESS_IDENTIFIER",
	},
	{
		value: "0150",
		name: "Madge Networks Ltd- ICD ATM Addressing Scheme ",
		key: "MADGE_NETWORKS_LTD_ICD_ATM_ADDRESSING_SCHEME",
	},
	{
		value: "0151",
		name: "Australian Business Number (ABN) Scheme ",
		key: "AUSTRALIAN_BUSINESS_NUMBER_ABN_SCHEME",
	},
	{
		value: "0152",
		name: "Edira Scheme Identifier Code ",
		key: "EDIRA_SCHEME_IDENTIFIER_CODE",
	},
	{
		value: "0153",
		name: "Concert Global Network Services ICD AESA ",
		key: "CONCERT_GLOBAL_NETWORK_SERVICES_ICD_AESA",
	},
	{
		value: "0154",
		name: "Identification number of economic subjects: (ICO) ",
		key: "IDENTIFICATION_NUMBER_OF_ECONOMIC_SUBJECTS_ICO",
	},
	{
		value: "0155",
		name: "Global Crossing AESA (ATM End System Address) ",
		key: "GLOBAL_CROSSING_AESA_ATM_END_SYSTEM_ADDRESS",
	},
	{ value: "0156", name: "AUNA ", key: "AUNA" },
	{
		value: "0157",
		name: "ATM interconnection with the Dutch KPN Telecom ",
		key: "ATM_INTERCONNECTION_WITH_THE_DUTCH_KPN_TELECOM",
	},
	{
		value: "0158",
		name: "Identification number of economic subject (ICO) Act on State Statistics of 29 November 2'001, § 27 ",
		key: "IDENTIFICATION_NUMBER_OF_ECONOMIC_SUBJECT_ICO_ACT_ON_STATE_STATISTICS_OF_29_NOVEMBER_2_001_27",
	},
	{
		value: "0159",
		name: "ACTALIS Object Identifiers ",
		key: "ACTALIS_OBJECT_IDENTIFIERS",
	},
	{
		value: "0160",
		name: "GTIN - Global Trade Item Number ",
		key: "GTIN_GLOBAL_TRADE_ITEM_NUMBER",
	},
	{
		value: "0161",
		name: "ECCMA Open Technical Directory ",
		key: "ECCMA_OPEN_TECHNICAL_DIRECTORY",
	},
	{
		value: "0162",
		name: "CEN/ISSS Object Identifier Scheme ",
		key: "CEN_ISSS_OBJECT_IDENTIFIER_SCHEME",
	},
	{
		value: "0163",
		name: "US-EPA Facility Identifier ",
		key: "US_EPA_FACILITY_IDENTIFIER",
	},
	{ value: "0164", name: "TELUS Corporation ", key: "TELUS_CORPORATION" },
	{
		value: "0165",
		name: "FIEIE Object identifiers ",
		key: "FIEIE_OBJECT_IDENTIFIERS",
	},
	{
		value: "0166",
		name: "Swissguide Identifier Scheme ",
		key: "SWISSGUIDE_IDENTIFIER_SCHEME",
	},
	{
		value: "0167",
		name: "Priority Telecom ATM End System Address Plan ",
		key: "PRIORITY_TELECOM_ATM_END_SYSTEM_ADDRESS_PLAN",
	},
	{
		value: "0168",
		name: "Vodafone Ireland OSI Addressing ",
		key: "VODAFONE_IRELAND_OSI_ADDRESSING",
	},
	{
		value: "0169",
		name: "Swiss Federal Business Identification Number. Central Business names Index (zefix) Identification Number ",
		key: "SWISS_FEDERAL_BUSINESS_IDENTIFICATION_NUMBER_CENTRAL_BUSINESS_NAMES_INDEX_ZEFIX_IDENTIFICATION_NUMBER",
	},
	{ value: "0170", name: "Teikoku Company Code ", key: "TEIKOKU_COMPANY_CODE" },
	{
		value: "0171",
		name: "Luxembourg CP &amp; CPS (Certification Policy and Certification Practice Statement) Index ",
		key: "LUXEMBOURG_CP_AMP_CPS_CERTIFICATION_POLICY_AND_CERTIFICATION_PRACTICE_STATEMENT_INDEX",
	},
	{
		value: "0172",
		name: "Project Group “Lists of Properties” (PROLIST®) ",
		key: "PROJECT_GROUP_LISTS_OF_PROPERTIES_PROLIST",
	},
	{ value: "0173", name: "eCI@ss ", key: "E_CI_SS" },
	{ value: "0174", name: "StepNexus ", key: "STEP_NEXUS" },
	{ value: "0175", name: "Siemens AG ", key: "SIEMENS_AG" },
	{ value: "0176", name: "Paradine GmbH ", key: "PARADINE_GMB_H" },
	{
		value: "0177",
		name: "Odette International Limited ",
		key: "ODETTE_INTERNATIONAL_LIMITED",
	},
	{ value: "0178", name: "Route1 MobiNET ", key: "ROUTE1_MOBI_NET" },
	{
		value: "0179",
		name: "Penango Object Identifiers ",
		key: "PENANGO_OBJECT_IDENTIFIERS",
	},
	{
		value: "0180",
		name: "Lithuanian military PKI ",
		key: "LITHUANIAN_MILITARY_PKI",
	},
	{
		value: "0183",
		name: "Numéro d'identification suisse des enterprises (IDE), Swiss Unique Business Identification Number (UIDB) ",
		key: "NUME_RO_D_IDENTIFICATION_SUISSE_DES_ENTERPRISES_IDE_SWISS_UNIQUE_BUSINESS_IDENTIFICATION_NUMBER_UIDB",
	},
	{ value: "0184", name: "DIGSTORG ", key: "DIGSTORG" },
	{ value: "0185", name: "Perceval Object Code ", key: "PERCEVAL_OBJECT_CODE" },
	{
		value: "0186",
		name: "TrustPoint Object Identifiers ",
		key: "TRUST_POINT_OBJECT_IDENTIFIERS",
	},
	{
		value: "0187",
		name: "Amazon Unique Identification Scheme ",
		key: "AMAZON_UNIQUE_IDENTIFICATION_SCHEME",
	},
	{
		value: "0188",
		name: "Corporate Number of The Social Security and Tax Number System ",
		key: "CORPORATE_NUMBER_OF_THE_SOCIAL_SECURITY_AND_TAX_NUMBER_SYSTEM",
	},
	{
		value: "0189",
		name: "European Business Identifier (EBID) ",
		key: "EUROPEAN_BUSINESS_IDENTIFIER_EBID",
	},
	{
		value: "0190",
		name: "Organisatie Indentificatie Nummer (OIN) ",
		key: "ORGANISATIE_INDENTIFICATIE_NUMMER_OIN",
	},
	{
		value: "0191",
		name: "Company Code (Estonia) ",
		key: "COMPANY_CODE_ESTONIA",
	},
	{ value: "0192", name: "Organisasjonsnummer ", key: "ORGANISASJONSNUMMER" },
	{
		value: "0193",
		name: "UBL.BE Party Identifier ",
		key: "UBL_BE_PARTY_IDENTIFIER",
	},
	{
		value: "0194",
		name: "KOIOS Open Technical Dictionary",
		key: "KOIOS_OPEN_TECHNICAL_DICTIONARY",
	},
	{
		value: "0195",
		name: "Singapore Nationwide E-lnvoice Framework ",
		key: "SINGAPORE_NATIONWIDE_E_LNVOICE_FRAMEWORK",
	},
	{
		value: "0196",
		name: "Icelandic identifier - Íslensk kennitala ",
		key: "ICELANDIC_IDENTIFIER_I_SLENSK_KENNITALA",
	},
	{ value: "0197", name: "APPLiA Pl Standard", key: "APP_LI_A_PL_STANDARD" },
	{ value: "0198", name: "ERSTORG", key: "ERSTORG" },
	{
		value: "0199",
		name: "Legal Entity Identifier (LEI)",
		key: "LEGAL_ENTITY_IDENTIFIER_LEI",
	},
	{
		value: "0200",
		name: "Legal entity code (Lithuania)",
		key: "LEGAL_ENTITY_CODE_LITHUANIA",
	},
	{
		value: "0201",
		name: "Codice Univoco Unità Organizzativa iPA",
		key: "CODICE_UNIVOCO_UNITA_ORGANIZZATIVA_I_PA",
	},
	{
		value: "0202",
		name: "Indirizzo di Posta Elettronica Certificata",
		key: "INDIRIZZO_DI_POSTA_ELETTRONICA_CERTIFICATA",
	},
	{
		value: "0203",
		name: "eDelivery Network Participant identifier",
		key: "E_DELIVERY_NETWORK_PARTICIPANT_IDENTIFIER",
	},
	{ value: "0204", name: "Leitweg-ID", key: "LEITWEG_ID" },
	{ value: "0205", name: "CODDEST", key: "CODDEST" },
	{
		value: "0206",
		name: "Registre du Commerce et de l’Industrie : RCI",
		key: "REGISTRE_DU_COMMERCE_ET_DE_L_INDUSTRIE_RCI",
	},
	{
		value: "0207",
		name: "PiLog Ontology Codification Identifier (POCI)",
		key: "PI_LOG_ONTOLOGY_CODIFICATION_IDENTIFIER_POCI",
	},
	{
		value: "0208",
		name: "Numero d'entreprise / ondernemingsnummer / Unternehmensnummer",
		key: "NUMERO_D_ENTREPRISE_ONDERNEMINGSNUMMER_UNTERNEHMENSNUMMER",
	},
	{
		value: "0209",
		name: "GS1 identification keys",
		key: "GS1_IDENTIFICATION_KEYS",
	},
	{ value: "0210", name: "CODICE FISCALE", key: "CODICE_FISCALE" },
	{ value: "0211", name: "PARTITA IVA", key: "PARTITA_IVA" },
	{
		value: "0212",
		name: "Finnish Organization Identifier",
		key: "FINNISH_ORGANIZATION_IDENTIFIER",
	},
	{
		value: "0213",
		name: "Finnish Organization Value Add Tax Identifier",
		key: "FINNISH_ORGANIZATION_VALUE_ADD_TAX_IDENTIFIER",
	},
	{
		value: "0214",
		name: "Tradeplace TradePI Standard",
		key: "TRADEPLACE_TRADE_PI_STANDARD",
	},
	{ value: "0215", name: "Net service ID", key: "NET_SERVICE_ID" },
	{ value: "0216", name: "OVTcode", key: "OV_TCODE" },
	{
		value: "0217",
		name: "The Netherlands Chamber of Commerce and Industry establishment number",
		key: "THE_NETHERLANDS_CHAMBER_OF_COMMERCE_AND_INDUSTRY_ESTABLISHMENT_NUMBER",
	},
	{
		value: "0218",
		name: "Unified registration number (Latvia)",
		key: "UNIFIED_REGISTRATION_NUMBER_LATVIA",
	},
	{
		value: "0219",
		name: "Taxpayer registration code (Latvia)",
		key: "TAXPAYER_REGISTRATION_CODE_LATVIA",
	},
	{
		value: "0220",
		name: "The Register of Natural Persons (Latvia)",
		key: "THE_REGISTER_OF_NATURAL_PERSONS_LATVIA",
	},
	{
		value: "0221",
		name: "The registered number of the qualified invoice issuer",
		key: "THE_REGISTERED_NUMBER_OF_THE_QUALIFIED_INVOICE_ISSUER",
	},
	{
		value: "0222",
		name: "Metadata Registry Support",
		key: "METADATA_REGISTRY_SUPPORT",
	},
	{ value: "0223", name: "EU based company", key: "EU_BASED_COMPANY" },
	{ value: "0224", name: "FTCTC CODE ROUTAGE", key: "FTCTC_CODE_ROUTAGE" },
	{
		value: "0225",
		name: "FRCTC ELECTRONIC ADDRESS",
		key: "FRCTC_ELECTRONIC_ADDRESS",
	},
	{ value: "0226", name: "FRCTC Particulier", key: "FRCTC_PARTICULIER" },
	{
		value: "0227",
		name: "NON - EU based company",
		key: "NON_EU_BASED_COMPANY",
	},
	{
		value: "0228",
		name: "Répertoire des Entreprises et des Etablissements (RIDET)",
		key: "RE_PERTOIRE_DES_ENTREPRISES_ET_DES_ETABLISSEMENTS_RIDET",
	},
	{
		value: "0229",
		name: "T.A.H.I.T.I (traitement automatique hiérarchisé des institutions de Tahiti et des îles)",
		key: "T_A_H_I_T_I_TRAITEMENT_AUTOMATIQUE_HIE_RARCHISE_DES_INSTITUTIONS_DE_TAHITI_ET_DES_I_LES",
	},
	{
		value: "0230",
		name: "National e-Invoicing Framework",
		key: "NATIONAL_E_INVOICING_FRAMEWORK",
	},
	{
		value: "0231",
		name: "Single taxable company (France)",
		key: "SINGLE_TAXABLE_COMPANY_FRANCE",
	},
	{ value: "0232", name: "NOBB product number", key: "NOBB_PRODUCT_NUMBER" },
	{
		value: "0233",
		name: "Description not known",
		key: "DESCRIPTION_NOT_KNOWN",
	},
	{ value: "0234", name: "Toimitusosoite ID", key: "TOIMITUSOSOITE_ID" },
	{
		value: "0235",
		name: "UAE Tax Identification Number (TIN)",
		key: "UAE_TAX_IDENTIFICATION_NUMBER_TIN",
	},
	{
		value: "0236",
		name: "Description not known",
		key: "DESCRIPTION_NOT_KNOWN",
	},
	{
		value: "0237",
		name: "CPR (Danish person civil registration number)",
		key: "CPR_DANISH_PERSON_CIVIL_REGISTRATION_NUMBER",
	},
	{
		value: "0238",
		name: "Plateforme.s agréée.s à la facturation électronique (PPF/PDP)",
		key: "PLATEFORME_S_AGRE_E_E_S_A_LA_FACTURATION_E_LECTRONIQUE_PPF_PDP",
	},
	{ value: "0239", name: "EAEU", key: "EAEU" },
	{
		value: "0240",
		name: "Register of legal persons (in French : Répertoire des personnes morales)",
		key: "REGISTER_OF_LEGAL_PERSONS_IN_FRENCH_RE_PERTOIRE_DES_PERSONNES_MORALES",
	},
] as const satisfies Codelist;

declare module "@node-zugferd/core" {
	interface ZugferdCodelistRegistry {
		icd: typeof icd;
	}
}
registerCodelist("icd", icd);

export default icd;
