/**
 * Automatically generated by {@link Script} on Mon, 04 Aug 2025 12:40:40 GMT
 *
 * @see {@link https://github.com/jslno/node-zugferd/blob/main/packages/node-zugferd/scripts/codelists/filename/output.xml|Source}
 */

import type Script from "../../scripts/codelists/filename/index.ts";

export type FilenameDefinition = {
	value: string;
	definition: string;
	usage?: string | undefined;
};
export type FilenameCode = (typeof FILENAME)[number]["value"];

export const PUBLISHED = "Factur-X" as const;

/**
 * Automatically generated by {@link Script} on Mon, 04 Aug 2025 12:40:40 GMT
 *
 * @see {@link https://github.com/jslno/node-zugferd/blob/main/packages/node-zugferd/scripts/codelists/filename/output.xml|Source}
 */
export const FILENAME = [
	{
		value: "factur-x.xml",
		definition:
			"The hybrid document contains a Factur-X \u002F ZUGFeRD XML-file",
		usage: "The ConformanceLevel MUST not be XRECHNUNG",
	},
	{
		value: "xrechnung.xml",
		definition: "The hybrid document contains a XRechnung XML file",
		usage: "The ConformanceLevel MUST be XRECHNUNG",
	},
	{
		value: "order-x.xml",
		definition: "The hybrid document contains an Order-X XML file",
		usage: undefined,
	},
] as const satisfies FilenameDefinition[];

export const filenameCode = FILENAME.map(({ value }) => value);
