/**
 * Automatically generated by {@link Script}
 *
 * @see {@link https://github.com/jslno/node-zugferd/blob/main/packages/node-zugferd/scripts/codelists/hybrid-conformance/output.xml|Source}
 */

import type Script from "../../scripts/codelists/hybrid-conformance/index.ts";

export type HybridConformanceDefinition = {
	value: string;
	definition: string;
	usage: string;
	comment?: string | undefined;
};
export type HybridConformanceCode =
	(typeof HYBRID_CONFORMANCE)[number]["value"];

export const PUBLISHED = "Factur-X" as const;

/**
 * Automatically generated by {@link Script}
 *
 * @see {@link https://github.com/jslno/node-zugferd/blob/main/packages/node-zugferd/scripts/codelists/hybrid-conformance/output.xml|Source}
 */
export const HYBRID_CONFORMANCE = [
	{
		value: "MINIMUM",
		definition: "The included document uses a MINIMUM profile",
		usage: "Only applicable in Factur-X\u002FZUGFeRD",
		comment: "Not allowed in Germany from 2025-01-01",
	},
	{
		value: "BASIC WL",
		definition: "The included document uses a Basic Without Lines profile",
		usage: "Only applicable in Factur-X\u002FZUGFeRD",
		comment: "Not allowed in Germany from 2025-01-01",
	},
	{
		value: "BASIC",
		definition: "The included document uses a Basic profile",
		usage:
			"Applicable in Factur-X\u002FZUGFeRD and Order-X. For Factur-X\u002FZUGFeRD the BASIC profile is compliant to the EN16931.",
		comment: undefined,
	},
	{
		value: "COMFORT",
		definition: "The included document uses a Comfort profile",
		usage: "Only applicable in Order-X",
		comment: undefined,
	},
	{
		value: "EN 16931",
		definition: "The included document uses a EN 16931 profile",
		usage:
			"Only applicable in Factur-X\u002FZUGFeRD. This profile is compliant to the EN16931.",
		comment: undefined,
	},
	{
		value: "EXTENDED",
		definition: "The included document uses a Comfort profile",
		usage:
			"Applicable in Factur-X\u002FZUGFeRD and Order-X. For Factur-X\u002FZUGFeRD the EXTENDED profile is compliant to and conformant extension of the EN16931.",
		comment: undefined,
	},
	{
		value: "XRECHNUNG",
		definition: "The included document uses an XRECHNUNG profile",
		usage: "Only applicable in Factur-X\u002FZUGFeRD.",
		comment: "Not applicable in France",
	},
] as const satisfies HybridConformanceDefinition[];

export const hybridConformanceCode = HYBRID_CONFORMANCE.map(
	({ value }) => value,
);
