/**
 * Automatically generated by {@link Script} on Mon, 04 Aug 2025 12:40:40 GMT
 *
 * @see {@link https://github.com/jslno/node-zugferd/blob/main/packages/node-zugferd/scripts/codelists/incoterms/output.xml|Source}
 */

import type Script from "../../scripts/codelists/incoterms/index.ts";
import { createEnum } from "./";

export type IncotermsDefinition = {
	key: string;
	name: string;
	value: string;
};
export type IncotermsCode = (typeof INCOTERMS)[number]["value"];

export const PUBLISHED = "Factur-X" as const;

/**
 * Automatically generated by {@link Script} on Mon, 04 Aug 2025 12:40:40 GMT
 *
 * @see {@link https://github.com/jslno/node-zugferd/blob/main/packages/node-zugferd/scripts/codelists/incoterms/output.xml|Source}
 */
export const INCOTERMS = [
	{
		key: "DELIVERY_ARRANGED_BY_SUPPLIER",
		name: "Delivery arranged by supplier",
		value: "1",
	},
	{
		key: "DELIVERY_ARRANGED_BY_LOGISTIC_SERVICE_PROVIDER",
		name: "Delivery arranged by logistic service provider",
		value: "2",
	},
	{ key: "COST_AND_FREIGHT", name: "Cost and Freight", value: "CFR" },
	{
		key: "COST_INSURANCE_AND_FREIGHT",
		name: "Cost, Insurance and Freight",
		value: "CIF",
	},
	{
		key: "CARRIAGE_AND_INSURANCE_PAID_TO_INSERT_NAMED_PLACE_OF_DESTINATION",
		name: "Carriage and Insurance Paid to (insert named place of destination)",
		value: "CIP",
	},
	{
		key: "CARRIAGE_PAID_TO_INSERT_NAMED_PLACE_OF_DESTINATION",
		name: "Carriage Paid To (insert named place of destination)",
		value: "CPT",
	},
	{
		key: "DELIVERED_AT_PLACE_INSERT_NAMED_PLACE_OF_DESTINATION",
		name: "Delivered At Place (insert named place of destination)",
		value: "DAP",
	},
	{
		key: "DELIVERED_DUTY_PAID_INSERT_NAMED_PLACE_OF_DESTINATION",
		name: "Delivered Duty Paid (insert named place of destination)",
		value: "DDP",
	},
	{
		key: "DELIVERED_AT_PLACE_UNLOADED_INSERT_NAMED_PLACE_OF_UNLOADING",
		name: "Delivered At Place Unloaded (insert named place of unloading)",
		value: "DPU",
	},
	{
		key: "EX_WORKS_INSERT_NAMED_PLACE_OF_DELIVERY",
		name: "Ex Works (insert named place of delivery)",
		value: "EXW",
	},
	{
		key: "FREE_ALONGSIDE_SHIP_INSERT_NAMED_PORT_OF_SHIPMENT",
		name: "Free Alongside Ship (insert named port of shipment)",
		value: "FAS",
	},
	{
		key: "FREE_CARRIER_INSERT_NAMED_PLACE_OF_DELIVERY",
		name: "Free Carrier (insert named place of delivery)",
		value: "FCA",
	},
	{
		key: "FREE_ON_BOARD_INSERT_NAMED_PORT_OF_SHIPMENT",
		name: "Free On Board (insert named port of shipment)",
		value: "FOB",
	},
] as const satisfies IncotermsDefinition[];

export const incotermsCode = INCOTERMS.map(({ value }) => value);

export const Incoterms = createEnum(INCOTERMS, {
	keyProp: "key",
	valueProp: "value",
});
