/**
 * Automatically generated by {@link Script} on Sun, 03 Aug 2025 15:58:51 GMT
 *
 * @see {@link https://github.com/jslno/node-zugferd/blob/main/packages/node-zugferd/scripts/codelists/line-reason/output.xml|Source}
 */

import type Script from "../../scripts/codelists/line-reason/index.ts";
import { createEnum } from "./";

export type LineReasonDefinition = {
	key: string;
	name: string;
	value: string;
};
export type LineReasonCode = (typeof LINE_REASON)[number]["value"];

export const PUBLISHED = "Factur-X" as const;

/**
 * Automatically generated by {@link Script} on Sun, 03 Aug 2025 15:58:51 GMT
 *
 * @see {@link https://github.com/jslno/node-zugferd/blob/main/packages/node-zugferd/scripts/codelists/line-reason/output.xml|Source}
 */
export const LINE_REASON = [
	{
		key: "REGULAR_ITEM_POSITION_STANDARD_CASE",
		name: "Regular item position (standard case)",
		value: "DETAIL",
	},
	{ key: "SUBTOTAL_OR_GROUP", name: "Subtotal or group", value: "GROUP" },
	{
		key: "FOR_INFORMATION_ONLY",
		name: "For information only",
		value: "INFORMATION",
	},
] as const satisfies LineReasonDefinition[];

export const lineReasonCode = LINE_REASON.map(({ value }) => value);

export const LineReason = createEnum(LINE_REASON, {
	keyProp: "key",
	valueProp: "value",
});
