/**
 * Automatically generated by {@link Script} on Sun, 03 Aug 2025 15:58:50 GMT
 *
 * @see {@link https://github.com/jslno/node-zugferd/blob/main/packages/node-zugferd/scripts/codelists/mime/output.xml|Source}
 */

import type Script from "../../scripts/codelists/mime/index.ts";

export type MimeDefinition = {
	value: string;
};
export type MimeCode = (typeof MIME)[number]["value"];

/**
 * Automatically generated by {@link Script} on Sun, 03 Aug 2025 15:58:50 GMT
 *
 * @see {@link https://github.com/jslno/node-zugferd/blob/main/packages/node-zugferd/scripts/codelists/mime/output.xml|Source}
 */
export const MIME = [
	{ value: "application\u002Fpdf" },
	{ value: "image\u002Fpng" },
	{ value: "image\u002Fjpeg" },
	{ value: "text\u002Fcsv" },
	{
		value:
			"application\u002Fvnd.openxmlformats-officedocument.spreadsheetml.sheet",
	},
	{ value: "application\u002Fvnd.oasis.opendocument.spreadsheet" },
	{ value: "application\u002Fxml" },
	{ value: "text\u002Fxml" },
] as const satisfies MimeDefinition[];

export const mimeCode = MIME.map(({ value }) => value);
