/**
 * Automatically generated by {@link Script}
 *
 * @see {@link https://github.com/jslno/node-zugferd/blob/main/packages/node-zugferd/scripts/codelists/transport/output.xml|Source}
 */

import type Script from "../../scripts/codelists/transport/index.ts";
import { createEnum } from "./";

export type TransportDefinition = {
	key: string;
	name: string;
	value: string;
	description: string;
};
export type TransportCode = (typeof TRANSPORT)[number]["value"];

/**
 * Automatically generated by {@link Script}
 *
 * @see {@link https://github.com/jslno/node-zugferd/blob/main/packages/node-zugferd/scripts/codelists/transport/output.xml|Source}
 */
export const TRANSPORT = [
	{
		key: "TRANSPORT_MODE_NOT_SPECIFIED",
		name: "Transport mode not specified",
		value: "0",
		description:
			"Transport mode has not been specified\nNotes:\n1) This code can be used when the mode is not known or when information on it is not available at the time of issuing the document concerned.",
	},
	{
		key: "MARITIME_TRANSPORT",
		name: "Maritime transport",
		value: "1",
		description: "Transport of goods and\u002For persons is by sea.",
	},
	{
		key: "RAIL_TRANSPORT",
		name: "Rail transport",
		value: "2",
		description: "Transport of goods and\u002For persons is by rail.",
	},
	{
		key: "ROAD_TRANSPORT",
		name: "Road transport",
		value: "3",
		description: "Transport of goods and\u002For persons is by road.",
	},
	{
		key: "AIR_TRANSPORT",
		name: "Air transport",
		value: "4",
		description: "Transport of goods and\u002For persons is by air.",
	},
	{
		key: "MAIL",
		name: "Mail",
		value: "5",
		description:
			"Method to convey goods is by mail\nNotes:\n1) This code is provided for practical reasons, despite the fact that mail is not a genuine mode of transport. In many countries, the value of merchandise exported and imported by mail is considerable, but the exporter or importer concerned would be unable to state by which mode postal items had been conveyed.",
	},
	{
		key: "MULTIMODAL_TRANSPO",
		name: "Multimodal transpo",
		value: "6",
		description:
			"Method to convey goods and\u002For persons is by multimodal transport.\nNotes:\n1) This code is provided for practical reasons, despite the fact that multimodal transport is not a genuine mode of transport. It can be used when goods are carried by at least two different modes from a place at which the goods are taken in charge by a transport operator to a place designated for delivery, on the basis of one transport contract. (Operations of pick-up and delivery of goods carried out in the performance of a single mode of transport, as defined in such a contract, shall not be considered as multimodal transport).",
	},
	{
		key: "FIXED_TRANSPORT_INSTALLATION",
		name: "Fixed transport installation",
		value: "7",
		description:
			"Transport of item is via a fixed transport installation.\nNotes:\n1) This code applies to installations for continuous transport such as pipelines, ropeways and electric power lines.",
	},
	{
		key: "INLAND_WATER_TRANSPORT",
		name: "Inland water transport",
		value: "8",
		description: "Transport of goods and\u002For persons is by inland water.",
	},
	{
		key: "TRANSPORT_MODE_NOT_APPLICABLE",
		name: "Transport mode not applicable",
		value: "9",
		description: "The mode of transport is not applicable.",
	},
] as const satisfies TransportDefinition[];

export const transportCode = TRANSPORT.map(({ value }) => value);

export const Transport = createEnum(TRANSPORT, {
	keyProp: "key",
	valueProp: "value",
});
