/**
 * Automatically generated by {@link Script} on Sun, 03 Aug 2025 15:58:50 GMT
 *
 * @see {@link https://github.com/jslno/node-zugferd/blob/main/packages/node-zugferd/scripts/codelists/vatex/output.xml|Source}
 */

import type Script from "../../scripts/codelists/vatex/index.ts";
import { createEnum } from "./";

export type VatExDefinition = {
	key: string;
	name: string;
	value: string;
	remark?: string | undefined;
};
export type VatExCode = (typeof VATEX)[number]["value"];

export const PUBLISHED = "7" as const;

/**
 * Automatically generated by {@link Script} on Sun, 03 Aug 2025 15:58:50 GMT
 *
 * @see {@link https://github.com/jslno/node-zugferd/blob/main/packages/node-zugferd/scripts/codelists/vatex/output.xml|Source}
 */
export const VATEX = [
	{
		key: "EXEMPT_BASED_ON_ARTICLE_79_POINT_C_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 79, point c of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-79-C",
		remark: "VATEX-EU-79-C",
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132 of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_A_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (a) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1A",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_B_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (b) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1B",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_C_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (c) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1C",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_D_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (d) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1D",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_E_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (e) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1E",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_F_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (f) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1F",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_G_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (g) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1G",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_H_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (h) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1H",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_I_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (i) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1I",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_J_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (j) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1J",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_K_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (k) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1K",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_L_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (l) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1L",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_M_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (m) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1M",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_N_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (n) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1N",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_O_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (o) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1O",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_P_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (p) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1P",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_132_SECTION_1_Q_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 132, section 1 (q) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-132-1Q",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_143_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 143 of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-143",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_143_SECTION_1_A_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 143, section 1 (a) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-143-1A",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_143_SECTION_1_B_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 143, section 1 (b) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-143-1B",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_143_SECTION_1_C_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 143, section 1 (c) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-143-1C",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_143_SECTION_1_D_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 143, section 1 (d) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-143-1D",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_143_SECTION_1_E_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 143, section 1 (e) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-143-1E",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_143_SECTION_1_F_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 143, section 1 (f) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-143-1F",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_143_SECTION_1_FA_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 143, section 1 (fa) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-143-1FA",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_143_SECTION_1_G_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 143, section 1 (g) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-143-1G",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_143_SECTION_1_H_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 143, section 1 (h) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-143-1H",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_143_SECTION_1_I_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 143, section 1 (i) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-143-1I",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_143_SECTION_1_J_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 143, section 1 (j) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-143-1J",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_143_SECTION_1_K_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 143, section 1 (k) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-143-1K",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_143_SECTION_1_L_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 143, section 1 (l) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-143-1L",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_144_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 144 of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-144",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_146_SECTION_1_E_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 146 section 1 (e) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-146-1E",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_148_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 148 of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-148",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_148_SECTION_A_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 148, section (a) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-148-A",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_148_SECTION_B_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 148, section (b) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-148-B",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_148_SECTION_C_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 148, section (c) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-148-C",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_148_SECTION_D_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 148, section (d) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-148-D",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_148_SECTION_E_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 148, section (e) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-148-E",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_148_SECTION_F_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 148, section (f) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-148-F",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_148_SECTION_G_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 148, section (g) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-148-G",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_151_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 151 of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-151",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_151_SECTION_1_A_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 151, section 1 (a) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-151-1A",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_151_SECTION_1_AA_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 151, section 1 (aa) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-151-1AA",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_151_SECTION_1_B_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 151, section 1 (b) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-151-1B",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_151_SECTION_1_C_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 151, section 1 (c) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-151-1C",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_151_SECTION_1_D_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 151, section 1 (d) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-151-1D",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_151_SECTION_1_E_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 151, section 1 (e) of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-151-1E",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_153_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 153 of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-153",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_159_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 159 of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-159",
		remark: undefined,
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_309_OF_COUNCIL_DIRECTIVE_2006112EC",
		name: "Exempt based on article 309 of Council Directive 2006\u002F112\u002FEC",
		value: "VATEX-EU-309",
		remark: undefined,
	},
	{
		key: "REVERSE_CHARGE",
		name: "Reverse charge",
		value: "VATEX-EU-AE",
		remark: "VATEX-EU-AE",
	},
	{
		key: "TRAVEL_AGENTS_VAT_SCHEME",
		name: "Travel agents VAT scheme.",
		value: "VATEX-EU-D",
		remark: "VATEX-EU-D",
	},
	{
		key: "SECOND_HAND_GOODS_VAT_SCHEME",
		name: "Second hand goods VAT scheme.",
		value: "VATEX-EU-F",
		remark: "VATEX-EU-F",
	},
	{
		key: "EXPORT_OUTSIDE_THE_EU",
		name: "Export outside the EU",
		value: "VATEX-EU-G",
		remark: "VATEX-EU-G",
	},
	{
		key: "WORKS_OF_ART_VAT_SCHEME",
		name: "Works of art VAT scheme.",
		value: "VATEX-EU-I",
		remark: "VATEX-EU-I",
	},
	{
		key: "INTRA_COMMUNITY_SUPPLY",
		name: "Intra-community supply",
		value: "VATEX-EU-IC",
		remark: "VATEX-EU-IC",
	},
	{
		key: "COLLECTORS_ITEMS_AND_ANTIQUES_VAT_SCHEME",
		name: "Collectors items and antiques VAT scheme.",
		value: "VATEX-EU-J",
		remark: "VATEX-EU-J",
	},
	{
		key: "NOT_SUBJECT_TO_VAT",
		name: "Not subject to VAT",
		value: "VATEX-EU-O",
		remark: "VATEX-EU-O",
	},
	{
		key: "FRANCE_DOMESTIC_VAT_FRANCHISE_IN_BASE",
		name: "France domestic VAT franchise in base",
		value: "VATEX-FR-FRANCHISE",
		remark: "VATEX-FR-FRANCHISE",
	},
	{
		key: "FRANCE_DOMESTIC_CREDIT_NOTES_WITHOUT_VAT_DUE_TO_SUPPLIER_FORFEIT_OF_VAT_FOR_DISCOUNT",
		name: "France domestic Credit Notes without VAT, due to supplier forfeit of VAT for discount",
		value: "VATEX-FR-CNWVAT",
		remark: "VATEX-FR-CNWVAT",
	},
	{
		key: "EXEMPT_BASED_ON_1_OF_ARTICLE_261_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 1 of article 261 of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261-1",
		remark: "VATEX-FR-CGI261-1",
	},
	{
		key: "EXEMPT_BASED_ON_2_OF_ARTICLE_261_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 2 of article 261 of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261-2",
		remark: "VATEX-FR-CGI261-2",
	},
	{
		key: "EXEMPT_BASED_ON_3_OF_ARTICLE_261_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 3 of article 261 of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261-3",
		remark: "VATEX-FR-CGI261-3",
	},
	{
		key: "EXEMPT_BASED_ON_4_OF_ARTICLE_261_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 4 of article 261 of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261-4",
		remark: "VATEX-FR-CGI261-4",
	},
	{
		key: "EXEMPT_BASED_ON_5_OF_ARTICLE_261_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 5 of article 261 of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261-5",
		remark: "VATEX-FR-CGI261-5",
	},
	{
		key: "EXEMPT_BASED_ON_7_OF_ARTICLE_261_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 7 of article 261 of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261-7",
		remark: "VATEX-FR-CGI261-7",
	},
	{
		key: "EXEMPT_BASED_ON_8_OF_ARTICLE_261_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 8 of article 261 of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261-8",
		remark: "VATEX-FR-CGI261-8",
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_261_A_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on article 261 A of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261A",
		remark: "VATEX-FR-CGI261A",
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_261_B_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on article 261 B of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261B",
		remark: "VATEX-FR-CGI261B",
	},
	{
		key: "EXEMPT_BASED_ON_1_OF_ARTICLE_261_C_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 1° of article 261 C of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261C-1",
		remark: "VATEX-FR-CGI261C-1",
	},
	{
		key: "EXEMPT_BASED_ON_2_OF_ARTICLE_261_C_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 2° of article 261 C of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261C-2",
		remark: "VATEX-FR-CGI261C-2",
	},
	{
		key: "EXEMPT_BASED_ON_3_OF_ARTICLE_261_C_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 3° of article 261 C of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261C-3",
		remark: "VATEX-FR-CGI261C-3",
	},
	{
		key: "EXEMPT_BASED_ON_1_OF_ARTICLE_261_D_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 1° of article 261 D of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261D-1",
		remark: "VATEX-FR-CGI261D-1",
	},
	{
		key: "EXEMPT_BASED_ON_1BIS_OF_ARTICLE_261_D_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 1°bis of article 261 D of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261D-1BIS",
		remark: "VATEX-FR-CGI261D-1BIS",
	},
	{
		key: "EXEMPT_BASED_ON_2_OF_ARTICLE_261_D_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 2° of article 261 D of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261D-2",
		remark: "VATEX-FR-CGI261D-2",
	},
	{
		key: "EXEMPT_BASED_ON_3_OF_ARTICLE_261_D_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE_EXONERATION_DE_TVA_ARTICLE_261_D_3_DU_CODE_GENERAL_DES_IMPOTS",
		name: "Exempt based on 3° of article 261 D of the Code Général des Impôts (CGI ; General tax code)\nExonération de TVA - Article 261 D-3° du Code Général des Impôts",
		value: "VATEX-FR-CGI261D-3",
		remark: "VATEX-FR-CGI261D-3",
	},
	{
		key: "EXEMPT_BASED_ON_4_OF_ARTICLE_261_D_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 4° of article 261 D of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261D-4",
		remark: "VATEX-FR-CGI261D-4",
	},
	{
		key: "EXEMPT_BASED_ON_1_OF_ARTICLE_261_E_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 1° of article 261 E of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261E-1",
		remark: "VATEX-FR-CGI261E-1",
	},
	{
		key: "EXEMPT_BASED_ON_2_OF_ARTICLE_261_E_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 2° of article 261 E of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI261E-2",
		remark: "VATEX-FR-CGI261E-2",
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_277_A_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on article 277 A of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI277A",
		remark: "VATEX-FR-CGI277A",
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_275_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on article 275 of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI275",
		remark: "VATEX-FR-CGI275",
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_298_SEXDECIES_A_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on article 298 sexdecies A of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-298SEXDECIESA",
		remark: "VATEX-FR-298SEXDECIESA",
	},
	{
		key: "EXEMPT_BASED_ON_ARTICLE_295_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on article 295 of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-CGI295",
		remark: "VATEX-FR-CGI295",
	},
	{
		key: "EXEMPT_BASED_ON_2_OF_ARTICLE_283_OF_THE_CODE_GENERAL_DES_IMPOTS_CGI__GENERAL_TAX_CODE",
		name: "Exempt based on 2 of article 283 of the Code Général des Impôts (CGI ; General tax code)",
		value: "VATEX-FR-AE",
		remark: "VATEX-FR-AE",
	},
] as const satisfies VatExDefinition[];

export const vatExCode = VATEX.map(({ value }) => value);

export const VatEx = createEnum(VATEX, {
	keyProp: "key",
	valueProp: "value",
});
