import type { Codelist } from "@node-zugferd/core";
import { registerCodelist } from "@node-zugferd/data-types";

const currency = [
	{ name: "UAE Dirham", value: "AED", key: "UAE_DIRHAM" },
	{ name: "Afghani", value: "AFN", key: "AFGHANI" },
	{ name: "Lek", value: "ALL", key: "LEK" },
	{ name: "Armenian Dram", value: "AMD", key: "ARMENIAN_DRAM" },
	{
		name: "Netherlands Antillean Guilder",
		value: "ANG",
		key: "NETHERLANDS_ANTILLEAN_GUILDER",
	},
	{ name: "Kwanza", value: "AOA", key: "KWANZA" },
	{ name: "Argentine Peso", value: "ARS", key: "ARGENTINE_PESO" },
	{ name: "Australian Dollar", value: "AUD", key: "AUSTRALIAN_DOLLAR" },
	{ name: "Aruban Florin", value: "AWG", key: "ARUBAN_FLORIN" },
	{ name: "Azerbaijan Manat", value: "AZN", key: "AZERBAIJAN_MANAT" },
	{ name: "Convertible Mark", value: "BAM", key: "CONVERTIBLE_MARK" },
	{ name: "Barbados Dollar", value: "BBD", key: "BARBADOS_DOLLAR" },
	{ name: "Taka", value: "BDT", key: "TAKA" },
	{ name: "Bulgarian Lev", value: "BGN", key: "BULGARIAN_LEV" },
	{ name: "Bahraini Dinar", value: "BHD", key: "BAHRAINI_DINAR" },
	{ name: "Burundi Franc", value: "BIF", key: "BURUNDI_FRANC" },
	{ name: "Bermudian Dollar", value: "BMD", key: "BERMUDIAN_DOLLAR" },
	{ name: "Brunei Dollar", value: "BND", key: "BRUNEI_DOLLAR" },
	{ name: "Boliviano", value: "BOB", key: "BOLIVIANO" },
	{ name: "Mvdol", value: "BOV", key: "MVDOL" },
	{ name: "Brazilian Real", value: "BRL", key: "BRAZILIAN_REAL" },
	{ name: "Bahamian Dollar", value: "BSD", key: "BAHAMIAN_DOLLAR" },
	{ name: "Ngultrum", value: "BTN", key: "NGULTRUM" },
	{ name: "Pula", value: "BWP", key: "PULA" },
	{ name: "Belarusian Ruble", value: "BYN", key: "BELARUSIAN_RUBLE" },
	{ name: "Belize Dollar", value: "BZD", key: "BELIZE_DOLLAR" },
	{ name: "Canadian Dollar", value: "CAD", key: "CANADIAN_DOLLAR" },
	{ name: "Congolese Franc", value: "CDF", key: "CONGOLESE_FRANC" },
	{ name: "WIR Euro", value: "CHE", key: "WIR_EURO" },
	{ name: "Swiss Franc", value: "CHF", key: "SWISS_FRANC" },
	{ name: "WIR Franc", value: "CHW", key: "WIR_FRANC" },
	{ name: "Unidad de Fomento", value: "CLF", key: "UNIDAD_DE_FOMENTO" },
	{ name: "Chilean Peso", value: "CLP", key: "CHILEAN_PESO" },
	{ name: "Yuan Renminbi", value: "CNY", key: "YUAN_RENMINBI" },
	{ name: "Colombian Peso", value: "COP", key: "COLOMBIAN_PESO" },
	{ name: "Unidad de Valor Real", value: "COU", key: "UNIDAD_DE_VALOR_REAL" },
	{ name: "Costa Rican Colon", value: "CRC", key: "COSTA_RICAN_COLON" },
	{ name: "Cuban Peso", value: "CUP", key: "CUBAN_PESO" },
	{ name: "Cabo Verde Escudo", value: "CVE", key: "CABO_VERDE_ESCUDO" },
	{ name: "Czech Koruna", value: "CZK", key: "CZECH_KORUNA" },
	{ name: "Djibouti Franc", value: "DJF", key: "DJIBOUTI_FRANC" },
	{ name: "Danish Krone", value: "DKK", key: "DANISH_KRONE" },
	{ name: "Dominican Peso", value: "DOP", key: "DOMINICAN_PESO" },
	{ name: "Algerian Dinar", value: "DZD", key: "ALGERIAN_DINAR" },
	{ name: "Egyptian Pound", value: "EGP", key: "EGYPTIAN_POUND" },
	{ name: "Nakfa", value: "ERN", key: "NAKFA" },
	{ name: "Ethiopian Birr", value: "ETB", key: "ETHIOPIAN_BIRR" },
	{ name: "Euro", value: "EUR", key: "EURO" },
	{ name: "Fiji Dollar", value: "FJD", key: "FIJI_DOLLAR" },
	{
		name: "Falkland Islands Pound",
		value: "FKP",
		key: "FALKLAND_ISLANDS_POUND",
	},
	{ name: "Pound Sterling", value: "GBP", key: "POUND_STERLING" },
	{ name: "Lari", value: "GEL", key: "LARI" },
	{ name: "Ghana Cedi", value: "GHS", key: "GHANA_CEDI" },
	{ name: "Gibraltar Pound", value: "GIP", key: "GIBRALTAR_POUND" },
	{ name: "Dalasi", value: "GMD", key: "DALASI" },
	{ name: "Guinean Franc", value: "GNF", key: "GUINEAN_FRANC" },
	{ name: "Quetzal", value: "GTQ", key: "QUETZAL" },
	{ name: "Guyana Dollar", value: "GYD", key: "GUYANA_DOLLAR" },
	{ name: "Hong Kong Dollar", value: "HKD", key: "HONG_KONG_DOLLAR" },
	{ name: "Lempira", value: "HNL", key: "LEMPIRA" },
	{ name: "Gourde", value: "HTG", key: "GOURDE" },
	{ name: "Forint", value: "HUF", key: "FORINT" },
	{ name: "Rupiah", value: "IDR", key: "RUPIAH" },
	{ name: "New Israeli Sheqel", value: "ILS", key: "NEW_ISRAELI_SHEQEL" },
	{ name: "Indian Rupee", value: "INR", key: "INDIAN_RUPEE" },
	{ name: "Iraqi Dinar", value: "IQD", key: "IRAQI_DINAR" },
	{ name: "Iranian Rial", value: "IRR", key: "IRANIAN_RIAL" },
	{ name: "Iceland Krona", value: "ISK", key: "ICELAND_KRONA" },
	{ name: "Jamaican Dollar", value: "JMD", key: "JAMAICAN_DOLLAR" },
	{ name: "Jordanian Dinar", value: "JOD", key: "JORDANIAN_DINAR" },
	{ name: "Yen", value: "JPY", key: "YEN" },
	{ name: "Kenyan Shilling", value: "KES", key: "KENYAN_SHILLING" },
	{ name: "Som", value: "KGS", key: "SOM" },
	{ name: "Riel", value: "KHR", key: "RIEL" },
	{ name: "Comorian Franc ", value: "KMF", key: "COMORIAN_FRANC" },
	{ name: "North Korean Won", value: "KPW", key: "NORTH_KOREAN_WON" },
	{ name: "Won", value: "KRW", key: "WON" },
	{ name: "Kuwaiti Dinar", value: "KWD", key: "KUWAITI_DINAR" },
	{ name: "Cayman Islands Dollar", value: "KYD", key: "CAYMAN_ISLANDS_DOLLAR" },
	{ name: "Tenge", value: "KZT", key: "TENGE" },
	{ name: "Lao Kip", value: "LAK", key: "LAO_KIP" },
	{ name: "Lebanese Pound", value: "LBP", key: "LEBANESE_POUND" },
	{ name: "Sri Lanka Rupee", value: "LKR", key: "SRI_LANKA_RUPEE" },
	{ name: "Liberian Dollar", value: "LRD", key: "LIBERIAN_DOLLAR" },
	{ name: "Loti", value: "LSL", key: "LOTI" },
	{ name: "Libyan Dinar", value: "LYD", key: "LIBYAN_DINAR" },
	{ name: "Moroccan Dirham", value: "MAD", key: "MOROCCAN_DIRHAM" },
	{ name: "Moldovan Leu", value: "MDL", key: "MOLDOVAN_LEU" },
	{ name: "Malagasy Ariary", value: "MGA", key: "MALAGASY_ARIARY" },
	{ name: "Denar", value: "MKD", key: "DENAR" },
	{ name: "Kyat", value: "MMK", key: "KYAT" },
	{ name: "Tugrik", value: "MNT", key: "TUGRIK" },
	{ name: "Pataca", value: "MOP", key: "PATACA" },
	{ name: "Ouguiya", value: "MRU", key: "OUGUIYA" },
	{ name: "Mauritius Rupee", value: "MUR", key: "MAURITIUS_RUPEE" },
	{ name: "Rufiyaa", value: "MVR", key: "RUFIYAA" },
	{ name: "Malawi Kwacha", value: "MWK", key: "MALAWI_KWACHA" },
	{ name: "Mexican Peso", value: "MXN", key: "MEXICAN_PESO" },
	{
		name: "Mexican Unidad de Inversion (UDI)",
		value: "MXV",
		key: "MEXICAN_UNIDAD_DE_INVERSION_UDI",
	},
	{ name: "Malaysian Ringgit", value: "MYR", key: "MALAYSIAN_RINGGIT" },
	{ name: "Mozambique Metical", value: "MZN", key: "MOZAMBIQUE_METICAL" },
	{ name: "Namibia Dollar", value: "NAD", key: "NAMIBIA_DOLLAR" },
	{ name: "Naira", value: "NGN", key: "NAIRA" },
	{ name: "Cordoba Oro", value: "NIO", key: "CORDOBA_ORO" },
	{ name: "Norwegian Krone", value: "NOK", key: "NORWEGIAN_KRONE" },
	{ name: "Nepalese Rupee", value: "NPR", key: "NEPALESE_RUPEE" },
	{ name: "New Zealand Dollar", value: "NZD", key: "NEW_ZEALAND_DOLLAR" },
	{ name: "Rial Omani", value: "OMR", key: "RIAL_OMANI" },
	{ name: "Balboa", value: "PAB", key: "BALBOA" },
	{ name: "Sol", value: "PEN", key: "SOL" },
	{ name: "Kina", value: "PGK", key: "KINA" },
	{ name: "Philippine Peso", value: "PHP", key: "PHILIPPINE_PESO" },
	{ name: "Pakistan Rupee", value: "PKR", key: "PAKISTAN_RUPEE" },
	{ name: "Zloty", value: "PLN", key: "ZLOTY" },
	{ name: "Guarani", value: "PYG", key: "GUARANI" },
	{ name: "Qatari Rial", value: "QAR", key: "QATARI_RIAL" },
	{ name: "Romanian Leu", value: "RON", key: "ROMANIAN_LEU" },
	{ name: "Serbian Dinar", value: "RSD", key: "SERBIAN_DINAR" },
	{ name: "Russian Ruble", value: "RUB", key: "RUSSIAN_RUBLE" },
	{ name: "Rwanda Franc", value: "RWF", key: "RWANDA_FRANC" },
	{ name: "Saudi Riyal", value: "SAR", key: "SAUDI_RIYAL" },
	{
		name: "Solomon Islands Dollar",
		value: "SBD",
		key: "SOLOMON_ISLANDS_DOLLAR",
	},
	{ name: "Seychelles Rupee", value: "SCR", key: "SEYCHELLES_RUPEE" },
	{ name: "Sudanese Pound", value: "SDG", key: "SUDANESE_POUND" },
	{ name: "Swedish Krona", value: "SEK", key: "SWEDISH_KRONA" },
	{ name: "Singapore Dollar", value: "SGD", key: "SINGAPORE_DOLLAR" },
	{ name: "Saint Helena Pound", value: "SHP", key: "SAINT_HELENA_POUND" },
	{
		name: "Sierra Leone (new valuation 2022)",
		value: "SLE",
		key: "SIERRA_LEONE_NEW_VALUATION_2022",
	},
	{ name: "Somali Shilling", value: "SOS", key: "SOMALI_SHILLING" },
	{ name: "Surinam Dollar", value: "SRD", key: "SURINAM_DOLLAR" },
	{ name: "South Sudanese Pound", value: "SSP", key: "SOUTH_SUDANESE_POUND" },
	{ name: "Dobra", value: "STN", key: "DOBRA" },
	{ name: "El Salvador Colon", value: "SVC", key: "EL_SALVADOR_COLON" },
	{ name: "Syrian Pound", value: "SYP", key: "SYRIAN_POUND" },
	{ name: "Lilangeni", value: "SZL", key: "LILANGENI" },
	{ name: "Baht", value: "THB", key: "BAHT" },
	{ name: "Somoni", value: "TJS", key: "SOMONI" },
	{
		name: "Turkmenistan New Manat",
		value: "TMT",
		key: "TURKMENISTAN_NEW_MANAT",
	},
	{ name: "Tunisian Dinar", value: "TND", key: "TUNISIAN_DINAR" },
	{ name: "Pa’anga", value: "TOP", key: "PA_ANGA" },
	{ name: "Turkish Lira", value: "TRY", key: "TURKISH_LIRA" },
	{
		name: "Trinidad and Tobago Dollar",
		value: "TTD",
		key: "TRINIDAD_AND_TOBAGO_DOLLAR",
	},
	{ name: "New Taiwan Dollar", value: "TWD", key: "NEW_TAIWAN_DOLLAR" },
	{ name: "Tanzanian Shilling", value: "TZS", key: "TANZANIAN_SHILLING" },
	{ name: "Hryvnia", value: "UAH", key: "HRYVNIA" },
	{ name: "Uganda Shilling", value: "UGX", key: "UGANDA_SHILLING" },
	{ name: "US Dollar", value: "USD", key: "US_DOLLAR" },
	{ name: "US Dollar (Next day)", value: "USN", key: "US_DOLLAR_NEXT_DAY" },
	{
		name: "Uruguay Peso en Unidades Indexadas (UI)",
		value: "UYI",
		key: "URUGUAY_PESO_EN_UNIDADES_INDEXADAS_UI",
	},
	{ name: "Peso Uruguayo", value: "UYU", key: "PESO_URUGUAYO" },
	{ name: "Unidad Previsional", value: "UYW", key: "UNIDAD_PREVISIONAL" },
	{ name: "Uzbekistan Sum", value: "UZS", key: "UZBEKISTAN_SUM" },
	{
		name: "Bolívar Soberano, new valuation",
		value: "VED",
		key: "BOLI_VAR_SOBERANO_NEW_VALUATION",
	},
	{ name: "Bolívar Soberano", value: "VES", key: "BOLI_VAR_SOBERANO" },
	{ name: "Dong", value: "VND", key: "DONG" },
	{ name: "Vatu", value: "VUV", key: "VATU" },
	{ name: "Tala", value: "WST", key: "TALA" },
	{ name: "CFA Franc BEAC", value: "XAF", key: "CFA_FRANC_BEAC" },
	{ name: "Silver", value: "XAG", key: "SILVER" },
	{ name: "Gold", value: "XAU", key: "GOLD" },
	{
		name: "Bond Markets Unit European Composite Unit (EURCO)",
		value: "XBA",
		key: "BOND_MARKETS_UNIT_EUROPEAN_COMPOSITE_UNIT_EURCO",
	},
	{
		name: "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
		value: "XBB",
		key: "BOND_MARKETS_UNIT_EUROPEAN_MONETARY_UNIT_E_M_U_6",
	},
	{
		name: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
		value: "XBC",
		key: "BOND_MARKETS_UNIT_EUROPEAN_UNIT_OF_ACCOUNT_9_E_U_A_9",
	},
	{
		name: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
		value: "XBD",
		key: "BOND_MARKETS_UNIT_EUROPEAN_UNIT_OF_ACCOUNT_17_E_U_A_17",
	},
	{ name: "East Caribbean Dollar", value: "XCD", key: "EAST_CARIBBEAN_DOLLAR" },
	{
		name: "SDR (Special Drawing Right)",
		value: "XDR",
		key: "SDR_SPECIAL_DRAWING_RIGHT",
	},
	{ name: "CFA Franc BCEAO", value: "XOF", key: "CFA_FRANC_BCEAO" },
	{ name: "Palladium", value: "XPD", key: "PALLADIUM" },
	{ name: "CFP Franc", value: "XPF", key: "CFP_FRANC" },
	{ name: "Platinum", value: "XPT", key: "PLATINUM" },
	{ name: "Sucre", value: "XSU", key: "SUCRE" },
	{
		name: "Codes specifically reserved for testing purposes",
		value: "XTS",
		key: "CODES_SPECIFICALLY_RESERVED_FOR_TESTING_PURPOSES",
	},
	{ name: "ADB Unit of Account", value: "XUA", key: "ADB_UNIT_OF_ACCOUNT" },
	{
		name: "The codes assigned for transactions where no currency is involved",
		value: "XXX",
		key: "THE_CODES_ASSIGNED_FOR_TRANSACTIONS_WHERE_NO_CURRENCY_IS_INVOLVED",
	},
	{ name: "Yemeni Rial", value: "YER", key: "YEMENI_RIAL" },
	{ name: "Rand", value: "ZAR", key: "RAND" },
	{ name: "Zambian Kwacha", value: "ZMW", key: "ZAMBIAN_KWACHA" },
	{ name: "Zimbabwe Gold", value: "ZWG", key: "ZIMBABWE_GOLD" },
] as const satisfies Codelist;

declare module "@node-zugferd/core" {
	interface ZugferdCodelistRegistry {
		currency: typeof currency;
	}
}
registerCodelist("currency", currency);

export default currency;
