/**
 * This file is auto-generated. Do not edit this file directly.
 * To update the codelist, edit the generator script at scripts/codelists/vat-id/index.ts
 * and run `pnpm run script:codelists`.
 */

export type VatIdDefinition = {
	key: string;
	name: string;
	value: string;
};

export const vatId = [
	{ key: "VALUE_ADDED_TAX", name: "Value added tax", value: "VA" },
] as const satisfies VatIdDefinition[];

export type VatId = {
	[K in (typeof vatId)[number] as K["key"]]: K["value"];
};

export const VatId = Object.fromEntries(
	vatId.map((item) => [item.key, item.value]),
) as VatId;
