/**
 * This file is auto-generated. Do not edit this file directly.
 * To update the codelist, edit the generator script at scripts/codelists/untdid-3035/index.ts
 * and run `pnpm run script:codelists`.
 */

export type Untdid3035Definition = {
	key: string;
	name: string;
	value: string;
	description: string;
};

export const untdid3035 = [
	{
		key: "INSURANCE_CONTACT",
		name: "Insurance contact",
		value: "AA",
		description:
			"Department/person to contact for matters regarding insurance.",
	},
	{
		key: "WORKSHOP_CONTACT",
		name: "Workshop contact",
		value: "AB",
		description:
			"Department/person to contact for matters regarding the workshop.",
	},
	{
		key: "ACCEPTING_CONTACT",
		name: "Accepting contact",
		value: "AC",
		description: "Department/person in charge of accepting incoming goods.",
	},
	{
		key: "ACCOUNTING_CONTACT",
		name: "Accounting contact",
		value: "AD",
		description:
			"Department/person responsible for the accounts payable function within a corporation.",
	},
	{
		key: "CONTRACT_CONTACT",
		name: "Contract contact",
		value: "AE",
		description:
			"Department/person to contact for matters regarding contracts.",
	},
	{
		key: "LAND_REGISTRY_CONTACT",
		name: "Land registry contact",
		value: "AF",
		description:
			"Department/person to contact for matters regarding land registry.",
	},
	{
		key: "AGENT",
		name: "Agent",
		value: "AG",
		description:
			"Department/person of the agent which acts on behalf of another party.",
	},
	{
		key: "COORDINATION_CONTACT",
		name: "Coordination contact",
		value: "AH",
		description:
			"Department/person to contact for matters regarding technical coordination of works.",
	},
	{
		key: "PROJECT_MANAGEMENT_CONTACT",
		name: "Project management contact",
		value: "AI",
		description:
			"Department/person to contact for matters regarding project management on behalf of the contractor.",
	},
	{
		key: "INVESTMENT_CONTACT",
		name: "Investment contact",
		value: "AJ",
		description:
			"Department/person to contact for matters regarding investments.",
	},
	{
		key: "WORKS_MANAGEMENT_CONTACT",
		name: "Works management contact",
		value: "AK",
		description:
			"Department/person to contact for matters regarding management of works on behalf of the owner.",
	},
	{
		key: "PERSONNEL_CONTACT",
		name: "Personnel contact",
		value: "AL",
		description:
			"Department/person to contact for matters regarding personnel (human resources).",
	},
	{
		key: "CLAIMS_CONTACT",
		name: "Claims contact",
		value: "AM",
		description: "Department/person to contact for matters regarding claims.",
	},
	{
		key: "LABORATORY_CONTACT",
		name: "Laboratory contact",
		value: "AN",
		description: "Department/person to contact for laboratory matters.",
	},
	{
		key: "PLANT_EQUIPMENT_CONTACT",
		name: "Plant/equipment contact",
		value: "AO",
		description:
			"Department/person to contact for matters regarding plant/equipment.",
	},
	{
		key: "ACCOUNTS_PAYABLE_CONTACT",
		name: "Accounts payable contact",
		value: "AP",
		description:
			"Department/person responsible for the accounts payable function within a corporation.",
	},
	{
		key: "QUANTITY_SURVEYOR_CONTACT",
		name: "Quantity surveyor contact",
		value: "AQ",
		description:
			"Department/person to contact for matters regarding quantity surveying.",
	},
	{
		key: "ACCOUNTS_RECEIVABLE_CONTACT",
		name: "Accounts receivable contact",
		value: "AR",
		description:
			"Department/person responsible for the accounts receivable within a corporation.",
	},
	{
		key: "PUBLIC_RELATIONS_CONTACT",
		name: "Public relations contact",
		value: "AS",
		description:
			"Department/person to contact for matters regarding public relations.",
	},
	{
		key: "TECHNICAL_CONTACT",
		name: "Technical contact",
		value: "AT",
		description:
			"Department/person to contact for matters regarding technical issues.",
	},
	{
		key: "CITY_WORKS_AUTHORITY_CONTACT",
		name: "City works authority contact",
		value: "AU",
		description:
			"Department/person to contact for matters regarding city works.",
	},
	{
		key: "MAINTENANCE_CONTACT",
		name: "Maintenance contact",
		value: "AV",
		description:
			"Department/person to contact for matters regarding maintenance.",
	},
	{
		key: "TOWN_PLANNING_CONTACT",
		name: "Town planning contact",
		value: "AW",
		description:
			"Department/person to contact for matters regarding town ` planning.",
	},
	{
		key: "TRAFFIC_AUTHORITY_CONTACT",
		name: "Traffic authority contact",
		value: "AX",
		description: "Department/person to contact for matters regarding traffic.",
	},
	{
		key: "ELECTRICITY_SUPPLY_CONTACT",
		name: "Electricity supply contact",
		value: "AY",
		description:
			"Department/person to contact for matters regarding electricity supply.",
	},
	{
		key: "GAS_SUPPLY_CONTACT",
		name: "Gas supply contact",
		value: "AZ",
		description:
			"Department/person to contact for matters regarding gas supply.",
	},
	{
		key: "WATER_SUPPLY_CONTACT",
		name: "Water supply contact",
		value: "BA",
		description:
			"Department/person to contact for matters regarding water supply.",
	},
	{
		key: "TELECOMMUNICATIONS_NETWORK_CONTACT",
		name: "Telecommunications network contact",
		value: "BB",
		description:
			"Department/person to contact for matters regarding telecommunications network.",
	},
	{
		key: "BANKING_CONTACT",
		name: "Banking contact",
		value: "BC",
		description: "Contact person for bank.",
	},
	{
		key: "NEW_DEVELOPMENTS_CONTACT",
		name: "New developments contact",
		value: "BD",
		description:
			"Department/person to contact for matters regarding new developments (e.g. construction).",
	},
	{
		key: "TRANSPORT_INFRASTRUCTURE_AUTHORITY",
		name: "Transport infrastructure authority",
		value: "BE",
		description:
			"Department/person to contact for matters regarding transport infrastructure.",
	},
	{
		key: "SERVICE_CONTACT",
		name: "Service contact",
		value: "BF",
		description: "Department/person to be contacted in service matters.",
	},
	{
		key: "ULTIMATE_CONSIGNEE",
		name: "Ultimate consignee",
		value: "BU",
		description:
			"Department/designated on the invoice or packing list as the final recipient of the stated merchandise.",
	},
	{
		key: "CARRIER",
		name: "Carrier",
		value: "CA",
		description:
			"(3126) Party undertaking or arranging transport of goods between named points.",
	},
	{
		key: "CHANGED_BY",
		name: "Changed by",
		value: "CB",
		description: "Person who made the change.",
	},
	{
		key: "RESPONSIBLE_PERSON_FOR_INFORMATION_PRODUCTION",
		name: "Responsible person for information production",
		value: "CC",
		description:
			"Responsible person to contact for matters regarding the production of information.",
	},
	{
		key: "RESPONSIBLE_PERSON_FOR_INFORMATION_DISSEMINATION",
		name: "Responsible person for information dissemination",
		value: "CD",
		description:
			"Responsible person to contact for matters regarding information dissemination.",
	},
	{
		key: "HEAD_OF_UNIT_FOR_COMPUTER_DATA_PROCESSING",
		name: "Head of unit for computer data processing",
		value: "CE",
		description:
			"Head of unit to contact for matters regarding computer data processing.",
	},
	{
		key: "HEAD_OF_UNIT_FOR_INFORMATION_PRODUCTION",
		name: "Head of unit for information production",
		value: "CF",
		description:
			"Head of unit to contact for matters regarding the production of information.",
	},
	{
		key: "HEAD_OF_UNIT_FOR_INFORMATION_DISSEMINATION",
		name: "Head of unit for information dissemination",
		value: "CG",
		description:
			"Head of unit to contact for matters regarding dissemination of information.",
	},
	{
		key: "CONSIGNEE",
		name: "Consignee",
		value: "CN",
		description: "(3132) Party to which goods are consigned.",
	},
	{
		key: "CONSIGNOR",
		name: "Consignor",
		value: "CO",
		description:
			"(3336) Party which, by contract with a carrier, consigns or sends goods with the carrier, or has them conveyed by him. Synonym: shipper/sender.",
	},
	{
		key: "RESPONSIBLE_PERSON_FOR_COMPUTER_DATA_PROCESSING",
		name: "Responsible person for computer data processing",
		value: "CP",
		description:
			"Responsible person to contact for matters regarding computer data processing.",
	},
	{
		key: "CUSTOMER_RELATIONS",
		name: "Customer relations",
		value: "CR",
		description: "Individual responsible for customer relations.",
	},
	{
		key: "CONFIRMED_WITH",
		name: "Confirmed with",
		value: "CW",
		description:
			"Person with whom the contents of the purchase order has been discussed and agreed (e.g. by telephone) prior to the sending of this message.",
	},
	{
		key: "DEPARTMENT_EMPLOYEE_TO_EXECUTE_EXPORT_PROCEDURES",
		name: "Department/employee to execute export procedures",
		value: "DE",
		description: "Self explanatory.",
	},
	{
		key: "DEPARTMENT_EMPLOYEE_TO_EXECUTE_IMPORT_PROCEDURES",
		name: "Department/employee to execute import procedures",
		value: "DI",
		description: "Self explanatory.",
	},
	{
		key: "DELIVERY_CONTACT",
		name: "Delivery contact",
		value: "DL",
		description: "Department/person responsible for delivery.",
	},
	{
		key: "ENTERED_BY",
		name: "Entered by",
		value: "EB",
		description: "Name of an individual who made the entry.",
	},
	{
		key: "EDUCATION_COORDINATOR",
		name: "Education coordinator",
		value: "EC",
		description: "Person in charge of coordination of education.",
	},
	{
		key: "ENGINEERING_CONTACT",
		name: "Engineering contact",
		value: "ED",
		description:
			"Department/person to contact for matters regarding engineering.",
	},
	{
		key: "EXPEDITOR",
		name: "Expeditor",
		value: "EX",
		description: "Party to be contacted where goods are (to be) expedited.",
	},
	{
		key: "GOODS_RECEIVING_CONTACT",
		name: "Goods receiving contact",
		value: "GR",
		description:
			"Department/person responsible for receiving the goods at the place of delivery.",
	},
	{
		key: "EMERGENCY_DANGEROUS_GOODS_CONTACT",
		name: "Emergency dangerous goods contact",
		value: "HE",
		description:
			"Party who is to be contacted to intervene in case of emergency.",
	},
	{
		key: "DANGEROUS_GOODS_CONTACT",
		name: "Dangerous goods contact",
		value: "HG",
		description:
			"Department/person to be contacted for details about the transportation of dangerous goods/hazardous material.",
	},
	{
		key: "HAZARDOUS_MATERIAL_CONTACT",
		name: "Hazardous material contact",
		value: "HM",
		description:
			"Department/person responsible for hazardous material control.",
	},
	{
		key: "INFORMATION_CONTACT",
		name: "Information contact",
		value: "IC",
		description:
			"Department/person to contact for questions regarding transactions.",
	},
	{
		key: "INSURER_CONTACT",
		name: "Insurer contact",
		value: "IN",
		description: "Self explanatory.",
	},
	{
		key: "PLACE_OF_DELIVERY_CONTACT",
		name: "Place of delivery contact",
		value: "LB",
		description: "Self explanatory.",
	},
	{
		key: "PLACE_OF_COLLECTION_CONTACT",
		name: "Place of collection contact",
		value: "LO",
		description: "Self explanatory.",
	},
	{
		key: "MATERIAL_CONTROL_CONTACT",
		name: "Material control contact",
		value: "MC",
		description:
			"Department/person responsible for the controlling/inspection of goods.",
	},
	{
		key: "MATERIAL_DISPOSITION_CONTACT",
		name: "Material disposition contact",
		value: "MD",
		description:
			"Department/person responsible for the disposition/scheduling of goods.",
	},
	{
		key: "MATERIAL_HANDLING_CONTACT",
		name: "Material handling contact",
		value: "MH",
		description: "Self explanatory.",
	},
	{
		key: "MESSAGE_RECIPIENT_CONTACT",
		name: "Message recipient contact",
		value: "MR",
		description: "Self explanatory.",
	},
	{
		key: "MESSAGE_SENDER_CONTACT",
		name: "Message sender contact",
		value: "MS",
		description: "Self explanatory.",
	},
	{
		key: "NOTIFICATION_CONTACT",
		name: "Notification contact",
		value: "NT",
		description: "Self explanatory.",
	},
	{
		key: "ORDER_CONTACT",
		name: "Order contact",
		value: "OC",
		description: "An individual to contact for questions regarding this order.",
	},
	{
		key: "PROTOTYPE_COORDINATOR",
		name: "Prototype coordinator",
		value: "PA",
		description: "Description to be provided.",
	},
	{
		key: "PURCHASING_CONTACT",
		name: "Purchasing contact",
		value: "PD",
		description:
			"Department/person responsible for issuing this purchase order.",
	},
	{
		key: "PAYEE_CONTACT",
		name: "Payee contact",
		value: "PE",
		description: "Self explanatory.",
	},
	{
		key: "PRODUCT_MANAGEMENT_CONTACT",
		name: "Product management contact",
		value: "PM",
		description:
			"Department/person to contact for questions regarding this order.",
	},
	{
		key: "QUALITY_ASSURANCE_CONTACT",
		name: "Quality assurance contact",
		value: "QA",
		description: "Quality assurance contact within an organization.",
	},
	{
		key: "QUALITY_COORDINATOR_CONTACT",
		name: "Quality coordinator contact",
		value: "QC",
		description: "Quality coordinator contact within an organization.",
	},
	{
		key: "RECEIVING_DOCK_CONTACT",
		name: "Receiving dock contact",
		value: "RD",
		description: "The receiving dock contact within an organization.",
	},
	{
		key: "SALES_ADMINISTRATION",
		name: "Sales administration",
		value: "SA",
		description:
			"Name of the sales administration contact within a corporation.",
	},
	{
		key: "SCHEDULE_CONTACT",
		name: "Schedule contact",
		value: "SC",
		description: "Name of the scheduling contact within a corporation.",
	},
	{
		key: "SHIPPING_CONTACT",
		name: "Shipping contact",
		value: "SD",
		description: "The shipping department contact within an organization.",
	},
	{
		key: "SALES_REPRESENTATIVE_OR_DEPARTMENT",
		name: "Sales representative or department",
		value: "SR",
		description:
			"The sales representative or department contact within an organization.",
	},
	{
		key: "SUPPLIER_CONTACT",
		name: "Supplier contact",
		value: "SU",
		description: "Department/person to be contacted at the supplier.",
	},
	{
		key: "TRAFFIC_ADMINISTRATOR",
		name: "Traffic administrator",
		value: "TA",
		description: "The traffic administrator contact within an organization.",
	},
	{
		key: "TEST_CONTACT",
		name: "Test contact",
		value: "TD",
		description: "Department/person responsible for testing contact.",
	},
	{
		key: "TECHNICAL_DOCUMENTATION_RECIPIENT",
		name: "Technical documentation recipient",
		value: "TI",
		description: "Department/person to receive technical documentation.",
	},
	{
		key: "TRANSPORT_CONTACT",
		name: "Transport contact",
		value: "TR",
		description: "Department/person in charge of transportation.",
	},
	{
		key: "WAREHOUSE",
		name: "Warehouse",
		value: "WH",
		description: "The warehouse contact within an organization.",
	},
	{
		key: "MUTUALLY_DEFINED",
		name: "Mutually defined",
		value: "ZZZ",
		description: "Self explanatory.",
	},
] as const satisfies Untdid3035Definition[];

export type Untdid3035 = {
	[K in (typeof untdid3035)[number] as K["key"]]: K["value"];
};

export const Untdid3035 = Object.fromEntries(
	untdid3035.map((item) => [item.key, item.value]),
) as Untdid3035;
