/**
 * This file is auto-generated. Do not edit this file directly.
 * To update the codelist, edit the generator script at scripts/codelists/untdid-3035/index.ts
 * and run `pnpm run script:codelists`.
 */

export type Untdid3035Definition = {
	key: string;
	name: string;
	value: string;
	description: string;
};

export const untdid3035 = [
	{
		key: "PARTY_TO_BE_BILLED_AAR_ACCOUNTING_RULE_11",
		name: "Party to be billed (AAR Accounting rule 11)",
		value: "AA",
		description:
			"Party to be billed in accordance with AAR Accounting rule 11.",
	},
	{
		key: "BUYERS_AGENT_REPRESENTATIVE",
		name: "Buyer's agent/representative",
		value: "AB",
		description:
			"Third party who arranged the purchase of merchandise on behalf of the actual buyer.",
	},
	{
		key: "DECLARANTS_AGENT_REPRESENTATIVE",
		name: "Declarant's agent/representative",
		value: "AE",
		description:
			"Any natural or legal person who makes a declaration to an official body on behalf of another natural or legal person, where legally permitted (CCC).",
	},
	{
		key: "TRANSIT_PRINCIPAL",
		name: "Transit principal",
		value: "AF",
		description:
			"Natural or legal person responsible for the satisfactory performance of a Customs transit operation. Source: CCC.",
	},
	{
		key: "AGENT",
		name: "Agent",
		value: "AG",
		description:
			"(3196) Party authorized to act on behalf of another party. Synonym: Representative.",
	},
	{
		key: "TRANSIT_PRINCIPALS_AGENT_REPRESENTATIVE",
		name: "Transit principal's agent/representative",
		value: "AH",
		description: "Agent acting on behalf of the transit principal (CCC).",
	},
	{
		key: "SUCCESSFUL_JOB_APPLICANT",
		name: "Successful job applicant",
		value: "AI",
		description: "Person who has been chosen for a job.",
	},
	{
		key: "PARTY_ISSUING_MUTUALLY_AGREED_CODES",
		name: "Party issuing mutually agreed codes",
		value: "AJ",
		description:
			"The party which has issued all mutually agreed codes used in the message.",
	},
	{
		key: "ACKNOWLEDGEMENT_RECIPIENT",
		name: "Acknowledgement recipient",
		value: "AK",
		description: "Party to whom acknowledgement should be sent.",
	},
	{
		key: "PRINCIPAL_RESPONSIBLE_PARTY",
		name: "Principal responsible party",
		value: "AL",
		description:
			"(3340) Party accepting liability for goods held or moving (e.g. transit) under a Customs authorization and - when applicable - a guarantee.",
	},
	{
		key: "AUTHORIZED_OFFICIAL",
		name: "Authorized official",
		value: "AM",
		description:
			"Employee of a company or firm authorized to act on behalf of that company or firm e.g. to make a Customs declaration.",
	},
	{
		key: "APPROVED_IMPORTER",
		name: "Approved importer",
		value: "AN",
		description:
			"Person or company which is authorised by the relevant Customs authority to import goods without payment all taxes or specific taxes at the point of entry into the country.",
	},
	{
		key: "ACCOUNT_OF",
		name: "Account of",
		value: "AO",
		description: "Party account is assigned to.",
	},
	{
		key: "ACCEPTING_PARTY",
		name: "Accepting party",
		value: "AP",
		description: "(3336) Party accepting goods, products, services, etc.",
	},
	{
		key: "APPROVED_CONSIGNOR",
		name: "Approved consignor",
		value: "AQ",
		description:
			"Person or company approved by the relevant authority in the country to pack and export specific goods under Customs supervision.",
	},
	{
		key: "AUTHORIZED_EXPORTER",
		name: "Authorized exporter",
		value: "AR",
		description:
			"Exporter authorized/approved by Customs for special Customs procedures e.g. simplified procedure.",
	},
	{
		key: "ACCOUNT_SERVICING_FINANCIAL_INSTITUTION",
		name: "Account servicing financial institution",
		value: "AS",
		description:
			"Identifies the financial institution servicing the account(s).",
	},
	{
		key: "AUTHORIZED_IMPORTER",
		name: "Authorized importer",
		value: "AT",
		description:
			"Importer authorized/approved by Customs for special Customs procedures e.g. simplified procedure.",
	},
	{
		key: "AUTHORIZED_TRADER_TRANSIT",
		name: "Authorized trader (transit)",
		value: "AU",
		description:
			"Trader authorized/approved by Customs for special transit procedures e.g. simplified procedure.",
	},
	{
		key: "AUTHORIZING_OFFICIAL",
		name: "Authorizing official",
		value: "AV",
		description:
			"Party that has delegated the authority to take a certain action on behalf of a company or agency.",
	},
	{
		key: "APPLICANTS_BANK",
		name: "Applicant's bank",
		value: "AW",
		description:
			"(3234) Financial institution which is requested to issue the documentary credit.",
	},
	{
		key: "AUTHENTICATING_PARTY",
		name: "Authenticating party",
		value: "AX",
		description: "Party which certifies that a document is authentic.",
	},
	{
		key: "ANIMAL_BEING_INVESTIGATED",
		name: "Animal being investigated",
		value: "AY",
		description: "Animal being investigated.",
	},
	{
		key: "ISSUING_BANK",
		name: "Issuing bank",
		value: "AZ",
		description:
			"Financial institution which issues the documentary credit, if the applicant's bank is not acting as the issuing bank.",
	},
	{
		key: "CONTACT_BANK_1",
		name: "Contact bank 1",
		value: "B1",
		description:
			"Identifies an additional bank which must be informed of certain aspects of the message.",
	},
	{
		key: "CONTACT_BANK_2",
		name: "Contact bank 2",
		value: "B2",
		description:
			"Identifies an additional bank which must be informed of certain aspects of the message.",
	},
	{
		key: "BOOKING_AGENT",
		name: "Booking agent",
		value: "BA",
		description:
			"Party acting as a booking office for transport and forwarding services.",
	},
	{
		key: "BUYER_BANK_IDENTIFICATION",
		name: "Buyer bank identification",
		value: "BB",
		description:
			"[3421]To identify a bank employed by the buyer to make a payment.",
	},
	{
		key: "NEGOTIATING_BANK",
		name: "Negotiating bank",
		value: "BC",
		description:
			"Financial institution to whom a negotiable documentary credit is directed.",
	},
	{
		key: "DOCUMENTARY_CREDIT_REIMBURSING_BANK",
		name: "Documentary credit reimbursing bank",
		value: "BD",
		description: "A financial institution which reimburses documentary credit.",
	},
	{
		key: "BENEFICIARY",
		name: "Beneficiary",
		value: "BE",
		description:
			"The ultimate recipient of the funds. Normally the account owner who is reimbursed by the payer.",
	},
	{
		key: "BENEFICIARYS_BANK",
		name: "Beneficiary's bank",
		value: "BF",
		description:
			"Identifies the account servicer for the beneficiary or the payee.",
	},
	{
		key: "EMPLOYER",
		name: "Employer",
		value: "BG",
		description: "A party that keeps a person in service for payment.",
	},
	{
		key: "PREVIOUS_EMPLOYER",
		name: "Previous employer",
		value: "BH",
		description: "Previous employer of a person(s).",
	},
	{
		key: "BUYERS_FINANCIAL_INSTITUTION",
		name: "Buyer's financial institution",
		value: "BI",
		description: "Financial institution designated by buyer to make payment.",
	},
	{
		key: "RELEASE_TO_PARTY",
		name: "Release to party",
		value: "BJ",
		description:
			"Party to which the goods or container(s) is (are) to be released.",
	},
	{
		key: "FINANCIAL_INSTITUTION",
		name: "Financial institution",
		value: "BK",
		description: "Party acting as financial institution.",
	},
	{
		key: "BILL_OF_LADING_RECIPIENT",
		name: "Bill of lading recipient",
		value: "BL",
		description: "Party to receive B/L.",
	},
	{
		key: "INSURED",
		name: "Insured",
		value: "BM",
		description: "Party which is the object of an insurance contract.",
	},
	{
		key: "INSURANCE_BENEFICIARY",
		name: "Insurance beneficiary",
		value: "BN",
		description: "Party which benefits from insurance coverage.",
	},
	{
		key: "BROKER_OR_SALES_OFFICE",
		name: "Broker or sales office",
		value: "BO",
		description:
			"Party acting in the name of the seller as broker or as sales office.",
	},
	{
		key: "BUILDING_SITE_PURCHASER",
		name: "Building site purchaser",
		value: "BP",
		description:
			"Party at the building site responsible for the purchasing of goods and services for that particular site.",
	},
	{
		key: "CHEQUE_DRAWN_BANK",
		name: "Cheque drawn bank",
		value: "BQ",
		description:
			"Identifies the bank on which the cheque should be drawn, as instructed by the ordering customer.",
	},
	{
		key: "BILL_AND_SHIP_TO",
		name: "Bill and ship to",
		value: "BS",
		description: "Party receiving goods and relevant invoice.",
	},
	{
		key: "PARTY_TO_BE_BILLED_FOR_OTHER_THAN_FREIGHT_BILL_TO",
		name: "Party to be billed for other than freight (bill to)",
		value: "BT",
		description: "Party receiving invoice excluding freight costs.",
	},
	{
		key: "SERVICE_BUREAU",
		name: "Service bureau",
		value: "BU",
		description:
			"Party carrying out service bureau processing work, (e.g. a payroll bureau).",
	},
	{
		key: "MEMBER",
		name: "Member",
		value: "BV",
		description:
			"Member of a group (e.g. of a group of persons or a service scheme).",
	},
	{
		key: "BORROWER",
		name: "Borrower",
		value: "BW",
		description:
			"A person who acquires something temporarily with the promise or intention of returning.",
	},
	{
		key: "BUILDING_SITE_ENGINEER",
		name: "Building site engineer",
		value: "BX",
		description:
			"Party at the building site responsible for engineering matters for that particular site.",
	},
	{
		key: "BUYER",
		name: "Buyer",
		value: "BY",
		description: "[3002] Party to which merchandise or services are sold.",
	},
	{
		key: "BUILDING_SITE_FORWARDER",
		name: "Building site forwarder",
		value: "BZ",
		description:
			"Party at the building site responsible for forwarding the received goods on that particular site.",
	},
	{
		key: "IN_CARE_OF_PARTY_NO_1",
		name: "In care of party no. 1",
		value: "C1",
		description: "A person taking responsibility on behalf of party no. 1.",
	},
	{
		key: "IN_CARE_OF_PARTY_NO_2",
		name: "In care of party no. 2",
		value: "C2",
		description: "A person taking responsibility on behalf of party no. 2.",
	},
	{
		key: "CARRIER",
		name: "Carrier",
		value: "CA",
		description:
			"[3126] Party undertaking or arranging transport of goods between named points.",
	},
	{
		key: "CUSTOMS_BROKER",
		name: "Customs broker",
		value: "CB",
		description:
			"Agent or representative or a professional Customs clearing agent who deals directly with Customs on behalf of the importer or exporter (CCC).",
	},
	{
		key: "CLAIMANT",
		name: "Claimant",
		value: "CC",
		description: "Party who claims goods or insurance.",
	},
	{
		key: "AGENTS_BANK",
		name: "Agent's bank",
		value: "CD",
		description: "Bank of the agent.",
	},
	{
		key: "CEDING_COMPANY",
		name: "Ceding company",
		value: "CE",
		description: "Company which cedes something to someone.",
	},
	{
		key: "CONTAINER_OPERATOR_LESSEE",
		name: "Container operator/lessee",
		value: "CF",
		description:
			"Party to whom the possession of specified property (e.g. container) has been conveyed for a period of time in return for rental payments.",
	},
	{
		key: "CARRIERS_AGENT",
		name: "Carrier's agent",
		value: "CG",
		description: "Party authorized to act for or on behalf of carrier.",
	},
	{
		key: "CONNECTING_CARRIER",
		name: "Connecting carrier",
		value: "CH",
		description:
			"Owner or operator of a transportation conveyance to which goods in a given transaction will be transferred.",
	},
	{
		key: "COMMISSION_PROCESSOR",
		name: "Commission processor",
		value: "CI",
		description:
			"Party who provides extra treatment to goods on commission base.",
	},
	{
		key: "PREVIOUS_MEMBER",
		name: "Previous member",
		value: "CJ",
		description: "Previous member of a group of persons or a service scheme.",
	},
	{
		key: "EMPTY_EQUIPMENT_DESPATCH_PARTY",
		name: "Empty equipment despatch party",
		value: "CK",
		description:
			"Party from whose premises empty equipment will be or has been despatched.",
	},
	{
		key: "CONTAINER_LOCATION_PARTY",
		name: "Container location party",
		value: "CL",
		description:
			"Party from whose premises container will be or has been despatched.",
	},
	{
		key: "CUSTOMS",
		name: "Customs",
		value: "CM",
		description:
			"Identification of customs authority relevant to the transaction or shipment.",
	},
	{
		key: "CONSIGNEE",
		name: "Consignee",
		value: "CN",
		description: "[3132] Party to which goods are consigned.",
	},
	{
		key: "CASH_POOL_TOP_ACCOUNT_SERVICING_FINANCIAL_INSTITUTION",
		name: "Cash pool top account servicing financial institution",
		value: "CNX",
		description:
			"Identification of a financial institution servicing the top account of a cash pool.",
	},
	{
		key: "CASH_POOL_LEVEL_ACCOUNT_SERVICING_FINANCIAL_INSTITUTION",
		name: "Cash pool level account servicing financial institution",
		value: "CNY",
		description:
			"Identification of a financial institution servicing the level account of a cash pool.",
	},
	{
		key: "CASH_POOL_SUB_ACCOUNT_SERVICING_FINANCIAL_INSTITUTION",
		name: "Cash pool sub-account servicing financial institution",
		value: "CNZ",
		description:
			"Identification of a financial institution servicing the sub-account of a cash pool.",
	},
	{
		key: "CORPORATE_OFFICE",
		name: "Corporate office",
		value: "CO",
		description: "Identification of the Head Office within a company.",
	},
	{
		key: "ENTITY_IN_WHICH_A_FINANCIAL_INTEREST_IS_HELD",
		name: "Entity in which a financial interest is held",
		value: "COA",
		description: "Business in which a financial interest is held.",
	},
	{
		key: "INTERMEDIATE_LEVEL_PARENT_COMPANY",
		name: "Intermediate level parent company",
		value: "COB",
		description: "Identifies an intermediate parent company.",
	},
	{
		key: "TRANSSHIPMENT_PARTY",
		name: "Transshipment party",
		value: "COC",
		description: "A party responsible for transshipment.",
	},
	{
		key: "QUOTATION_REQUESTING_PARTY",
		name: "Quotation requesting party",
		value: "COD",
		description: "Party sending a request for a quotation.",
	},
	{
		key: "PARTY_MAINTAINING_THE_CODES_USED_IN_THE_MESSAGE",
		name: "Party maintaining the codes used in the message",
		value: "COE",
		description: "The party which maintains the codes used in the message.",
	},
	{
		key: "PARTY_MAINTAINING_THE_IDENTIFIERS_USED_IN_THE_MESSAGE",
		name: "Party maintaining the identifiers used in the message",
		value: "COF",
		description:
			"The party which maintains the identifiers used in the message.",
	},
	{
		key: "DISPATCHER",
		name: "Dispatcher",
		value: "COG",
		description:
			"An individual responsible for sending something to a destination.",
	},
	{
		key: "SUBMITTER_OF_SAMPLE",
		name: "Submitter of sample",
		value: "COH",
		description: "An entity responsible for the submission of a sample.",
	},
	{
		key: "INSTITUTIONAL_PROVIDER",
		name: "Institutional provider",
		value: "COI",
		description: "The institution providing the service.",
	},
	{
		key: "PRIMARY_HEALTH_CARE_PROVIDER",
		name: "Primary health care provider",
		value: "COJ",
		description:
			"Health care provider that has primary responsibility for patient.",
	},
	{
		key: "ASSISTANT_SURGEON",
		name: "Assistant surgeon",
		value: "COK",
		description: "Physician assisting in surgery.",
	},
	{
		key: "ADMITTING_HEALTH_CARE_PROVIDER",
		name: "Admitting health care provider",
		value: "COL",
		description: "Health care provider that admitted the patient.",
	},
	{
		key: "REFERRING_HEALTH_CARE_PROVIDER",
		name: "Referring health care provider",
		value: "COM",
		description:
			"Health care provider that referred patient to current provider of services.",
	},
	{
		key: "SUPERVISING_HEALTH_CARE_PROVIDER",
		name: "Supervising health care provider",
		value: "CON",
		description:
			"Health care provider that supervised the rendering of a service.",
	},
	{
		key: "PARTY_PROVIDING_FINANCING",
		name: "Party providing financing",
		value: "COO",
		description: "Identifies the party providing the financing.",
	},
	{
		key: "CONVOYING_PARTY",
		name: "Convoying party",
		value: "COP",
		description: "Party designated to escort the transported goods.",
	},
	{
		key: "NOMINATED_BANK",
		name: "Nominated bank",
		value: "COQ",
		description: "Identifies the nominated bank.",
	},
	{
		key: "FAMILY_MEMBER",
		name: "Family member",
		value: "COR",
		description: "Identifies a family member.",
	},
	{
		key: "CO_PARTICIPANT",
		name: "Co-participant",
		value: "COS",
		description: "Identifies another party who participates in an activity.",
	},
	{
		key: "INVOLVED_PARTY",
		name: "Involved party",
		value: "COT",
		description: "Party which is involved in an activity.",
	},
	{
		key: "ASSIGNER",
		name: "Assigner",
		value: "COU",
		description: "Identifies the entity who assigns.",
	},
	{
		key: "REGISTERED_PRINCIPAL",
		name: "Registered principal",
		value: "COV",
		description:
			"An individual who is registered as a principal for an entity.",
	},
	{
		key: "FREIGHT_PAYER_ON_BEHALF_OF_THE_CONSIGNOR",
		name: "Freight payer on behalf of the consignor",
		value: "COW",
		description:
			"Freight payer is a third party acting on behalf of the consignor.",
	},
	{
		key: "FREIGHT_PAYER_ON_BEHALF_OF_THE_CONSIGNEE",
		name: "Freight payer on behalf of the consignee",
		value: "COX",
		description:
			"Freight payer is a third party acting on behalf of the consignee.",
	},
	{
		key: "PARTY_RESPONSIBLE_FOR_DISINFECTION",
		name: "Party responsible for disinfection",
		value: "COY",
		description: "Party responsible for performing disinfection operations.",
	},
	{
		key: "PARTY_RESPONSIBLE_FOR_REFUELING",
		name: "Party responsible for refueling",
		value: "COZ",
		description: "Party responsible for performing refueling operations.",
	},
	{
		key: "PARTY_TO_RECEIVE_CERTIFICATE_OF_COMPLIANCE",
		name: "Party to receive certificate of compliance",
		value: "CP",
		description:
			"Party acting for or on behalf of seller in matters concerning compliance.",
	},
	{
		key: "ADVISING_BANK",
		name: "Advising bank",
		value: "CPA",
		description:
			"Identifies the financial institution used by the issuing bank to advise the documentary credit.",
	},
	{
		key: "REIMBURSING_BANK",
		name: "Reimbursing bank",
		value: "CPB",
		description:
			"Identifies the financial institution through which the reimbursement is to be effected.",
	},
	{
		key: "ADVISE_THROUGH_BANK",
		name: "Advise through bank",
		value: "CPC",
		description:
			"Identifies the financial institution through which the advising bank is to advise.",
	},
	{
		key: "CHARGES_PAYER_AT_DESTINATION",
		name: "Charges payer at destination",
		value: "CPD",
		description:
			"Party, other than the ordering party, which has to pay the charges concerning the destination operations.",
	},
	{
		key: "TRANSPORT_MEANS_MASTER_NAME",
		name: "Transport means master name",
		value: "CPE",
		description:
			"[3408] Name of the Master of a means of transport such as vessel.",
	},
	{
		key: "MEANS_OF_TRANSPORT_CHARTERER",
		name: "Means of transport charterer",
		value: "CPF",
		description: "Charterer of the means of transport.",
	},
	{
		key: "EXCISE_PARTY",
		name: "Excise party",
		value: "CPG",
		description: "Party to whom excise must be paid.",
	},
	{
		key: "COPY_REPORT_TO",
		name: "Copy report to",
		value: "CPH",
		description: "Party receiving a copy of a report.",
	},
	{
		key: "RELATED_HEALTHCARE_PARTY",
		name: "Related healthcare party",
		value: "CPI",
		description: "A healthcare party related to the subject.",
	},
	{
		key: "CLINICAL_INFORMATION_PROVIDER",
		name: "Clinical information provider",
		value: "CPJ",
		description: "Party providing clinical information.",
	},
	{
		key: "SERVICE_REQUESTER",
		name: "Service requester",
		value: "CPK",
		description: "Party requesting a service.",
	},
	{
		key: "PATIENT_ADMITTED_BY",
		name: "Patient admitted by",
		value: "CPL",
		description: "Party who admitted a patient.",
	},
	{
		key: "PATIENT_DISCHARGED_TO",
		name: "Patient discharged to",
		value: "CPM",
		description: "The party who receives the discharged patient.",
	},
	{
		key: "PATIENT_HOSTED_BY",
		name: "Patient hosted by",
		value: "CPN",
		description: "The party hosting the patient.",
	},
	{
		key: "PRESCRIBERS_CONTACT_PERSON",
		name: "Prescriber's contact person",
		value: "CPO",
		description: "Contact person for the prescriber.",
	},
	{
		key: "CHEQUE_ORDER",
		name: "Cheque order",
		value: "CQ",
		description:
			"Party to which the cheque will be ordered, when different from the beneficiary.",
	},
	{
		key: "EMPTY_EQUIPMENT_RETURN_PARTY",
		name: "Empty equipment return party",
		value: "CR",
		description:
			"Party to whose premises empty equipment will be or has been returned.",
	},
	{
		key: "CONSOLIDATOR",
		name: "Consolidator",
		value: "CS",
		description: "Party consolidating various consignments, payments etc.",
	},
	{
		key: "CONSIGNEE_TO_BE_SPECIFIED",
		name: "Consignee to be specified",
		value: "CT",
		description: "The party to be identified at a later time as the consignee.",
	},
	{
		key: "CONTAINER_RETURN_COMPANY",
		name: "Container return company",
		value: "CU",
		description: "The company to which containers have to be returned.",
	},
	{
		key: "CONSIGNEE_OF_VESSEL",
		name: "Consignee of vessel",
		value: "CV",
		description: "Party to which the vessel shall be delivered.",
	},
	{
		key: "EQUIPMENT_OWNER",
		name: "Equipment owner",
		value: "CW",
		description: "Owner of equipment (container, etc.).",
	},
	{
		key: "CONSIGNEES_AGENT",
		name: "Consignee's agent",
		value: "CX",
		description: "Party authorized to act on behalf of the consignee.",
	},
	{
		key: "COMMISSIONABLE_AGENT",
		name: "Commissionable agent",
		value: "CY",
		description: "IATA cargo agent entitled to commission.",
	},
	{
		key: "CONSIGNOR",
		name: "Consignor",
		value: "CZ",
		description:
			"[3336] Party which, by contract with a carrier, consigns or sends goods with the carrier, or has them conveyed by him. Synonym: shipper, sender.",
	},
	{
		key: "AVAILABLE_WITH_BANK_DOCUMENTARY_CREDITS",
		name: "Available with bank (documentary credits)",
		value: "DA",
		description:
			"Financial institution with whom the documentary credit is available.",
	},
	{
		key: "DISTRIBUTOR_BRANCH",
		name: "Distributor branch",
		value: "DB",
		description: "The affiliate of a retailer or distributor.",
	},
	{
		key: "DECONSOLIDATOR",
		name: "Deconsolidator",
		value: "DC",
		description:
			"Party that splits up a large consignment composed of separate consignments of goods. The smaller consignments of goods were grouped together into that large consignment for carriage as a larger unit in order to obtain a reduced rate.",
	},
	{
		key: "DESPATCH_CHARGE_PAYER",
		name: "Despatch charge payer",
		value: "DCP",
		description:
			"Party, other than the ordering party, which has to pay the charges concerning the despatch operations.",
	},
	{
		key: "PRESCRIPTION_DATABASE_OWNER",
		name: "Prescription database owner",
		value: "DCQ",
		description: "Organisation or person owning a prescription database.",
	},
	{
		key: "ORIGINAL_PRESCRIBER",
		name: "Original prescriber",
		value: "DCR",
		description: "The doctor who issued the original prescription.",
	},
	{
		key: "TEMPORARY_EMPLOYEE",
		name: "Temporary employee",
		value: "DCS",
		description: "A person employed on a temporary basis.",
	},
	{
		key: "DESIGNER",
		name: "Designer",
		value: "DCT",
		description: "A party who designs.",
	},
	{
		key: "QUOTATION_DELIVERED_TO",
		name: "Quotation delivered to",
		value: "DCU",
		description: "Party to whom the quotation is to be or has been delivered.",
	},
	{
		key: "DEVELOPER",
		name: "Developer",
		value: "DCV",
		description: "A party who develops.",
	},
	{
		key: "TEST_EXECUTION_PARTY",
		name: "Test execution party",
		value: "DCW",
		description: "The party performing a test.",
	},
	{
		key: "PARTY_TO_RECEIVE_REFUND",
		name: "Party to receive refund",
		value: "DCX",
		description: "Party to whom a refund is given.",
	},
	{
		key: "AUTHORISED_ISSUER_OF_PRESCRIPTION",
		name: "Authorised issuer of prescription",
		value: "DCY",
		description: "Party authorised to issue a prescription.",
	},
	{
		key: "AUTHORISED_DISPENSER_OF_MEDICINE",
		name: "Authorised dispenser of medicine",
		value: "DCZ",
		description: "Organisation or person authorised to dispense medicine.",
	},
	{
		key: "DOCUMENTARY_CREDIT_ACCOUNT_PARTYS_BANK",
		name: "Documentary credit account party's bank",
		value: "DD",
		description: "Bank of the documentary credit account party.",
	},
	{
		key: "REPORT_RESPONSIBLE_PARTY",
		name: "Report responsible party",
		value: "DDA",
		description: "The party or person taking responsibility for a report.",
	},
	{
		key: "INITIAL_SENDER",
		name: "Initial sender",
		value: "DDB",
		description: "The party who does the initial sending.",
	},
	{
		key: "THE_PARTY_AUTHORISING_THE_ORIGINAL_PRESCRIPTION",
		name: "The party authorising the original prescription",
		value: "DDC",
		description:
			"The party authorising the issuer of the original prescription.",
	},
	{
		key: "APPLICANT",
		name: "Applicant",
		value: "DDD",
		description: "A party who applies for something.",
	},
	{
		key: "METER_READER",
		name: "Meter reader",
		value: "DDE",
		description: "A party physically reading the meter.",
	},
	{
		key: "PRIMARY_ELECTRONIC_BUSINESS_CONTACT",
		name: "Primary electronic business contact",
		value: "DDF",
		description:
			"Code specifying a party who serves as a business entity's primary contact for matters related to electronic business.",
	},
	{
		key: "ALTERNATE_ELECTRONIC_BUSINESS_CONTACT",
		name: "Alternate electronic business contact",
		value: "DDG",
		description:
			"Code specifying a party who serves as a business entity's alternate contact for matters related to electronic business.",
	},
	{
		key: "PRIMARY_GOVERNMENT_BUSINESS_CONTACT",
		name: "Primary government business contact",
		value: "DDH",
		description:
			"Code specifying a party who serves as a business entity's primary contact for matters related to doing business with the government.",
	},
	{
		key: "ALTERNATE_GOVERNMENT_BUSINESS_CONTACT",
		name: "Alternate government business contact",
		value: "DDI",
		description:
			"Code specifying a party who serves as a business entity's alternate contact for matters related to doing business with the government.",
	},
	{
		key: "PAST_PERFORMANCE_CONTACT",
		name: "Past performance contact",
		value: "DDJ",
		description:
			"Code specifying a party who serves as a business entity's contact for matters related to the past performance of that entity.",
	},
	{
		key: "BALANCE_RESPONSIBLE_PARTY",
		name: "Balance responsible party",
		value: "DDK",
		description: "A party responsible for balancing supply and consumption.",
	},
	{
		key: "GROUP_OF_PASSENGERS",
		name: "Group of passengers",
		value: "DDL",
		description:
			"A group of persons conveyed by a means of transport, other than the crew.",
	},
	{
		key: "GRID_OPERATOR",
		name: "Grid operator",
		value: "DDM",
		description: "A party operating a grid.",
	},
	{
		key: "FIRST_FINANCIAL_INSTITUTION_IN_THE_TRANSACTION_CHAIN",
		name: "First financial institution in the transaction chain",
		value: "DDN",
		description:
			"Identifies the financial institution that is the point of entry into the interbank transaction chain.",
	},
	{
		key: "LOCATION_MANAGER",
		name: "Location manager",
		value: "DDO",
		description: "Party responsible for the management of the location.",
	},
	{
		key: "GROUP_LEADER",
		name: "Group leader",
		value: "DDP",
		description: "Party responsible for leading the group.",
	},
	{
		key: "BALANCE_POWER_SUPPLIER",
		name: "Balance power supplier",
		value: "DDQ",
		description: "The supplier of balance power.",
	},
	{
		key: "CONSIGNORS_FREIGHT_FORWARDER",
		name: "Consignor's freight forwarder",
		value: "DDR",
		description:
			"Identification of freight forwarder giving services to the consignor.",
	},
	{
		key: "CONSIGNEES_FREIGHT_FORWARDER",
		name: "Consignee's freight forwarder",
		value: "DDS",
		description:
			"Identification of freight forwarder giving services to the consignee.",
	},
	{
		key: "IN_TRANSIT_CREW_MEMBER",
		name: "In transit crew member",
		value: "DDT",
		description:
			"The movement of a crew member from one country to another via the territory of an intermediate country for which no entry is intended.",
	},
	{
		key: "IN_TRANSIT_PASSENGER",
		name: "In transit passenger",
		value: "DDU",
		description:
			"The movement of a passenger from one country to another via the territory of an intermediate country for which no entry is intended.",
	},
	{
		key: "ENERGY_CONSUMPTION_IMBALANCE_RESPONSIBLE_PARTY",
		name: "Energy consumption imbalance responsible party",
		value: "DDV",
		description:
			"A party who can be brought to rights, legally and financially, for any imbalance between energy bought and consumed for all associated metering points.",
	},
	{
		key: "ENERGY_PRODUCTION_IMBALANCE_RESPONSIBLE_PARTY",
		name: "Energy production imbalance responsible party",
		value: "DDW",
		description:
			"A party who can be brought to rights, legally and financially, for any imbalance between energy sold and produced for all associated metering points.",
	},
	{
		key: "IMBALANCE_SETTLEMENT_RESPONSIBLE_PARTY",
		name: "Imbalance settlement responsible party",
		value: "DDX",
		description:
			"A party that is responsible for settlement of the difference between planned and realised quantities.",
	},
	{
		key: "TRANSMISSION_CAPACITY_ALLOCATOR",
		name: "Transmission capacity allocator",
		value: "DDY",
		description: "A party managing the allocation of transmission capacity.",
	},
	{
		key: "METERING_POINT_ADMINISTRATOR",
		name: "Metering point administrator",
		value: "DDZ",
		description:
			"A party responsible for registering the technical specifications of metering points and the parties linked to them.",
	},
	{
		key: "DEPOSITOR",
		name: "Depositor",
		value: "DE",
		description: "Party depositing goods, financial payments or documents.",
	},
	{
		key: "METERED_DATA_AGGREGATOR",
		name: "Metered data aggregator",
		value: "DEA",
		description: "A party responsible for aggregation of metered data.",
	},
	{
		key: "METER_OPERATOR",
		name: "Meter operator",
		value: "DEB",
		description:
			"A party responsible for the operation of a meter, including installing  maintaining, testing, certifying and decommissioning.",
	},
	{
		key: "PARTY_CONNECTED_TO_GRID",
		name: "Party connected to grid",
		value: "DEC",
		description:
			"A party that contracts for the right to consume or produce electricity at a metering point.",
	},
	{
		key: "PROFILE_MAINTENANCE_PARTY",
		name: "Profile maintenance party",
		value: "DED",
		description: "A party that maintains profiles.",
	},
	{
		key: "STOWAWAY",
		name: "Stowaway",
		value: "DEE",
		description:
			"A person who hides on a conveyance in order to obtain free passage.",
	},
	{
		key: "MEAT_CUTTER",
		name: "Meat cutter",
		value: "DEF",
		description: "Person whose job is to cut up and/or mince meat.",
	},
	{
		key: "CONSORTIUM_CARRIER_MARITIME",
		name: "Consortium Carrier (maritime)",
		value: "DEG",
		description:
			"A marine carrier that transports goods for more than one shipping line between named points.",
	},
	{
		key: "NON_VESSEL_OPERATING_CARRIER",
		name: "Non-vessel operating carrier",
		value: "DEH",
		description: "A carrier that does not operate the vessel.",
	},
	{
		key: "MEANS_OF_TRANSPORT_OPERATOR",
		name: "Means of transport operator",
		value: "DEI",
		description:
			"The operator of a means of transport, e.g. the captain of a vessel.",
	},
	{
		key: "STUFFING_ADDRESS",
		name: "Stuffing address",
		value: "DEJ",
		description:
			"Address where cargo is loaded into the transport equipment e.g. container. Synonyms; vanning address / place of vanning.",
	},
	{
		key: "MOORING_SERVICE_PROVIDER",
		name: "Mooring service provider",
		value: "DEK",
		description:
			"Party responsible for mooring the vessel at the berth in the port. Synonym: Boatmen.",
	},
	{
		key: "PILOTAGE_SERVICE_PROVIDER",
		name: "Pilotage service provider",
		value: "DEL",
		description: "Party responsible for the pilotage of the vessel.",
	},
	{
		key: "BERTH_TOWAGE_SERVICE_PROVIDER",
		name: "Berth towage service provider",
		value: "DEM",
		description:
			"Party responsible for towing the vessel to/from the berth in the port.",
	},
	{
		key: "AGENT_REPRESENTATIVE_DIRECT_REPRESENTATION",
		name: "Agent/representative, direct representation",
		value: "DEN",
		description:
			"Party authorised to act in the name and on behalf of another person.",
	},
	{
		key: "AGENT_REPRESENTATIVE_INDIRECT_REPRESENTATION",
		name: "Agent/representative, indirect representation",
		value: "DEO",
		description:
			"Party authorised to act in its own name but on behalf of another person.",
	},
	{
		key: "STEVEDORE",
		name: "Stevedore",
		value: "DEP",
		description:
			"A party which handles the loading and unloading of marine vessels from several terminals. +    DEQ   Shipper Party responsible for the shipment of goods.",
	},
	{
		key: "DOCUMENTARY_CREDIT_APPLICANT",
		name: "Documentary credit applicant",
		value: "DF",
		description:
			"Party at whose request the applicant's bank/issuing bank is to issue a documentary credit.",
	},
	{
		key: "DOCUMENTARY_CREDIT_BENEFICIARY",
		name: "Documentary credit beneficiary",
		value: "DG",
		description:
			"Party in whose favour the documentary credit is to be issued and the party that must comply with the credit's terms and conditions.",
	},
	{
		key: "DOCUMENTARY_CREDIT_ACCOUNT_PARTY",
		name: "Documentary credit account party",
		value: "DH",
		description:
			"Party which is responsible for the payment settlement of the documentary credit with the applicant's bank/issuing bank, if different from the documentary credit applicant.",
	},
	{
		key: "DOCUMENTARY_CREDIT_SECOND_BENEFICIARY",
		name: "Documentary credit second beneficiary",
		value: "DI",
		description: "Party to whom the documentary credit can be transferred.",
	},
	{
		key: "PARTY_ACCORDING_TO_DOCUMENTARY_CREDIT_TRANSACTION",
		name: "Party according to documentary credit transaction",
		value: "DJ",
		description: "Party related to documentary credit transaction.",
	},
	{
		key: "DOCUMENTARY_CREDIT_BENEFICIARYS_BANK",
		name: "Documentary credit beneficiary's bank",
		value: "DK",
		description:
			"Financial institution with which the beneficiary of the documentary credit maintains an account.",
	},
	{
		key: "FACTOR",
		name: "Factor",
		value: "DL",
		description:
			"Company offering a financial service whereby a firm sells or transfers title to its accounts receivable to the factoring company.",
	},
	{
		key: "PARTY_TO_WHOM_DOCUMENTS_ARE_TO_BE_PRESENTED",
		name: "Party to whom documents are to be presented",
		value: "DM",
		description: "Party to whom documents are to be presented.",
	},
	{
		key: "OWNER_OF_OPERATION",
		name: "Owner of operation",
		value: "DN",
		description: "Owner of the operation.",
	},
	{
		key: "DOCUMENT_RECIPIENT",
		name: "Document recipient",
		value: "DO",
		description: "[1370] Party which should receive a specified document.",
	},
	{
		key: "DELIVERY_PARTY",
		name: "Delivery party",
		value: "DP",
		description:
			"[3144] Party to which goods should be delivered, if not identical with consignee, such as the place where a container is to be, or has been, positioned.",
	},
	{
		key: "OWNERS_AGENT",
		name: "Owner's agent",
		value: "DQ",
		description: "Person acting on delegation of powers of the owner.",
	},
	{
		key: "DRIVER",
		name: "Driver",
		value: "DR",
		description: "Person who drives a means of transport.",
	},
	{
		key: "DISTRIBUTOR",
		name: "Distributor",
		value: "DS",
		description: "Party distributing goods, financial payments or documents.",
	},
	{
		key: "DECLARANT",
		name: "Declarant",
		value: "DT",
		description:
			"[3140] Party which makes a declaration to an official body or - where legally permitted - in whose name, or on whose behalf, a declaration to an official body is made.",
	},
	{
		key: "OWNERS_REPRESENTATIVE",
		name: "Owner's representative",
		value: "DU",
		description:
			"Person commissioned by the owner to represent him in certain circumstances.",
	},
	{
		key: "PROJECT_MANAGEMENT_OFFICE",
		name: "Project management office",
		value: "DV",
		description:
			"Party commissioned by the owner to follow through the execution of all works.",
	},
	{
		key: "DRAWEE",
		name: "Drawee",
		value: "DW",
		description: "Party on whom drafts must be drawn.",
	},
	{
		key: "ENGINEER_CONSTRUCTION",
		name: "Engineer (construction)",
		value: "DX",
		description:
			"Party representing the contractor to advise and supervise engineering aspects of the works.",
	},
	{
		key: "ENGINEER_RESIDENT_CONSTRUCTION",
		name: "Engineer, resident (construction)",
		value: "DY",
		description:
			"Party commissioned by the owner to advise and supervise engineering aspects of the works.",
	},
	{
		key: "ARCHITECT",
		name: "Architect",
		value: "DZ",
		description:
			"A designer who prepares plans for buildings, ships, etc. and supervises their construction.",
	},
	{
		key: "ARCHITECT_DESIGNER",
		name: "Architect-designer",
		value: "EA",
		description: "Designer of the construction project.",
	},
	{
		key: "BUILDING_INSPECTORATE",
		name: "Building inspectorate",
		value: "EB",
		description:
			"Party controlling the conformity of works to legal and regulation rules.",
	},
	{
		key: "EXCHANGER",
		name: "Exchanger",
		value: "EC",
		description: "Party exchanging currencies or goods.",
	},
	{
		key: "ENGINEER_CONSULTANT",
		name: "Engineer, consultant",
		value: "ED",
		description: "Party providing professional engineering services.",
	},
	{
		key: "LOCATION_OF_GOODS_FOR_CUSTOMS_EXAMINATION_BEFORE_CLEARANCE",
		name: "Location of goods for customs examination before clearance",
		value: "EE",
		description:
			"The location where the goods are examined by customs before clearance.",
	},
	{
		key: "PROJECT_COORDINATION_OFFICE",
		name: "Project coordination office",
		value: "EF",
		description: "Party responsible for technical coordination of works.",
	},
	{
		key: "SURVEYOR_TOPOGRAPHICAL",
		name: "Surveyor, topographical",
		value: "EG",
		description: "Party responsible for topographical measurements.",
	},
	{
		key: "ENGINEER_MEASUREMENT",
		name: "Engineer, measurement",
		value: "EH",
		description: "Party responsible for quantity measurements.",
	},
	{
		key: "CONTROLLER_QUALITY",
		name: "Controller, quality",
		value: "EI",
		description:
			"Party controlling the quality of goods and workmanship for the project.",
	},
	{
		key: "SURVEYOR_QUANTITY",
		name: "Surveyor, quantity",
		value: "EJ",
		description:
			"Party responsible for the quantification and valuation of the works on behalf of the contractor.",
	},
	{
		key: "SURVEYOR_PROFESSIONAL_QUANTITY",
		name: "Surveyor (professional), quantity",
		value: "EK",
		description:
			"Party responsible to the owner for the quantification and valuation of the works.",
	},
	{
		key: "PROJECT",
		name: "Project",
		value: "EL",
		description:
			"Party responsible for a project, e.g. a construction project.",
	},
	{
		key: "PARTY_TO_RECEIVE_ELECTRONIC_MEMO_OF_INVOICE",
		name: "Party to receive electronic memo of invoice",
		value: "EM",
		description: "Party being informed about invoice issue (via EDI).",
	},
	{
		key: "TENDERER",
		name: "Tenderer",
		value: "EN",
		description: "Firm answering an invitation to tender.",
	},
	{
		key: "OWNER_OF_EQUIPMENT",
		name: "Owner of equipment",
		value: "EO",
		description: "Party who owns equipment.",
	},
	{
		key: "EQUIPMENT_DROP_OFF_PARTY",
		name: "Equipment drop-off party",
		value: "EP",
		description: "The party which drops off equipment.",
	},
	{
		key: "EMPTY_CONTAINER_RESPONSIBLE_PARTY",
		name: "Empty container responsible party",
		value: "EQ",
		description: "Party responsible for the empty container.",
	},
	{
		key: "EMPTY_CONTAINER_RETURN_AGENT",
		name: "Empty container return agent",
		value: "ER",
		description:
			"Party, designated by owner of containers, responsible for their collection as agreed between the owner and customer/ consignee.",
	},
	{
		key: "CONTRACTOR_LEAD",
		name: "Contractor, lead",
		value: "ES",
		description: "Leader representing a grouping of co-contractors.",
	},
	{
		key: "CO_CONTRACTOR",
		name: "Co-contractor",
		value: "ET",
		description: "Member of a grouping of co-contractors.",
	},
	{
		key: "CONTRACTOR_GENERAL",
		name: "Contractor, general",
		value: "EU",
		description:
			"Single contractor for the whole construction project, working by his own or with subcontractors.",
	},
	{
		key: "SUBCONTRACTOR",
		name: "Subcontractor",
		value: "EV",
		description: "Firm carrying out a part of the works for a contractor.",
	},
	{
		key: "SUBCONTRACTOR_WITH_DIRECT_PAYMENT",
		name: "Subcontractor with direct payment",
		value: "EW",
		description: "Subcontractor benefiting from direct payments.",
	},
	{
		key: "EXPORTER",
		name: "Exporter",
		value: "EX",
		description:
			"[3030] Party who makes, or on whose behalf the export declaration is made, and who is the owner of the goods or has similar rights of disposal over them at the time when the declaration is accepted.",
	},
	{
		key: "SUBCONTRACTOR_NOMINATED",
		name: "Subcontractor, nominated",
		value: "EY",
		description:
			"Subcontractor authorized by the owner after having been proposed.",
	},
	{
		key: "OPERATOR_ESSENTIAL_SERVICES",
		name: "Operator, essential services",
		value: "EZ",
		description:
			"Operator of essential services e.g. water, sewerage system, power.",
	},
	{
		key: "OPERATOR_COMMUNICATION_CHANNEL",
		name: "Operator, communication channel",
		value: "FA",
		description: "Operator of a communication channel.",
	},
	{
		key: "NOMINATED_FREIGHT_COMPANY",
		name: "Nominated freight company",
		value: "FB",
		description:
			"Party nominated to act as transport company or carrier for the goods.",
	},
	{
		key: "CONTRACTOR_MAIN",
		name: "Contractor, main",
		value: "FC",
		description:
			"Firm or grouping of co-contractors which has been awarded the contract.",
	},
	{
		key: "BUYERS_PARENT_COMPANY",
		name: "Buyer's parent company",
		value: "FD",
		description: "Parent company, e.g. holding company.",
	},
	{
		key: "CREDIT_RATING_AGENCY",
		name: "Credit rating agency",
		value: "FE",
		description: "A party which evaluates another party for credit rating.",
	},
	{
		key: "FACTOR_CORRESPONDENT",
		name: "Factor, correspondent",
		value: "FF",
		description:
			"Factoring company engaged by another factoring company to assist the letter with the services provided to the clients (sellers).",
	},
	{
		key: "BUYER_AS_OFFICIALLY_REGISTERED",
		name: "Buyer as officially registered",
		value: "FG",
		description: "Buying party as officially registered with government.",
	},
	{
		key: "SELLER_AS_OFFICIALLY_REGISTERED",
		name: "Seller as officially registered",
		value: "FH",
		description: "Selling party as officially registered with government.",
	},
	{
		key: "COPY_MESSAGE_TO",
		name: "Copy message to",
		value: "FI",
		description: "Party that is to receive a copy of a message.",
	},
	{
		key: "TRADE_UNION",
		name: "Trade Union",
		value: "FJ",
		description: "Organisation representing employees.",
	},
	{
		key: "PREVIOUS_TRADE_UNION",
		name: "Previous Trade Union",
		value: "FK",
		description:
			"Employee organisation who previously represented an employee .",
	},
	{
		key: "PASSENGER",
		name: "Passenger",
		value: "FL",
		description:
			"A person conveyed by a means of transport, other than the crew.",
	},
	{
		key: "CREW_MEMBER",
		name: "Crew member",
		value: "FM",
		description: "A person manning a means of transport.",
	},
	{
		key: "TARIFF_ISSUER",
		name: "Tariff issuer",
		value: "FN",
		description: "The issuer of a tariff, e.g. a freight tariff.",
	},
	{
		key: "PARTY_PERFORMING_INSPECTION",
		name: "Party performing inspection",
		value: "FO",
		description: "A party which inspects something.",
	},
	{
		key: "FREIGHT_CHARGES_PAYER",
		name: "Freight/charges payer",
		value: "FP",
		description: "Party responsible for the payment of freight.",
	},
	{
		key: "CONTAINER_SURVEY_AGENT",
		name: "Container survey agent",
		value: "FQ",
		description: "The container survey agency that will survey the containers.",
	},
	{
		key: "MESSAGE_FROM",
		name: "Message from",
		value: "FR",
		description: "Party where the message comes from.",
	},
	{
		key: "PARTY_AUTHORIZED_TO_MAKE_DEFINITE_A_CONTRACT_ACTION",
		name: "Party authorized to make definite a contract action",
		value: "FS",
		description:
			"Party who has the authority to make definite a contract action.",
	},
	{
		key: "FINANCIAL_SETTLEMENT_PARTY",
		name: "Financial settlement party",
		value: "FT",
		description:
			"[3450] Party responsible for either the transfer or repatriation of the funds relating to a transaction.",
	},
	{
		key: "HAZARDOUS_MATERIAL_OFFICE",
		name: "Hazardous material office",
		value: "FU",
		description:
			"The office responsible for providing information regarding hazardous material.",
	},
	{
		key: "PARTY_PROVIDING_GOVERNMENT_FURNISHED_PROPERTY",
		name: "Party providing government furnished property",
		value: "FV",
		description:
			"The party responsible for providing government furnished property.",
	},
	{
		key: "FREIGHT_FORWARDER",
		name: "Freight forwarder",
		value: "FW",
		description: "Party arranging forwarding of goods.",
	},
	{
		key: "CURRENT_RECEIVER",
		name: "Current receiver",
		value: "FX",
		description:
			"Current receiver of the goods in a multi-step transportation process (indirect flow) involving at least one grouping centre.",
	},
	{
		key: "CURRENT_SENDER",
		name: "Current sender",
		value: "FY",
		description:
			"Current sender of the goods in a multi-step transportation process (indirect flow) involving at least one grouping centre.",
	},
	{
		key: "GROUPING_CENTRE",
		name: "Grouping centre",
		value: "FZ",
		description:
			"A party in charge of groupage, including degroupage and regroupage.",
	},
	{
		key: "ROAD_CARRIER",
		name: "Road carrier",
		value: "GA",
		description: "A road carrier moving cargo.",
	},
	{
		key: "CHAMBER_OF_COMMERCE",
		name: "Chamber of commerce",
		value: "GB",
		description:
			"Name of the Chamber of Commerce of the town where the company is registered.",
	},
	{
		key: "GOODS_CUSTODIAN",
		name: "Goods custodian",
		value: "GC",
		description: "[3024] Party responsible for the keeping of goods.",
	},
	{
		key: "PRODUCER",
		name: "Producer",
		value: "GD",
		description: "Party or person who has produced the produce.",
	},
	{
		key: "REGISTRATION_TRIBUNAL",
		name: "Registration tribunal",
		value: "GE",
		description: "Name of the tribunal where the company is registered.",
	},
	{
		key: "SLOT_CHARTER_PARTY",
		name: "Slot charter party",
		value: "GF",
		description:
			"An identification code of a participant or user that books slots (space) on a ship, more likely on a long term basis on a series of sailings. He pays for the space whether he uses it or not.",
	},
	{
		key: "APPLICANT_FOR_JOB",
		name: "Applicant for job",
		value: "GH",
		description: "A person who applied for a job.",
	},
	{
		key: "SPOUSE",
		name: "Spouse",
		value: "GI",
		description: "Person is a spouse.",
	},
	{
		key: "MOTHER",
		name: "Mother",
		value: "GJ",
		description: "Person is a mother.",
	},
	{
		key: "FATHER",
		name: "Father",
		value: "GK",
		description: "Person is a father.",
	},
	{
		key: "SOCIALLY_INSURED_PERSON",
		name: "Socially insured person",
		value: "GL",
		description: "A person who is registered in a social security scheme.",
	},
	{
		key: "INVENTORY_CONTROLLER",
		name: "Inventory controller",
		value: "GM",
		description:
			"To specifically identify the party in charge of inventory control.",
	},
	{
		key: "PROCESSOR",
		name: "Processor",
		value: "GN",
		description: "Party or person who has or will apply a process.",
	},
	{
		key: "GOODS_OWNER",
		name: "Goods owner",
		value: "GO",
		description: "The party which owns the goods.",
	},
	{
		key: "PACKER",
		name: "Packer",
		value: "GP",
		description:
			"Party or person who has undertaken or will undertake packing.",
	},
	{
		key: "SLAUGHTERER",
		name: "Slaughterer",
		value: "GQ",
		description:
			"Party or person who has undertaken or will undertake a slaughter.",
	},
	{
		key: "GOODS_RELEASING_PARTY",
		name: "Goods releasing party",
		value: "GR",
		description:
			"[3026] Party entitled to authorize release of goods from custodian.",
	},
	{
		key: "CONSIGNORS_REPRESENTATIVE",
		name: "Consignor's representative",
		value: "GS",
		description: "Party authorised to represent the consignor.",
	},
	{
		key: "RAIL_CARRIER",
		name: "Rail carrier",
		value: "GT",
		description: "A carrier moving cargo, including containers, via rail.",
	},
	{
		key: "ORIGINATOR_OF_ARTICLE_NUMBER",
		name: "Originator of article number",
		value: "GU",
		description:
			"A code identifying the party which created a specific article number.",
	},
	{
		key: "PROCUREMENT_RESPONSIBILITY_FOR_ORDER",
		name: "Procurement responsibility for order",
		value: "GV",
		description:
			"A code used to identify the organization which is responsible for the procurement.",
	},
	{
		key: "PARTY_FULFILLING_ALL_OPERATIONS",
		name: "Party fulfilling all operations",
		value: "GW",
		description:
			"Code indicating the fact that the party identified carries out all operations within that company's activities.",
	},
	{
		key: "CENTRAL_CATALOGUE_PARTY",
		name: "Central catalogue party",
		value: "GX",
		description: "Party controlling a central catalogue.",
	},
	{
		key: "INVENTORY_REPORTING_PARTY",
		name: "Inventory reporting party",
		value: "GY",
		description: "Party reporting inventory information.",
	},
	{
		key: "SUBSTITUTE_SUPPLIER",
		name: "Substitute supplier",
		value: "GZ",
		description:
			"Party which may be in a position to supply products or services should the main usual supplier be unable to do so.",
	},
	{
		key: "PARTY_WHICH_DELIVERS_CONSIGNMENTS_TO_THE_TERMINAL",
		name: "Party which delivers consignments to the terminal",
		value: "HA",
		description: "Party which delivers consignments to a terminal.",
	},
	{
		key: "PARTY_WHICH_PICKS_UP_CONSIGNMENTS_FROM_THE_TERMINAL",
		name: "Party which picks up consignments from the terminal",
		value: "HB",
		description: "Party which picks up consignments from a terminal.",
	},
	{
		key: "TRANSIT_FREIGHT_FORWARDER",
		name: "Transit freight forwarder",
		value: "HC",
		description:
			"Freight forwarder to whom transit consignments are addressed, and from whom they are to be on-forwarded.",
	},
	{
		key: "INSPECTION_AND_ACCEPTANCE_PARTY",
		name: "Inspection and acceptance party",
		value: "HD",
		description: "The party who will perform inspection and acceptance.",
	},
	{
		key: "TRANSPORTATION_OFFICE",
		name: "Transportation office",
		value: "HE",
		description: "The office that provides transportation information.",
	},
	{
		key: "CONTRACT_ADMINISTRATION_OFFICE",
		name: "Contract administration office",
		value: "HF",
		description: "The office responsible for the administration of a contract.",
	},
	{
		key: "INVESTIGATOR",
		name: "Investigator",
		value: "HG",
		description: "A party who conducts investigations.",
	},
	{
		key: "AUDIT_OFFICE",
		name: "Audit office",
		value: "HH",
		description: "The office responsible for conducting audits.",
	},
	{
		key: "REQUESTOR",
		name: "Requestor",
		value: "HI",
		description: "The party requesting an action.",
	},
	{
		key: "FOREIGN_DISCLOSURE_INFORMATION_OFFICE",
		name: "Foreign disclosure information office",
		value: "HJ",
		description:
			"The office that reviews sensitive information for foreign disclosure.",
	},
	{
		key: "MARK_FOR_PARTY",
		name: "Mark-for party",
		value: "HK",
		description:
			"The party within an organization for whom the material is marked to be delivered.",
	},
	{
		key: "PARTY_TO_RECEIVE_REPORTS",
		name: "Party to receive reports",
		value: "HL",
		description: "The party to whom reports are to be submitted.",
	},
	{
		key: "ALTERNATIVE_MANUFACTURER",
		name: "Alternative manufacturer",
		value: "HM",
		description:
			"Party identification of an alternative manufacturer for a product.",
	},
	{
		key: "SERVICE_PERFORMER",
		name: "Service performer",
		value: "HN",
		description: "The party who is performing a service.",
	},
	{
		key: "SHIPPERS_ASSOCIATION",
		name: "Shipper's association",
		value: "HO",
		description: "An association of shippers.",
	},
	{
		key: "FINAL_MESSAGE_RECIPIENT",
		name: "Final message recipient",
		value: "HP",
		description: "To identify the final recipient of the message.",
	},
	{
		key: "ACCOUNT_OWNER",
		name: "Account owner",
		value: "HQ",
		description: "Identifies the owner of the account.",
	},
	{
		key: "SHIPPING_LINE_SERVICE",
		name: "Shipping line service",
		value: "HR",
		description: "Identifies the shipping line service organization.",
	},
	{
		key: "CREDITOR",
		name: "Creditor",
		value: "HS",
		description: "Party to whom payment is due.",
	},
	{
		key: "CLEARING_HOUSE",
		name: "Clearing house",
		value: "HT",
		description: "Institution through which funds will be paid.",
	},
	{
		key: "ORDERING_BANK",
		name: "Ordering bank",
		value: "HU",
		description:
			"Bank which instructed the sender to act on the transaction(s).",
	},
	{
		key: "RECEIVER_OF_FUNDS",
		name: "Receiver of funds",
		value: "HV",
		description: "Identifies the financial party that receives the funds.",
	},
	{
		key: "SENDER_OF_FUNDS",
		name: "Sender of funds",
		value: "HW",
		description: "Identifies the party that sends the funds.",
	},
	{
		key: "DEBTOR",
		name: "Debtor",
		value: "HX",
		description: "Party from whom payment is due.",
	},
	{
		key: "PRESENTING_BANK",
		name: "Presenting bank",
		value: "HY",
		description: "The bank which presents documents to the drawee.",
	},
	{
		key: "WORK_TEAM",
		name: "Work team",
		value: "HZ",
		description: "Team responsible for performing work.",
	},
	{
		key: "INTERMEDIARY_BANK_1",
		name: "Intermediary bank 1",
		value: "I1",
		description:
			"A financial institution between the ordered bank and the beneficiary's bank.",
	},
	{
		key: "INTERMEDIARY_BANK_2",
		name: "Intermediary bank 2",
		value: "I2",
		description:
			"A financial institution between the ordered bank and the beneficiary's bank.",
	},
	{
		key: "INTERMEDIARY_BROKER",
		name: "Intermediary/broker",
		value: "IB",
		description:
			"A person intervening between parties to produce agreement or reconciliation.",
	},
	{
		key: "INTERMEDIATE_CONSIGNEE",
		name: "Intermediate consignee",
		value: "IC",
		description: "The intermediate consignee.",
	},
	{
		key: "REPLACING_MANUFACTURER",
		name: "Replacing manufacturer",
		value: "ID",
		description:
			"A code used to identify a party who replaces the previous party for the manufacture of an article.",
	},
	{
		key: "NON_RESIDENT_THIRD_PARTY_COMPANY_WITH_WHOM_FINANCIAL",
		name: "Non-resident third party company with whom financial",
		value: "IE",
		description:
			"account is held Identifies the non-resident third party company with whom the financial account is held.",
	},
	{
		key: "NON_RESIDENT_GROUP_COMPANY_WITH_WHOM_FINANCIAL_ACCOUNT_IS",
		name: "Non-resident group company with whom financial account is",
		value: "IF",
		description:
			"held Identifies the non-resident group company with whom the financial account is held.",
	},
	{
		key: "NON_RESIDENT_BENEFICIARY",
		name: "Non-resident beneficiary",
		value: "IG",
		description:
			"The ultimate non-resident recipient of the funds. Normally the account owner who is reimbursed by the payer.",
	},
	{
		key: "RESIDENT_BENEFICIARY",
		name: "Resident beneficiary",
		value: "IH",
		description:
			"The ultimate resident recipient of the funds. Normally the account owner who is reimbursed by the payer.",
	},
	{
		key: "INVOICE_ISSUER",
		name: "Invoice issuer",
		value: "II",
		description: "[3028] Party issuing an invoice.",
	},
	{
		key: "NON_RESIDENT_INSTRUCTING_PARTY",
		name: "Non-resident instructing party",
		value: "IJ",
		description:
			"Identifies the non-resident party originating the instruction.",
	},
	{
		key: "RESIDENT_INSTRUCTING_PARTY",
		name: "Resident instructing party",
		value: "IL",
		description: "Identifies the resident party originating the instruction.",
	},
	{
		key: "IMPORTER",
		name: "Importer",
		value: "IM",
		description:
			"[3020] Party who makes - or on whose behalf a Customs clearing agent or other authorized person makes - an import declaration. This may include a person who has possession of the goods or to whom the goods are consigned.",
	},
	{
		key: "INSURER",
		name: "Insurer",
		value: "IN",
		description:
			"A person or company offering insurance policies for premiums.",
	},
	{
		key: "INSURANCE_COMPANY",
		name: "Insurance company",
		value: "IO",
		description: "A company engaged in the business of insurance.",
	},
	{
		key: "INSURANCE_CLAIM_ADJUSTER",
		name: "Insurance claim adjuster",
		value: "IP",
		description: "A party which adjusts losses on behalf of an insurer.",
	},
	{
		key: "DOMESTIC_FINANCIAL_INSTITUTION",
		name: "Domestic financial institution",
		value: "IQ",
		description: "Domestic party acting as financial institution.",
	},
	{
		key: "NON_DOMESTIC_FINANCIAL_INSTITUTION",
		name: "Non-domestic financial institution",
		value: "IR",
		description: "Non-domestic party acting as financial institution.",
	},
	{
		key: "PARTY_TO_RECEIVE_CERTIFIED_INSPECTION_REPORT",
		name: "Party to receive certified inspection report",
		value: "IS",
		description: "Party (at buyer) to receive certified inspection report.",
	},
	{
		key: "INSTALLATION_ON_SITE",
		name: "Installation on site",
		value: "IT",
		description:
			"A party who possesses the site on which an installation shall be made.",
	},
	{
		key: "NON_RESIDENT_DEBTOR",
		name: "Non-resident debtor",
		value: "IU",
		description:
			"Non-resident party who makes the payment or against whom a claim exists.",
	},
	{
		key: "INVOICEE",
		name: "Invoicee",
		value: "IV",
		description: "[3006] Party to whom an invoice is issued.",
	},
	{
		key: "NON_RESIDENT_CREDITOR",
		name: "Non-resident creditor",
		value: "IW",
		description:
			"Non-resident party receiving the payment or against whom a liability exists.",
	},
	{
		key: "SUPPLIER_WORK_TEAM",
		name: "Supplier work team",
		value: "IX",
		description: "The supplier's team responsible for performing the work.",
	},
	{
		key: "TENANT_MANAGER",
		name: "Tenant manager",
		value: "IY",
		description:
			"A code to identify the party who rents the rights to use the goodwill and facilities of an enterprise.",
	},
	{
		key: "PARTY_MANDATED_TO_LIQUIDATE_AN_ENTERPRISE",
		name: "Party mandated to liquidate an enterprise",
		value: "IZ",
		description:
			"A code to identify the party who has been legally mandated to sell off an enterprise.",
	},
	{
		key: "CERTIFIED_ACCOUNTANT",
		name: "Certified accountant",
		value: "JA",
		description: "Code identifying the party as a certified accountant.",
	},
	{
		key: "GOODS_COLLECTION_PARTY",
		name: "Goods collection party",
		value: "JB",
		description: "Party that will collect or has collected the goods.",
	},
	{
		key: "PARTY_AT_FINAL_PLACE_OF_POSITIONING",
		name: "Party at final place of positioning",
		value: "JC",
		description: "Identifies the party at the final place of positioning.",
	},
	{
		key: "CUSTOMS_OFFICE_OF_CLEARANCE",
		name: "Customs office of clearance",
		value: "JD",
		description:
			"Identifies the office where customs clearance procedures take place.",
	},
	{
		key: "PARTY_FROM_WHOM_CUSTOMS_DOCUMENTS_ARE_TO_BE_PICKED_UP",
		name: "Party from whom customs documents are to be picked up",
		value: "JE",
		description:
			"Identification of the party from whom customs documents are to be picked up.",
	},
	{
		key: "PARTY_FROM_WHOM_NON_CUSTOMS_DOCUMENTS_ARE_TO_BE_PICKED_UP",
		name: "Party from whom non-customs documents are to be picked up",
		value: "JF",
		description:
			"Identification of the party from whom non-customs documents are to be picked up.",
	},
	{
		key: "PARTY_TO_RECEIVE_CUSTOMS_DOCUMENTS",
		name: "Party to receive customs documents",
		value: "JG",
		description:
			"Identification of the party to whom customs documents are to be delivered.",
	},
	{
		key: "PARTY_TO_RECEIVE_NON_CUSTOMS_DOCUMENTS",
		name: "Party to receive non-customs documents",
		value: "JH",
		description:
			"Identification of the party to whom non-customs documents are to be delivered.",
	},
	{
		key: "PARTY_DESIGNATED_TO_PROVIDE_LIVING_ANIMAL_CARE",
		name: "Party designated to provide living animal care",
		value: "LA",
		description:
			"Party responsible to take care of transported living animals.",
	},
	{
		key: "CO_PRODUCER",
		name: "Co-producer",
		value: "LB",
		description:
			"A code used to identify a party who participates in production.",
	},
	{
		key: "PARTY_DECLARING_THE_VALUE_ADDED_TAX_VAT",
		name: "Party declaring the Value Added Tax (VAT)",
		value: "LC",
		description:
			"A code to identify the party who is responsible for declaring the Value Added Tax (VAT) on the sale of goods or services.",
	},
	{
		key: "PARTY_RECOVERING_THE_VALUE_ADDED_TAX_VAT",
		name: "Party recovering the Value Added Tax (VAT)",
		value: "LD",
		description:
			"A code to identify the party who is eligible to recover the Value Added Tax (VAT) on the sale of goods or services.",
	},
	{
		key: "PERSON_ON_CLAIM",
		name: "Person on claim",
		value: "LE",
		description: "To identify the person who is the subject of the claim.",
	},
	{
		key: "BUYERS_CORPORATE_OFFICE",
		name: "Buyer's corporate office",
		value: "LF",
		description: "The identification of the buyer's corporate office.",
	},
	{
		key: "SUPPLIERS_CORPORATE_OFFICE",
		name: "Supplier's corporate office",
		value: "LG",
		description: "The identification of the supplier's corporate office.",
	},
	{
		key: "LIQUIDATOR",
		name: "Liquidator",
		value: "LH",
		description: "The party responsible for settling or paying a debt.",
	},
	{
		key: "ACCOUNT_COORDINATOR",
		name: "Account coordinator",
		value: "LI",
		description:
			"An individual with coordination responsibilities for a specific account.",
	},
	{
		key: "INSPECTION_LEADER",
		name: "Inspection leader",
		value: "LJ",
		description: "An individual responsible for an inspection team.",
	},
	{
		key: "PATIENT",
		name: "Patient",
		value: "LK",
		description:
			"A person receiving or registered to receive medical treatment.",
	},
	{
		key: "PATIENT_COMPANION",
		name: "Patient companion",
		value: "LL",
		description: "Person accompanying the patient.",
	},
	{
		key: "MEDICAL_TREATMENT_EXECUTANT",
		name: "Medical treatment executant",
		value: "LM",
		description: "The party who executes a medical treatment.",
	},
	{
		key: "LENDER",
		name: "Lender",
		value: "LN",
		description: "Party lending goods or equipment.",
	},
	{
		key: "MEDICAL_TREATMENT_PRESCRIBER",
		name: "Medical treatment prescriber",
		value: "LO",
		description: "The party who prescribes a medical treatment.",
	},
	{
		key: "LOADING_PARTY",
		name: "Loading party",
		value: "LP",
		description: "Party responsible for the loading when other than carrier.",
	},
	{
		key: "DEBT_PAYMENT_AUTHORISATION_PARTY",
		name: "Debt payment authorisation party",
		value: "LQ",
		description: "A party which authorises the payment of a debt.",
	},
	{
		key: "ADMINISTRATION_CENTRE",
		name: "Administration centre",
		value: "LR",
		description: "Identification of an administration centre.",
	},
	{
		key: "PRODUCT_SERVICES_AND_REPAIRS_CENTRE",
		name: "Product services and repairs centre",
		value: "LS",
		description: "A centre which services and repairs products.",
	},
	{
		key: "SECRETARIAT",
		name: "Secretariat",
		value: "LT",
		description: "Party is a secretariat.",
	},
	{
		key: "ENTRY_POINT_TECHNICAL_ASSESSMENT_GROUP",
		name: "Entry point technical assessment group",
		value: "LU",
		description: "Party acts as an entry point for technical assessment.",
	},
	{
		key: "PARTY_ASSIGNING_A_STATUS",
		name: "Party assigning a status",
		value: "LV",
		description: "Party responsible for assigning a status.",
	},
	{
		key: "PARTY_FOR_WHOM_ITEM_IS_ULTIMATELY_INTENDED",
		name: "Party for whom item is ultimately intended",
		value: "MA",
		description: "Party for whom item is ultimately intended.",
	},
	{
		key: "METER_ADMINISTRATOR",
		name: "Meter administrator",
		value: "MAD",
		description:
			"A party responsible for keeping a register of meters and related characteristics.",
	},
	{
		key: "METERED_DATA_RESPONSIBLE",
		name: "Metered data responsible",
		value: "MDR",
		description:
			"A party responsible for the establishment and validation of metered data received from the Metered Data Collector.",
	},
	{
		key: "MANUFACTURER_OF_GOODS",
		name: "Manufacturer of goods",
		value: "MF",
		description: "[3513] Party who manufactures the goods.",
	},
	{
		key: "PARTY_DESIGNATED_TO_EXECUTE_RE_ICING",
		name: "Party designated to execute re-icing",
		value: "MG",
		description:
			"Party designated to execute re-icing, selected in the official list of mandatories competent for this kind of operation.",
	},
	{
		key: "PLANNING_SCHEDULE_MATERIAL_RELEASE_ISSUER",
		name: "Planning schedule/material release issuer",
		value: "MI",
		description: "A party issuing a planning schedule/material release.",
	},
	{
		key: "MANUFACTURING_UNIT",
		name: "Manufacturing unit",
		value: "MP",
		description:
			"A party acting as a particular production unit of a manufacturer.",
	},
	{
		key: "MESSAGE_RECIPIENT",
		name: "Message recipient",
		value: "MR",
		description: "A party to receive a message or messages.",
	},
	{
		key: "DOCUMENT_MESSAGE_ISSUER_SENDER",
		name: "Document/message issuer/sender",
		value: "MS",
		description: "Issuer of a document and/or sender of a message.",
	},
	{
		key: "PARTY_DESIGNATED_TO_EXECUTE_SANITARY_PROCEDURES",
		name: "Party designated to execute sanitary procedures",
		value: "MT",
		description: "A party which is designated to execute sanitary procedures.",
	},
	{
		key: "N1_NOTIFY_PARTY_NO_1",
		name: "N1    Notify party no. 1",
		value: "X",
		description: "The first party which is to be notified.",
	},
	{
		key: "NOTIFY_PARTY_NO_2",
		name: "Notify party no. 2",
		value: "N2",
		description: "The second party which is to be notified.",
	},
	{
		key: "NOTIFY_PARTY",
		name: "Notify party",
		value: "NI",
		description: "[3180] Party to be notified. Synonym: Notify party No. 1.",
	},
	{
		key: "BREAK_BULK_BERTH_OPERATOR",
		name: "Break bulk berth operator",
		value: "OA",
		description:
			"Party who offers facilities for berthing of vessels, handling and storage of break bulk cargo.",
	},
	{
		key: "ORDERED_BY",
		name: "Ordered by",
		value: "OB",
		description: "Party who issued an order.",
	},
	{
		key: "PARTY_DATA_RESPONSIBLE_PARTY",
		name: "Party data responsible party",
		value: "OC",
		description: "The party responsible for all party data.",
	},
	{
		key: "EQUIPMENT_REPAIR_PARTY",
		name: "Equipment repair party",
		value: "OD",
		description: "A party making repairs to equipment.",
	},
	{
		key: "OWNER_OF_PROPERTY",
		name: "Owner of property",
		value: "OE",
		description: "Party owning a property.",
	},
	{
		key: "ON_BEHALF_OF",
		name: "On behalf of",
		value: "OF",
		description: "Party on behalf of which an action is executed.",
	},
	{
		key: "OWNER_OR_LESSORS_SURVEYOR",
		name: "Owner or lessor's surveyor",
		value: "OG",
		description: "Surveyor hired by the owner or lessor of the item.",
	},
	{
		key: "LESSEES_SURVEYOR",
		name: "Lessee's surveyor",
		value: "OH",
		description: "Surveyor hired by the lessee of the item.",
	},
	{
		key: "OUTSIDE_INSPECTION_AGENCY",
		name: "Outside inspection agency",
		value: "OI",
		description: "Third party inspecting goods or equipment.",
	},
	{
		key: "THIRD_PARTY",
		name: "Third party",
		value: "OJ",
		description: "Another party besides the two principals.",
	},
	{
		key: "RECEIVERS_SUB_ENTITY",
		name: "Receiver's sub-entity",
		value: "OK",
		description: "Identifies a sub-entity within the receiver's organization.",
	},
	{
		key: "CASE_OF_NEED_PARTY",
		name: "Case of need party",
		value: "OL",
		description: "Party to be approached in case of difficulty.",
	},
	{
		key: "COLLECTING_BANK",
		name: "Collecting bank",
		value: "OM",
		description:
			"Any bank, other than the remitting bank, involved in processing the collection.",
	},
	{
		key: "REMITTING_BANK",
		name: "Remitting bank",
		value: "ON",
		description:
			"The bank to which the principal has entrusted the handling of a collection.",
	},
	{
		key: "ORDER_OF_THE_SHIPPER_PARTY",
		name: "Order of the shipper party",
		value: "OO",
		description:
			"The owner of goods under consignment which are moving under a negotiable transport document and will only be released upon receipt of the original transport document.",
	},
	{
		key: "OPERATOR_OF_PROPERTY_OR_EQUIPMENT",
		name: "Operator of property or equipment",
		value: "OP",
		description: "The party which operates property or a unit of equipment.",
	},
	{
		key: "COLLECTION_PRINCIPAL",
		name: "Collection principal",
		value: "OQ",
		description: "The party entrusting the handling of a collection to a bank.",
	},
	{
		key: "ORDERED_BANK",
		name: "Ordered bank",
		value: "OR",
		description:
			"Identifies the bank servicing the account for the ordering customer or payer.",
	},
	{
		key: "ORIGINAL_SHIPPER",
		name: "Original shipper",
		value: "OS",
		description: "The original supplier of the goods.",
	},
	{
		key: "OUTSIDE_TEST_AGENCY",
		name: "Outside test agency",
		value: "OT",
		description: "Third party testing goods, equipment or services.",
	},
	{
		key: "ACCOUNT_OWNERS_SERVICING_BANK_ON_THE_SENDING_SIDE",
		name: "Account owner's servicing bank on the sending side",
		value: "OU",
		description:
			"Identifies the financial institution on the sending side which services the account owner's bank account(s).",
	},
	{
		key: "TRANSPORT_MEANS_OWNER",
		name: "Transport means owner",
		value: "OV",
		description:
			"Party owning the means of transport. No synonym of carrier (= CA).",
	},
	{
		key: "ACCOUNT_OWNERS_SERVICING_BANK_ON_THE_RECEIVING_SIDE",
		name: "Account owner's servicing bank on the receiving side",
		value: "OW",
		description:
			"Identifies the financial institution on the receiving side which services the account owner's bank account(s).",
	},
	{
		key: "SENDERS_CORRESPONDENT_BANK",
		name: "Sender's correspondent bank",
		value: "OX",
		description:
			"The account, or branch of the sender, or another financial institution, through which the sender will reimburse the receiver.",
	},
	{
		key: "ORDERING_CUSTOMER",
		name: "Ordering customer",
		value: "OY",
		description: "Identifies the originator of the instruction.",
	},
	{
		key: "RECEIVERS_CORRESPONDENT_BANK",
		name: "Receiver's correspondent bank",
		value: "OZ",
		description:
			"The branch of the receiver, or another financial institution, at which the funds will be made available to the receiver.",
	},
	{
		key: "CONTACT_PARTY_1",
		name: "Contact party 1",
		value: "P1",
		description: "First party to contact.",
	},
	{
		key: "CONTACT_PARTY_2",
		name: "Contact party 2",
		value: "P2",
		description: "Second party to contact.",
	},
	{
		key: "CONTACT_PARTY_3",
		name: "Contact party 3",
		value: "P3",
		description: "Third party to contact.",
	},
	{
		key: "CONTACT_PARTY_4",
		name: "Contact party 4",
		value: "P4",
		description: "Fourth party to contact.",
	},
	{
		key: "PARTY_TO_RECEIVE_INSPECTION_REPORT",
		name: "Party to receive inspection report",
		value: "PA",
		description: "Party to whom the inspection report should be sent.",
	},
	{
		key: "PAYING_FINANCIAL_INSTITUTION",
		name: "Paying financial institution",
		value: "PB",
		description: "Financial institution designated to make payment.",
	},
	{
		key: "ACTUAL_PURCHASERS_CUSTOMER",
		name: "Actual purchaser's customer",
		value: "PC",
		description:
			"Party the purchaser within the actual message is selling the ordered goods or services to.",
	},
	{
		key: "PURCHASERS_DEPARTMENT_BUYER",
		name: "Purchaser's department buyer",
		value: "PD",
		description: "Purchasing department of buyer.",
	},
	{
		key: "PAYEE",
		name: "Payee",
		value: "PE",
		description: "Identifies the credit party when other than the beneficiary.",
	},
	{
		key: "PARTY_TO_RECEIVE_FREIGHT_BILL",
		name: "Party to receive freight bill",
		value: "PF",
		description: "Party to whom the freight bill should be sent.",
	},
	{
		key: "PRIME_CONTRACTOR",
		name: "Prime contractor",
		value: "PG",
		description:
			"Party responsible for the whole project if other than the buyer.",
	},
	{
		key: "PAYERS_FINANCIAL_INSTITUTION",
		name: "Payer's financial institution",
		value: "PH",
		description:
			"Institution chosen by the payer to execute financial transactions on his behalf.",
	},
	{
		key: "PAYEES_COMPANY_NAME_ID",
		name: "Payee's company name/ID",
		value: "PI",
		description: "Receiving company name/ID (ACH transfers).",
	},
	{
		key: "PARTY_TO_RECEIVE_CORRESPONDENCE",
		name: "Party to receive correspondence",
		value: "PJ",
		description:
			"Second party designated by a first party to receive certain correspondence in lieu of it being mailed directly to this first party.",
	},
	{
		key: "CONTACT_PARTY",
		name: "Contact party",
		value: "PK",
		description: "Party to contact.",
	},
	{
		key: "PL_PAYOR",
		name: "PL    Payor",
		value: "X",
		description:
			"Identifies the debit party when other than the ordering customer (for banking purposes). Note: 1. This code value will be removed effective with directory D.09A.",
	},
	{
		key: "PARTY_TO_RECEIVE_PAPER_MEMO_OF_INVOICE",
		name: "Party to receive paper memo of invoice",
		value: "PM",
		description: "Party being informed about invoice issue (via paper).",
	},
	{
		key: "PARTY_TO_RECEIVE_SHIPPING_NOTICE",
		name: "Party to receive shipping notice",
		value: "PN",
		description: "The party is to be the recipient of the shipping notice.",
	},
	{
		key: "ORDERING_PARTY",
		name: "Ordering party",
		value: "PO",
		description:
			"To be used only if ordering party and buyer are not identical.",
	},
	{
		key: "CERTIFYING_PARTY",
		name: "Certifying party",
		value: "PQ",
		description: "A party which certifies something.",
	},
	{
		key: "PAYER",
		name: "Payer",
		value: "PR",
		description: "[3308] Party responsible for making a payment.",
	},
	{
		key: "PAYERS_COMPANY_NAME_ID_CHECK_DRAFT_OR_WIRE",
		name: "Payer's company name/ID (Check, Draft or Wire)",
		value: "PS",
		description: "Party to send cheque, draft or wire for payment.",
	},
	{
		key: "PARTY_TO_RECEIVE_TEST_REPORT",
		name: "Party to receive test report",
		value: "PT",
		description: "A party which is named to be the recipient of test reports.",
	},
	{
		key: "DESPATCH_PARTY",
		name: "Despatch party",
		value: "PW",
		description:
			"[3282] Party where goods are to be, or have been, taken over by a carrier such as the place where a container is picked-up.",
	},
	{
		key: "PARTY_TO_RECEIVE_ALL_DOCUMENTS",
		name: "Party to receive all documents",
		value: "PX",
		description: "A party which is named to be the recipient of all documents.",
	},
	{
		key: "CHECKING_PARTY",
		name: "Checking party",
		value: "PY",
		description:
			"Party or contact designated on behalf of carrier or his agent to establish the actual figures for quantities, weight, volume and/or (cube) measurements of goods or containers which are to appear in the transport contract and on which charges will be based.",
	},
	{
		key: "PARTY_TO_PRINT_SOME_DOCUMENT",
		name: "Party to print some document",
		value: "PZ",
		description: "The party that is to print a specific document.",
	},
	{
		key: "CENTRAL_BANK_OR_REGULATORY_AUTHORITY",
		name: "Central bank or regulatory authority",
		value: "RA",
		description:
			"Identifies central bank or regulatory authority which must be informed of certain aspects of a message.",
	},
	{
		key: "RECEIVING_FINANCIAL_INSTITUTION",
		name: "Receiving financial institution",
		value: "RB",
		description: "Financial institution designated to receive payment.",
	},
	{
		key: "PARTY_TO_RECEIVE_COMMERCIAL_INVOICE_REMITTANCE",
		name: "Party to receive commercial invoice remittance",
		value: "RE",
		description:
			"Party to whom payment for a commercial invoice or bill should be remitted.",
	},
	{
		key: "RECEIVED_FROM",
		name: "Received from",
		value: "RF",
		description:
			"Name of a person or department which actually delivers the goods.",
	},
	{
		key: "SELLERS_FINANCIAL_INSTITUTION",
		name: "Seller's financial institution",
		value: "RH",
		description:
			"Financial institution designated by seller to receive payment. RDFI (ACH transfers).",
	},
	{
		key: "REINSURANCE_INTERMEDIARY_BROKER",
		name: "Reinsurance intermediary/broker",
		value: "RI",
		description: "Intermediary party between ceding company and reinsurance.",
	},
	{
		key: "REPORTING_CARRIER_CUSTOMS",
		name: "Reporting carrier (Customs)",
		value: "RL",
		description: "Party who makes the cargo report to Customs.",
	},
	{
		key: "REPORTING_CARRIERS_NOMINATED_AGENT_REPRESENTATIVE",
		name: "Reporting carrier's nominated agent/representative",
		value: "RM",
		description:
			"(Customs) Agent who formally makes a cargo report to Customs on behalf of the carrier.",
	},
	{
		key: "ROUTING_PARTY",
		name: "Routing party",
		value: "RP",
		description: "Party responsible for the selection of the carrier(s).",
	},
	{
		key: "PARTY_TO_RECEIVE_STATEMENT_OF_ACCOUNT",
		name: "Party to receive statement of account",
		value: "RS",
		description: "Party to whom the statement of account should be sent.",
	},
	{
		key: "RECEIVER_OF_CHEQUE",
		name: "Receiver of cheque",
		value: "RV",
		description:
			"Identifies the party which is to receive the actual cheque, when different from the receiver of funds.",
	},
	{
		key: "ISSUER_OF_WAYBILL",
		name: "Issuer of waybill",
		value: "RW",
		description: "Party issuing the contract (waybill) for carriage.",
	},
	{
		key: "SALES_RESPONSIBILITY",
		name: "Sales responsibility",
		value: "SB",
		description: "A party being responsible for sales.",
	},
	{
		key: "SELLER",
		name: "Seller",
		value: "SE",
		description: "[3346] Party selling merchandise or services to a buyer.",
	},
	{
		key: "SHIP_FROM",
		name: "Ship from",
		value: "SF",
		description:
			"Identification of the party from where goods will be or have been shipped.",
	},
	{
		key: "STORE_GROUP",
		name: "Store group",
		value: "SG",
		description: "A chain of shops or stores.",
	},
	{
		key: "SHIPPING_SCHEDULE_ISSUER",
		name: "Shipping schedule issuer",
		value: "SI",
		description: "The party which issues a shipping schedule.",
	},
	{
		key: "STORE_KEEPER",
		name: "Store keeper",
		value: "SN",
		description: "A party keeping a shop or store.",
	},
	{
		key: "SOLD_TO_IF_DIFFERENT_THAN_BILL_TO",
		name: "Sold to if different than bill to",
		value: "SO",
		description:
			"Party to whom the goods have been sold, if different to the bill to party.",
	},
	{
		key: "SELLER_AGENT",
		name: "Seller agent",
		value: "SR",
		description:
			"[3254] Party representing the seller for the purpose of a trade transaction.",
	},
	{
		key: "SOCIAL_SECURITIES_COLLECTORS_OFFICE",
		name: "Social securities collector's office",
		value: "SS",
		description: "Party collecting social securities premiums.",
	},
	{
		key: "SHIP_TO",
		name: "Ship to",
		value: "ST",
		description:
			"Identification of the party to where goods will be or have been shipped.",
	},
	{
		key: "SUPPLIER",
		name: "Supplier",
		value: "SU",
		description: "Party who supplies goods and or services.",
	},
	{
		key: "SURETY_FOR_ADDITIONS",
		name: "Surety for additions",
		value: "SX",
		description:
			"Natural of legal person (generally a bank of insurance company) who accepts responsibility in due legal form for the financial guarantee to Customs of the payment of additional duties or fees that become due against a particular shipment, which have not previously been covered by surety.",
	},
	{
		key: "SURETY",
		name: "Surety",
		value: "SY",
		description:
			"Natural or legal person (generally a bank or insurance company) who accepts responsibility in due legal form for the financial consequences of non-fulfillment of another's obligations to the Customs (CCC).",
	},
	{
		key: "SURETY_FOR_ANTIDUMPING_COUNTERVAILING_DUTY",
		name: "Surety for antidumping/countervailing duty",
		value: "SZ",
		description:
			"Natural or legal person that has been contracted by the importer to guarantee to Customs the payment of antidumping and/or countervailing duties that become due against a particular shipment.",
	},
	{
		key: "LEGAL_RECEIVER",
		name: "Legal receiver",
		value: "TA",
		description: "The party responsible for a receivership.",
	},
	{
		key: "SUBMITTER",
		name: "Submitter",
		value: "TB",
		description: "To specify that the party is a submitter.",
	},
	{
		key: "TAX_COLLECTORS_OFFICE",
		name: "Tax collector's office",
		value: "TC",
		description: "Party collecting taxes.",
	},
	{
		key: "TRANSIT_CHARGE_PAYER",
		name: "Transit charge payer",
		value: "TCP",
		description:
			"Party, other than the ordering party, which has to pay the charges concerning the transit operations.",
	},
	{
		key: "TRANSPORT_CAPACITY_RESPONSIBLE_PARTY",
		name: "Transport capacity responsible party",
		value: "TCR",
		description: "Party responsible for transport capacity.",
	},
	{
		key: "PARTY_TO_RECEIVE_TECHNICAL_DOCUMENTATION",
		name: "Party to receive technical documentation",
		value: "TD",
		description: "Party to whom technical documentation should be sent.",
	},
	{
		key: "BANKRUPTCY_REFEREE",
		name: "Bankruptcy referee",
		value: "TE",
		description: "To specify that the party is a referee in a bankruptcy case.",
	},
	{
		key: "SOURCE_OF_INFORMATION",
		name: "Source of information",
		value: "TF",
		description: "To specify that the party is the source of information.",
	},
	{
		key: "JUDGE",
		name: "Judge",
		value: "TG",
		description: "To specify that the party is a judge.",
	},
	{
		key: "ATTORNEY",
		name: "Attorney",
		value: "TH",
		description: "To specify that the party is an attorney.",
	},
	{
		key: "LAW_FIRM",
		name: "Law firm",
		value: "TI",
		description: "To specify that the party is a law firm.",
	},
	{
		key: "TRUSTEE",
		name: "Trustee",
		value: "TJ",
		description: "To specify that the party is a trustee.",
	},
	{
		key: "SIGNATORY",
		name: "Signatory",
		value: "TK",
		description: "To specify that the party is a signatory.",
	},
	{
		key: "OCCUPANT",
		name: "Occupant",
		value: "TL",
		description: "The party is an occupant.",
	},
	{
		key: "CO_OCCUPANT",
		name: "Co-occupant",
		value: "TM",
		description: "The party is a co-occupant.",
	},
	{
		key: "SUBJECT_OF_INQUIRY",
		name: "Subject of inquiry",
		value: "TN",
		description: "The party is the subject of an inquiry.",
	},
	{
		key: "LESSOR",
		name: "Lessor",
		value: "TO",
		description: "The party is a lessor.",
	},
	{
		key: "OWNER_OF_RESIDENCE",
		name: "Owner of residence",
		value: "TP",
		description: "Identifies the owner of a residence.",
	},
	{
		key: "FOUNDER",
		name: "Founder",
		value: "TQ",
		description: "Identifies the founder.",
	},
	{
		key: "TERMINAL_OPERATOR",
		name: "Terminal operator",
		value: "TR",
		description:
			"A party which handles the loading and unloading of marine vessels.",
	},
	{
		key: "PARTY_TO_RECEIVE_CERTIFIED_TEST_RESULTS",
		name: "Party to receive certified test results",
		value: "TS",
		description: "Party to whom the certified test results should be sent.",
	},
	{
		key: "TRANSFER_TO",
		name: "Transfer to",
		value: "TT",
		description: "The party which is the recipient of a transfer.",
	},
	{
		key: "PRESIDENT",
		name: "President",
		value: "TU",
		description: "Identifies the president.",
	},
	{
		key: "CHAIRPERSON",
		name: "Chairperson",
		value: "TV",
		description: "Identifies the chairperson.",
	},
	{
		key: "LEGAL_TITLE_HOLDER",
		name: "Legal title holder",
		value: "TW",
		description: "Identifies the legal title holder.",
	},
	{
		key: "SHAREHOLDER",
		name: "Shareholder",
		value: "TX",
		description: "Identifies a shareholder.",
	},
	{
		key: "PROVIDER",
		name: "Provider",
		value: "TY",
		description: "Identifies the provider.",
	},
	{
		key: "MILITARY_BRANCH",
		name: "Military branch",
		value: "TZ",
		description: "Identifies the branch of the military.",
	},
	{
		key: "EDUCATIONAL_INSTITUTION",
		name: "Educational institution",
		value: "UA",
		description: "Identifies a university, college or school.",
	},
	{
		key: "ASSIGNOR",
		name: "Assignor",
		value: "UB",
		description: "Identifies the assignor.",
	},
	{
		key: "ULTIMATE_CONSIGNEE",
		name: "Ultimate consignee",
		value: "UC",
		description:
			"Party who has been designated on the invoice or packing list as the final recipient of the stated merchandise.",
	},
	{
		key: "ULTIMATE_CUSTOMER",
		name: "Ultimate customer",
		value: "UD",
		description: "The final recipient of goods.",
	},
	{
		key: "ADVISOR",
		name: "Advisor",
		value: "UE",
		description: "Identifies the advisor.",
	},
	{
		key: "CO_DEFENDANT",
		name: "Co-defendant",
		value: "UF",
		description: "Identifies the co-defendant.",
	},
	{
		key: "MERGED_COMPANY_WITH_RETAINED_IDENTITY",
		name: "Merged company with retained identity",
		value: "UG",
		description: "Company whose identity has been retained from a merger.",
	},
	{
		key: "PARTY_REPRESENTED",
		name: "Party represented",
		value: "UH",
		description: "Identifies the party represented.",
	},
	{
		key: "UNEXPECTED_HANDLING_PARTY",
		name: "Unexpected handling party",
		value: "UHP",
		description:
			"Party authorized (during a voyage) to apply unexpected handling procedures or party having applied these procedures.",
	},
	{
		key: "ASSIGNEE",
		name: "Assignee",
		value: "UI",
		description: "Identifies the assignee.",
	},
	{
		key: "KEY_PERSON",
		name: "Key person",
		value: "UJ",
		description: "Identifies the key person.",
	},
	{
		key: "AUTHOR",
		name: "Author",
		value: "UK",
		description: "Identifies the author.",
	},
	{
		key: "ULTIMATE_PARENT_COMPANY",
		name: "Ultimate parent company",
		value: "UL",
		description: "Identifies the ultimate parent company.",
	},
	{
		key: "PARTY_NOT_TO_BE_CONFUSED_WITH",
		name: "Party not to be confused with",
		value: "UM",
		description: "Identifies a party not to be confused with another party.",
	},
	{
		key: "ACCOUNTANT",
		name: "Accountant",
		value: "UN",
		description: "Identifies the accountant.",
	},
	{
		key: "PLAINTIFF",
		name: "Plaintiff",
		value: "UO",
		description: "Identifies the plaintiff.",
	},
	{
		key: "UNLOADING_PARTY",
		name: "Unloading party",
		value: "UP",
		description: "A party to unload the goods.",
	},
	{
		key: "PARENT_COMPANY",
		name: "Parent company",
		value: "UQ",
		description: "Identifies the parent company.",
	},
	{
		key: "AFFILIATED_COMPANY",
		name: "Affiliated company",
		value: "UR",
		description: "Identifies the affiliated company.",
	},
	{
		key: "BAILIFF",
		name: "Bailiff",
		value: "US",
		description: "Identifies the bailiff.",
	},
	{
		key: "MERGED_COMPANY",
		name: "Merged company",
		value: "UT",
		description: "Identifies the company involved in a merger.",
	},
	{
		key: "DEFENDANT",
		name: "Defendant",
		value: "UU",
		description: "Identifies the defendant.",
	},
	{
		key: "PETITIONING_CREDITOR",
		name: "Petitioning creditor",
		value: "UV",
		description: "Identifies the petitioning creditor.",
	},
	{
		key: "GUARANTEE_AGENCY",
		name: "Guarantee agency",
		value: "UW",
		description: "Identifies the guarantee agency.",
	},
	{
		key: "ORGANIZATION_GROUP",
		name: "Organization group",
		value: "UX",
		description: "Identifies the organization group.",
	},
	{
		key: "SUBSIDIARY",
		name: "Subsidiary",
		value: "UY",
		description: "Identifies the subsidiary.",
	},
	{
		key: "INDUSTRY_ASSOCIATION",
		name: "Industry association",
		value: "UZ",
		description: "Identifies the industry association.",
	},
	{
		key: "JOINT_OWNER",
		name: "Joint owner",
		value: "VA",
		description: "Identifies the joint owner.",
	},
	{
		key: "JOINT_VENTURE",
		name: "Joint venture",
		value: "VB",
		description: "Identifies the joint venture.",
	},
	{
		key: "FILING_OFFICE",
		name: "Filing office",
		value: "VC",
		description: "Identifies the filing office.",
	},
	{
		key: "COURT",
		name: "Court",
		value: "VE",
		description: "Identifies the court.",
	},
	{
		key: "LIABILITY_HOLDER",
		name: "Liability holder",
		value: "VF",
		description: "Identifies the liability holder.",
	},
	{
		key: "LOCAL_GOVERNMENT_SPONSOR",
		name: "Local government sponsor",
		value: "VG",
		description: "Identifies the local government sponsor.",
	},
	{
		key: "MORTGAGE_COMPANY",
		name: "Mortgage company",
		value: "VH",
		description: "Identifies the mortgage company.",
	},
	{
		key: "NOTARY_PUBLIC",
		name: "Notary public",
		value: "VI",
		description: "Identifies the notary public.",
	},
	{
		key: "OFFICER",
		name: "Officer",
		value: "VJ",
		description: "Identifies the officer.",
	},
	{
		key: "PUBLISHER",
		name: "Publisher",
		value: "VK",
		description: "Identifies the publisher.",
	},
	{
		key: "PARTY_MANUFACTURED_FOR",
		name: "Party manufactured for",
		value: "VL",
		description:
			"Identifies the party for whom manufacturing of goods is done.",
	},
	{
		key: "PREVIOUS_OWNER",
		name: "Previous owner",
		value: "VM",
		description: "Identifies the previous owner.",
	},
	{
		key: "VENDOR",
		name: "Vendor",
		value: "VN",
		description: "Party vending goods or services.",
	},
	{
		key: "PURCHASED_COMPANY",
		name: "Purchased company",
		value: "VO",
		description: "Identifies the purchased company.",
	},
	{
		key: "RECEIVER_MANAGER",
		name: "Receiver manager",
		value: "VP",
		description:
			"Manager of a business which is in receivership status and which will not be liquidated.",
	},
	{
		key: "RESPONSIBLE_GOVERNMENT_AGENCY",
		name: "Responsible government agency",
		value: "VQ",
		description: "Identifies the responsible government agency.",
	},
	{
		key: "SOLE_PROPRIETOR",
		name: "Sole proprietor",
		value: "VR",
		description: "Identifies the sole proprietor.",
	},
	{
		key: "AUCTIONEER",
		name: "Auctioneer",
		value: "VS",
		description: "Identifies the auctioneer.",
	},
	{
		key: "BRANCH",
		name: "Branch",
		value: "VT",
		description: "Identifies the branch.",
	},
	{
		key: "BUSINESS",
		name: "Business",
		value: "VU",
		description: "Identifies the business.",
	},
	{
		key: "ULTIMATE_SAME_COUNTRY_PARENT_COMPANY",
		name: "Ultimate same country parent company",
		value: "VV",
		description:
			"Identifies the highest level parent company in the same country.",
	},
	{
		key: "RESPONSIBLE_PARTY",
		name: "Responsible party",
		value: "VW",
		description: "Identifies the party that can be called to account.",
	},
	{
		key: "SECURED_PARTY",
		name: "Secured party",
		value: "VX",
		description: "Identifies a party that is guaranteed against loss.",
	},
	{
		key: "OTHER_RELATED_PARTY",
		name: "Other related party",
		value: "VY",
		description: "Identifies an entity as an unspecified but related party.",
	},
	{
		key: "CO_DEBTOR",
		name: "Co-debtor",
		value: "VZ",
		description: "Identifies an entity as a joint or mutual debtor.",
	},
	{
		key: "COMPANY_WHICH_HOLDS_FINANCIAL_INTEREST",
		name: "Company which holds financial interest",
		value: "WA",
		description:
			"Identifies a company which holds any financial stake in an undertaking or organization.",
	},
	{
		key: "RATING_ORGANIZATION",
		name: "Rating organization",
		value: "WB",
		description:
			"Identifies an organization responsible for assigning a classification or rating.",
	},
	{
		key: "INFORMATION_REFERENCE_AGENCY",
		name: "Information reference agency",
		value: "WC",
		description: "The agency responsible for the reference of information.",
	},
	{
		key: "WAREHOUSE_DEPOSITOR",
		name: "Warehouse depositor",
		value: "WD",
		description: "[3004] Party depositing goods in a warehouse.",
	},
	{
		key: "COMPILATION_AGENCY",
		name: "Compilation agency",
		value: "WE",
		description: "The agency responsible for the compilation of information.",
	},
	{
		key: "INFORMATION_MAINTENANCE_AGENCY",
		name: "Information maintenance agency",
		value: "WF",
		description: "The agency responsible for the maintenance of information.",
	},
	{
		key: "INFORMATION_DISSEMINATION_AGENCY",
		name: "Information dissemination agency",
		value: "WG",
		description: "The agency responsible for the dissemination of information.",
	},
	{
		key: "WAREHOUSE_KEEPER",
		name: "Warehouse keeper",
		value: "WH",
		description:
			"[3022] Party taking responsibility for goods entered into a warehouse.",
	},
	{
		key: "INSPECTION_ADDRESS",
		name: "Inspection address",
		value: "WI",
		description: "Specifies the address for an inspection.",
	},
	{
		key: "REFUSAL_PARTY",
		name: "Refusal party",
		value: "WJ",
		description: "Identification of the party responsible for a refusal.",
	},
	{
		key: "VALUE_ADDED_NETWORK_PROVIDER",
		name: "Value added network provider",
		value: "WK",
		description:
			"A party that provides telecommunications interconnectivity services in an electronic data interchange environment.",
	},
	{
		key: "AGENCY",
		name: "Agency",
		value: "WL",
		description: "The business or establishment of an agent.",
	},
	{
		key: "WORKS_MANAGER",
		name: "Works manager",
		value: "WM",
		description: "A party managing works.",
	},
	{
		key: "PARTY_TO_RECEIVE_ORDER_TO_SUPPLY",
		name: "Party to receive order to supply",
		value: "WN",
		description:
			"Party designated by the registering party to receive a binding direction to supply something.",
	},
	{
		key: "PARTY_TO_RECEIVE_INVITATION_TO_OFFER",
		name: "Party to receive invitation to offer",
		value: "WO",
		description: "An entity to receive an invitation to offer.",
	},
	{
		key: "SUB_ENTITY",
		name: "Sub-entity",
		value: "WP",
		description: "A part into which an entity has been divided.",
	},
	{
		key: "WEIGHTING_PARTY",
		name: "Weighting party",
		value: "WPA",
		description: "Party designated (legally accepted) to ascertain the weight.",
	},
	{
		key: "DOING_BUSINESS_AS",
		name: "Doing business as",
		value: "WQ",
		description: "The name under which business is conducted.",
	},
	{
		key: "PARTY_SUBMITTING_QUOTE",
		name: "Party submitting quote",
		value: "WR",
		description: "The party stating the price of something to be purchased.",
	},
	{
		key: "WHOLESALER",
		name: "Wholesaler",
		value: "WS",
		description:
			"Seller of articles, often in large quantities, to be retailed by others.",
	},
	{
		key: "AFFILIATED_PARTY",
		name: "Affiliated party",
		value: "WT",
		description: "A party attached or connected to another party.",
	},
	{
		key: "PREVIOUS_NAME",
		name: "Previous name",
		value: "WU",
		description: "Name of an entity used before the current name.",
	},
	{
		key: "PARTY_PERFORMING_TASK",
		name: "Party performing task",
		value: "WV",
		description:
			"An entity responsible for performing a task to be undertaken.",
	},
	{
		key: "REGISTERING_PARTY",
		name: "Registering party",
		value: "WW",
		description: "Party performing the registration.",
	},
	{
		key: "MUTUALLY_DEFINED",
		name: "Mutually defined",
		value: "ZZZ",
		description:
			"Party specification mutually agreed between interchanging parties. Data Element Cross Reference DataElement 3035 is used in the following Batch Segments:",
	},
	{
		key: "NAD_PNA",
		name: "NAD    PNA",
		value: "FII",
		description:
			"DataElement 3035 is used in the following Interactive Segments:",
	},
	{
		key: "PRT",
		name: "PRT",
		value: "NAA",
		description:
			"DataElement 3035 is used in the following Interactive Composite Elements: E012    E032    E966    E985    E986 Copyright United Nations, all rights reserved     UN Economic Commission for Europe Palais des Nations, CH-1211 Geneva 10, Switzerland  Tel: +41-22 917 2773 Fax: +41-22 917 0037  E-mail: TradeMaster@unece.org UN/EDIFACT Directories",
	},
] as const satisfies Untdid3035Definition[];

export type Untdid3035 = {
	[K in (typeof untdid3035)[number] as K["key"]]: K["value"];
};

export const Untdid3035 = Object.fromEntries(
	untdid3035.map((item) => [item.key, item.value]),
) as Untdid3035;
